//! Item icons: one per id, illustrated (SVG rasterised with anti-aliasing) in
//! an atlas generated by `tools/icones/gerar_icones.py` (see
//! docs/PIPELINE_ARTE.md).
//!
//! The PNG goes INSIDE the binary (`include_bytes!`), like the HUD font:
//! there is no async load at boot and no file that can be missing at runtime.
//! The texture uploads the first time an icon is drawn — already inside the
//! frame, with the GL context standing.
//!
//! The RARITY frame is not in the atlas: rarity belongs to the piece's
//! instance, not to the id. Whoever knows the rarity passes it to `icone`.

use std::cell::OnceCell;

use macroquad::prelude::*;

#[path = "icones_indice.rs"]
mod indice;

const PNG: &[u8] = include_bytes!("../../../assets/icones/itens.png");

thread_local! {
    static ATLAS: OnceCell<Texture2D> = const { OnceCell::new() };
}

fn atlas() -> Texture2D {
    ATLAS.with(|c| {
        c.get_or_init(|| {
            let t = Texture2D::from_file_with_format(PNG, Some(ImageFormat::Png));
            // A large cell (96) drawn smaller: a linear filter shrinks smoothly;
            // the nearest filter of the old pixel art aliased the illustration.
            t.set_filter(FilterMode::Linear);
            t
        })
        .clone()
    })
}

/// The item's cell in the atlas, in pixels. `None` = item with no atlas icon.
pub fn celula(item_id: u16) -> Option<Rect> {
    let k = indice::ICONES
        .binary_search_by_key(&item_id, |e| e.0)
        .ok()?;
    let n = indice::ICONES[k].1 as u32;
    let lado = indice::LADO as f32;
    Some(Rect::new(
        (n % indice::COLUNAS) as f32 * lado,
        (n / indice::COLUNAS) as f32 * lado,
        lado,
        lado,
    ))
}

/// Draws the atlas icon centered and square inside `r`. Returns `false` if
/// the item has no icon (the caller draws the substitute).
pub fn desenha(item_id: u16, r: Rect, alfa: f32) -> bool {
    let Some(fonte) = celula(item_id) else {
        return false;
    };
    let lado = r.w.min(r.h);
    let destino = vec2(lado, lado);
    let x = r.x + (r.w - lado) * 0.5;
    let y = r.y + (r.h - lado) * 0.5;
    draw_texture_ex(
        &atlas(),
        x,
        y,
        Color::new(1.0, 1.0, 1.0, alfa),
        DrawTextureParams {
            dest_size: Some(destino),
            source: Some(fonte),
            ..Default::default()
        },
    );
    true
}

/// The full icon: background and frame in the rarity color (1..5, the same as
/// `shared::items::tier_color_hex`), the drawing and the quantity in the corner.
pub fn icone(item_id: u16, r: Rect, raridade: Option<u8>, quantidade: Option<u32>) {
    icone_com_3d(item_id, r, raridade, quantidade, None);
}

/// Uses the 3D model of pets and mounts where the panel has the stage for it.
pub fn icone_com_3d(
    item_id: u16,
    r: Rect,
    raridade: Option<u8>,
    quantidade: Option<u32>,
    palco: Option<(&crate::vox::VoxCache, &macroquad::material::Material)>,
) {
    if let Some(t) = raridade {
        let h = shared::items::tier_color_hex(t).trim_start_matches('#');
        let v = u32::from_str_radix(h, 16).unwrap_or(0xbf_bf_bf);
        let cor = Color::from_rgba((v >> 16) as u8, (v >> 8) as u8, v as u8, 255);
        draw_rectangle(r.x, r.y, r.w, r.h, Color::new(cor.r, cor.g, cor.b, 0.18));
        draw_rectangle_lines(r.x, r.y, r.w, r.h, 1.5, cor);
    }
    let pad = r.w.min(r.h) * 0.06;
    let desenho = Rect::new(r.x + pad, r.y + pad, r.w - pad * 2.0, r.h - pad * 2.0);
    let bicho_3d = palco.is_some_and(|(vox, solido)| {
        let giro = get_time() as f32 * 0.5 + item_id as f32 * 0.7;
        crate::render3d::vitrine_pet(vox, item_id, desenho, giro, solido)
            || crate::render3d::vitrine_montaria(vox, item_id, desenho, giro, solido)
            || vitrine_skin(vox, item_id, desenho, giro, solido)
    });
    if !bicho_3d {
        desenha(item_id, desenho, 1.0);
    }
    if let Some(q) = quantidade.filter(|q| *q > 1) {
        let t = q.to_string();
        let tam = (r.w * 0.26).clamp(10.0, 16.0) as u16;
        let w = crate::hud_estilo::medir_forte(&t, tam);
        crate::hud_estilo::texto_sombra(r.x + r.w - w - 4.0, r.y + r.h - 4.0, &t, tam, WHITE, true);
    }
}

/// A SKIN item as the character wearing it, turning like a pet or a mount.
/// It had no icon at all: the flat set has nothing for skins, and a bought
/// Storm Captain sat in the bag as an empty square. The look is the default
/// one with only the skin changed — the outfit on the body, or the hat in
/// the hair slot (`aparencia::cabelo_do_chapeu`).
pub(crate) fn vitrine_skin(
    vox: &crate::vox::VoxCache,
    item_id: u16,
    r: Rect,
    giro: f32,
    solido: &macroquad::material::Material,
) -> bool {
    use shared::aparencia as ap;
    let Some(skin) = ap::skin_do_item(item_id) else {
        return false;
    };
    // A mount coat shows on the dragon: the coat is the point, and the
    // biggest creature carries it best in a bag slot.
    crate::render3d::vitrine_de_skin(vox, skin, ap::Aparencia::default(),
        shared::item_id::MONTARIA_BASE + 4, r, giro, solido)
}

#[cfg(test)]
mod testes {
    use super::*;
    use shared::item_id as i;
    use std::collections::HashSet;

    /// Every item the game knows (the server's item seed).
    fn conhecidos() -> Vec<u16> {
        let mut v = vec![
            i::GOLD,
            i::HEALTH_POTION,
            i::MANA_POTION,
            i::GREATER_HEAL,
            i::GREATER_MANA,
            i::STAMINA_POTION,
            i::XP_POTION,
            i::FORTUNA_POTION,
            i::SORTE_POTION,
            i::WOOD_T1,
            i::WOOD_T2,
            i::WOOD_T3,
            i::WOOD_T4,
            i::FISH_ANCHOVY,
            i::FISH_CLOWNFISH,
            i::FISH_SURGEONFISH,
            i::FISH_PUFFERFISH,
            i::COPPER,
            i::DARKSTEEL,
            i::GLITTERING_POWDER,
        ];
        v.extend(i::ESPADA_E_ESCUDO..=i::CINTO);
        for base in i::MATERIAIS_COLORIDOS {
            for cor in 1..=4 {
                v.push(i::na_cor(base, cor));
            }
        }
        v.extend(i::todas_as_chaves());
        v.extend([
            i::MARCAS_TEMPESTADE,
            i::SELO_TEMPESTADE,
            i::PERGAMINHO_TELEPORTE,
        ]);
        v.sort_unstable();
        v.dedup();
        v
    }

    fn atlas_cpu() -> Image {
        Image::from_file_with_format(PNG, Some(ImageFormat::Png)).expect("atlas decodifica")
    }

    #[test]
    fn todo_item_conhecido_tem_icone_dentro_do_atlas() {
        let img = atlas_cpu();
        assert_eq!(
            (img.width as u32, img.height as u32),
            (indice::LARGURA, indice::ALTURA)
        );
        for id in conhecidos() {
            let c = celula(id).unwrap_or_else(|| panic!("item {id} sem icone"));
            assert!(c.x >= 0.0 && c.y >= 0.0, "{id}");
            assert!(
                c.x + c.w <= img.width as f32 && c.y + c.h <= img.height as f32,
                "{id} fora do atlas"
            );
        }
        assert!(celula(u16::MAX).is_none());
    }

    #[test]
    fn indice_ordenado_e_sem_celula_repetida() {
        let ids: Vec<u16> = indice::ICONES.iter().map(|e| e.0).collect();
        assert!(
            ids.windows(2).all(|w| w[0] < w[1]),
            "indice precisa estar ordenado pra busca binaria"
        );
        let celulas: HashSet<u16> = indice::ICONES.iter().map(|e| e.1).collect();
        assert_eq!(celulas.len(), indice::ICONES.len());
    }

    /// One icon per real item: none empty, and none equal to another.
    #[test]
    fn icones_nao_vazios_e_todos_diferentes() {
        let img = atlas_cpu();
        let lado = indice::LADO as usize;
        let mut vistos = HashSet::new();
        for &(id, _) in indice::ICONES {
            let c = celula(id).unwrap();
            let mut px = Vec::with_capacity(lado * lado * 4);
            let mut opacos = 0;
            for y in 0..lado {
                for x in 0..lado {
                    let i = ((c.y as usize + y) * img.width as usize + c.x as usize + x) * 4;
                    px.extend_from_slice(&img.bytes[i..i + 4]);
                    if img.bytes[i + 3] >= 200 {
                        opacos += 1;
                    }
                }
            }
            assert!(
                opacos > lado * lado / 10,
                "icone de {id} quase vazio ({opacos} px)"
            );
            assert!(vistos.insert(px), "icone de {id} igual a outro");
        }
    }
}
