// GENERATED by tools/icones/gerar_icones_ui.py — do not edit by hand.
// Run `python3 tools/icones/gerar_icones_ui.py` to rebuild atlas and index.

pub const LADO_UI: u32 = 64;
pub const COLUNAS_UI: u32 = 8;
pub const LARGURA_UI: u32 = 512;
pub const ALTURA_UI: u32 = 448;

pub const LADO_MAPA: u32 = 48;
pub const COLUNAS_MAPA: u32 = 8;
pub const LARGURA_MAPA: u32 = 384;
pub const ALTURA_MAPA: u32 = 96;

pub const LADO_SKILLS: u32 = 96;
pub const COLUNAS_SKILLS: u32 = 6;
pub const LARGURA_SKILLS: u32 = 576;
pub const ALTURA_SKILLS: u32 = 192;

pub const LADO_LOJA: u32 = 128;
pub const COLUNAS_LOJA: u32 = 4;
pub const LARGURA_LOJA: u32 = 512;
pub const ALTURA_LOJA: u32 = 256;

/// (name, cell), ordered by name.
pub const UI: &[(&str, u16)] = &[
    ("amigos", 0),
    ("atacar", 1),
    ("auto_coleta", 2),
    ("auto_combate", 3),
    ("aventuras", 4),
    ("avisos", 5),
    ("banco", 6),
    ("barra_itens", 7),
    ("bolsa", 8),
    ("cadeado", 9),
    ("caneca", 10),
    ("clan", 11),
    ("coleta", 12),
    ("combinar", 13),
    ("configuracoes", 14),
    ("conquistas", 15),
    ("coroa", 16),
    ("correio", 17),
    ("craft", 18),
    ("dash", 19),
    ("diarias", 20),
    ("encantar", 21),
    ("engrenagem", 22),
    ("fechar", 23),
    ("ficha", 24),
    ("forja", 25),
    ("graficos", 26),
    ("grupo", 27),
    ("guarda_roupa", 28),
    ("habilidades", 29),
    ("ilha_magica", 30),
    ("loja_tp", 31),
    ("lojas", 32),
    ("mais", 33),
    ("mapa", 34),
    ("menu", 35),
    ("mercado", 36),
    ("minha_ilha", 37),
    ("missoes", 38),
    ("mobs", 39),
    ("montaria", 40),
    ("paleta", 41),
    ("pets", 42),
    ("presenca", 43),
    ("pulo", 44),
    ("recuperar_xp", 45),
    ("sair", 46),
    ("sprint", 47),
    ("todas_missoes", 48),
    ("trocar_personagem", 49),
    ("voltar", 50),
];

/// (name, cell), ordered by name.
pub const MAPA: &[(&str, u16)] = &[
    ("arqueiro", 0),
    ("caranguejo", 1),
    ("chefe", 2),
    ("cidade", 3),
    ("destino", 4),
    ("jogador", 5),
    ("lobo", 6),
    ("madeira", 7),
    ("mago", 8),
    ("npc", 9),
    ("owlbear", 10),
    ("pedra", 11),
    ("pistoleiro", 12),
    ("porto", 13),
    ("tigre", 14),
    ("urso", 15),
];

/// (skill id, cell), ordered by id.
pub const SKILLS: &[(u32, u16)] = &[
    (1, 0),
    (2, 1),
    (3, 2),
    (4, 3),
    (5, 4),
    (6, 5),
    (7, 6),
    (8, 7),
    (9, 8),
    (10, 9),
    (11, 10),
    (12, 11),
];

/// (name, cell), ordered by name. Colored shop art (TP, bundles, gold).
pub const LOJA: &[(&str, u16)] = &[
    ("ouro", 0),
    ("tp", 1),
    ("tp_1", 2),
    ("tp_2", 3),
    ("tp_3", 4),
    ("tp_4", 5),
];
