//! PROGRESSION: how long a level takes, and where its XP comes from.
//!
//! The owner's rule (04/10/2026): in every ten levels the main story gives at
//! most 10-15% of the XP, side missions 10-20%, and the rest is fighting (or
//! the Magic Island). Before this the story's rewards were written by hand
//! and grew faster than the curve — from level 85 a single step paid most of
//! a level — and the Quest Master's ten-minute contracts paid several times
//! the kills they asked for.
//!
//! The target is the BEST case — pistols, always fighting, no gathering,
//! crafting or trading — reaching 120 in about 200 hours. Real players do the
//! rest of the game too, and take longer.
//!
//! `balanceamento::tempo_de_nivel` measures it; `calibrar_xp_do_mob` prints
//! the kill factor below.

/// Seconds level `n` takes in the best case: `SEGUNDOS_POR_NIVEL x n`. One
/// straight line, so every level is slower than the one before (the owner:
/// "it always has to get harder") and 1-120 sums to 200 hours. Bands come out
/// 1.3h, 4.1h, 6.9h … 32h, each ~2.8h longer than the last.
pub const SEGUNDOS_POR_NIVEL: f32 = 720_000.0 / 7_140.0;

/// Best-case seconds to go from `n` to `n + 1`.
pub fn segundos_do_nivel(n: u32) -> f32 {
    SEGUNDOS_POR_NIVEL * n as f32
}

/// Share of each band's XP from the main story.
pub const PARCELA_DA_HISTORIA: f32 = 0.12;
/// Share from side missions (one-off, contracts and dailies together).
pub const PARCELA_SECUNDARIA: f32 = 0.15;
/// What is left: fighting.
pub const PARCELA_DOS_MOBS: f32 = 1.0 - PARCELA_DA_HISTORIA - PARCELA_SECUNDARIA;

use std::collections::HashMap;
use std::sync::OnceLock;

use crate::constants::{xp_for_level_with_mult, DEFAULT_XP_MULTIPLIER};
use crate::quests::{objective_kind as ok, QuestDef, ALVO_QUALQUER_CHEFE, QUESTS};

/// The level cap the targets are written for.
pub const TETO: u32 = 120;

/// Side missions split into three parts. One-off missions share this much
/// of their band's XP between them.
pub const PARCELA_DAS_UNICAS: f32 = 0.05;
/// A repeatable contract pays this fraction of the kills it asks for, on top
/// of them. Done non-stop, contracts are ~7% of the XP; they never outrun
/// fighting, however often they are repeated.
pub const BONUS_DO_CONTRATO: f32 = 0.10;
/// Every daily of an island together pays this many levels (at the dailies'
/// level) per day.
pub const DIARIAS_POR_DIA: f32 = 0.15;

/// Kill-XP factor on the species' table XP, one per level (index = level;
/// past the end, the last). Generated by
/// `balanceamento::tempo_de_nivel::calibrar_xp_do_mob`: for every level, the
/// factor that makes the best case spend `segundos_do_nivel` on it with
/// fighting giving `PARCELA_DOS_MOBS` of the XP. Per level and not per band,
/// so an island whose mobs are worth more, or die faster, cannot make a level
/// shorter than the one before. Rerun it after touching mob XP, mob speed or
/// kill time. (It was `1 + 0.1 x (level - 1)`.)
pub const FATOR_DO_MOB: [f32; 121] = include!("progressao_fator.in");

/// The kill-XP factor at `nivel`.
pub fn fator_do_mob(nivel: u32) -> f32 {
    FATOR_DO_MOB[(nivel as usize).min(FATOR_DO_MOB.len() - 1)]
}

/// XP of a kill of a species whose table XP is `base`, at `nivel`.
pub fn xp_do_abate(base: u64, nivel: u32) -> u64 {
    ((base as f32 * fator_do_mob(nivel)).round() as u64).max(1)
}

/// Table XP of a typical regular mob (the zones average 60-84), for the
/// rewards measured in kills.
const BASE_TIPICA: u64 = 70;

fn custo(nivel: u32) -> u64 {
    let m = DEFAULT_XP_MULTIPLIER;
    xp_for_level_with_mult(nivel + 1, m).saturating_sub(xp_for_level_with_mult(nivel, m))
}

fn xp_entre(a: u32, b: u32) -> u64 {
    let m = DEFAULT_XP_MULTIPLIER;
    xp_for_level_with_mult(b, m).saturating_sub(xp_for_level_with_mult(a, m))
}

/// The ten-level band of `nivel`: (first level, last level).
fn faixa(nivel: u32) -> (u32, u32) {
    let f = (nivel.max(1) / 10).min(TETO / 10 - 1);
    (f * 10, f * 10 + 10)
}

/// THE XP A QUEST PAYS, in the default curve. Every place that grants or
/// shows a quest's XP goes through here; the `reward_xp` written in the quest
/// is now only its WEIGHT against the others of its group, so a boss still
/// pays more than a conversation.
///
///   * main story: `PARCELA_DA_HISTORIA` of the XP between two level gates,
///     split among the steps between them;
///   * one-off side mission: `PARCELA_DAS_UNICAS` of its band, split among
///     the band's one-offs;
///   * contract (repeatable on a cooldown): `BONUS_DO_CONTRATO` of the kills
///     it costs;
///   * daily: its share of `DIARIAS_POR_DIA` levels, with the other dailies
///     of its island.
pub fn xp_da_quest(q: &QuestDef) -> u64 {
    if q.reward_xp == 0 {
        return 0;
    }
    if crate::historia::e_da_historia(q.id) {
        return da_historia().get(&q.id).copied().unwrap_or(0);
    }
    if q.daily {
        // The island's dailies together (the Master hands them out where he
        // lives: `quests::zona_da_missao`).
        let ilha = crate::quests::zona_da_missao(q.id);
        let soma: u64 = QUESTS
            .iter()
            .filter(|d| d.daily && crate::quests::zona_da_missao(d.id) == ilha)
            .map(|d| d.reward_xp)
            .sum();
        let dia = DIARIAS_POR_DIA as f64 * custo(q.min_level.max(1)) as f64;
        return (dia * q.reward_xp as f64 / soma.max(1) as f64).round() as u64;
    }
    if q.repeatable {
        let abates = match q.obj_kind {
            ok::KILL if q.obj_target == ALVO_QUALQUER_CHEFE => 20,
            ok::KILL | ok::PVP_KILL | ok::GATHER | ok::COLLECT => q.obj_count.max(1),
            ok::DUNGEON | ok::RAID => 60,
            _ => 10,
        } as f64;
        let nivel = q.min_level.max(1);
        return (BONUS_DO_CONTRATO as f64 * abates * xp_do_abate(BASE_TIPICA, nivel) as f64).round() as u64;
    }
    let (a, b) = faixa(q.min_level);
    let soma: u64 = QUESTS
        .iter()
        .filter(|d| !d.repeatable && !d.daily && !crate::historia::e_da_historia(d.id))
        // Only what a player can get: a mission with no island has no giver
        // in the world (`zona_da_missao`), and its share would go nowhere.
        .filter(|d| crate::quests::zona_da_missao(d.id).is_some())
        .filter(|d| faixa(d.min_level) == (a, b))
        .map(|d| d.reward_xp)
        .sum();
    let verba = PARCELA_DAS_UNICAS as f64 * xp_entre(a.max(1), b) as f64;
    (verba * q.reward_xp as f64 / soma.max(1) as f64).round() as u64
}

/// The story's XP per step: between two consecutive level gates, the
/// story's share of the XP from the first gate to the second, split by the
/// written weights. Before the first gate, the written XP. Steps after the
/// cap's gate pay nothing (no level to gain there).
fn da_historia() -> &'static HashMap<u16, u64> {
    static M: OnceLock<HashMap<u16, u64>> = OnceLock::new();
    M.get_or_init(|| {
        let mut m = HashMap::new();
        let mut trecho: Vec<(u16, u64)> = Vec::new();
        let mut desde = 1u32;
        let fecha = |trecho: &mut Vec<(u16, u64)>, de: u32, ate: u32, m: &mut HashMap<u16, u64>| {
            let soma: u64 = trecho.iter().map(|t| t.1).sum();
            let verba = PARCELA_DA_HISTORIA as f64 * xp_entre(de, ate.min(TETO)) as f64;
            for (id, w) in trecho.drain(..) {
                m.insert(id, (verba * w as f64 / soma.max(1) as f64).round() as u64);
            }
        };
        let mut i = 0u32;
        let mut antes_da_primeira_trava = true;
        while desde < TETO {
            let Some(id) = crate::historia::id_do_passo(i) else { break };
            let Some(q) = crate::historia::def_da_historia(id) else { break };
            i += 1;
            // Chapters I and II have no level gate: the player finishes them
            // as a tutorial, well before 20. The owner kept them as written
            // (04/10/2026) — the rule starts at the first gate.
            if antes_da_primeira_trava && q.obj_kind != ok::NIVEL {
                m.insert(q.id, q.reward_xp);
                continue;
            }
            if q.obj_kind == ok::NIVEL && antes_da_primeira_trava {
                antes_da_primeira_trava = false;
                desde = q.obj_count.max(1);
                continue;
            }
            if q.obj_kind == ok::NIVEL {
                let ate = q.obj_count.max(desde);
                fecha(&mut trecho, desde, ate, &mut m);
                desde = ate;
            } else if q.reward_xp > 0 {
                trecho.push((q.id, q.reward_xp));
            }
        }
        fecha(&mut trecho, desde, TETO, &mut m);
        m
    })
}

#[cfg(test)]
mod testes {
    use super::*;

    #[test]
    fn o_fator_do_mob_existe_em_todo_nivel() {
        for n in 1..=TETO {
            assert!(fator_do_mob(n) > 0.0, "level {n}");
        }
        assert_eq!(fator_do_mob(500), FATOR_DO_MOB[120]);
    }

    /// The owner's rule, measured on the data: in every gated stretch the
    /// story pays its share, and nothing more.
    #[test]
    fn a_historia_paga_a_parcela_de_cada_trecho() {
        let mut total = 0u64;
        let mut inicio = 0u64;
        let mut antes = true;
        for q in crate::historia::PASSOS {
            if q.obj_kind == ok::NIVEL {
                if antes {
                    inicio = xp_for_level_with_mult(q.obj_count, DEFAULT_XP_MULTIPLIER);
                }
                antes = false;
            } else if !antes {
                total += xp_da_quest(q);
            }
        }
        let teto = (xp_for_level_with_mult(TETO, DEFAULT_XP_MULTIPLIER) - inicio) as f64;
        let parcela = total as f64 / teto;
        assert!(parcela <= PARCELA_DA_HISTORIA as f64 + 0.005, "story pays {parcela:.3} of 1-120");
        assert!(parcela >= PARCELA_DA_HISTORIA as f64 * 0.8, "story pays only {parcela:.3} of 1-120");
    }

    #[test]
    fn contrato_nunca_paga_mais_que_os_abates() {
        for q in QUESTS.iter().filter(|q| q.repeatable && !q.daily && q.obj_kind == ok::KILL && q.obj_target == 0) {
            let abates = q.obj_count as u64 * xp_do_abate(BASE_TIPICA, q.min_level.max(1));
            assert!(xp_da_quest(q) * 5 < abates, "{} '{}' pays {} for kills worth {abates}", q.id, q.title, xp_da_quest(q));
        }
    }
}
