//! Cliente: HUD, menus, painéis e os avisos que o próprio cliente escreve.
//!
//! As regras dos buracos estão em `super`.

/// O texto do CLIENTE: HUD, menus, painéis, avisos locais.
pub const VERBETES: &[(&str, &str)] = &[
    // ─────────────────────────── cliente: rede e versão ───────────────────────────
    ("já existe", "already exists"),
    ("dados inválidos", "invalid data"),
    ("resposta sem corpo", "response had no body"),
    ("erro do servidor ({c})", "server error ({c})"),
    ("erro ({c})", "error ({c})"),
    ("resposta sem codigo HTTP", "response had no HTTP status"),
    ("servidor respondeu {codigo}", "server replied {codigo}"),
    ("resposta inesperada ({codigo})", "unexpected response ({codigo})"),
    ("resposta incompleta do servidor", "incomplete response from the server"),
    ("release: HTTP {codigo}", "release: HTTP {codigo}"),
    ("lista de servidores: {e}", "server list: {e}"),
    // atualizacao.rs — a tela que aparece quando o protocolo não bate
    ("Voltar", "Back"),
    ("Agora não", "Not now"),
    ("Abrir TestFlight", "Open TestFlight"),
    ("Atualizar na loja", "Update in the store"),
    ("Baixar atualização", "Download update"),
    ("Cliente desatualizado", "Client out of date"),
    ("Atualização necessária", "Update required"),
    ("Abrir site para atualizar", "Open the site to update"),
    ("Verificando atualizações...", "Checking for updates..."),
    ("Não foi possível abrir o navegador.", "Could not open the browser."),
    ("Abra mmo.brunji.com.br no navegador.", "Open mmo.brunji.com.br in your browser."),
    ("Atualize o jogo pelo site para continuar.", "Update the game from the site to continue."),
    ("Sua versão é incompatível com o servidor.", "Your version is incompatible with the server."),
    ("Uma nova versão do Tempest está disponível.", "A new version of Tempest is available."),
    // ─────────────────────────────── cliente: auras ───────────────────────────────
    ("Recorte", "Crop"),
    ("AURAS DE PETS", "PET AURAS"),
    ("AURAS DE MONTARIAS", "MOUNT AURAS"),
    ("AURAS POR EQUIPAMENTO", "AURAS BY GEAR"),
    (
        "Verde T1 +12 / Azul T2 +12 / Roxo T3 +12 / Laranja T4 +12",
        "Green T1 +12 / Blue T2 +12 / Purple T3 +12 / Orange T4 +12",
    ),
    (
        "Mesma cor e refino: T4           T3           T2           T1",
        "Same colour and refine: T4           T3           T2           T1",
    ),
    // ──────────────────────────── cliente: os automáticos ────────────────────────────
    ("AUTO COLETA · COLETANDO", "AUTO GATHER · GATHERING"),
    ("AUTO COLETA · PROCURANDO", "AUTO GATHER · SEARCHING"),
    ("AUTO COLETA · BOLSA CHEIA", "AUTO GATHER · BAG FULL"),
    ("AUTO COLETA · INDO AO RECURSO", "AUTO GATHER · HEADING TO NODE"),
    ("AUTO COLETA · AGUARDANDO RECURSOS…", "AUTO GATHER · WAITING FOR NODES…"),
    ("AUTO COMBATE · ATACANDO", "AUTO COMBAT · ATTACKING"),
    ("AUTO COMBATE · BUSCANDO", "AUTO COMBAT · SEARCHING"),
    ("AUTO MISSÃO · {} · {}", "AUTO QUEST · {} · {}"),
    ("indo ao veio", "heading to the vein"),
    ("indo conversar", "going to talk"),
    ("voltando ao Mestre", "returning to the Master"),
    ("indo ao ponto-chave", "heading to the key point"),
    ("recebendo a próxima", "taking the next one"),
    ("procurando o objetivo", "looking for the objective"),
    ("indo à zona dos bichos", "heading to the beast zone"),
    ("procurando outro recurso", "looking for another node"),
    ("História: {nome} para continuar.", "Story: {nome} to continue."),
    (
        "Auto missão: o Mestre não tem missão nova agora.",
        "Auto quest: the Master has no new quest right now.",
    ),
    (
        "Auto missão encerrada: \"{nome}\" não está mais ativa.",
        "Auto quest stopped: \"{nome}\" is no longer active.",
    ),
    (
        "Auto missão: não sei onde fica o objetivo de \"{nome}\" nesta ilha.",
        "Auto quest: I don't know where the objective of \"{nome}\" is on this island.",
    ),
    // auto_resumo.rs
    ("item {id}", "item {id}"),
    ("{} Energia", "{} Energy"),
    ("Coletado: {}", "Gathered: {}"),
    ("Coletado: {coletado}", "Gathered: {coletado}"),
    ("Na fila: {}", "Queued: {}"),
    ("Sem recompensa", "No reward"),
    ("Última: {} · {}", "Last: {} · {}"),
    ("Anterior: {} · {}", "Previous: {} · {}"),
    ("Concluída: {} · {}", "Completed: {} · {}"),
    ("Total recebido: {}", "Total received: {}"),
    ("Escolhendo próxima missão...", "Picking the next quest..."),
    ("AUTO MISSÃO  ·  {} concluída(s)", "AUTO QUEST  ·  {} completed"),
    ("Fazendo: {nome}  {feito}/{total}", "Doing: {nome}  {feito}/{total}"),
    ("Recompensas: aguardando conclusão", "Rewards: waiting for completion"),
    // ──────────────────────────────── cliente: banco ────────────────────────────────
    ("Banco", "Bank"),
    ("Bolsa", "Bag"),
    ("Ouro {}", "Gold {}"),
    ("Tamanho máximo", "Maximum size"),
    ("+{} espaços · {} ouro", "+{} slots · {} gold"),
    (
        "toque num item para guardar ou retirar",
        "tap an item to store or withdraw",
    ),
    // ───────────────────────────── cliente: barra de vida ─────────────────────────────
    ("sem Sorte ativa", "no Luck active"),
    ("sem Fortuna ativa", "no Fortune active"),
    ("mana abaixo do limiar", "mana below the threshold"),
    ("sem bônus de XP ativo", "no XP bonus active"),
    ("vida abaixo do limiar", "health below the threshold"),
    ("vigor abaixo do limiar", "stamina below the threshold"),
    // ──────────────────────────────── cliente: bolsa ────────────────────────────────
    ("Arma", "Weapon"),
    ("Mana", "Mana"),
    ("Tudo", "All"),
    ("Usar", "Use"),
    ("Vida", "Health"),
    ("Cinto", "Belt"),
    ("Comum", "Common"),
    ("Craft", "Craft"),
    ("Força", "Strength"),
    ("Moeda", "Currency"),
    ("Nível", "Level"),
    ("Poder", "Power"),
    ("Ataque", "Attack"),
    ("Brinco", "Earring"),
    ("Defesa", "Defence"),
    ("Amuleto", "Amulet"),
    ("Crítico", "Critical"),
    ("Equipar", "Equip"),
    ("Refinar", "Refine"),
    ("Armadura", "Armour"),
    ("Cancelar", "Cancel"),
    ("Combinar", "Combine"),
    ("Destreza", "Dexterity"),
    ("Material", "Material"),
    ("Montaria", "Mount"),
    ("Nível {}", "Level {}"),
    ("Nível {req}", "Level {req}"),
    ("Aces. pet", "Pet acc."),
    ("Aprimorar", "Upgrade"),
    ("Arma · {}", "Weapon · {}"),
    ("Bracelete", "Bracelet"),
    ("Organizar", "Sort"),
    ("Sabedoria", "Wisdom"),
    ("Abrir 10+1", "Open 10+1"),
    ("Consumível", "Consumable"),
    ("Desequipar", "Unequip"),
    ("Esporeando", "Spurring"),
    ("Secundária", "Off-hand"),
    ("Velocidade", "Speed"),
    ("Aces. mont.", "Mount acc."),
    ("Desmantelar", "Salvage"),
    ("Equipamento", "Gear"),
    ("Equipar: {}", "Equip: {}"),
    ("Vel. ataque", "Atk. speed"),
    ("Busca saque a", "Loot pickup range"),
    ("Quantidade {}", "Quantity {}"),
    ("Recupera mana.", "Restores mana."),
    ("Recupera vida.", "Restores health."),
    ("Recupera vigor.", "Restores stamina."),
    ("Em uso: {} · {}", "In use: {} · {}"),
    ("vs. correr a pé", "vs. running on foot"),
    ("Desmantelar item?", "Salvage item?"),
    ("Requer nível {req}", "Requires level {req}"),
    ("A bolsa está cheia.", "Your bag is full."),
    ("Ouro {}    Cobre {}", "Gold {}    Copper {}"),
    ("Em uso: nenhuma arma", "In use: no weapon"),
    ("Material de criação.", "Crafting material."),
    ("mesmo poder do vestido", "same power as equipped"),
    ("Pergaminho de Invocação", "Summoning Scroll"),
    ("Ativo com um pet equipado", "Active with a pet equipped"),
    ("Darksteel {}    Energia {}", "Darksteel {}    Energy {}"),
    ("Retrato sem espaço na tela", "No room for the portrait"),
    ("Ativo com montaria equipada", "Active with a mount equipped"),
    ("{s} de poder sobre o vestido", "{s} power over what you have on"),
    ("+{s} de poder sobre o vestido", "+{s} power over what you have on"),
    ("{} · Tier {} · nível do item {}", "{} · Tier {} · item level {}"),
    ("Nenhum item compatível na bolsa.", "No compatible item in your bag."),
    ("{}: 10% de chance de recuperar 1", "{}: 10% chance to recover 1"),
    (
        "A peça será consumida. Você receberá:",
        "The piece will be consumed. You will receive:",
    ),
    (
        "Peça básica, sem instância de atributos.",
        "Basic piece, with no attribute roll.",
    ),
    (
        "+30% de XP por 1 hora. Beber outra renova a hora.",
        "+30% XP for 1 hour. Drinking another resets the hour.",
    ),
    (
        "Abra para revelar um prêmio aleatório decidido pelo servidor.",
        "Open to reveal a random prize decided by the server.",
    ),
    (
        "+30% de ouro e cobre dos bichos por 1 hora. Beber outra renova a hora.",
        "+30% gold and copper from beasts for 1 hour. Drinking another resets the hour.",
    ),
    (
        "+20% de chance de drop (bichos e coleta) por 1 hora. Beber outra renova a hora.",
        "+20% drop chance (beasts and gathering) for 1 hour. Drinking another resets the hour.",
    ),
    // ─────────────────────────────── cliente: coleção ───────────────────────────────
    ("Em uso", "In use"),
    ("No topo", "At the top"),
    ("{} · em uso", "{} · in use"),
    ("Combinar {}/{}", "Combine {}/{}"),
    (
        "Nada ainda. O pergaminho da Loja traz um.",
        "Nothing yet. The scroll in the Shop brings one.",
    ),
    (
        "Laranja é o topo: não há grau acima para combinar.",
        "Orange is the top: there is no higher grade to combine.",
    ),
    (
        "Combinar: {} {} tentam {}, {}% de chance, {} de cobre. Falhar consome os {}.",
        "Combine: {} {} attempt {}, {}% chance, {} copper. Failing consumes the {}.",
    ),
    ("Coletando · {} · {:.1} s", "Gathering · {} · {:.1} s"),
    ("Bolsa cheia — coleta pausada", "Bag full — gathering paused"),
    // ────────────────────────────── cliente: a colônia ──────────────────────────────
    ("Colher", "Harvest"),
    ("Retirar", "Withdraw"),
    ("Melhorar", "Upgrade"),
    ("Moradores", "Residents"),
    ("Minha Ilha", "My Island"),
    ("No máximo.", "At maximum."),
    ("montando a ilha…", "building the island…"),
    ("{} daria {} {}/h", "{} would give {} {}/h"),
    ("→ {} espaços (de {})", "→ {} slots (from {})"),
    ("{}, 1 casa de ofício.", "{}, 1 trade house."),
    ("Pronto para colher: {}", "Ready to harvest: {}"),
    ("{}, {v} casas de ofício.", "{}, {v} trade houses."),
    ("{}, sem casa pra morador.", "{}, no house for a resident."),
    ("→ {nome}, {b} casas (+{})", "→ {nome}, {b} houses (+{})"),
    ("{} espaços no baú da ilha.", "{} slots in the island chest."),
    ("→ {}/h por morador (de {})", "→ {}/h per resident (from {})"),
    ("Baú da ilha · {}/{} espaços", "Island chest · {}/{} slots"),
    ("Vazio — a colheita cai aqui.", "Empty — the harvest lands here."),
    ("→ {nome}, mais terreno plano", "→ {nome}, more flat ground"),
    ("A ilha ainda não rendeu nada.", "The island hasn't yielded anything yet."),
    ("Casa vazia — escolha um ofício", "Empty house — pick a trade"),
    ("arraste para girar · pinça dá zoom", "drag to rotate · pinch to zoom"),
    (
        "Cada morador rende {q}/h do ofício dele.",
        "Each resident yields {q}/h of their trade.",
    ),
    (
        "{horas:.0}h de {h:.0}h — rendendo cheio.",
        "{horas:.0}h of {h:.0}h — yielding at full rate.",
    ),
    (
        "Tamanho {} · Recursos {} · Banco {} espaços",
        "Size {} · Resources {} · Bank {} slots",
    ),
    (
        "{horas:.0}h — parou de render às {teto:.0}h. Colha.",
        "{horas:.0}h — stopped yielding at {teto:.0}h. Harvest it.",
    ),
    (
        "Rendendo {}/h. A primeira unidade sai em ~{min} min.",
        "Yielding {}/h. The first unit arrives in ~{min} min.",
    ),
    (
        "Ninguém mora aqui. Contrate um ofício numa casa vazia.",
        "Nobody lives here. Hire a trade in an empty house.",
    ),
    (
        "{horas:.0}h — passou das {h:.0}h e desde então rende metade.",
        "{horas:.0}h — past {h:.0}h, and yielding half since then.",
    ),
    (
        "Ninguém mora aqui. Melhore o Assentamento para abrir uma casa.",
        "Nobody lives here. Upgrade the Settlement to open a house.",
    ),
    // ──────────────────────────── cliente: barra de itens ────────────────────────────
    ("Vazio", "Empty"),
    ("Limpar", "Clear"),
    ("AUTO · ligado", "AUTO · on"),
    ("Barra de itens", "Item bar"),
    ("AUTO usa com {}", "AUTO uses at {}"),
    ("AUTO · desligado", "AUTO · off"),
    ("Consumíveis na bolsa", "Consumables in your bag"),
    ("Escolha um item na lista ›", "Pick an item from the list ›"),
    ("Nenhum consumível na bolsa.", "No consumables in your bag."),
    (
        "Escolha um item e depois um espaço (ou o contrário). Na tela, arraste o botão pra CIMA pra ligar o AUTO.",
        "Pick an item and then a slot (or the other way round). On screen, drag the button UP to switch AUTO on.",
    ),
    // ─────────────────────────── cliente: opções de coleta ───────────────────────────
    ("Energia", "Energy"),
    ("Auto coleta", "Auto gather"),
    ("O que coletar", "What to gather"),
    ("Raio de busca", "Search radius"),
    (
        "Defender-se: atacado, mata o bicho e volta",
        "Defend yourself: if attacked, kill the beast and return",
    ),
    (
        "Procura a partir de onde o AUTO foi ligado.",
        "Searches from where AUTO was switched on.",
    ),
    // ─────────────────────────── cliente: opções de combate ───────────────────────────
    ("Combate", "Combat"),
    ("Jogador", "Player"),
    ("O mais perto", "The nearest"),
    ("Contra jogador", "Against players"),
    ("Nunca atacar jogador", "Never attack players"),
    ("Atacar qualquer jogador", "Attack any player"),
    ("Quem me acerta de longe", "Whoever hits me from afar"),
    ("Depois dela, nesta ordem", "After that, in this order"),
    ("Só revidar em quem me bateu", "Only strike back at whoever hit me"),
    (
        "só entra se o PvP abaixo permitir",
        "only applies if the PvP setting below allows it",
    ),
    (
        "o de sempre: o que estiver mais próximo",
        "the usual: whichever is closest",
    ),
    (
        "Missão de caça ativa vem sempre primeiro.",
        "An active hunt quest always comes first.",
    ),
    (
        "você bate no de perto e continua apanhando",
        "you hit the near one and keep taking hits",
    ),
    // ────────────────────────── cliente: opções de interface ──────────────────────────
    ("Leves", "Light"),
    ("Nunca", "Never"),
    ("Bonitas", "Pretty"),
    ("Sombras", "Shadows"),
    ("Interface", "Interface"),
    ("{min} min", "{min} min"),
    ("Desligadas", "Off"),
    ("Ativar agora", "Enable now"),
    ("Tamanho do HUD", "HUD size"),
    ("Tamanho padrão", "Default size"),
    ("Economia de energia", "Battery saver"),
    ("Auto após inatividade", "Auto after idling"),
    ("Voltar ao padrão ({:.0}%)", "Back to default ({:.0}%)"),
    ("Tamanho do HUD e dos textos", "Size of the HUD and text"),
    ("Bonitas: sol de fim de tarde", "Pretty: late-afternoon sun"),
    ("e sombras suaves do cenário.", "and soft shadows from the scenery."),
    ("A escolha fica salva no aparelho.", "The choice is saved on this device."),
    // O idioma, que é o motivo deste módulo existir.
    ("Idioma", "Language"),
    ("Idioma do jogo", "Game language"),
    (
        "Vale para menus, itens, missões e avisos. Fica salvo no aparelho.",
        "Applies to menus, items, quests and notices. Saved on this device.",
    ),
    (
        "Frase sem tradução aparece em português.",
        "Untranslated text falls back to Portuguese.",
    ),
    // ───────────────────────── cliente: confirmar e recomeçar ─────────────────────────
    ("{m}m", "{m}m"),
    ("{s}s", "{s}s"),
    ("{h}h {m:02}m", "{h}h {m:02}m"),
    ("Usar de novo?", "Use again?"),
    ("Usar assim mesmo", "Use it anyway"),
    ("{nome} já está ativa, com {} restando.", "{nome} is already active, with {} left."),
    (
        "Usar outra recomeça a hora do zero: o tempo que resta é perdido, e o efeito não acumula.",
        "Using another restarts the hour from zero: the remaining time is lost, and the effect does not stack.",
    ),
    (
        "Entrar sozinho sem tocar na tela por",
        "Enter alone without touching the screen for",
    ),
    (
        "Muda na hora e fica salvo no personagem.",
        "Changes right away and is saved on the character.",
    ),
    (
        "Bonitas: luz de fim de tarde e sombras do cenário.",
        "Pretty: late-afternoon light and shadows from the scenery.",
    ),
    // ──────────────────────────────── cliente: criação ────────────────────────────────
    ("Aço", "Steel"),
    ("Criar", "Craft"),
    ("Chifre", "Horn"),
    ("Dá: {}", "Gives: {}"),
    ("Escama", "Scale"),
    ("Katana", "Katana"),
    ("Pistolas", "Pistols"),
    ("Aço Verde", "Green Steel"),
    ("Materiais", "Materials"),
    ("Chifre Verde", "Green Horn"),
    ("Força +{emp}", "Strength +{emp}"),
    ("Ingredientes", "Ingredients"),
    ("Armadura Leve", "Light Armour"),
    ("Pó Cintilante", "Shimmering Dust"),
    ("Armadura Média", "Medium Armour"),
    ("Requer nível {}", "Requires level {}"),
    ("{} · nível mínimo {}", "{} · minimum level {}"),
    ("usar a partir do Nv {}", "usable from Lv {}"),
    ("Nenhuma receita nesta aba.", "No recipe in this tab."),
    ("Cria: {qtd}× {nome_da_saida}", "Creates: {qtd}× {nome_da_saida}"),
    ("Faltam {faltam} ingrediente(s)", "Missing {faltam} ingredient(s)"),
    (
        "chave + materiais da cor + darksteel + cobre",
        "key + materials of that colour + darksteel + copper",
    ),
    (
        "chaves, pets e montarias: 5 para tentar a cor seguinte",
        "keys, pets and mounts: 5 to attempt the next colour",
    ),
    (
        "duas peças iguais sobem o tier; duas Tier IV +8 sobem a cor",
        "two identical pieces raise the tier; two Tier IV +8 raise the colour",
    ),
    (
        "10 materiais + cobre, darksteel e pó criam 1 da cor seguinte",
        "10 materials + copper, darksteel and dust create 1 of the next colour",
    ),
    // ─────────────────────────────── cliente: diálogo ───────────────────────────────
    ("Fechar", "Close"),
    ("Aceitar", "Accept"),
    ("Próximo", "Next"),
    ("Receber", "Claim"),
    ("Concluir", "Turn in"),
    ("Recompensa: {}", "Reward: {}"),
    // ─────────────────────────────── cliente: diárias ───────────────────────────────
    ("Item", "Item"),
    ("Pegar", "Take"),
    ("Diárias", "Dailies"),
    ("Em breve", "Coming soon"),
    ("Disponível", "Available"),
    ("Ir entregar", "Go turn it in"),
    ("Concluída hoje", "Completed today"),
    ("Pré-requisitos", "Prerequisites"),
    ("Pronta pra entregar", "Ready to turn in"),
    ("Poção de Experiência", "Experience Potion"),
    ("{ilha} · reset em {}", "{ilha} · resets in {}"),
    ("Nenhuma diária nesta ilha.", "No daily on this island."),
    ("Em andamento · {feito}/{total}", "In progress · {feito}/{total}"),
    ("\"{}\" concluída hoje · reset em {}.", "\"{}\" completed today · resets in {}."),
    // ───────────────────────── cliente: recompensas de dungeon ─────────────────────────
    ("Chefe", "Boss"),
    ("Consultando progresso…", "Checking progress…"),
    ("Drops possíveis do boss", "Possible boss drops"),
    ("Já recebeu nesta semana", "Already received this week"),
    ("Chave aleatória · cor {}", "Random key · colour {}"),
    ("Chave {}: {:.0}% no total.", "Key {}: {:.0}% in total."),
    ("Equipamento: {:.0}% · até {}.", "Gear: {:.0}% · up to {}."),
    ("Equipamento garantido: {graus}.", "Guaranteed gear: {graus}."),
    ("Já concluída · bônus único encerrado", "Already completed · one-off bonus closed"),
    ("Primeira conclusão · estágio {estagio}", "First completion · stage {estagio}"),
    ("Primeira vitória da semana · por conta", "First win of the week · per account"),
    (
        "Nenhum drop cadastrado para este chefe.",
        "No drop registered for this boss.",
    ),
    ("Equipamento aleatório · uma destas peças", "Random gear · one of these pieces"),
    (
        "Baú de conclusão · separado do drop do boss",
        "Completion chest · separate from the boss drop",
    ),
    (
        "{} ouro + {} Marcas da Tempestade (sem bônus).",
        "{} gold + {} Storm Marks (no bonus).",
    ),
    (
        "Bônus de tempo: +50% de Marcas e material extra.",
        "Time bonus: +50% Marks and extra material.",
    ),
    (
        "Também contém cobre, darksteel e material de craft.",
        "Also contains copper, darksteel and crafting material.",
    ),
    (
        "Entrega no Correio ao vencer com entrada/recompensa.",
        "Delivered by Mail when you win with an entry/reward.",
    ),
    (
        "1 equipamento aleatório + 1 chave de craft aleatória.",
        "1 random piece of gear + 1 random crafting key.",
    ),
    (
        "Ajudante: sem equipamento, chave ou bônus de estreia.",
        "Helper: no gear, key or first-time bonus.",
    ),
    (
        "Na estreia, os dois bônus podem ser recebidos juntos.",
        "On your first run, both bonuses can be received together.",
    ),
    (
        "+1 equipamento aleatório garantido, enviado ao Correio.",
        "+1 guaranteed random piece of gear, sent to your Mail.",
    ),
    (
        "Saque no chão; itens e quantidades variam a cada abate.",
        "Loot on the ground; items and amounts vary with each kill.",
    ),
    // ───────────────────────────── cliente: dungeon e arena ─────────────────────────────
    ("Sair", "Leave"),
    ("Solo", "Solo"),
    ("Entrar", "Enter"),
    ("› AUTO", "› AUTO"),
    ("Começar", "Start"),
    ("Dungeon", "Dungeon"),
    ("Entrada", "Entry"),
    ("Estágio", "Stage"),
    ("Recusar", "Decline"),
    ("Reviver", "Revive"),
    ("VITÓRIA", "VICTORY"),
    (" (líder)", " (leader)"),
    ("Dungeons", "Dungeons"),
    ("Ilha nova", "New island"),
    ("VOCÊ CAIU", "YOU FELL"),
    ("Criar sala", "Create room"),
    ("Andar {}/{}", "Floor {}/{}"),
    ("Carregando…", "Loading…"),
    ("Fechado: {}", "Closed: {}"),
    ("Recompensas", "Rewards"),
    ("Toque: AUTO", "Tap: AUTO"),
    ("Completar {}", "Complete {}"),
    ("Juntar saque", "Gather loot"),
    ("Sair da fila", "Leave queue"),
    ("Sair da sala", "Leave room"),
    ("SAIR DA ARENA", "LEAVE THE ARENA"),
    ("Sair da Arena", "Leave the Arena"),
    ("Voltar à ilha", "Back to island"),
    ("{} · Em breve", "{} · Coming soon"),
    ("Entrar na fila", "Join queue"),
    ("Entrar sozinho", "Enter alone"),
    ("Procurar salas", "Find rooms"),
    ("TEMPO ESGOTADO", "OUT OF TIME"),
    ("Grupo de até {}", "Party of up to {}"),
    ("Ir para a Arena", "Go to the Arena"),
    ("BAÚ DE CONCLUSÃO", "COMPLETION CHEST"),
    ("Dungeon: {texto}", "Dungeon: {texto}"),
    ("Grupo encontrado", "Party found"),
    ("Entrar na dungeon", "Enter the dungeon"),
    ("Só o líder começa", "Leader starts it"),
    ("Reviver em {:.0} s", "Revive in {:.0} s"),
    ("{} · nível {} · {}", "{} · level {} · {}"),
    ("Esperando os outros…", "Waiting for the others…"),
    ("{} · estágio {} · {}", "{} · stage {} · {}"),
    ("Recompensas hoje: {}/{}", "Rewards today: {}/{}"),
    ("Comprar entrada · {} ouro", "Buy entry · {} gold"),
    ("{} · estágio {} · {:.0} s", "{} · stage {} · {:.0} s"),
    ("{} · estágio {} · {andar}", "{} · stage {} · {andar}"),
    ("A dungeon começa na Arena.", "The dungeon starts in the Arena."),
    ("Sua sala · {} · estágio {}", "Your room · {} · stage {}"),
    ("Entradas: {}/{} (2 por dia)", "Entries: {}/{} (2 per day)"),
    ("Completa as vagas pela fila.", "Fills the open spots from the queue."),
    ("Vitória em {}! Toque no baú.", "Victory in {}! Tap the chest."),
    ("PRIMEIRA VITÓRIA · NO CORREIO", "FIRST WIN · IN YOUR MAIL"),
    ("Bônus de tempo: +50% de Marcas", "Time bonus: +50% Marks"),
    ("{} · inimigos {} · grupo {}/{}", "{} · enemies {} · party {}/{}"),
    ("A Caçada (raid) chega em breve.", "The Hunt (raid) is coming soon."),
    ("Tempo esgotado: o estágio falhou.", "Out of time: the stage failed."),
    ("Vitória! Toque no baú para abrir.", "Victory! Tap the chest to open it."),
    ("{} · {} · limite {} · vitórias {}", "{} · {} · limit {} · wins {}"),
    ("Nenhuma sala aberta neste estágio.", "No room open at this stage."),
    ("Procurando grupo · {} · {} na fila", "Finding a party · {} · {} in the queue"),
    ("{} item(ns) no Correio: bolsa cheia", "{} item(s) in your Mail: bag full"),
    (
        "Junte o saque · a dungeon fecha em {}",
        "Gather the loot · the dungeon closes in {}",
    ),
    ("{lider} · {} jogador(es) · {} vaga(s)", "{lider} · {} player(s) · {} spot(s)"),
    (
        "Sem perda de experiência dentro da dungeon.",
        "No experience lost inside the dungeon.",
    ),
    (
        "Completar as vagas pela fila depois de 1 min",
        "Fill the open spots from the queue after 1 min",
    ),
    (
        "Sem baú de conclusão. A entrada ficou gasta.",
        "No completion chest. The entry was spent.",
    ),
    (
        "Entre sozinho ou vá até lá para formar grupo.",
        "Enter alone or go there to form a party.",
    ),
    (
        "Cada compra do dia custa o triplo da anterior.",
        "Each purchase of the day costs triple the last one.",
    ),
    (
        "Chave de craft {} {:.0}% · Marcas da Tempestade",
        "Crafting key {} {:.0}% · Storm Marks",
    ),
    (
        "Toque no baú para abrir (abre sozinho em 1 min).",
        "Tap the chest to open it (opens by itself in 1 min).",
    ),
    (
        "Entrada livre; sem recompensa, só cobre e Marcas.",
        "Free entry; no reward, just copper and Marks.",
    ),
    (
        "PROCURANDO GRUPO · {} · est. {} · {} · {} na fila",
        "FINDING A PARTY · {} · st. {} · {} · {} in the queue",
    ),
    (
        "Inimigos nível {nivel} · poder mínimo {} · peça até {}",
        "Enemies level {nivel} · minimum power {} · piece up to {}",
    ),
    (
        "Sem entrada você vai como Ajudante: sem peça nem chave.",
        "With no entry you go as a Helper: no piece and no key.",
    ),
    // ────────────────────────── cliente: ganhos e modo economia ──────────────────────────
    ("Ouro", "Gold"),
    ("Mortes", "Deaths"),
    ("Níveis", "Levels"),
    ("{m}m {seg:02}s", "{m}m {seg:02}s"),
    ("DESDE QUE LIGOU", "SINCE YOU STARTED"),
    ("+ {} outros itens", "+ {} other items"),
    ("Nenhum item ainda", "No item yet"),
    ("Deslize para voltar", "Swipe to go back"),
    ("Nenhum item coletado", "No item gathered"),
    ("MODO ECONOMIA DE ENERGIA", "BATTERY SAVER MODE"),
    ("Enquanto você estava fora", "While you were away"),
    ("Lv {} {nome}", "Lv {} {nome}"),
    ("+{q} Energia", "+{q} Energy"),
    // ─────────────────────────── cliente: escolha de NPC ───────────────────────────
    ("Missões", "Quests"),
    ("O que você quer?", "What do you want?"),
    ("toque fora para fechar", "tap outside to close"),
    // ────────────────────────── cliente: evolução de habilidade ──────────────────────────
    ("Cobre {}", "Copper {}"),
    ("Energia {}", "Energy {}"),
    ("Tier {}: {}", "Tier {}: {}"),
    ("PARA O TIER {}", "TO TIER {}"),
    ("Fabricar tomo {}", "Craft tome {}"),
    ("Evoluir habilidade", "Evolve skill"),
    ("Libera no nível {}", "Unlocks at level {}"),
    ("Tier {}  ·  +{:.0}%", "Tier {}  ·  +{:.0}%"),
    ("{} cobre · você: {}", "{} copper · you: {}"),
    ("Tier máximo alcançado", "Maximum tier reached"),
    ("{} Energia · você: {}", "{} Energy · you: {}"),
    ("TOMOS DESTA HABILIDADE", "TOMES FOR THIS SKILL"),
    ("Este tier não pede tomo.", "This tier needs no tome."),
    ("Nível {} · você: {nivel}", "Level {} · you: {nivel}"),
    ("Tier {}  ·  Poder {:.0}%", "Tier {}  ·  Power {:.0}%"),
    ("1 tomo {} · você: {tem_tomo}", "1 tome {} · you: {tem_tomo}"),
    (
        "Fabricar 1 tomo {} desta habilidade — custa {} Energia + {} cobre",
        "Craft 1 tome {} for this skill — costs {} Energy + {} copper",
    ),
    // ──────────────────────── cliente: ficha do personagem ────────────────────────
    ("Bloqueio", "Block"),
    ("PODER  {}", "POWER  {}"),
    ("Red. dano", "Dmg. red."),
    ("Reg. mana", "Mana regen"),
    ("Reg. vida", "Health regen"),
    ("Livres: {}", "Unspent: {}"),
    ("Reg. vigor", "Stamina regen"),
    ("Vigor máx.", "Max stamina"),
    ("Anel mágico", "Magic ring"),
    ("Mana máxima", "Maximum mana"),
    ("Nv. {nivel}", "Lv. {nivel}"),
    ("Vida máxima", "Maximum health"),
    ("Nível máximo", "Maximum level"),
    ("PROFICIÊNCIAS", "PROFICIENCIES"),
    ("Confirmar reset", "Confirm reset"),
    ("Espada e escudo", "Sword and shield"),
    ("Recarga do Dash", "Dash cooldown"),
    ("{}  ·  Nv. {nivel}", "{}  ·  Lv. {nivel}"),
    ("+1 ataque · +2 vida", "+1 attack · +2 health"),
    ("FICHA DO PERSONAGEM", "CHARACTER SHEET"),
    ("Redistribuir grátis", "Redistribute for free"),
    ("+1 defesa · bloqueio", "+1 defence · block"),
    ("Aguardando servidor…", "Waiting for the server…"),
    ("+5 vida · regeneração", "+5 health · regeneration"),
    ("Energia: {} · ponto −{}", "Energy: {} · point −{}"),
    ("+1 dano mágico · +2 mana", "+1 magic damage · +2 mana"),
    ("XP para o próximo nível: {}", "XP to the next level: {}"),
    ("+1 destreza · crítico/ataque", "+1 dexterity · crit/attack"),
    ("Toque novamente para confirmar", "Tap again to confirm"),
    ("Bônus ativos com a arma equipada", "Bonuses active with the equipped weapon"),
    ("Aguardando atributos do servidor…", "Waiting for attributes from the server…"),
    ("Equipe esta arma para ativar os bônus", "Equip this weapon to activate the bonuses"),
    (
        "+2 vigor · regeneração · recarga do Dash",
        "+2 stamina · regeneration · Dash cooldown",
    ),
    (
        "Destreza também aumenta o dano desta arma.",
        "Dexterity also raises this weapon's damage.",
    ),
    (
        "Os bônus são calculados pelo seu nível atual.",
        "The bonuses are worked out from your current level.",
    ),
    // ──────────────────────────────── cliente: forja ────────────────────────────────
    ("Forja", "Forge"),
    ("na bolsa", "in your bag"),
    ("Chance: {}%", "Chance: {}%"),
    ("Vel. coleta", "Gather speed"),
    ("Sim, refinar", "Yes, refine"),
    ("Vel. montado", "Mounted speed"),
    ("+{} (no topo)", "+{} (at the top)"),
    ("Cobre {cu}/{}", "Copper {cu}/{}"),
    ("Darksteel {ds}/{}", "Darksteel {ds}/{}"),
    ("Refinar (arriscado)", "Refine (risky)"),
    ("Não deu pra refinar.", "Refining wasn't possible."),
    ("Refinar mesmo assim?", "Refine anyway?"),
    ("SE O REFINO DER CERTO", "IF THE REFINE SUCCEEDS"),
    ("Não refinou: {motivo}.", "Not refined: {motivo}."),
    ("Poder {a} › {b}  (+{})", "Power {a} › {b}  (+{})"),
    ("Nenhuma peça refinável.", "No refinable piece."),
    ("Este item não ganha atributo.", "This item gains no attribute."),
    ("Falhou e {nome} foi destruída.", "It failed and {nome} was destroyed."),
    ("Falhar aqui só gasta o material.", "Failing here only spends the material."),
    ("Sucesso! {nome} agora é +{nivel}.", "Success! {nome} is now +{nivel}."),
    ("{}% de subir · {}% de DESTRUIR a peça.", "{}% to rise · {}% to DESTROY the piece."),
    ("Atenção: se falhar, a peça é DESTRUÍDA.", "Careful: if it fails, the piece is DESTROYED."),
    (
        "Falhou. {nome} continua +{nivel} (só o material foi).",
        "It failed. {nome} stays +{nivel} (only the material was spent).",
    ),
    (
        "até +5 é seguro · do +6 em diante falhar destrói a peça",
        "up to +5 is safe · from +6 on, failing destroys the piece",
    ),
    (
        "Destruída, ela não volta: o refino e os materiais dela vão junto.",
        "Once destroyed it does not come back: its refine and its materials go with it.",
    ),
    // ────────────────────────────── cliente: guarda-roupa ──────────────────────────────
    ("Pele", "Skin tone"),
    ("Rosto", "Face"),
    ("Cabelo", "Hair"),
    ("padrão", "default"),
    ("Aplicar", "Apply"),
    ("sem cabelo", "no hair"),
    ("Aparência e skins", "Appearance and skins"),
    ("Arraste para girar", "Drag to rotate"),
    ("Carregando personagem…", "Loading character…"),
    (
        "Veja as mudanças antes de aplicar.",
        "See the changes before applying them.",
    ),
    // ───────────────────────────── cliente: habilidades ─────────────────────────────
    ("Solte: AUTO", "Release: AUTO"),
    ("{} · Tier {}", "{} · Tier {}"),
    ("Solte: MANUAL", "Release: MANUAL"),
    ("Skill em recarga", "Skill on cooldown"),
    ("Mana insuficiente", "Not enough mana"),
    ("Skill interrompida", "Skill interrupted"),
    ("Uso automático ativado", "Automatic use switched on"),
    ("Personagem incapacitado", "Character incapacitated"),
    ("Uso automático desativado", "Automatic use switched off"),
    ("Aguarde terminar a ação atual", "Wait for the current action to finish"),
    ("Esta skill ainda está bloqueada", "This skill is still locked"),
    (
        "Selecione um inimigo para usar esta skill",
        "Select an enemy to use this skill",
    ),
    (
        "Lv {}  ·  {} MP  ·  {:.0}s  ·  {}  ·  pra cima: AUTO · pra baixo: manual",
        "Lv {}  ·  {} MP  ·  {:.0}s  ·  {}  ·  up: AUTO · down: manual",
    ),
    // ───────────────────────────────── cliente: HUD ─────────────────────────────────
    ("Grupo", "Party"),
    ("Avisos", "Notices"),
    ("Hostil", "Hostile"),
    ("Montar", "Mount"),
    ("{min}m", "{min}m"),
    ("Pacífico", "Peaceful"),
    ("Presença", "Presence"),
    ("Desmontar", "Dismount"),
    ("Explorando", "Exploring"),
    ("Lv {nivel}", "Lv {nivel}"),
    ("Curando vida", "Healing"),
    ("Mundo aberto", "Open world"),
    ("Recuperando mana", "Recovering mana"),
    ("{nome} · {:.0} s", "{nome} · {:.0} s"),
    ("{} · sem estoque", "{} · out of stock"),
    ("Recuperando vigor", "Recovering stamina"),
    ("{dica} · {min} min", "{dica} · {min} min"),
    ("+{}% chance de drop", "+{}% drop chance"),
    ("Ligar sprint [Shift]", "Sprint on [Shift]"),
    ("Desligar sprint [Shift]", "Sprint off [Shift]"),
    ("Toque para ativar Hostil", "Tap to switch to Hostile"),
    ("Toque para ficar Pacífico", "Tap to go Peaceful"),
    ("+{}% ouro e cobre de bicho", "+{}% gold and copper from beasts"),
    (
        "Espaço vazio · clique pra configurar",
        "Empty slot · click to configure",
    ),
    (
        "{:.0} fps · tick {tick} · {ents} entidades · {pedacos}/{vivos} terreno",
        "{:.0} fps · tick {tick} · {ents} entities · {pedacos}/{vivos} terrain",
    ),
    (
        "{base} · {} · pra cima: AUTO · pra baixo: manual · botão direito configura",
        "{base} · {} · up: AUTO · down: manual · right click configures",
    ),
    // ────────────────────────────── cliente: invocação ──────────────────────────────
    ("Tomo", "Tome"),
    ("Chave", "Key"),
    ("Grau {}", "Grade {}"),
    ("Tomo {}", "Tome {}"),
    ("Habilidade", "Skill"),
    ("REVELANDO…", "REVEALING…"),
    ("Chifre Azul", "Blue Horn"),
    ("Chave de Craft", "Crafting Key"),
    ("ABRINDO PERGAMINHO", "OPENING THE SCROLL"),
    ("toque para revelar", "tap to reveal"),
    ("INVOCAÇÃO CONCLUÍDA", "SUMMONING COMPLETE"),
    ("11 PRÊMIOS · BÔNUS 10+1", "11 PRIZES · 10+1 BONUS"),
    ("{} · agora x{quantidade}", "{} · now x{quantidade}"),
    ("{nome} · você possui x{quantidade}", "{nome} · you own x{quantidade}"),
    (
        "Equipe no slot da montaria: {:.0}% de velocidade montado",
        "Equip in the mount slot: {:.0}% mounted speed",
    ),
    (
        "Equipe no slot do pet: busca o saque a {:.0} tiles e dá {} pontos",
        "Equip in the pet slot: picks loot up at {:.0} tiles and gives {} points",
    ),
    // ────────────────────────────── cliente: ir até lá ──────────────────────────────
    ("Chegou: {}.", "Arrived: {}."),
    ("INDO · {} · {:.0} m", "HEADING · {} · {:.0} m"),
    ("Não achei caminho até {rotulo}.", "I found no path to {rotulo}."),
    // ──────────────────────────── cliente: login com Google ────────────────────────────
    ("Abrindo o Google…", "Opening Google…"),
    ("Não deu pra iniciar: {e}", "Could not start: {e}"),
    ("O pedido expirou. Tente de novo.", "The request expired. Try again."),
    ("Aguardando confirmação no navegador…", "Waiting for confirmation in the browser…"),
    ("Tempo esgotado esperando o navegador.", "Timed out waiting for the browser."),
    // ─────────────────────────────── cliente: lojas ───────────────────────────────
    ("Máx", "Max"),
    ("Comprar {}x", "Buy {}x"),
    ("na bolsa: {}", "in your bag: {}"),
    ("Nada à venda.", "Nothing for sale."),
    ("Trocar por {}x", "Trade for {}x"),
    ("Total: {} {moeda}", "Total: {} {moeda}"),
    ("Moedas Mágicas: {}", "Magic Coins: {}"),
    ("Cobre {}  ·  Ouro {}", "Copper {}  ·  Gold {}"),
    ("Equipamento: um por vez.", "Gear: one at a time."),
    ("Vendedores da ilha", "Island vendors"),
    ("Nenhum vendedor nesta ilha.", "No vendor on this island."),
    (
        "Só se compra falando com o vendedor: \"Ir\" leva você até ele.",
        "You can only buy by talking to the vendor: \"Go\" takes you to them.",
    ),
    // ───────────────────────────── cliente: loja de TP ─────────────────────────────
    ("Pets", "Pets"),
    ("{n}x", "{n}x"),
    ("Preço", "Price"),
    ("Moedas", "Coins"),
    ("Roxa 5%", "Purple 5%"),
    ("{lote}x", "{lote}x"),
    ("AGUARDE…", "PLEASE WAIT…"),
    ("Azul 12%", "Blue 12%"),
    ("Roxo 20%", "Purple 20%"),
    ("Aparência", "Appearance"),
    ("Cinza 55%", "Grey 55%"),
    ("Seu saldo", "Your balance"),
    ("Verde 28%", "Green 28%"),
    ("Verde 75%", "Green 75%"),
    ("COMPRAR TP", "BUY TP"),
    ("Bolsa de TP", "TP pouch"),
    ("Lendário 5%", "Legendary 5%"),
    ("Você recebe", "You receive"),
    ("MELHOR VALOR", "BEST VALUE"),
    ("{:.1} TP/mil", "{:.1} TP/thousand"),
    ("+{}% DE BÔNUS", "+{}% BONUS"),
    ("Após a compra", "After the purchase"),
    ("Loja: {texto}", "Shop: {texto}"),
    ("{} de Energia", "{} Energy"),
    ("{} de uma vez", "{} at once"),
    ("Confirmar compra", "Confirm purchase"),
    ("Invocação de Pet", "Pet Summoning"),
    ("{} + {} de bônus", "{} + {} bonus"),
    ("Compra concluída!", "Purchase complete!"),
    ("1 entrada · 30 min", "1 entry · 30 min"),
    ("COMPRAR PERGAMINHO", "BUY SCROLL"),
    ("Invocação de Tomos", "Tome Summoning"),
    ("PAGAMENTO SIMULADO", "SIMULATED PAYMENT"),
    ("Preço · {lote}x {}", "Price · {lote}x {}"),
    ("Saldo insuficiente", "Not enough balance"),
    ("{:.0} TP por passe", "{:.0} TP per pass"),
    ("{} · entra na hora", "{} · applied right away"),
    ("Invocação de Chaves", "Key Summoning"),
    ("{} entradas · {} min", "{} entries · {} min"),
    ("Últimas compras:  {}", "Latest purchases:  {}"),
    ("Carregando a vitrine…", "Loading the storefront…"),
    ("Invocação de Montaria", "Mount Summoning"),
    ("Pacote de Tempest Points", "Tempest Points bundle"),
    ("Toque para ver e comprar", "Tap to view and buy"),
    ("1 chave aleatória de craft.", "1 random crafting key."),
    ("1 montaria, espécie sorteada.", "1 mount, species drawn at random."),
    ("{} de Energia · entra na hora", "{} Energy · applied right away"),
    ("Itens exclusivos da Tempestade", "Items exclusive to the Storm"),
    ("1 pet coletor, espécie sorteada.", "1 gatherer pet, species drawn at random."),
    ("Nenhuma aparência à venda agora.", "No appearance for sale right now."),
    ("1 tomo para uma de 12 habilidades.", "1 tome for one of 12 skills."),
    ("Pagamento simulado: nada é cobrado.", "Simulated payment: nothing is charged."),
    ("A loja está desligada neste servidor.", "The shop is switched off on this server."),
    ("MONTADO · {nome} · cavaleiro no tigre", "MOUNTED · {nome} · rider on the tiger"),
    (
        "Pergaminho · abra na bolsa · chave aleatória",
        "Scroll · open it in your bag · random key",
    ),
    (
        "TP é da conta e vale em todos os servidores.",
        "TP belongs to the account and works on every server.",
    ),
    (
        "Chapéu · fica no guarda-roupa deste personagem",
        "Hat · kept in this character's wardrobe",
    ),
    (
        "Pergaminho · 1 montaria · espécie e cor sorteadas",
        "Scroll · 1 mount · species and colour drawn at random",
    ),
    (
        "Pergaminho de Invocação: Montaria entregue na bolsa!",
        "Summoning Scroll: Mount delivered to your bag!",
    ),
    (
        "Pergaminho · tomo aleatório para 1 de 12 habilidades",
        "Scroll · random tome for 1 of 12 skills",
    ),
    (
        "Pergaminho · 1 pet coletor · espécie e grau sorteados",
        "Scroll · 1 gatherer pet · species and grade drawn at random",
    ),
    (
        "Roupa completa · fica no guarda-roupa deste personagem",
        "Full outfit · kept in this character's wardrobe",
    ),
    (
        "Passe · vai pra bolsa · use quando quiser ({} entrada{})",
        "Pass · goes to your bag · use it whenever you like ({} use{})",
    ),
    (
        "Skin · use na bolsa · fica no guarda-roupa deste personagem",
        "Skin · use it from your bag · kept in this character's wardrobe",
    ),
    (
        "Montarias e skins não dão poder de combate: só estilo e mobilidade.",
        "Mounts and skins give no combat power: only style and mobility.",
    ),
    (
        "MUNDO · {nome} · lobo, urso, tigre, owlbear, chefe Lobo Alfa, cavaleiro no tigre",
        "WORLD · {nome} · wolf, bear, tiger, owlbear, Alpha Wolf boss, rider on the tiger",
    ),
    // ─────────────────────────────── cliente: Ilha Mágica ───────────────────────────────
    ("Ponte", "Bridge"),
    ("relógio", "clock"),
    ("sem bônus", "no bonus"),
    ("PvP aberto", "PvP open"),
    ("Ilha Mágica", "Magic Island"),
    ("{n} = {}min", "{n} = {}min"),
    ("Sair da ilha", "Leave island"),
    ("Abre no nível {}", "Opens at level {}"),
    ("Entrar — {n} grátis", "Enter — {n} free"),
    ("Entrar — {n} passe(s)", "Enter — {n} pass(es)"),
    ("Zona segura · sem PvP", "Safe zone · no PvP"),
    ("Voltar sem gastar passe", "Go back without spending a pass"),
    ("Mobs nv {}-{} · poder {}", "Mobs lv {}-{} · power {}"),
    ("{} · mobs nv {}-{} · poder {}", "{} · mobs lv {}-{} · power {}"),
    ("Trocar de ilha sem gastar passe", "Switch island without spending a pass"),

    ("Mobs nv {}-{} · poder {} · você {}", "Mobs lv {}-{} · power {} · you {}"),
    ("Trocar e sair não pausam o relógio.", "Switching and leaving do not pause the clock."),
    ("Entrar — {de_graca} grátis + {} passe", "Enter — {de_graca} free + {} pass"),
    (
        "Seu tempo continua correndo fora da ilha.",
        "Your time keeps running while you are off the island.",
    ),
    (
        "Cada entrada vale 30 min. As grátis voltam às 4h.",
        "Each entry is worth 30 min. The free ones come back at 4am.",
    ),
    (
        "Sete ilhotas por pontes · PvP aberto · morrer volta à chegada",
        "Seven islets joined by bridges · PvP open · dying sends you back to the landing",
    ),
    (
        "Sem entrada: as 3 grátis voltam às 4h, e o passe cai de chefes.",
        "No entry left: the 3 free ones come back at 4am, and passes drop from bosses.",
    ),
    // ──────────────────────── cliente: o laço principal e o login ────────────────────────
    ("Loja", "Shop"),
    ("e-mail", "e-mail"),
    ("não deu", "didn't work"),
    ("usuário", "username"),
    ("Indo: {}", "Heading to: {}"),
    ("Banqueira", "Banker"),
    ("Criado: {}", "Created: {}"),
    ("Personagem", "Character"),
    ("AUTO COLETA", "AUTO GATHER"),
    ("AUTO MISSÃO", "AUTO QUEST"),
    ("SEM CONEXÃO", "NO CONNECTION"),
    ("criar conta", "create account"),
    ("falhou: {e}", "failed: {e}"),
    ("falhou: {m}", "failed: {m}"),
    ("AUTO COMBATE", "AUTO COMBAT"),
    ("Andando · {}", "Walking · {}"),
    ("Tutorial: {}", "Tutorial: {}"),
    ("sair da fila", "leave queue"),
    ("teto de 10 s", "10 s cap"),
    ("{jog} online", "{jog} online"),
    ("enviar o link", "send the link"),
    ("Banco · {nome}", "Bank · {nome}"),
    ("kick: {reason}", "kicked: {reason}"),
    ("lembrar de mim", "remember me"),
    ("loja: {reason}", "shop: {reason}"),
    ("AGUARDANDO VOCÊ", "WAITING FOR YOU"),
    ("CHEFE DERROTADO", "BOSS DEFEATED"),
    ("Fechar tutorial", "Close the tutorial"),
    ("Nova missão: {}", "New quest: {}"),
    ("e-mail inválido", "invalid e-mail"),
    ("fila de entrada", "entry queue"),
    ("indo pra {zona}", "heading to {zona}"),
    ("mapa: lá é água", "map: that is water"),
    ("repetir a senha", "repeat the password"),
    ("Grupo: em breve.", "Party: coming soon."),
    ("MISSÃO CONCLUÍDA", "QUEST COMPLETE"),
    ("Mercado: {texto}", "Market: {texto}"),
    ("Sem {} na bolsa.", "No {} in your bag."),
    ("procurar de novo", "search again"),
    ("servidor {realm}", "server {realm}"),
    ("Entrar com Google", "Sign in with Google"),
    ("Avisos: nada novo.", "Notices: nothing new."),
    ("Missão aceita: {}.", "Quest accepted: {}."),
    ("escolha o servidor", "choose the server"),
    ("Mapa: só nas ilhas.", "Map: only on the islands."),
    ("esqueci minha senha", "I forgot my password"),
    ("Auto missão pausada.", "Auto quest paused."),
    ("{} · {}/{} · Pronta!", "{} · {}/{} · Ready!"),
    ("Indo ao banco: {nome}", "Heading to the bank: {nome}"),
    ("Não achei o NPC aqui.", "I couldn't find the NPC here."),
    ("este canal está cheio", "this channel is full"),
    ("nenhum servidor no ar", "no server online"),
    ("{posicao}º de {total}", "{posicao} of {total}"),
    ("{} exige ação manual.", "{} needs you to act."),
    ("Não aprimorou: {texto}", "Not upgraded: {texto}"),
    ("login negado: {reason}", "login denied: {reason}"),
    ("Craft recusado: {motivo}", "Craft refused: {motivo}"),
    ("Sem visada · aproximando", "No line of sight · closing in"),
    ("procurando servidores...", "looking for servers..."),
    ("Digite o e-mail da conta.", "Type the account's e-mail."),
    ("Nenhum inimigo por perto.", "No enemy nearby."),
    ("viagem: caminho bloqueado", "travel: path blocked"),
    ("Missões concluídas: {} · {}", "Quests completed: {} · {}"),
    ("Aprimorado: {} agora é {} {}!", "Upgraded: {} is now {} {}!"),
    ("Sem visada · trocando de alvo", "No line of sight · switching target"),
    ("as duas senhas não são iguais", "the two passwords don't match"),
    ("senha: no mínimo 6 caracteres", "password: at least 6 characters"),
    ("usuário: de 1 a 32 caracteres", "username: 1 to 32 characters"),
    ("Auto missão pausada: você caiu.", "Auto quest paused: you went down."),
    ("Não consegui abrir o navegador.", "I couldn't open the browser."),
    ("Saque no chão · colete os itens", "Loot on the ground · pick the items up"),
    ("senha: no máximo 128 caracteres", "password: at most 128 characters"),
    ("Auto coleta: atacado, revidando.", "Auto gather: attacked, striking back."),
    ("Fila terminada: {f} missão(ões).", "Queue finished: {f} quest(s)."),
    ("sua sessão expirou — entre de novo", "your session expired — sign in again"),
    ("Auto missão seguiu para \"{nome}\".", "Auto quest moved on to \"{nome}\"."),
    ("Missão: crie um equipamento no Craft.", "Quest: craft a piece of gear in Craft."),
    ("Missão: tente refinar uma peça na Forja.", "Quest: try refining a piece at the Forge."),
    (
        "Auto missão: só restam passos que são seus.",
        "Auto quest: only steps that are yours to do are left.",
    ),
    (
        "Fila terminada: {f} feita(s), {pl} pulada(s).",
        "Queue finished: {f} done, {pl} skipped.",
    ),
    (
        "Seguindo {nome}. Mova-se ou use Esc para parar.",
        "Following {nome}. Move or press Esc to stop.",
    ),
    (
        "Missão: vença a dungeon (o auto não luta por você).",
        "Quest: win the dungeon (auto does not fight for you).",
    ),
    (
        "{from} convidou você para um grupo. Abra Menu › Grupo.",
        "{from} invited you to a party. Open Menu › Party.",
    ),
    (
        "Fila: {} missões. O que não der pra fazer agora é pulado.",
        "Queue: {} quests. Whatever can't be done now is skipped.",
    ),
    (
        "Banco: procure a Banqueira da cidade ou o Banqueiro do porto.",
        "Bank: look for the Banker in the city or the Banker at the port.",
    ),
    (
        "Esse mob não aparece na ilha atual. Viaje para a ilha dele antes de usar Ir.",
        "That mob does not appear on the current island. Travel to its island before using Go.",
    ),
    (
        "Montaria: equipe uma no slot Montaria da bolsa. Onde obter: Menu › Comércio › Loja.",
        "Mount: equip one in the Mount slot of your bag. Where to get one: Menu › Trade › Shop.",
    ),
    (
        "Mapa: toque um círculo FORTE para ir à área com mais mobs. Ao chegar, o auto combate liga.",
        "Map: tap a STRONGHOLD circle to head for the area with more mobs. On arrival, auto combat switches on.",
    ),
    (
        "Secundárias: toque Pegar, depois Ir. A auto missão segue o objetivo; craft e dungeon pedem sua ação.",
        "Side quests: tap Take, then Go. Auto quest follows the objective; craft and dungeon need you to act.",
    ),
    (
        "Se houver uma conta com esse e-mail, o link já saiu.                          Confira a caixa de entrada e o spam.",
        "If an account with that e-mail exists, the link is already on its way.                          Check your inbox and your spam.",
    ),
    // ───────────────────────────────── cliente: mapa ─────────────────────────────────
    ("Ilha", "Island"),
    ("Mobs", "Mobs"),
    ("Vila", "Village"),
    ("água", "water"),
    ("Mundo", "World"),
    ("Vilas", "Villages"),
    ("Bichos", "Beasts"),
    ("Chefes", "Bosses"),
    ("Cidade", "City"),
    ("Filtros", "Filters"),
    ("Ir para", "Go to"),
    ("Madeira", "Wood"),
    ("Recurso", "Node"),
    ("Recursos", "Nodes"),
    ("sem zona", "no zone"),
    ("Barqueiro", "Boatman"),
    ("Pedra azul", "Blue stone"),
    ("Pedra roxa", "Purple stone"),
    ("Pedra cinza", "Grey stone"),
    ("Pedra verde", "Green stone"),
    ("Bicho {kind}", "Beast {kind}"),
    ("Zona de caça", "Hunting zone"),
    ("Mapa · {nome}", "Map · {nome}"),
    ("Mural da Ilha", "Island Board"),
    ("Nv {a}–{b} · ", "Lv {a}–{b} · "),
    ("Praça da vila", "Village square"),
    (" · volta em {}", " · back in {}"),
    ("carregando mapa…", "loading map…"),
    ("carregando zonas…", "loading zones…"),
    ("Viajando · {:.0} m", "Travelling · {:.0} m"),
    ("Forte · {} · Nv {}–{}", "Stronghold · {} · Lv {}–{}"),
    ("consultando as ilhas…", "asking the islands…"),
    ("{n} regiões · {:.0} m", "{n} regions · {:.0} m"),
    ("nenhuma ilha respondeu.", "no island replied."),
    ("NPCs ({n_npcs}) · {acao}", "NPCs ({n_npcs}) · {acao}"),
    ("clique: ir caçar (auto combate)", "click: go hunt (auto combat)"),
    ("clique: ir coletar (auto coleta)", "click: go gather (auto gather)"),
    ("clique: ir falar (ou teleportar)", "click: go talk (or teleport)"),
    ("muito mais inimigos no mesmo espaço", "many more enemies in the same space"),
    ("chefes de todas as ilhas · Esc fecha", "bosses from every island · Esc closes"),
    (
        "clique: viajar · zona/recurso: ir · Esc fecha",
        "click: travel · zone/node: go · Esc closes",
    ),
    // ─────────────────────────────── cliente: o menu ───────────────────────────────
    ("Clã", "Clan"),
    ("Mapa", "Map"),
    ("Barra", "Bar"),
    ("Ficha", "Sheet"),
    ("Todas", "All"),
    ("Amigos", "Friends"),
    ("Coleta", "Gathering"),
    ("Trocar", "Switch"),
    ("Correio", "Mail"),
    ("Mercado", "Market"),
    ("COMÉRCIO", "TRADE"),
    ("Encantar", "Enchant"),
    ("Conquistas", "Achievements"),
    ("Vendedores", "Vendors"),
    ("Habilidades", "Skills"),
    ("Recuperar XP", "Recover XP"),
    // ────────────────────────── cliente: o diário de missões ──────────────────────────
    ("Abrir", "Open"),
    ("Fazer", "Do"),
    ("Todos", "All"),
    ("Facção", "Faction"),
    ("MISSÕES", "QUESTS"),
    ("Detalhes", "Details"),
    ("História", "Story"),
    ("A oficina", "Workshop"),
    ("Concluída", "Completed"),
    ("Bloqueadas", "Locked"),
    ("Como subir", "How to level"),
    ("Concluídas", "Completed"),
    ("Na ilha {}", "On {}"),
    ("Só para {}", "Only for {}"),
    ("Conclua: {}", "Complete: {}"),
    ("Disponíveis", "Available"),
    ("Secundárias", "Side quests"),
    ("Conclua: {t}", "Complete: {t}"),
    ("Dá: {premio}", "Gives: {premio}"),
    ("Em andamento", "In progress"),
    ("Fazer as {n}", "Do all {n}"),
    ("Marcar todas", "Select all"),
    ("{}h {:02}min", "{}h {:02}min"),
    ("Gente da vila", "Village folk"),
    ("Mãos na terra", "Hands in the soil"),
    ("Requer nível ", "Requires level "),
    ("Subida do Gelo", "The Ice Climb"),
    ("Tutorial · {o}", "Tutorial · {o}"),
    ("Guia do Mirante", "Lookout Guide"),
    ("Porões e adegas", "Cellars and vaults"),
    ("{} de {} passos", "{} of {} steps"),
    ("Costa das Morsas", "Walrus Coast"),
    ("O que fazer: {}.", "What to do: {}."),
    ("qualquer dungeon", "any dungeon"),
    ("{} pts de facção", "{} faction pts"),
    ("Os primeiros dias", "The first days"),
    ("Abrigo da Floresta", "Forest Shelter"),
    ("Alcance o nível {}", "Reach level {}"),
    ("Passagem dos Ursos", "Bear Pass"),
    ("Porão do Naufrágio", "Shipwreck Cellar"),
    ("a dungeon indicada", "the dungeon named"),
    ("Bestiário do Bosque", "Bestiary of the Grove"),
    ("Os chefes do Bosque", "The bosses of the Grove"),
    ("Passo {} de {} · {}", "Step {} of {} · {}"),
    ("Segredos da Geleira", "Secrets of the Glacier"),
    ("Nada de {} nesta aba.", "No {} in this tab."),
    ("Nada pra pegar agora.", "Nothing to take right now."),
    ("Nenhuma linha travada.", "No locked line."),
    ("Pronta · entregar: {q}", "Ready · turn in to: {q}"),
    ("Aprenda a fazer missões", "Learn how quests work"),
    ("Conclua a raid indicada", "Complete the raid named"),
    ("\"{}\" já foi concluída.", "\"{}\" has already been completed."),
    ("Indisponível nesta versão", "Unavailable in this version"),
    ("\"{}\" exige ação manual.", "\"{}\" needs you to act."),
    ("Siga a descrição da missão", "Follow the quest description"),
    ("Tutorial · {o}  {}/{total}", "Tutorial · {o}  {}/{total}"),
    ("Disponível · pegar com: {q}", "Available · take it from: {q}"),
    ("Manual · {feito}/{total} · {}", "Manual · {feito}/{total} · {}"),
    ("Encante o equipamento indicado", "Enchant the gear named"),
    ("Nenhuma linha concluída ainda.", "No line completed yet."),
    ("Disponível de novo em {min} min", "Available again in {min} min"),
    ("A fila já tem {FILA_MAX} missões.", "The queue already has {FILA_MAX} quests."),
    ("Combate PvP: derrote {} rival(is)", "PvP combat: defeat {} rival(s)"),
    ("Mapa: encontre e abra o baú indicado", "Map: find and open the chest named"),
    ("Menu › Craft: crie {} equipamento(s)", "Menu › Craft: create {} piece(s) of gear"),
    ("Menu › Forja: tente refinar {} vez(es)", "Menu › Forge: try refining {} time(s)"),
    ("Nada em andamento. Veja as Disponíveis.", "Nothing in progress. Check Available."),
    (
        "Menu › Dungeons: conclua {} vez(es) {onde}",
        "Menu › Dungeons: complete {onde} {} time(s)",
    ),
    (
        "Fila: {n} de {FILA_MAX} · bloqueada é pulada",
        "Queue: {n} of {FILA_MAX} · locked ones are skipped",
    ),
    (
        "Nível {feito}/{total} · escolha: Ilha Mágica, missões secundárias ou caça em áreas densas",
        "Level {feito}/{total} · your pick: Magic Island, side quests or hunting in dense areas",
    ),
    // ─────────────────────────────── cliente: mercado ───────────────────────────────
    ("Mín", "Min"),
    ("Seu", "Yours"),
    ("Subir", "Up"),
    ("Total", "Total"),
    ("Buscar", "Search"),
    ("Descer", "Down"),
    ("Vender", "Sell"),
    ("Vendeu", "Sold"),
    ("Comprar", "Buy"),
    ("Comprou", "Bought"),
    ("Item {}", "Item {}"),
    ("Seus TP", "Your TP"),
    ("Anunciar", "List"),
    ("Da bolsa", "From bag"),
    ("Entregas", "Deliveries"),
    ("Taxa {}%", "Fee {}%"),
    ("Histórico", "History"),
    ("Próxima ›", "Next ›"),
    ("Página {}", "Page {}"),
    ("Quantidade", "Quantity"),
    ("‹ Anterior", "‹ Previous"),
    ("Anunciar TP", "List TP"),
    ("Gold por TP", "Gold per TP"),
    ("Nada ainda.", "Nothing yet."),
    ("TP a vender", "TP to sell"),
    ("Buscar item…", "Search item…"),
    ("Receber tudo", "Claim everything"),
    ("Meus anúncios", "My listings"),
    ("Ativos ({}/{})", "Active ({}/{})"),
    ("Gold insuficiente.", "Not enough gold."),
    ("Anúncios ativos {}/{}", "Active listings {}/{}"),
    ("Nenhum anúncio ativo.", "No active listing."),
    ("Nada vendável na bolsa.", "Nothing sellable in your bag."),
    ("Preço por unidade (gold)", "Price per unit (gold)"),
    ("TP à venda (gold por TP)", "TP for sale (gold per TP)"),
    ("Escolha um item da bolsa.", "Pick an item from your bag."),
    ("{} gold cada · {} à venda", "{} gold each · {} for sale"),
    ("Nenhum anúncio encontrado.", "No listing found."),
    ("Nenhuma entrega esperando.", "No delivery waiting."),
    ("Ninguém vendendo TP agora.", "Nobody selling TP right now."),
    ("Menor preço à venda: {} gold", "Lowest asking price: {} gold"),
    ("Vender TP libera no nível {}.", "Selling TP unlocks at level {}."),
    ("{presos} vinculado(s) fora da lista", "{presos} bound item(s) left out of the list"),
    (
        "Vender no mercado libera no nível {}.",
        "Selling on the market unlocks at level {}.",
    ),
    (
        "Vendas, compras, cancelamentos e devoluções esperam aqui.",
        "Sales, purchases, cancellations and returns wait here.",
    ),
    // ──────────────────────── cliente: objetivos das missões ────────────────────────
    ("Chegar", "Reach"),
    ("Ir até", "Go to"),
    ("Juntar", "Collect"),
    ("Vencer", "Beat"),
    ("Viajar", "Travel"),
    ("Coletar", "Gather"),
    ("Aprender", "Learn"),
    ("Derrotar", "Defeat"),
    ("Entregar", "Turn in"),
    ("Objetivo", "Objective"),
    ("Abandonar", "Abandon"),
    ("Conversar", "Talk"),
    ("Ir até {}", "Go to {}"),
    ("Missões ›", "Quests ›"),
    ("{}x {nome}", "{}x {nome}"),
    ("Concluindo…", "Turning in…"),
    ("Diário de missões", "Quest journal"),
    ("quem deu a missão", "whoever gave the quest"),
    ("Conversar com {nome}", "Talk to {nome}"),
    ("Nenhuma missão ativa.", "No active quest."),
    ("Pronta — entregue: {quem}", "Ready — turn in to: {quem}"),
    ("Fale com o Capitão do Porto", "Talk to the Harbour Captain"),
    ("Nenhuma missão em andamento", "No quest in progress"),
    ("Vencer {} · toque para abrir", "Beat {} · tap to open"),
    ("Alcance o nível {} · você: {nivel}", "Reach level {} · you: {nivel}"),
    ("Vencer uma dungeon · toque para abrir", "Beat a dungeon · tap to open"),
    (
        "Nenhuma missão ativa. Abra Menu › Missões para pegar várias.",
        "No active quest. Open Menu › Quests to take several.",
    ),
    // ────────────────────────────── cliente: bestiário ──────────────────────────────
    ("{} · seu {}", "{} · yours {}"),
    ("{} · sua {}", "{} · yours {}"),
    ("Proficiência", "Proficiency"),
    ("+{} · sua +{}", "+{} · yours +{}"),
    ("Ataque do mob", "Mob attack"),
    ("Defesa do mob", "Mob defence"),
    ("Poder sugerido", "Suggested power"),
    ("Refino da arma", "Weapon refine"),
    ("Ataque sugerido", "Suggested attack"),
    ("Defesa sugerida", "Suggested defence"),
    ("Peças do conjunto", "Set pieces"),
    ("{} {} Nv{} · suas {}", "{} {} Lv{} · yours {}"),
    ("Visite uma ilha para ver seus mobs.", "Visit an island to see its mobs."),
    ("Toque em um mob para ver os detalhes.", "Tap a mob to see the details."),
    (
        "Inimigos das áreas visitadas · atributos reais do servidor",
        "Enemies from the areas you've visited · real attributes from the server",
    ),
    // ────────────────────────────── cliente: montarias ──────────────────────────────
    ("MONTANDO…", "MOUNTING…"),
    ("Ver na Loja", "See in Shop"),
    ("MINHAS MONTARIAS", "MY MOUNTS"),
    ("Velocidade montado", "Mounted speed"),
    (
        "Nenhuma montaria equipada. Equipe uma no slot Montaria da bolsa — a cor dela manda na velocidade.",
        "No mount equipped. Equip one in the Mount slot of your bag — its colour sets the speed.",
    ),
    // ──────────────────────────────── cliente: morte ────────────────────────────────
    ("Reviver na cidade", "Revive in city"),
    ("VOCÊ FOI DERROTADO", "YOU WERE DEFEATED"),
    ("RECUPERAR EXPERIÊNCIA", "RECOVER EXPERIENCE"),
    ("Recuperar XP · {} ouro", "Recover XP · {} gold"),
    ("{} XP · expira em {resta} h", "{} XP · expires in {resta} h"),
    ("Nenhuma morte para recuperar.", "No death to recover from."),
    ("Recuperar XP (grátis {gratis}/3)", "Recover XP (free {gratis}/3)"),
    ("Grátis hoje: {}/3 · depois custa ouro", "Free today: {}/3 · after that it costs gold"),
    ("Recuperar XP não devolve proficiência.", "Recovering XP does not give proficiency back."),
    (
        "Nenhuma experiência a recuperar desta morte.",
        "No experience to recover from this death.",
    ),
    (
        "Cada proficiência treinada perde XP ao morrer:",
        "Each trained proficiency loses XP when you die:",
    ),
    (
        "Experiência perdida: {} (recuperável por 24 h)",
        "Experience lost: {} (recoverable for 24 h)",
    ),
    (
        "10% do custo do próximo nível. Seu nível pode cair.",
        "10% of the cost of the next level. Your level can drop.",
    ),
    ("{} · fora do ar", "{} · offline"),
    ("{} · você está aqui", "{} · you are here"),
    // ──────────────────────────────── cliente: rede ────────────────────────────────
    ("server fechou", "the server closed the connection"),
    ("conexao TLS nao suportada ainda", "TLS connection not supported yet"),
    // ───────────────────────── cliente: caminhos para o nível ─────────────────────────
    ("ILHA MÁGICA", "MAGIC ISLAND"),
    ("MISSÕES SECUNDÁRIAS", "SIDE QUESTS"),
    ("CAÇAR EM ÁREAS DENSAS", "HUNT IN DENSE AREAS"),
    ("CAMINHOS PARA O NÍVEL {alvo}", "WAYS TO REACH LEVEL {alvo}"),
    (
        "Escolha como ganhar XP para continuar a história.",
        "Choose how to earn XP to carry on with the story.",
    ),
    (
        "PvP nas ilhotas de combate; XP e coleta até 2× nas ilhotas de bônus.",
        "PvP on the combat islets; XP and gathering up to 2× on the bonus islets.",
    ),
    (
        "No mapa, toque um círculo FORTE. Ir leva até lá e liga o auto combate.",
        "On the map, tap a STRONGHOLD circle. Go takes you there and switches auto combat on.",
    ),
    (
        "XP, equipamentos e recursos. Toque Pegar e depois Ir para usar auto missão.",
        "XP, gear and resources. Tap Take and then Go to use auto quest.",
    ),
    ("NÍVEL {nivel}", "LEVEL {nivel}"),
    ("Continuar", "Continue"),
    ("Novidades", "What's new"),
    ("NOVIDADES DO TEMPEST", "WHAT'S NEW IN TEMPEST"),
    // ─────────────────────────────── cliente: oficina ───────────────────────────────
    ("Combinar 1x", "Combine 1x"),
    ("Combinar {n}x", "Combine {n}x"),
    ("Sintetizar 1x", "Synthesise 1x"),
    ("Sintetizar {n}x", "Synthesise {n}x"),
    ("sempre dá certo", "always succeeds"),
    ("{} · {} para {}", "{} · {} to {}"),
    ("{}% por tentativa", "{}% per attempt"),
    ("Cada síntese gasta", "Each synthesis spends"),
    ("Faltam {} de cobre", "Missing {} copper"),
    ("Não criou: {motivo}", "Not created: {motivo}"),
    ("Cada tentativa gasta", "Each attempt spends"),
    ("Falhar consome tudo.", "Failing consumes everything."),
    ("Lendário IV é o topo", "Legendary IV is the top"),
    ("Nenhuma peça na bolsa.", "No piece in your bag."),
    ("Não combinou: {motivo}", "Not combined: {motivo}"),
    ("Requer nível {} para {}", "Requires level {} for {}"),
    ("{} por 1 · {}% · tem {}", "{} for 1 · {}% · you have {}"),
    ("{} · Tier {} · {} na bolsa", "{} · Tier {} · {} in your bag"),
    ("{} por 1 · garantido · tem {}", "{} for 1 · guaranteed · you have {}"),
    ("Falta material para uma tentativa.", "Not enough material for one attempt."),
    ("mostrar só o que dá ({quantas_dao})", "show only what works ({quantas_dao})"),
    ("mostrando só o que dá ({quantas_dao})", "showing only what works ({quantas_dao})"),
    ("Craft de material: {criados}x {saida}!", "Material craft: {criados}x {saida}!"),
    (
        "Crie no Craft ou guarde as que caírem.",
        "Make them in Craft or keep the ones that drop.",
    ),
    (
        "O refino +{perdido} das peças se perde.",
        "The +{perdido} refine on the pieces is lost.",
    ),
    (
        "Duas Tier IV +{} viram uma da cor de cima,",
        "Two Tier IV +{} become one of the colour above,",
    ),
    (
        "Duas peças iguais viram uma do tier de cima,",
        "Two identical pieces become one of the tier above,",
    ),
    (
        "{tentativas} tentativa(s), nenhuma deu certo.",
        "{tentativas} attempt(s), none succeeded.",
    ),
    (
        "no Tier I, com os atributos fixos da nova cor.",
        "at Tier I, with the fixed attributes of the new colour.",
    ),
    (
        "{tentativas} tentativa(s): {sucessos}x {saida}!",
        "{tentativas} attempt(s): {sucessos}x {saida}!",
    ),
    (
        "com os atributos fixos do novo tier, mais fortes.",
        "with the fixed attributes of the new tier, stronger ones.",
    ),
    (
        "Para subir de cor: duas Tier IV +{} (você tem {n})",
        "To raise the colour: two Tier IV +{} (you have {n})",
    ),
    (
        "Precisa de mais uma peça igual (mesmo item, cor e tier)",
        "You need one more identical piece (same item, colour and tier)",
    ),
    (
        "Nada pronto pra criar agora. Toque de novo pra ver a lista inteira.",
        "Nothing ready to create right now. Tap again to see the whole list.",
    ),
    (
        "Nada pronto pra combinar agora. Toque de novo pra ver a lista inteira.",
        "Nothing ready to combine right now. Tap again to see the whole list.",
    ),
    // ────────────────────────────── cliente: onde obter ──────────────────────────────
    ("Ilhas", "Islands"),
    ("Missão", "Quest"),
    ("Outra ilha", "Another island"),
    ("Renascendo", "Respawning"),
    ("Coletar: {}", "Gather: {}"),
    ("Comprar: {}", "Buy: {}"),
    ("Fora de ilha", "Off the islands"),
    ("Caçar: {nome}", "Hunt: {nome}"),
    ("Chefe: {nome}", "Boss: {nome}"),
    ("Criar: {nome}", "Craft: {nome}"),
    ("Missão diária", "Daily quest"),
    ("{preco} de ouro", "{preco} gold"),
    ("Craft de material", "Material craft"),
    ("Não há nesta ilha", "None on this island"),
    ("{} por morte · {}", "{} per kill · {}"),
    ("Onde obter: {nome}", "Where to get: {nome}"),
    ("{} por coleta · {}", "{} per gather · {}"),
    ("Recompensa: {titulo}", "Reward: {titulo}"),
    ("Chefe Nv {nivel} · {}", "Boss Lv {nivel} · {}"),
    ("Calendário de presença", "Attendance calendar"),
    ("Craft · nível mínimo {}", "Craft · minimum level {}"),
    ("Chefe de dungeon (Gruta)", "Dungeon boss (Cavern)"),
    ("Requer nível {nivel_min}", "Requires level {nivel_min}"),
    ("Resgate diário · dia{} {}", "Daily claim · day{} {}"),
    ("Comprar de outros jogadores", "Buy from other players"),
    ("Nv {}–{} · {} por morte · {}", "Lv {}–{} · {} per kill · {}"),
    ("Zona nível {}+: acima do seu nível", "Level {}+ zone: above your level"),
    ("Nenhuma fonte conhecida para este item.", "No known source for this item."),
    ("15/10/6/3/1% por faixa · Caçada em breve", "15/10/6/3/1% per band · Hunt coming soon"),
    (
        "{} da cor anterior · {} cobre · {} darksteel · {} pó",
        "{} of the previous colour · {} copper · {} darksteel · {} dust",
    ),
    (
        "Nível {nivel}: bem acima do seu — o combate não liga sozinho",
        "Level {nivel}: well above yours — combat won't switch on by itself",
    ),
    // ───────────────────────── cliente: escolha de personagem ─────────────────────────
    ("Roupa", "Outfit"),
    ("FACÇÃO", "FACTION"),
    ("APARÊNCIA", "APPEARANCE"),
    ("ARMA INICIAL", "STARTING WEAPON"),
    ("Indisponível", "Unavailable"),
    ("Arma & Facção", "Weapon & Faction"),
    ("nome ja em uso", "name already taken"),
    ("Entrar no mundo", "Enter the world"),
    ("Escolha um nome", "Choose a name"),
    ("Magia e suporte", "Magic and support"),
    ("Nível {}  ·  {}", "Level {}  ·  {}"),
    ("nome 2-24 chars", "name 2-24 chars"),
    ("Criar personagem", "Create character"),
    ("Defesa e pressão", "Defence and pressure"),
    ("Crie sua história", "Write your own story"),
    ("+  Novo personagem", "+  New character"),
    ("NOME DO PERSONAGEM", "CHARACTER NAME"),
    ("Combate à distância", "Ranged combat"),
    ("Abre e fecha a luta", "Opens and closes the fight"),
    ("Criando personagem…", "Creating the character…"),
    ("Escolha seu personagem", "Choose your character"),
    ("SEUS PERSONAGENS  ·  {}", "YOUR CHARACTERS  ·  {}"),
    ("nome so letras/numeros/_", "name: letters/numbers/_ only"),
    ("Prévia sem espaço na tela", "No room for the preview"),
    ("Uma arma. Um novo começo.", "One weapon. One fresh start."),
    ("Use de 2 a 24 caracteres.", "Use 2 to 24 characters."),
    ("Toque para escolher o nome", "Tap to choose the name"),
    ("Piratas em busca de saques.", "Pirates after plunder."),
    ("Aventureiros e exploradores.", "Adventurers and explorers."),
    ("Escolha uma arma disponível.", "Choose an available weapon."),
    ("Arraste o personagem para girar", "Drag the character to rotate"),
    ("Arraste para ver mais personagens", "Drag to see more characters"),
    ("Modelo do personagem indisponível", "Character model unavailable"),
    ("Use um nome de 2 a 24 caracteres.", "Use a name of 2 to 24 characters."),
    ("Aguardando confirmação do servidor…", "Waiting for confirmation from the server…"),
    ("Seu próximo capítulo está esperando.", "Your next chapter is waiting."),
    ("Use letras sem acento, números ou _.", "Use unaccented letters, numbers or _."),
    ("2 a 24 caracteres · letras, números e _", "2 to 24 characters · letters, numbers and _"),
    ("Esse nome já está em uso. Escolha outro.", "That name is already taken. Choose another."),
    (
        "Personagem criado. Sua jornada pode começar.",
        "Character created. Your journey can begin.",
    ),
    (
        "Nenhuma arma inicial disponível neste servidor.",
        "No starting weapon available on this server.",
    ),
    (
        "Sua história começa aqui. Crie seu primeiro personagem.",
        "Your story starts here. Create your first character.",
    ),
    (
        "Mantenha distância com tiros precisos, rajadas e um barril explosivo.",
        "Keep your distance with precise shots, bursts and an explosive barrel.",
    ),
    (
        "Lute na linha de frente com investidas, cortes amplos e uma barreira protetora.",
        "Fight on the front line with charges, wide slashes and a protective barrier.",
    ),
    (
        "Restaure sua vida, cure aliados próximos e invoque um impacto mágico sobre o alvo.",
        "Restore your health, heal nearby allies and call down a magical impact on your target.",
    ),
    (
        "Empunhe com as duas mãos: o saque contra quem ainda não te viu dá 2,5x de dano, e o golpe em alvo abaixo de 30% de vida dá 1,6x. Em troca, o dano contínuo é menor que o das pistolas, e a vida só volta na janela da Dança.",
        "Wield it two-handed: the draw against someone who has not seen you hits for 2.5x, and a strike on a target below 30% health for 1.6x. In exchange its sustained damage is lower than the pistols', and health only comes back inside Danca's window.",
    ),
    // ───────────────────────────────── cliente: pets ─────────────────────────────────
    ("MEUS PETS", "MY PETS"),
    ("Nível máximo.", "Maximum level."),
    ("Alimentar ({racoes})", "Feed ({racoes})"),
    ("Skill para o slot {}", "Skill for slot {}"),
    ("A Ração dura {}h por uso", "Feed lasts {}h per use"),
    ("Alimentado por mais {}h{:02}", "Fed for another {}h{:02}"),
    ("Slot livre · toque para escolher", "Free slot · tap to choose"),
    ("Com fome: não ganha experiência nenhuma", "Hungry: gains no experience at all"),
    ("Faltam {} de experiência para o nível {}", "{} experience short of level {}"),
    ("Nível {nivel} / {} · {ocupados}/3 pets · T{} +{}", "Level {nivel} / {} · {ocupados}/3 pets · T{} +{}"),
    (
        "Toque num slot livre para escolher uma skill da bolsa.",
        "Tap a free slot to choose a skill from your bag.",
    ),
    (
        "Você não tem skills disponíveis na bolsa. Elas podem ser compradas na Loja.",
        "You have no skills available in your bag. They can be bought in the Shop.",
    ),
    (
        "Nenhum pet equipado. Equipe um no slot Pet da bolsa — ele nasce no mundo e busca o saque do chão pra você.",
        "No pet equipped. Equip one in the Pet slot of your bag — it appears in the world and picks loot up off the ground for you.",
    ),
    // ──────────────────────────────── cliente: presença ────────────────────────────────
    ("Inv. Pet", "Pet Summ."),
    ("Resgatar", "Claim"),
    ("Resgatado", "Claimed"),
    ("{} de ouro", "{} gold"),
    ("Dia {n}: {}", "Day {n}: {}"),
    ("Inv. Montaria", "Mount Summ."),
    ("Resgatados {}/{}", "Claimed {}/{}"),
    ("{} · termina em {}", "{} · ends in {}"),
    ("Próximo resgate em {}", "Next claim in {}"),
    ("Nenhum calendário ativo.", "No active calendar."),
    ("Presença · dia {dia}: {}", "Attendance · day {dia}: {}"),
    ("Resgate de hoje disponível", "Today's claim is available"),
    (" (bolsa cheia: parte no Correio)", " (bag full: part of it in your Mail)"),
    ("{} · o mês vira no dia 1 às 04:00", "{} · the month turns over on the 1st at 04:00"),
    (
        "Presença · prêmio pendente entregue: {}",
        "Attendance · pending prize delivered: {}",
    ),
    ("+{} facção", "+{} faction"),
    // ───────────────────────────── cliente: HUD social ─────────────────────────────
    ("Ações +", "Actions +"),
    ("Ações −", "Actions −"),
    ("GRUPO · {}  {}", "PARTY · {}  {}"),
    ("Seguir jogador", "Follow player"),
    ("Adicionar amigo", "Add friend"),
    ("Fora de alcance", "Out of range"),
    ("Parar de seguir", "Stop following"),
    ("Gerenciar grupo ›", "Manage party ›"),
    ("Convidar para grupo", "Invite to party"),
    // ──────────────────── cliente: correio, amigos, clã e grupo ────────────────────
    ("Para", "To"),
    ("Caixa", "Inbox"),
    ("Carta", "Letter"),
    ("Líder", "Leader"),
    ("Apagar", "Delete"),
    ("Capitã", "Captain"),
    ("De: {}", "From: {}"),
    ("Enviar", "Send"),
    ("Assunto", "Subject"),
    ("Remover", "Remove"),
    ("Sistema", "System"),
    (" · Líder", " · Leader"),
    ("Convidar", "Invite"),
    ("Corsário", "Corsair"),
    ("Expulsar", "Kick"),
    ("Mensagem", "Message"),
    ("Adicionar", "Add"),
    ("Confirmar", "Confirm"),
    ("Criar clã", "Create clan"),
    ("Responder", "Reply"),
    ("Recebidos.", "Received."),
    ("Bolsa cheia", "Bag full"),
    ("Buscar item", "Search item"),
    ("Nome do clã", "Clan name"),
    ("Sair do clã", "Leave clan"),
    ("neste canal", "on this channel"),
    ("Aviso do clã", "Clan notice"),
    ("Sair do clã?", "Leave the clan?"),
    ("Salvar aviso", "Save notice"),
    ("Dissolver clã", "Disband clan"),
    ("Poção de Vida", "Health Potion"),
    ("Receber itens", "Claim items"),
    ("Sair do grupo", "Leave party"),
    ("Texto {} / {}", "Text {} / {}"),
    ("Um personagem", "One character"),
    ("Anexos: {} / 8", "Attachments: {} / 8"),
    ("Carta enviada.", "Letter sent."),
    ("Escrever carta", "Write a letter"),
    ("Pedra de Forja", "Forge Stone"),
    ("Voltar à carta", "Back to the letter"),
    ("pedido enviado", "request sent"),
    ("Envio admin/mod", "Admin/mod send"),
    ("Encontro na vila", "Meeting in the village"),
    ("Primeira vitória", "First win"),
    ("Recompensas ({})", "Rewards ({})"),
    ("fora deste canal", "off this channel"),
    ("Apagar esta carta?", "Delete this letter?"),
    ("Convites recebidos", "Invites received"),
    ("Nome do personagem", "Character name"),
    ("quer ser seu amigo", "wants to be your friend"),
    ("{} · convite de {}", "{} · invite from {}"),
    ("Aguardando resgate.", "Waiting to be claimed."),
    ("Convidar personagem", "Invite a character"),
    ("Expulsar {n} do clã?", "Kick {n} from the clan?"),
    ("Recompensa do evento", "Event reward"),
    ("Todos os personagens", "All characters"),
    ("{nome} convidou você", "{nome} invited you"),
    ("Sua caixa está vazia.", "Your inbox is empty."),
    ("Todos: {} personagens", "All: {} characters"),
    ("{}  |  Anexos: {}. {}", "{}  |  Attachments: {}. {}"),
    ("Apagar tudo ({quantas})", "Delete everything ({quantas})"),
    ("Correio oficial enviado", "Official mail sent"),
    ("Oficiais · trocar caixa", "Official · switch inbox"),
    ("Pessoais · trocar caixa", "Personal · switch inbox"),
    ("Você está jogando solo.", "You are playing solo."),
    ("Buscar item por nome ou ID", "Search for an item by name or ID"),
    ("Primeira vitória da semana", "First win of the week"),
    ("Esvaziando a caixa… faltam {}", "Emptying the inbox… {} left"),
    ("Selecione uma carta para ler.", "Select a letter to read."),
    ("Mensagem (até 1000 caracteres)", "Message (up to 1000 characters)"),
    ("Pegar tudo e apagar ({quantas})", "Take everything and delete ({quantas})"),
    ("Prontos para a próxima aventura?", "Ready for the next adventure?"),
    ("{} · {} / {} membros · Líder: {}", "{} · {} / {} members · Leader: {}"),
    ("Você ainda não tem convites de clã.", "You have no clan invites yet."),
    ("Nome do novo clã (3 a 24 caracteres)", "Name of the new clan (3 to 24 characters)"),
    ("Remover amizade ou pedido com {nome}?", "Remove friendship or request with {nome}?"),
    ("Adicione amigos para encontrá-los aqui.", "Add friends to find them here."),
    (
        "Nenhuma recompensa aguardando no Correio.",
        "No reward waiting in your Mail.",
    ),
    (
        "Encontro na vila para a próxima expedição.",
        "Meeting in the village for the next expedition.",
    ),
    (
        "Dissolver o clã e remover todos os membros?",
        "Disband the clan and remove every member?",
    ),
    (
        "TODOS os personagens existentes (aprox. {})",
        "EVERY existing character (approx. {})",
    ),
    (
        "{} / {} amigos · Presença indica este canal",
        "{} / {} friends · Presence points to this channel",
    ),
    (
        "Vamos explorar juntos depois de reunir o grupo?",
        "Shall we explore together once the party is together?",
    ),
    (
        "2 próximos: +10% (55% cada) · 3: +20% (40% cada)",
        "2 nearby: +10% (55% each) · 3: +20% (40% each)",
    ),
    (
        "4 próximos: +30% (32,5% cada) · 5: +30% (26% cada)",
        "4 nearby: +30% (32.5% each) · 5: +30% (26% each)",
    ),
    (
        "Obrigado por participar! Receba seus itens abaixo.",
        "Thank you for taking part! Claim your items below.",
    ),
    (
        "Até 5 jogadores no mesmo canal. Convites duram 60 segundos.",
        "Up to 5 players on the same channel. Invites last 60 seconds.",
    ),
    (
        "Transferir a liderança para {n}? Você perderá a administração do clã.",
        "Transfer leadership to {n}? You will lose control of the clan.",
    ),
    (
        "XP dividida igualmente: membros na mesma área, a até 25 m de quem abate.",
        "XP split evenly: members in the same area, within 25 m of whoever lands the kill.",
    ),
    (
        "Receber os itens de {} carta(s) e apagar as {quantas}? Não dá pra desfazer.",
        "Claim the items from {} letter(s) and delete all {quantas}? This cannot be undone.",
    ),
    (
        "Bônus cresce até 4 participantes. Solo: 100%. Frações de XP são descartadas.",
        "The bonus grows up to 4 participants. Solo: 100%. Fractions of XP are discarded.",
    ),
    (
        "Vamos reunir o grupo na vila e explorar as dungeons. Se precisar de ajuda, mande uma carta!",
        "Let's gather the party in the village and explore the dungeons. If you need help, send a letter!",
    ),
    (
        "Enviar correio oficial para {destino}? Assunto: {}. Anexos por destinatário: {}. O envio será registrado e não pode ser desfeito.",
        "Send official mail to {destino}? Subject: {}. Attachments per recipient: {}. The send will be logged and cannot be undone.",
    ),
    // ────────────────────────── cliente: som, chefe e viagem ──────────────────────────
    ("Som: desligado", "Sound: off"),
    ("FASE 1", "PHASE 1"),
    ("FASE 2", "PHASE 2"),
    ("CHEFE · {}", "BOSS · {}"),
    ("{nome} · Lv {nivel}", "{nome} · Lv {nivel}"),
    ("Embarcar", "Board"),
    ("Nível {}–{}", "Level {}–{}"),
    ("Rumo à Geleira", "Bound for the Glacier"),
    ("{nivel} · bloqueada", "{nivel} · locked"),
    ("{nivel} · você está aqui", "{nivel} · you are here"),
    ("{nivel} · libera em \"{}\"", "{nivel} · unlocks at \"{}\""),
    (
        "{nivel} · sem barco agora (servidor fora do ar)",
        "{nivel} · no boat right now (server offline)",
    ),
    (
        "Sua colônia · rende sozinha enquanto você navega",
        "Your colony · yields on its own while you sail",
    ),
    (
        "O Capitão leva a qualquer ilha que a história já abriu.",
        "The Captain will take you to any island the story has opened.",
    ),
    // ─────────────── os que sobraram da varredura (rótulo solto, título curto) ───────────────
    ("Nova: ", "New: "),
    ("Porto", "Port"),
    ("Cobre", "Copper"),
    ("Acessório", "Accessory"),
    ("Outros", "Other"),
    ("Derrote monstros da floresta  3/10", "Defeat forest monsters  3/10"),
    // ───────────────── os rótulos em CAIXA ALTA (HUD, menu, botão) ─────────────────
    //
    // Esta leva quase escapou: a varredura tratava todo literal em caixa alta
    // como nome de const e jogava fora. Só apareceu na captura de tela, com
    // "ATRIBUTOS" e "COMBATE" em português no meio da ficha em inglês — e é
    // justamente a classe mais visível, porque é o menu e o HUD.
    ("ATRIBUTOS", "ATTRIBUTES"),
    ("COMBATE", "COMBAT"),
    ("BOLSA", "BAG"),
    ("PODER", "POWER"),
    ("VOLTAR", "BACK"),
    ("COLETA", "GATHER"),
    ("LIGADO", "ON"),
    ("ATACAR", "ATTACK"),
    ("ALVO", "TARGET"),
    ("VIGOR", "STAMINA"),
    ("CHEFE", "BOSS"),
    ("PERSONAGEM", "CHARACTER"),
    ("PROGRESSO", "PROGRESS"),
    ("OFICINA", "WORKSHOP"),
    ("AVENTURA", "ADVENTURE"),
    ("EVENTO", "EVENT"),
    ("SISTEMA", "SYSTEM"),
    ("SALDOS", "BALANCES"),
    ("MORTO", "DEAD"),
    ("PARADO", "IDLE"),
    ("NOME", "NAME"),
    ("MAPAS", "MAPS"),
    ("MONTARIA", "MOUNT"),
    ("MONTAR", "MOUNT UP"),
    ("ITENS", "ITEMS"),
    ("HABILIDADES", "SKILLS"),
    ("GUARDAR", "STORE"),
    ("FORTE", "STRONGHOLD"),
    // DUAS FORMAS, e não uma com `{}{}` no fim.
    //
    // A linha é montada com um sufixo condicional, então no ar ela existe em
    // duas formas. O verbete único terminado em `{}{}` NÃO casa nenhuma das
    // duas: dois buracos colados deixam entre eles um pedaço fixo vazio, e não
    // há como saber onde um termina e o outro começa. A forma mais longa vem
    // primeiro porque tem mais texto fixo.
    (
        "Grátis hoje {}/{}  ·  Passes {}  ·  resta {}:{}",
        "Free today {}/{}  ·  Passes {}  ·  {}:{} left",
    ),
    ("Grátis hoje {}/{}  ·  Passes {}", "Free today {}/{}  ·  Passes {}"),
    // Chegaram DEPOIS da varredura, com a caixa de grupo no rastreador. É o
    // caso normal: frase nova no jogo, verbete novo aqui.
    ("Você não está em grupo", "You are not in a party"),
    ("Convidar jogadores ›", "Invite players ›"),
    ("fora de alcance", "out of range"),
    ("confira o web (/api/channels)", "check the web (/api/channels)"),
];
