//!  Dados do jogo: itens, habilidades, bichos, loja, pets, montarias, colônia.

pub const VERBETES: &[(&str, &str)] = &[
    // ─────────────────────────── as cores e os graus ───────────────────────────
    // Estas cinco frases aparecem em item, chave, pet, montaria e refino. São a
    // espinha do vocabulário: mudar uma aqui muda o jogo inteiro.
    ("Azul", "Blue"),
    ("Cinza", "Grey"),
    ("Verde", "Green"),
    ("Roxa", "Purple"),
    ("Roxo", "Purple"),
    ("Épica", "Epic"),
    ("Épico", "Epic"),
    ("Lendária", "Legendary"),
    ("Lendário", "Legendary"),
    ("Fino", "Fine"),
    ("Raro", "Rare"),
    // ─────────────────────────── acessórios: os bônus ───────────────────────────
    ("XP recebido +10%", "XP gained +10%"),
    ("Chance de drop +10%", "Drop chance +10%"),
    ("Coleta de Energia +15%", "Energy gathering +15%"),
    ("Coleta de minério +15%", "Ore gathering +15%"),
    ("Regen base de vida +1/s", "Base health regen +1/s"),
    ("Coleta de Darksteel +15%", "Darksteel gathering +15%"),
    ("Chance de loot melhor +5%", "Better loot chance +5%"),
    ("Regen base de mana +0,5/s", "Base mana regen +0.5/s"),
    // ───────────────────────────── aparência: chapéus ─────────────────────────────
    ("Capuz", "Hood"),
    ("Faixa", "Headband"),
    ("Lenço", "Bandana"),
    ("Touca", "Cap"),
    ("Andarilho", "Wanderer"),
    ("Tricórnio", "Tricorne"),
    ("Mercenário", "Mercenary"),
    ("Aventureiro", "Adventurer"),
    ("Boina de Pena", "Feathered Beret"),
    ("Chapéu de Aba", "Brimmed Hat"),
    ("Chapéu Pontudo", "Pointed Hat"),
    ("Capitão da Tempestade", "Storm Captain"),
    // ──────────────────────────── chefes e seus golpes ────────────────────────────
    ("{r}s", "{r}s"),
    ("{m}m{r:02}s", "{m}m{r:02}s"),
    ("Meteoro", "Meteor"),
    ("Rodopio", "Whirl"),
    ("Barragem", "Barrage"),
    ("Investida", "Charge"),
    ("Raio Arcano", "Arcane Bolt"),
    ("Urso Anciao", "Elder Bear"),
    ("Nova de Gelo", "Ice Nova"),
    ("Patada Dupla", "Double Swipe"),
    ("Patada Larga", "Wide Swipe"),
    ("Giro Selvagem", "Feral Spin"),
    ("Linha de Tiro", "Firing Line"),
    ("Onda de Pedra", "Stone Wave"),
    ("Pisao Sismico", "Seismic Stomp"),
    ("Anel de Chamas", "Ring of Flames"),
    ("Corte de Sabre", "Sabre Slash"),
    ("Salto Predador", "Predator Leap"),
    ("Tiro de Canhao", "Cannon Shot"),
    ("Garras em Leque", "Fanning Claws"),
    ("Owlbear Primevo", "Primeval Owlbear"),
    ("Pancada Sísmica", "Seismic Blow"),
    ("Rajada em Leque", "Fanning Volley"),
    ("Relampago Caido", "Fallen Lightning"),
    ("Uivo da Matilha", "Howl of the Pack"),
    ("Arqueira do Ermo", "Archer of the Waste"),
    ("Barril Explosivo", "Explosive Barrel"),
    ("Chuva de Flechas", "Arrow Rain"),
    ("Queda Estrondosa", "Thunderous Fall"),
    ("Rugido Esmagador", "Crushing Roar"),
    ("Flecha Perfurante", "Piercing Arrow"),
    ("Lobo da Tempestade", "Storm Wolf"),
    ("Uivo da Tempestade", "Howl of the Storm"),
    ("Armadilha Espinhosa", "Thorn Trap"),
    ("Mordida Dilacerante", "Rending Bite"),
    ("Investida Trovejante", "Thundering Charge"),
    ("Investida do Colosso", "Charge of the Colossus"),
    ("Saqueador das Areias", "Sand Raider"),
    ("Arquimago da Tormenta", "Archmage of the Tempest"),
    ("Lobo Alfa da Clareira", "Alpha Wolf of the Glade"),
    ("Capitao Barba-Tormenta", "Captain Stormbeard"),
    ("Colosso da Ilha Mágica", "Colossus of the Magic Island"),
    // ──────────────────────────────── a colônia ────────────────────────────────
    ("Casa", "House"),
    ("Ofício", "Trade"),
    ("Castelo", "Castle"),
    ("Curtidor", "Tanner"),
    ("Lenhador", "Woodcutter"),
    ("Minerador", "Miner"),
    ("Assentamento", "Settlement"),
    // ──────────────────────────── os NPCs da vila ────────────────────────────
    ("Armeiro", "Armourer"),
    ("Alfaiate", "Tailor"),
    ("Ferreiro", "Blacksmith"),
    ("Naufrago", "Castaway"),
    ("Banqueiro", "Banker"),
    ("Treinador", "Trainer"),
    ("Cartografo", "Cartographer"),
    ("Taberneiro", "Innkeeper"),
    ("Identificador", "Appraiser"),
    ("Capitao do Porto", "Harbour Captain"),
    ("Mestre de Missoes", "Quest Master"),
    ("Morador", "Resident"),
    ("Alquimista", "Alchemist"),
    ("Mestre", "Master"),
    // ─────────────────────────────── as dungeons ───────────────────────────────
    ("Gruta", "Cavern"),
    ("Caçada", "Hunt"),
    ("Arena", "Arena"),
    ("Forja do Titã", "Forge of the Titan"),
    ("Mãe-da-Nevasca", "Mother of Blizzards"),
    ("Casco Congelado", "Frozen Hull"),
    ("Requer nível {n}", "Requires level {n}"),
    ("Cemitério de Navios", "Ship Graveyard"),
    ("Mosteiro dos Ventos", "Monastery of the Winds"),
    ("Vença o estágio {e}", "Beat stage {e}"),
    ("Grutas de Gelo Fundo", "Deep Ice Caverns"),
    ("Poder {tem}/{precisa}", "Power {tem}/{precisa}"),
    ("Toca dos Lobos-do-Mar", "Sea Wolves' Den"),
    ("Adega do Contrabandista", "Smuggler's Cellar"),
    ("Requer Selo da Tempestade", "Requires a Storm Seal"),
    ("Tumba das Areias Salgadas", "Tomb of the Salt Sands"),
    // ──────────────────────────── a forja: as recusas ────────────────────────────
    ("tire as gemas das peças antes", "take the gems out of the pieces first"),
    (
        "as duas peças precisam ser da mesma cor",
        "both pieces have to be the same colour",
    ),
    (
        "as duas peças precisam ser o mesmo item",
        "both pieces have to be the same item",
    ),
    (
        "as duas peças precisam ter o mesmo tier",
        "both pieces have to be the same tier",
    ),
    (
        "para subir de cor, as duas Tier IV precisam estar +{REFINO_PARA_COR}",
        "to raise the colour, both Tier IV pieces have to be +{REFINO_PARA_COR}",
    ),
    // ─────────────────── os afixos dos itens (a instância de atributos) ───────────────────
    // São sufixos e prefixos que se colam ao nome da peça. Em inglês o gênero
    // desaparece, então "Ágil" e "da Fúria" viram os dois um adjetivo ou um
    // "of the …" — o que soar como nome de item.
    ("Ágil", "Nimble"),
    ("Forte", "Mighty"),
    ("Sábio", "Wise"),
    ("Veloz", "Swift"),
    ("Brutal", "Brutal"),
    ("Mágico", "Arcane"),
    ("do Mago", "of the Mage"),
    ("do Urso", "of the Bear"),
    ("da Fúria", "of Fury"),
    ("do Lince", "of the Lynx"),
    ("do Touro", "of the Bull"),
    ("do Vento", "of the Wind"),
    ("Implacável", "Relentless"),
    ("Resistente", "Sturdy"),
    ("Fortificado", "Fortified"),
    ("da Tartaruga", "of the Turtle"),
    ("do Assassino", "of the Assassin"),
    ("do Manancial", "of the Wellspring"),
    ("da Regeneração", "of Regeneration"),
    // ───────────────────────────── a loja de TP: os pacotes ─────────────────────────────
    ("Baú de TP", "TP Chest"),
    ("Saco de Ouro", "Sack of Gold"),
    ("Punhado de TP", "Handful of TP"),
    ("R$ {r},{c:02}", "R$ {r}.{c:02}"),
    ("Saco de Cobre", "Sack of Copper"),
    ("Tesouro de TP", "TP Hoard"),
    ("Bolsa de Passes", "Pouch of Passes"),
    ("TP insuficiente.", "Not enough TP."),
    ("Núcleo de Energia", "Energy Core"),
    ("Punhado de Passes", "Handful of Passes"),
    ("Cristal de Energia", "Energy Crystal"),
    ("Fagulha de Energia", "Energy Spark"),
    ("Removedor de Skill", "Skill Remover"),
    ("Barras de Darksteel", "Darksteel Bars"),
    ("Produto indisponível.", "Product unavailable."),
    (
        "Tira todas as skills do pet e devolve os slots.",
        "Strips every skill from the pet and gives the slots back.",
    ),
    (
        "Abra na bolsa para invocar 1 chave aleatória de craft.",
        "Open it in your bag to summon 1 random crafting key.",
    ),
    (
        "Alimenta o pet por 2 h. Com fome ele não ganha experiência.",
        "Feeds the pet for 2 h. While hungry it gains no experience.",
    ),
    (
        "Sorteia de novo os atributos do pet ou da montaria equipada.",
        "Rerolls the attributes of the equipped pet or mount.",
    ),
    // ───────────────────────────── a Ilha Mágica: as ilhotas ─────────────────────────────
    ("Pedra", "Stone"),
    ("Colosso", "Colossus"),
    ("Espólio", "Spoils"),
    ("Experiência", "Experience"),
    ("Ilha Mágica I", "Magic Island I"),
    ("Ilha Mágica II", "Magic Island II"),
    ("Ilhota do Ouro", "Islet of Gold"),
    ("Ilha Mágica III", "Magic Island III"),
    ("Ilhota da Pedra", "Islet of Stone"),
    ("Guia dos Degraus", "Guide of the Steps"),
    ("Ilhota da Energia", "Islet of Energy"),
    ("Ilhota da Madeira", "Islet of Wood"),
    ("Ilhota do Colosso", "Islet of the Colossus"),
    ("Ilhota do Espólio", "Islet of Spoils"),
    ("entre 1 e 3 entradas", "between 1 and 3 entries"),
    ("Ilhota da Experiência", "Islet of Experience"),
    ("Colosso Maior da Ilha Mágica", "Greater Colossus of the Magic Island"),
    ("Colosso Ancião da Ilha Mágica", "Elder Colossus of the Magic Island"),
    ("faltam passes: você tem {passes}", "not enough passes: you have {passes}"),
    (
        "seu tempo já está perto do teto de 1h30",
        "your time is already close to the 1h30 cap",
    ),
    // ────────────────────────────── mercado: as recusas ──────────────────────────────
    ("Quantidade inválida.", "Invalid quantity."),
    ("Item vinculado: não pode ser vendido.", "Bound item: it cannot be sold."),
    (
        "Limite de {MAX_ANUNCIOS} anúncios ativos.",
        "Limit of {MAX_ANUNCIOS} active listings.",
    ),
    (
        "Preço inválido (1 a {PRECO_MAX_UNIT} por unidade).",
        "Invalid price (1 to {PRECO_MAX_UNIT} per unit).",
    ),
    (
        "O preço do anúncio mudou; o gold volta em Entregas.",
        "The listing's price changed; the gold comes back in Deliveries.",
    ),
    (
        "Mercado indisponível agora. Tente de novo em instantes.",
        "Market unavailable right now. Try again in a moment.",
    ),
    (
        "Precisa do nível {NIVEL_PARA_VENDER} para vender no mercado.",
        "You need level {NIVEL_PARA_VENDER} to sell on the market.",
    ),
    (
        "Não dá para comprar o próprio anúncio; o gold volta em Entregas.",
        "You cannot buy your own listing; the gold comes back in Deliveries.",
    ),
    (
        "O anúncio acabou ou não tem essa quantidade; o gold volta em Entregas.",
        "The listing is gone or has less than that; the gold comes back in Deliveries.",
    ),
    // ──────────────────────────────── as montarias ────────────────────────────────
    ("Dragão", "Dragon"),
    ("Hipogrifo", "Hippogriff"),
    ("Cervo do Bosque", "Grove Stag"),
    ("Silencioso na neve, feroz na estrada.", "Silent in the snow, fierce on the road."),
    (
        "Leal e ligeiro, criado nas matas do Bosque.",
        "Loyal and quick, raised in the woods of the Grove.",
    ),
    (
        "Meio águia, meio cavalo. Não anda: quase voa.",
        "Half eagle, half horse. It doesn't walk: it nearly flies.",
    ),
    (
        "O topo. Quem monta um, todo mundo vê de longe.",
        "The very top. Ride one and everybody sees you coming.",
    ),
    (
        "Manso e ligeiro. A primeira montaria de qualquer um.",
        "Gentle and quick. Everybody's first mount.",
    ),
    // ───────────────────────────── os pets e suas skills ─────────────────────────────
    ("Laranja", "Orange"),
    ("Aprendiz", "Apprentice"),
    ("Corujurso", "Owlbear Cub"),
    ("Porquinho", "Piglet"),
    ("+4 de DES.", "+4 DEX."),
    ("+4 de FOR.", "+4 STR."),
    ("+4 de INT.", "+4 INT."),
    ("+4 de RES.", "+4 RES."),
    ("+4 de SPD.", "+4 SPD."),
    ("+4 de VIT.", "+4 VIT."),
    ("Passo Leve", "Light Step"),
    ("Faro Apurado", "Keen Nose"),
    ("Estômago Fundo", "Deep Stomach"),
    ("Fonte Interior", "Inner Spring"),
    ("Sopro Curativo", "Healing Breath"),
    ("Filhote de Lobo", "Wolf Cub"),
    ("Filhote de Tigre", "Tiger Cub"),
    ("Força Emprestada", "Borrowed Strength"),
    ("Vigor Emprestado", "Borrowed Stamina"),
    ("Filhote de Dragão", "Dragon Hatchling"),
    ("+20% de velocidade.", "+20% speed."),
    ("Destreza Emprestada", "Borrowed Dexterity"),
    ("Ligeireza Emprestada", "Borrowed Quickness"),
    ("Sabedoria Emprestada", "Borrowed Wisdom"),
    ("A Ração dura o dobro.", "Feed lasts twice as long."),
    ("Vitalidade Emprestada", "Borrowed Vitality"),
    ("Resistência Emprestada", "Borrowed Resilience"),
    ("+2 de mana por segundo.", "+2 mana per second."),
    ("+1,5 de vida por segundo.", "+1.5 health per second."),
    ("+3 tiles no raio de busca.", "+3 tiles on the search radius."),
    ("Come tudo e não reclama. Vitalidade.", "Eats anything, complains about nothing. Vitality."),
    ("+50% da experiência que o pet recebe.", "+50% of the experience the pet gains."),
    ("Estranho e sábio. O pet da arma mágica.", "Odd and wise. The pet for the magic weapon."),
    ("Caçador desde pequeno. Força e destreza.", "A hunter from the start. Strength and dexterity."),
    ("Rápido e curioso. Destreza e velocidade.", "Quick and curious. Dexterity and speed."),
    (
        "Pequeno, e já sabe disso. O topo da escada.",
        "Small, and well aware of it. The top of the ladder.",
    ),
    (
        "+3 pontos de atributo, na afinidade da espécie.",
        "+3 attribute points, in the species' affinity.",
    ),
    ("Vigor", "Stamina"),
    // ───────────────────────────── presença: o calendário ─────────────────────────────
    ("Presença do mês", "Attendance for the month"),
    ("Esse calendário não está ativo.", "That calendar is not active."),
    (
        "Calendário completo! O próximo começa no dia 1.",
        "Calendar complete! The next one starts on the 1st.",
    ),
    (
        "Você já resgatou hoje. Volte depois do reset (04:00).",
        "You've already claimed today. Come back after the reset (04:00).",
    ),
    ("Calendário indisponível agora. Tente de novo.", "Calendar unavailable right now. Try again."),
    // ───────────────────── as habilidades e os degraus de evolução ─────────────────────
    ("Aura", "Aura"),
    ("Dança", "Dance"),
    ("Saque", "Draw"),
    ("Barril", "Barrel"),
    ("Bênção", "Blessing"),
    ("Rajada", "Volley"),
    ("Muralha", "Bulwark"),
    ("Aura maior", "Wider aura"),
    ("Julgamento", "Judgement"),
    ("Área maior", "Wider area"),
    ("Cura máxima", "Maximum healing"),
    ("Golpe Largo", "Wide Strike"),
    ("Golpe final", "Final strike"),
    ("Leque maior", "Wider fan"),
    ("Rajada final", "Final volley"),
    ("Impacto maior", "Greater impact"),
    ("Tiro Certeiro", "True Shot"),
    ("Cura reforçada", "Stronger healing"),
    ("Empurra o alvo", "Pushes the target"),
    ("Explosão maior", "Bigger explosion"),
    ("Vento Cortante", "Cutting Wind"),
    ("Cone mais longo", "Longer cone"),
    ("Corte reforçado", "Stronger slash"),
    ("Muralha por 6 s", "Bulwark for 6 s"),
    ("Tiro mais forte", "Stronger shot"),
    ("Empurra inimigos", "Pushes enemies"),
    ("Julgamento final", "Final judgement"),
    ("Linha mais longa", "Longer line"),
    ("Crítico garantido", "Guaranteed critical"),
    ("Reduz 55% do dano", "Cuts 55% of the damage"),
    ("Reduz 60% por 8 s", "Cuts 60% for 8 s"),
    ("Impacto mais forte", "Stronger impact"),
    ("Explosão mais forte", "Stronger explosion"),
    ("Incêndio devastador", "Devastating blaze"),
    ("Onda final ampliada", "Wider final wave"),
    ("Corte final ampliado", "Wider final slash"),
    ("Golpe final ampliado", "Wider final strike"),
    ("Pulso de cura máximo", "Maximum healing pulse"),
    ("Saque final ampliado", "Wider final draw"),
    ("Recuperação adicional", "Extra recovery"),
    ("Área e dano ampliados", "Wider area and more damage"),
    ("Área e cura reforçadas", "Wider area and stronger healing"),
    ("Onda mais forte e longa", "Stronger, longer wave"),
    ("Restaura a própria vida.", "Restores your own health."),
    ("Onda atravessa mais longe", "The wave travels further"),
    ("Corte atravessa mais longe", "The slash travels further"),
    ("Atinge alvos mais distantes", "Reaches targets further away"),
    ("Escudo por 2 s após a investida", "Shield for 2 s after the charge"),
    ("Cura você e aliados ao seu redor.", "Heals you and allies around you."),
    (
        "Arremessa um barril que explode no alvo.",
        "Hurls a barrel that explodes on the target.",
    ),
    (
        "Saca a katana e corta em linha até o alvo.",
        "Draws the katana and cuts in a line up to the target.",
    ),
    (
        "Corte amplo voltado para o alvo selecionado.",
        "A wide slash aimed at the selected target.",
    ),
    (
        "Reduz o dano recebido em 50% por 5 segundos.",
        "Cuts incoming damage by 50% for 5 seconds.",
    ),
    (
        "Uma onda cortante atinge o alvo selecionado.",
        "A cutting wave strikes the selected target.",
    ),
    (
        "Dispara um tiro poderoso no alvo selecionado.",
        "Fires a powerful shot at the selected target.",
    ),
    (
        "Avança até o alvo e atinge inimigos no caminho.",
        "Charges to the target, hitting enemies on the way.",
    ),
    (
        "Impacto mágico no alvo e nos inimigos próximos.",
        "A magical impact on the target and the enemies near it.",
    ),
    (
        "Rajada em leque voltada para o alvo selecionado.",
        "A fanning volley aimed at the selected target.",
    ),
    (
        "Atinge o alvo próximo e os inimigos ao redor dele.",
        "Strikes the nearby target and the enemies around it.",
    ),
    ("Vigia", "Watchman"),
    // ─────────────────────── os itens (o nome que vem do banco) ───────────────────────
    // Estes nomes nascem no seed do Postgres e chegam ao cliente pelo protocolo.
    // A tradução acontece no desenho, então não há coluna nova nem migração: o
    // banco continua em português e é ele que a lógica compara.
    ("Baiacu", "Pufferfish"),
    ("Bainha", "Scabbard"),
    ("Coldre", "Holster"),
    ("Anchova", "Anchovy"),
    ("Aço Azul", "Blue Steel"),
    ("Aço Roxa", "Purple Steel"),
    ("Aço Cinza", "Grey Steel"),
    ("Couro T1", "Leather T1"),
    ("Couro T2", "Leather T2"),
    ("Couro T3", "Leather T3"),
    ("Couro T4", "Leather T4"),
    ("Garra Azul", "Blue Claw"),
    ("Garra Roxa", "Purple Claw"),
    ("Garra Cinza", "Grey Claw"),
    ("Garra Verde", "Green Claw"),
    ("Madeira T1", "Wood T1"),
    ("Madeira T2", "Wood T2"),
    ("Madeira T3", "Wood T3"),
    ("Madeira T4", "Wood T4"),
    ("Anel Mágico", "Magic Ring"),
    ("Chifre Roxa", "Purple Horn"),
    ("Chifre Cinza", "Grey Horn"),
    ("Escama Azul", "Blue Scale"),
    ("Escama Roxa", "Purple Scale"),
    ("Escama Cinza", "Grey Scale"),
    ("Escama Verde", "Green Scale"),
    ("Moeda Mágica", "Magic Coin"),
    ("Platina Azul", "Blue Platinum"),
    ("Platina Roxa", "Purple Platinum"),
    ("Platina Cinza", "Grey Platinum"),
    ("Platina Verde", "Green Platinum"),
    ("Ração de Pet", "Pet Feed"),
    ("Duas Pistolas", "Twin Pistols"),
    ("Manto do Mago", "Mage's Mantle"),
    ("Peixe-palhaço", "Clownfish"),
    ("Couro Lendário", "Legendary Leather"),
    ("Garra Lendária", "Legendary Claw"),
    ("Poção de Sorte", "Potion of Luck"),
    ("Armadura Pesada", "Heavy Armour"),
    ("Chifre Lendário", "Legendary Horn"),
    ("Escama Lendária", "Legendary Scale"),
    ("Espada e Escudo", "Sword and Shield"),
    ("Peixe-cirurgião", "Surgeonfish"),
    ("Poção de Fortuna", "Potion of Fortune"),
    ("Manto do Guerreiro", "Warrior's Mantle"),
    ("Pedra de Afinidade", "Affinity Stone"),
    ("Quintessência Azul", "Blue Quintessence"),
    ("Quintessência Roxa", "Purple Quintessence"),
    ("Selo da Tempestade", "Storm Seal"),
    ("Pedra de Ânima Azul", "Blue Anima Stone"),
    ("Pedra de Ânima Roxa", "Purple Anima Stone"),
    ("Quintessência Cinza", "Grey Quintessence"),
    ("Quintessência Verde", "Green Quintessence"),
    ("Marcas da Tempestade", "Storm Marks"),
    ("Passe da Ilha Mágica", "Magic Island Pass"),
    ("Pedra de Ânima Cinza", "Grey Anima Stone"),
    ("Pedra de Ânima Verde", "Green Anima Stone"),
    ("Pergaminho de Teleporte", "Teleport Scroll"),
    ("Pedra Sombra-da-Lua Azul", "Blue Moonshadow Stone"),
    ("Pedra Sombra-da-Lua Roxa", "Purple Moonshadow Stone"),
    ("Fragmento Iluminante Azul", "Blue Illuminating Shard"),
    ("Fragmento Iluminante Roxa", "Purple Illuminating Shard"),
    ("Pedra Sombra-da-Lua Cinza", "Grey Moonshadow Stone"),
    ("Pedra Sombra-da-Lua Verde", "Green Moonshadow Stone"),
    ("Removedor de Skill de Pet", "Pet Skill Remover"),
    ("Berloque de Exorcismo Azul", "Blue Exorcism Charm"),
    ("Berloque de Exorcismo Roxa", "Purple Exorcism Charm"),
    ("Fragmento Iluminante Cinza", "Grey Illuminating Shard"),
    ("Fragmento Iluminante Verde", "Green Illuminating Shard"),
    ("Berloque de Exorcismo Cinza", "Grey Exorcism Charm"),
    ("Berloque de Exorcismo Verde", "Green Exorcism Charm"),
    ("Pedra do Coração Negro Azul", "Blue Blackheart Stone"),
    ("Pedra do Coração Negro Roxa", "Purple Blackheart Stone"),
    ("Pedra do Coração Negro Cinza", "Grey Blackheart Stone"),
    ("Pedra do Coração Negro Verde", "Green Blackheart Stone"),
    ("Pergaminho de Invocação: Pet", "Summoning Scroll: Pet"),
    ("Pergaminho de Invocação: Tomos", "Summoning Scroll: Tomes"),
    ("Pergaminho de Invocação: Chaves", "Summoning Scroll: Keys"),
    ("Pergaminho de Invocação: Montaria", "Summoning Scroll: Mount"),
    ("Skill: {}", "Skill: {}"),
    // ───────────────────────────── os bichos do mundo ─────────────────────────────
    ("Morsa", "Walrus"),
    ("Tigre", "Tiger"),
    ("Rochoso", "Rockback"),
    ("Arqueiro", "Archer"),
    ("Caranguejo", "Crab"),
    ("Pistoleiro", "Gunman"),
    ("Escaravelho", "Scarab"),
    ("Lobo Grande", "Great Wolf"),
    ("Urso Branco", "White Bear"),
    ("Tigre Branco", "White Tiger"),
    ("Caranguejo-rei", "King Crab"),
    ("Rainha Escaravelho", "Scarab Queen"),
    ("Lobo", "Wolf"),
    ("Urso", "Bear"),
    ("Mago", "Mage"),
    ("Owlbear", "Owlbear"),
    ("Tigre das Neves", "Snow Tiger"),
    ("Lobo da Clareira", "Glade Wolf"),
    ("Lobo da Meia-Noite", "Midnight Wolf"),
    ("Guardião de Treino", "Training Guardian"),
    ("Vale dos Ventos", "Valley of Winds"),
];
