//!  História: os capítulos, as crônicas e as falas da campanha.

pub const VERBETES: &[(&str, &str)] = &[
    // ───────────────── os lugares que a bússola diz (frases curtas) ─────────────────
    ("a praça", "the square"),
    ("o lugar", "the place"),
    ("o porto", "the port"),
    ("o mirante", "the lookout"),
    ("a ponta do cais", "the end of the quay"),
    ("a costa distante", "the distant coast"),
    ("a saída da cidade", "the way out of the city"),
    // ──────────────────────── os títulos dos passos da história ────────────────────────
    ("Mãos firmes", "Steady hands"),
    ("Siga a dica", "Follow the hint"),
    ("Ar rarefeito", "Thin air"),
    ("Pedra do céu", "Skystone"),
    ("Rumo ao Ermo", "Bound for the Waste"),
    ("A última runa", "The last rune"),
    ("Aço de trovão", "Thunder steel"),
    ("Fogo na forja", "Fire in the forge"),
    ("O que há além", "What lies beyond"),
    ("Magos da areia", "Mages of the sand"),
    ("O farol do céu", "The lighthouse of the sky"),
    ("O mapa do Ermo", "The map of the Waste"),
    ("Sinais no cais", "Signs on the quay"),
    ("Água e remédio", "Water and remedy"),
    ("Arma do deserto", "Weapon of the desert"),
    ("O brilho do aço", "The gleam of steel"),
    ("O calor do Ermo", "The heat of the Waste"),
    ("Pedra que canta", "The singing stone"),
    ("Sombras na mata", "Shadows in the woods"),
    ("Tome isto e vá.", "Take this and go."),
    ("A caçada sem fim", "The endless hunt"),
    ("A costa distante", "The distant coast"),
    ("A luz nas pedras", "The light in the stones"),
    ("De volta ao cais", "Back to the quay"),
    ("Fogo mais quente", "A hotter fire"),
    ("Luta sem as mãos", "Fighting hands-free"),
    ("Lâminas de vidro", "Blades of glass"),
    ("Rumo ao Planalto", "Bound for the Plateau"),
    ("Suba antes dele.", "Climb before he does."),
    ("Têmpera no calor", "Tempered in the heat"),
    ("Ursos na encosta", "Bears on the slope"),
    ("Vigia do mirante", "Watch of the lookout"),
    ("A frota de Morgan", "Morgan's fleet"),
    ("As feras do vento", "The beasts of the wind"),
    ("Brinde aos faróis", "A toast to the lighthouses"),
    ("Crônica {n} · {t}", "Chronicle {n} · {t}"),
    ("Desperte na praça", "Wake in the square"),
    ("O Capitão do Ermo", "The Captain of the Waste"),
    ("O cerco das dunas", "The siege of the dunes"),
    ("O farol congelado", "The frozen lighthouse"),
    ("O farol soterrado", "The buried lighthouse"),
    ("Pedras que cantam", "Stones that sing"),
    ("Sua primeira peça", "Your first piece"),
    ("A estrada do porto", "The port road"),
    ("A trilha dos lobos", "The wolves' trail"),
    ("Alcance o nível 22", "Reach level 22"),
    ("Alcance o nível 25", "Reach level 25"),
    ("Alcance o nível 30", "Reach level 30"),
    ("Alcance o nível 35", "Reach level 35"),
    ("Alcance o nível 40", "Reach level 40"),
    ("Alcance o nível 45", "Reach level 45"),
    ("Alcance o nível 50", "Reach level 50"),
    ("Alcance o nível 55", "Reach level 55"),
    ("Alcance o nível 60", "Reach level 60"),
    ("Aço que não quebra", "Steel that will not break"),
    ("Coleta sem esforço", "Gathering without effort"),
    ("Corujursos na neve", "Owlbear cubs in the snow"),
    ("Feras da maré alta", "Beasts of the high tide"),
    ("Lenha para a forja", "Firewood for the forge"),
    ("O Capitão do Porto", "The Harbour Captain"),
    ("O rastro do trovão", "The trail of thunder"),
    ("O veio da tormenta", "The vein of the tempest"),
    ("Um gole de coragem", "A sip of courage"),
    ("Vidro de relâmpago", "Lightning glass"),
    ("Golpe no automático", "Striking on automatic"),
    ("O cais ao amanhecer", "The quay at dawn"),
    ("O fragmento de gelo", "The shard of ice"),
    ("O olho no horizonte", "The eye on the horizon"),
    ("Poção na hora certa", "A potion at the right moment"),
    ("A patrulha de Morgan", "Morgan's patrol"),
    ("Armadura para o olho", "Armour for the eye"),
    ("Arqueiros da nevasca", "Archers of the blizzard"),
    ("Histórias de taberna", "Tavern tales"),
    ("Minério do relâmpago", "Lightning ore"),
    ("O porão do naufrágio", "The shipwreck cellar"),
    ("O primeiro despertar", "The first waking"),
    ("O que o nível te deu", "What the level gave you"),
    ("A dança da tempestade", "The dance of the storm"),
    ("Couraça contra o frio", "A shell against the cold"),
    ("I · O Farol do Bosque", "I · The Lighthouse of the Grove"),
    ("O metal da tempestade", "The metal of the storm"),
    ("O naufrágio de Morgan", "Morgan's shipwreck"),
    ("Ferro forjado no vento", "Iron forged in the wind"),
    ("Gelo que guarda trovão", "Ice that holds thunder"),
    ("II · O Farol Congelado", "II · The Frozen Lighthouse"),
    ("Sentinelas do Planalto", "Sentinels of the Plateau"),
    ("Frio de rachar os ossos", "Bone-cracking cold"),
    ("III · Areias que Gritam", "III · Sands That Scream"),
    ("O juramento do Guardião", "The Guardian's oath"),
    ("O mapa mostra o caminho", "The map shows the way"),
    ("Uma peça para a jornada", "A piece for the journey"),
    ("Capa de lã-de-tempestade", "Cloak of stormwool"),
    ("Os pistoleiros de Morgan", "Morgan's gunmen"),
    ("A adega do contrabandista", "The smuggler's cellar"),
    ("Garras no caminho do cais", "Claws on the road to the quay"),
    ("Que os faróis guiem você.", "May the lighthouses guide you."),
    ("Crônicas da Tempestade · {}", "Chronicles of the Storm · {}"),
    ("Leve cobre e crie sua arma.", "Take copper and craft your weapon."),
    ("Suba lá antes que ele caia.", "Get up there before it falls."),
    ("IV · O Coração da Tempestade", "IV · The Heart of the Storm"),
    ("Suas crônicas começam agora.", "Your chronicles begin now."),
    ("Você está pronto para o que vem.", "You are ready for what comes next."),
    ("Tente refinar duas vezes na Forja.", "Try refining twice at the Forge."),
    ("Tente refinar três vezes na Forja.", "Try refining three times at the Forge."),
    ("O barco está pronto e a maré ajuda.", "The boat is ready and the tide is with us."),
    ("Crônica {n} · Guardião da Tempestade", "Chronicle {n} · Guardian of the Storm"),
    ("Crônica {n} · Alcance o nível {trava}", "Chronicle {n} · Reach level {trava}"),
    ("O último farol fica lá. Eu levo você.", "The last lighthouse is out there. I'll take you."),
    ("Beba. Amanhã o vento vai soprar forte.", "Drink. Tomorrow the wind will blow hard."),
    ("Você chegou vivo ao Ermo. Poucos chegam.", "You reached the Waste alive. Few do."),
    ("Mova-se com a tempestade, não contra ela.", "Move with the storm, not against it."),
    ("O Cartógrafo do porto tem algo para você.", "The Cartographer at the port has something for you."),
    ("Três faróis acesos! A casa paga a rodada.", "Three lighthouses lit! The house buys this round."),
    ("Arqueiros vigiam os penhascos. Derrote 12.", "Archers watch the cliffs. Defeat 12."),
    ("O ar é fino aqui em cima. Respire devagar.", "The air is thin up here. Breathe slowly."),
    ("Com o mapa na mão, volte ao pátio do porto.", "With the map in hand, return to the port yard."),
    ("Quando estiver pronto, o Mestre espera você.", "When you're ready, the Master is waiting for you."),
    ("Com isso dá para cortar o vento da tempestade.", "With this you can cut through the storm's wind."),
    ("Fale com o Alquimista antes de pisar na areia.", "Talk to the Alchemist before you set foot on the sand."),
    ("Daqui dá para ver o olho da tempestade girando.", "From here you can see the eye of the storm turning."),
    ("Mas a tempestade não morre: ela dorme e acorda.", "But the storm does not die: it sleeps and it wakes."),
    ("Mostre o que achou nas pedras ao Identificador.", "Show the Appraiser what you found in the stones."),
    ("O farol do Ermo voltou a brilhar. Eu vi do mar.", "The lighthouse of the Waste shines again. I saw it from the sea."),
    ("Crie uma peça nova no Craft para o frio que vem.", "Create a new piece in Craft for the cold that's coming."),
    ("Quem luta dentro do vento não pode ficar parado.", "Whoever fights inside the wind cannot stand still."),
    ("Alguém está arrancando pedras do farol congelado.", "Someone is tearing stones out of the frozen lighthouse."),
    ("Crie uma peça nova no Craft com o que o Ermo deu.", "Create a new piece in Craft with what the Waste gave you."),
    ("Dizem que Morgan desembarcou com a frota inteira.", "They say Morgan has landed with the entire fleet."),
    ("Com os quatro faróis acesos, talvez o mar se abra.", "With all four lighthouses lit, perhaps the sea will open."),
    ("Deixe eu ver… Este fragmento é um pedaço do farol.", "Let me see… This shard is a piece of the lighthouse."),
    ("Leve o mapa. Volte ao porto quando estiver pronto.", "Take the map. Come back to the port when you're ready."),
    ("Mas o olho da tempestade se aproximou do Planalto.", "But the eye of the storm has moved closer to the Plateau."),
    ("O Identificador lê a runa gravada na pedra do céu.", "The Appraiser reads the rune carved into the skystone."),
    ("O Mestre mandou você? Então é o náufrago do farol.", "The Master sent you? Then you're the castaway from the lighthouse."),
    ("Os Morganeers querem o farol. Derrote 40 inimigos.", "The Morganeers want the lighthouse. Defeat 40 enemies."),
    ("Arqueiros dos Morganeers vigiam o farol. Derrote 8.", "Morganeer archers are watching the lighthouse. Defeat 8."),
    // ─────────────────── as falas: o que os NPCs dizem em cada passo ───────────────────
    ("O Ermo fica ao sul, depois do mar de areia molhada.", "The Waste lies to the south, past the sea of wet sand."),
    ("Leve o vidro ao Ferreiro. Dizem que corta tempestade.", "Take the glass to the Blacksmith. They say it cuts through storms."),
    ("Você salvou nosso farol. Esta capa é por minha conta.", "You saved our lighthouse. This cloak is on me."),
    ("Água, sal e remédio: é o que mantém alguém vivo aqui.", "Water, salt and remedy: that's what keeps a person alive out here."),
    ("A pedra da Geleira prende relâmpago. Quebre 20 pedras.", "The Glacier's stone traps lightning. Break 20 rocks."),
    ("Onde o raio cai, a areia vira pedra. Quebre 25 pedras.", "Where lightning strikes, sand turns to stone. Break 25 rocks."),
    ("Os magos usam o trovão da areia. Cuidado com os raios.", "The mages use the thunder in the sand. Mind the lightning."),
    ("Vidro de relâmpago… Afiado como nada que eu já forjei.", "Lightning glass… Sharper than anything I've ever forged."),
    ("Bem-vindo ao porto da Geleira. A estrada leva à cidade.", "Welcome to the Glacier's port. The road leads to the city."),
    ("Ninguém nunca desenhou o que existe além da tempestade.", "Nobody has ever drawn what lies beyond the storm."),
    ("O Capitão acendeu um sinal na ponta do cais. Vá até lá.", "The Captain lit a signal at the end of the quay. Go to him."),
    ("O farol de lá foi soterrado. Morgan esteve lá primeiro.", "The lighthouse there was buried. Morgan got there first."),
    ("Os corujursos descem das trilhas atrás deles, famintos.", "The owlbear cubs come down the trails after them, starving."),
    ("Owlbears famintos atacam as trilhas de gelo. Derrote 6.", "Starving owlbears are attacking the ice trails. Defeat 6."),
    ("Então você viu o farol apagado do mirante. Eu vi também.", "So you saw the dark lighthouse from the lookout. I saw it too."),
    ("O farol do Ermo está no topo das dunas. Suba ao mirante.", "The Waste's lighthouse sits atop the dunes. Climb to the lookout."),
    ("Ouvi falar dos lobos. Nada mal para quem chegou boiando.", "I heard about the wolves. Not bad for someone who washed up floating."),
    ("E a pedra daqui prende relâmpago. Eles querem essa pedra.", "And the stone here traps lightning. That stone is what they want."),
    ("O Taberneiro sabe onde os Morganeers se escondem na neve.", "The Innkeeper knows where the Morganeers hide in the snow."),
    ("Pedra que canta? Deixe eu ouvir… É trovão preso no metal.", "A singing stone? Let me listen… That's thunder trapped in metal."),
    ("Esta runa diz: “quem acende o farol do céu vira guardião”.", "This rune reads: “whoever lights the lighthouse of the sky becomes a guardian”."),
    ("Guarde isto: quintessência. Armadura nenhuma fecha sem ela.", "Keep this: quintessence. No armour closes without it."),
    ("Nosso farol ainda brilha, mas o gelo está rachando a pedra.", "Our lighthouse still shines, but the ice is cracking the stone."),
    ("O Cartógrafo quer desenhar o que existe além da tempestade.", "The Cartographer wants to draw what lies beyond the storm."),
    ("Os lobos estão estranhos. Vá ver a trilha, mas com cuidado.", "The wolves are behaving strangely. Go look at the trail, but carefully."),
    ("Sem água ninguém atravessa as dunas. Fale com o Alquimista.", "Nobody crosses the dunes without water. Talk to the Alchemist."),
    ("No porto, o Capitão diz que o último farol fica no Planalto.", "At the port, the Captain says the last lighthouse is on the Plateau."),
    ("O farol da Geleira fica no alto. Suba até o mirante da ilha.", "The Glacier's lighthouse stands high up. Climb to the island's lookout."),
    ("Se os faróis caírem, a tempestade engole as ilhas uma a uma.", "If the lighthouses fall, the storm swallows the islands one by one."),
    ("Senta, esquenta as mãos. Morganeers? Chegaram com a nevasca.", "Sit, warm your hands. Morganeers? They came in with the blizzard."),
    ("Três faróis voltaram a brilhar. O Taberneiro serve a rodada.", "Three lighthouses shine again. The Innkeeper is pouring."),
    ("As pedras do Planalto guardam o trovão mais forte. Quebre 30.", "The Plateau's stones hold the strongest thunder. Break 30."),
    ("No Planalto o vento corta. Apresente-se ao Mestre de Missões.", "On the Plateau the wind cuts. Report to the Quest Master."),
    ("No teto do poder, a guarda nunca acaba. Derrote {q} inimigos.", "At the roof of power, the watch never ends. Defeat {q} enemies."),
    ("O último farol é o mais alto de todos. Vai precisar de força.", "The last lighthouse is the highest of them all. You'll need strength."),
    ("Os quatro faróis brilham. Você fez o que nenhum náufrago fez.", "All four lighthouses shine. You did what no castaway ever has."),
    ("Primeiro, cuide de você: o Alquimista tem o que você precisa.", "First, look after yourself: the Alchemist has what you need."),
    ("Barcos estranhos rondam a costa mais distante da ilha. Vá ver.", "Strange boats are circling the island's far coast. Go and look."),
    ("Magos dos Morganeers usam o trovão preso na areia. Derrote 10.", "Morganeer mages use the thunder trapped in the sand. Defeat 10."),
    ("O Alfaiate costura com fios que seguram o vento. Fale com ele.", "The Tailor sews with thread that holds the wind. Talk to him."),
    ("Suba a bordo. Do outro lado, apresente-se ao Capitão do Porto.", "Come aboard. On the other side, report to the Harbour Captain."),
    ("Da ponta do cais se vê o olho da tempestade girando. Vá até lá.", "From the end of the quay you can see the eye of the storm turning. Go there."),
    ("Morgan leu a mesma runa. Ele quer ser o guardião da tempestade.", "Morgan read the same rune. He wants to be the guardian of the storm."),
    ("O Capitão sabe por que os faróis apagam. Fale com ele no porto.", "The Captain knows why the lighthouses go dark. Talk to him at the port."),
    ("Vá até a ponta do cais comigo ao amanhecer. Vou mostrar a rota.", "Come to the end of the quay with me at dawn. I'll show you the route."),
    ("A frota inteira dos Morganeers desembarcou. Derrote 50 inimigos.", "The Morganeers' entire fleet has landed. Defeat 50 enemies."),
    ("A nau capitânia de Morgan jaz na costa mais distante. Vá até lá.", "Morgan's flagship lies on the far coast. Go there."),
    ("Crie uma peça nova no Craft para enfrentar o olho da tempestade.", "Create a new piece in Craft to face the eye of the storm."),
    ("Tem uma ilhota a meia hora do cais. Sem dono desde a tempestade.", "There's an islet half an hour from the quay. Ownerless since the storm."),
    ("Esse metal é o que endurece os bichos. E também faz boa armadura.", "That metal is what hardens the beasts. It also makes good armour."),
    ("Lã-de-tempestade: fio que segura o vento. Não é para qualquer um.", "Stormwool: thread that holds the wind. Not for just anyone."),
    ("Você está vivo! O mar trouxe você na noite em que o farol apagou.", "You're alive! The sea brought you in the night the lighthouse went dark."),
    ("Os Morganeers cercam a ilha. Derrote 30 inimigos de qualquer tipo.", "The Morganeers are closing in on the island. Defeat 30 enemies of any kind."),
    ("Os guardiões precisam de equipamento novo. Crie uma peça no Craft.", "The guardians need new gear. Create a piece in Craft."),
    ("Um barco dos Morganeers encalhou na costa mais distante. Vá até lá.", "A Morganeer boat ran aground on the far coast. Go there."),
    ("Os Peacemain guardam o porto. Siga pela estrada até o pátio do cais.", "The Peacemain guard the port. Follow the road to the quay yard."),
    ("Os faróis bebem pedra de trovão. Quebre {q} pedras em qualquer veio.", "The lighthouses drink thunderstone. Break {q} rocks at any vein."),
    ("Vá até a ponta do cais: o Capitão prometeu mostrar a rota das ilhas.", "Go to the end of the quay: the Captain promised to show the island route."),
    ("Areia até onde a vista alcança. Procure o Mestre de Missões na praça.", "Sand as far as the eye can see. Look for the Quest Master in the square."),
    ("Embarque com o Capitão rumo ao Planalto, perto do olho da tempestade.", "Set sail with the Captain for the Plateau, close to the eye of the storm."),
    ("Peça fraca não aguenta a tempestade. Tente refinar uma peça na Forja.", "A weak piece won't survive the storm. Try refining a piece at the Forge."),
    ("As feras do olho da tempestade descem ao Planalto. Derrote 15 owlbears.", "The beasts from the eye of the storm come down to the Plateau. Defeat 15 owlbears."),
    ("Faça o juramento dos Guardiões: vigiar os faróis enquanto houver vento.", "Take the Guardians' oath: to watch the lighthouses as long as there is wind."),
    ("O último farol fica no ponto mais alto do arquipélago. Suba ao mirante.", "The last lighthouse stands at the highest point of the archipelago. Climb to the lookout."),
    ("Quem sabe dos Morganeers na neve é o Taberneiro. Pague um ouvido a ele.", "The one who knows about the Morganeers in the snow is the Innkeeper. Buy his ear."),
    ("A escritura é sua. Terra pequena, mas rende sozinha enquanto você navega.", "The deed is yours. Small land, but it yields on its own while you sail."),
    ("O Cartógrafo do porto desenhou a rota para o Ermo. Busque o mapa com ele.", "The Cartographer at the port drew the route to the Waste. Fetch the map from him."),
    ("Os quatro faróis brilham. O Mestre de Missões tem um juramento para você.", "All four lighthouses shine. The Quest Master has an oath for you."),
    ("Quando quiser ir até lá, é só me dizer: o barco sai daqui e volta pra cá.", "Whenever you want to go there, just say the word: the boat leaves here and comes back here."),
    ("Suba ao mirante da ilha em que estiver e confira se o farol ainda brilha.", "Climb to the lookout of whichever island you're on and check whether the lighthouse still shines."),
    ("O Capitão do Porto leva você ao Ermo, onde o terceiro farol foi soterrado.", "The Harbour Captain will take you to the Waste, where the third lighthouse was buried."),
    ("O Treinador conhece o passo de quem luta dentro do vento. Aprenda com ele.", "The Trainer knows the footwork of those who fight inside the wind. Learn it from him."),
    ("Os ursos desceram das encostas atrás do cheiro de trovão. Derrote 4 ursos.", "The bears came down from the slopes chasing the smell of thunder. Defeat 4 bears."),
    ("Tome o cobre também. Com o que você juntou, já dá uma armadura. Vá ao Craft.", "Take the copper as well. With what you've gathered, that's an armour. Go to Craft."),
    ("O farol daqui está debaixo das dunas, e os magos de Morgan cavam dia e noite.", "The lighthouse here is under the dunes, and Morgan's mages dig day and night."),
    ("Outro só arrancando de chefe: o do Porão do Naufrágio carrega chave no bolso.", "Another one only a boss will give up: the one in the Shipwreck Cellar carries a key in his pocket."),
    (
        "A forja precisa de lenha e o Ferreiro paga bem por ela. Vá derrubar umas árvores.",
        "The forge needs firewood and the Blacksmith pays well for it. Go fell some trees.",
    ),
    (
        "O do Bosque se apagou. Os bichos enlouquecem e os Morganeers já sentiram o cheiro.",
        "The one in the Grove went dark. The beasts are going mad and the Morganeers have caught the scent.",
    ),
    (
        "A tempestade não dorme e os bichos não param. Derrote {q} inimigos de qualquer tipo.",
        "The storm does not sleep and the beasts do not stop. Defeat {q} enemies of any kind.",
    ),
    (
        "Pistoleiros dos Morganeers rondam a mata atrás das pedras do farol. Derrote 6 deles.",
        "Morganeer gunmen prowl the woods after the lighthouse stones. Defeat 6 of them.",
    ),
    (
        "Sem poção, a mata engole qualquer um. Tome estas, e beba antes de cair — não depois.",
        "Without potions, the woods swallow anyone. Take these, and drink before you fall — not after.",
    ),
    (
        "Aço que enfrenta a tempestade é aço refinado. Tente refinar {vezes} vez(es) na Forja.",
        "Steel that faces the storm is refined steel. Try refining {vezes} time(s) at the Forge.",
    ),
    (
        "Há gerações quatro faróis de pedra-trovão seguram a Grande Tempestade longe das ilhas.",
        "For generations, four lighthouses of thunderstone have held the Great Storm away from the islands.",
    ),
    (
        "Os Peacemain guardam os portos e os faróis. Os Morganeers querem a tempestade para eles.",
        "The Peacemain guard the ports and the lighthouses. The Morganeers want the storm for themselves.",
    ),
    (
        "O farol da Geleira ainda brilha, mas por pouco. Peça ao Capitão do Porto um lugar no barco.",
        "The Glacier's lighthouse still shines, but only just. Ask the Harbour Captain for a place on the boat.",
    ),
    (
        "Você desembarcou no porto da Geleira. Fale com o Capitão antes de seguir pela estrada até a cidade.",
        "You've landed at the Glacier's port. Talk to the Captain before following the road to the city.",
    ),
    (
        "Seu morador já trabalhou. Toque em COLHER: o que ele produziu vai pro BAÚ DA ILHA, e não pra sua bolsa.",
        "Your resident has been working. Tap HARVEST: what they produced goes into the ISLAND CHEST, not into your bag.",
    ),
    (
        "A história continua quando você chegar a esse nível. Cace, colete e faça as diárias do Mestre de Missões.",
        "The story carries on once you reach that level. Hunt, gather and do the Quest Master's dailies.",
    ),
    (
        "Toda peça pede um couro curtido para segurar o metal. Tome o meu — é o último, e some depois de uma forja.",
        "Every piece asks for a tanned leather to hold the metal. Take mine — it's the last one, and it's gone after one forging.",
    ),
    (
        "O baú é da ilha. Toque em RETIRAR para passar o que há nele pra sua bolsa — o que não couber fica guardado.",
        "The chest belongs to the island. Tap WITHDRAW to move what's in it into your bag — whatever doesn't fit stays stored.",
    ),
    (
        "O Mestre quer você de pé. Fale com o Alquimista, na loja de toldo verde: sem poção, a mata engole qualquer um.",
        "The Master wants you on your feet. Talk to the Alchemist, at the green-awning shop: without potions, the woods swallow anyone.",
    ),
    (
        "Suba ao ponto mais alto da ilha. De lá se vê o olho da tempestade — e, lá embaixo, o casco do naufrágio encalhado.",
        "Climb to the highest point on the island. From there you can see the eye of the storm — and, down below, the grounded hull of the wreck.",
    ),
    (
        "Você acordou na praia na noite em que o farol do Bosque apagou. Procure o Mestre de Missões, perto do poço da praça.",
        "You woke on the beach the night the Grove's lighthouse went dark. Look for the Quest Master, near the well in the square.",
    ),
    (
        "Uma casa sozinha não sustenta ninguém. No painel da ilha, melhore o ASSENTAMENTO: ele abre a primeira casa de ofício.",
        "One house alone supports nobody. On the island panel, upgrade the SETTLEMENT: it opens the first trade house.",
    ),
    (
        "O Treinador mostra: arraste uma skill PARA CIMA e ela passa a ser usada sozinha no combate. Para baixo, volta pro manual.",
        "The Trainer shows you: drag a skill UP and it starts being used on its own in combat. Drag it down and it goes back to manual.",
    ),
    (
        "Você sobreviveu aos lobos. O Treinador da praça quer ver do que é capaz — e guarda quintessência para quem aguenta o tranco.",
        "You survived the wolves. The Trainer in the square wants to see what you can do — and he keeps quintessence for whoever can take a beating.",
    ),
    (
        "Casa vazia não rende. Na casa que abriu, escolha um ofício — o Lenhador traz madeira, o Minerador traz aço, o Mercenário traz cobre.",
        "An empty house yields nothing. In the house you opened, pick a trade — the Woodcutter brings wood, the Miner brings steel, the Mercenary brings copper.",
    ),
    (
        "Leve o que ouviu nas pedras ao Ferreiro. Ele sabe o que o metal carrega — e guarda o couro e o cobre que faltam para quem vai forjar.",
        "Take what you heard in the stones to the Blacksmith. He knows what the metal carries — and he keeps the leather and copper that anyone about to forge is missing.",
    ),
    (
        "A forja come madeira e pedra. Toque em COLETA: o personagem corta e quebra sozinho o que estiver por perto — a engrenagem do botão escolhe o quê.",
        "The forge eats wood and stone. Tap GATHER: your character cuts and breaks whatever is nearby on its own — the gear icon on the button chooses what.",
    ),
    (
        "A Energia que você juntou no Bosque não é só brilho: ela desperta o que você já sabe. Abra Menu › Personagem › Habilidades, escolha uma das suas e suba um tier.",
        "The Energy you gathered in the Grove isn't just a glow: it wakes what you already know. Open Menu › Character › Skills, pick one of yours and raise it a tier.",
    ),
    (
        "Antes dos lobos, aprenda a lutar sem pensar: toque em COMBATE, no canto de baixo, e o personagem enfrenta sozinho o que estiver perto. Toque de novo para parar.",
        "Before the wolves, learn to fight without thinking: tap COMBAT, in the bottom corner, and your character takes on whatever is near on its own. Tap again to stop.",
    ),
    (
        "As pedras da ilha zumbem com o trovão. Quebre 10 pedras em qualquer veio — é da pedra que saem o Aço e o Darksteel de toda peça. A mineradora completa o seu Aço.",
        "The island's stones hum with thunder. Break 10 rocks at any vein — stone is where the Steel and Darksteel of every piece come from. The miner tops up your Steel.",
    ),
    (
        "O Alquimista insiste: poção boa é a que se bebe sozinha. Abra Menu › Sistema › Barra, escolha a Poção de Vida e ajuste com − e + a % de vida em que ela é bebida.",
        "The Alchemist insists: a good potion is one that drinks itself. Open Menu › System › Bar, pick the Health Potion and use − and + to set the health % at which it is drunk.",
    ),
    (
        "Tigres cercam a estrada dos carregadores e ninguém passa com carga. Derrote 5 — deles se tira a Quintessência, que toda armadura pede e a pedra dá a conta-gotas.",
        "Tigers have surrounded the porters' road and nobody gets through with cargo. Defeat 5 — they're where Quintessence comes from, which every armour asks for and stone gives a drop at a time.",
    ),
    (
        "A forja da vila come madeira dia e noite. Derrube 8 árvores — é da árvore que sai toda a madeira da ilha. O Ferreiro paga em Darksteel, o metal escuro que toda peça pede.",
        "The village forge eats wood day and night. Fell 8 trees — trees are where all the island's wood comes from. The Blacksmith pays in Darksteel, the dark metal every piece asks for.",
    ),
    (
        "Antes de zarpar, o Capitão quer o porto limpo: os contrabandistas de Morgan guardam pedra do farol numa adega sob o cais. Toque no passo (ou em Dungeons, no Menu) e limpe a Adega do Contrabandista.",
        "Before setting sail, the Captain wants the port clean: Morgan's smugglers are keeping lighthouse stone in a cellar under the quay. Tap the step (or Dungeons, in the Menu) and clear the Smuggler's Cellar.",
    ),
    (
        "Os lobos enlouqueceram desde que o farol apagou: descem à trilha de dia, coisa que nunca fizeram. Derrote 5 fora da cidade. Os caçadores juntaram berloques que os bichos arrancaram das carroças — são seus.",
        "The wolves have gone mad since the lighthouse went dark: they come down to the trail in daylight, which they never did. Defeat 5 outside the city. The hunters gathered up charms the beasts tore off the carts — they're yours.",
    ),
    (
        "Toque no minimapa para abrir o mapa da ilha e toque num lugar: o personagem vai sozinho até lá. Ao concluir, abra o Pergaminho de Invocação: Montaria na bolsa, equipe a montaria e use o botão Montar para viajar mais rápido.",
        "Tap the minimap to open the island map and tap a place: your character walks there on its own. When you're done, open the Summoning Scroll: Mount in your bag, equip the mount and use the Mount button to travel faster.",
    ),
    (
        "O Capitão te entrega uma escritura: uma ilhota a meia hora do cais, sem dono desde a tempestade. É sua — e ela rende sozinha enquanto você navega. Abra Menu › Minha Ilha para vê-la: o Capitão deixou lá o material da primeira obra.",
        "The Captain hands you a deed: an islet half an hour from the quay, ownerless since the storm. It's yours — and it yields on its own while you sail. Open Menu › My Island to see it: the Captain left the material for the first build there.",
    ),
    (
        "O trovão deixou cristais azuis no relevo: é Energia, e ela não ocupa espaço na bolsa e é o que paga os seus pontos de atributo. Toque no passo que o caminho até um veio abre sozinho — junte o bastante pra gastar tudo o que os primeiros níveis te deram.",
        "The thunder left blue crystals across the terrain: that's Energy, it takes no space in your bag, and it's what pays for your attribute points. Tap the step and the path to a vein opens on its own — gather enough to spend everything the first few levels gave you.",
    ),
    (
        "Do mirante você viu o casco. Os Morganeers fizeram do porão um esconderijo, e quem manda lá dentro carrega chave no bolso — chefe de dungeon larga chave bem mais que chefe de campo. Toque no passo (ou em Dungeons, no Menu) e limpe o Porão do Naufrágio. Sozinho dá.",
        "From the lookout you saw the hull. The Morganeers have made the cellar a hideout, and whoever rules down there carries a key in his pocket — a dungeon boss drops keys far more often than a field boss. Tap the step (or Dungeons, in the Menu) and clear the Shipwreck Cellar. Solo is enough.",
    ),
    (
        "Cada ponto de atributo custa Energia — a mesma dos cristais azuis do relevo. Abra Menu › Personagem › Ficha e coloque um ponto no atributo que combina com a sua arma: FOR bate mais forte, DES acerta mais, INT move a magia. Se faltar Energia, quebre um cristal e volte.",
        "Every attribute point costs Energy — the same Energy as the blue crystals out on the terrain. Open Menu › Character › Sheet and put a point into the attribute that suits your weapon: STR hits harder, DEX lands more often, INT drives the magic. If you run short of Energy, break a crystal and come back.",
    ),
    (
        "Você tem tudo o que a Armadura pede: o couro do Ferreiro, Aço, Quintessência, Berloque, Darksteel e cobre. Abra o Craft e crie sua primeira armadura. Depois disso, tudo isso se farma: pedra, árvore, bicho e chefe — e o pergaminho que o Ferreiro te dá chama quem colhe por você.",
        "You have everything the Armour asks for: the Blacksmith's leather, Steel, Quintessence, a Charm, Darksteel and copper. Open Craft and create your first armour. After that, all of it can be farmed: stone, tree, beast and boss — and the scroll the Blacksmith gives you calls someone who gathers for you.",
    ),
];
