//!  Missões: título, descrição e fala de entrega de cada uma.

pub const VERBETES: &[(&str, &str)] = &[
    // ─────────────────────────── os títulos das missões ───────────────────────────
    // Título curto é o que mais aparece: lista, diário, bússola. Vale soar como
    // nome de missão em inglês, não como tradução literal.
    ("Curtume", "The Tannery"),
    ("Gelo fundo", "Deep ice"),
    ("Madeireiro", "Timberman"),
    ("Mão pesada", "Heavy hand"),
    ("Caça do dia", "Hunt of the day"),
    ("Mãos à obra", "To work"),
    ("Chefe do dia", "Boss of the day"),
    ("Fogo Cruzado", "Crossfire"),
    ("Forja quente", "Hot forge"),
    ("Pelas Névoas", "Through the Mists"),
    ("Porão do dia", "Cellar of the day"),
    ("Pule a Pedra", "Jump the Rock"),
    ("Aço temperado", "Tempered steel"),
    ("Carga no cais", "Cargo on the quay"),
    ("Caçada do dia", "Chase of the day"),
    ("Couro de urso", "Bear leather"),
    ("Limpa-trilhas", "Trail-clearing"),
    ("Madeira nobre", "Fine timber"),
    ("Olhos na mata", "Eyes on the woods"),
    ("Quintessência", "Quintessence"),
    ("Rastro branco", "White trail"),
    ("Ronda da vila", "Village rounds"),
    ("Ursos na mata", "Bears in the woods"),
    ("Veio profundo", "Deep vein"),
    ("Calor e Cinzas", "Heat and Ashes"),
    ("Encanto do dia", "Enchant of the day"),
    ("Forje sua Arma", "Forge your Weapon"),
    ("Guarda do Ermo", "Watch of the Waste"),
    ("Mãos calejadas", "Calloused hands"),
    ("O Sal da Terra", "The Salt of the Earth"),
    ("Presas de lobo", "Wolf fangs"),
    ("Resgate Ousado", "A Bold Rescue"),
    ("Rotina de caça", "Hunting routine"),
    ("Visite o Porto", "Visit the Port"),
    ("Bichos na praia", "Beasts on the beach"),
    ("Casco na trilha", "Shells on the trail"),
    ("Cobre pra forja", "Copper for the forge"),
    ("Costa protegida", "A guarded coast"),
    ("Limpeza da mata", "Clearing the woods"),
    ("Linha de defesa", "Line of defence"),
    ("Marcas na areia", "Marks in the sand"),
    ("Marcas na pedra", "Marks in the stone"),
    ("Metal do abrigo", "Metal for the shelter"),
    ("Pedreira do dia", "Quarry of the day"),
    ("Prove seu Valor", "Prove your Worth"),
    ("Pólvora na mata", "Gunpowder in the woods"),
    ("Rato de dungeon", "Dungeon rat"),
    ("Toque em COLETA", "Tap GATHER"),
    ("Vozes na subida", "Voices on the climb"),
    ("A Força da Forja", "The Strength of the Forge"),
    ("A adega, de novo", "The cellar, again"),
    ("Ameaça crescente", "A growing threat"),
    ("Couro da Geleira", "Glacier leather"),
    ("Defesa Peacemain", "Peacemain Defence"),
    ("Garras na trilha", "Claws on the trail"),
    ("Limpeza da costa", "Clearing the coast"),
    ("Matilha cinzenta", "The grey pack"),
    ("No mural: Colher", "On the board: Harvest"),
    ("O Forte Costeiro", "The Coastal Stronghold"),
    ("O primeiro chefe", "The first boss"),
    ("Patrulha da água", "Water patrol"),
    ("Ramos congelados", "Frozen branches"),
    ("Reserva de metal", "Metal reserve"),
    ("Seguindo o Vento", "Following the Wind"),
    ("Tesouro lendário", "Legendary treasure"),
    ("Toque em COMBATE", "Tap COMBAT"),
    ("Vigia das Morsas", "Walrus Watch"),
    ("A lenda do Bosque", "The legend of the Grove"),
    ("A primeira escama", "The first scale"),
    ("Batedor dos Ursos", "Bear Scout"),
    ("Caçador de chefes", "Boss hunter"),
    ("Couro de proteção", "Protective leather"),
    ("De volta ao porão", "Back to the cellar"),
    ("Domínio Morganeer", "Morganeer Dominion"),
    ("Encante uma peça.", "Enchant a piece."),
    ("Escama da Geleira", "Glacier scale"),
    ("Lenha para o cais", "Firewood for the quay"),
    ("Martelo e bigorna", "Hammer and anvil"),
    ("O abrigo da costa", "The shelter on the coast"),
    ("O caminho do cume", "The way to the summit"),
    ("O casco enterrado", "The buried hull"),
    ("Pedras sob a neve", "Stones under the snow"),
    ("Provisora do Ermo", "Provisioner of the Waste"),
    ("Vigia da Clareira", "Glade Watch"),
    ("A floresta respira", "The forest breathes"),
    ("A rainha das dunas", "The queen of the dunes"),
    ("Aço para a muralha", "Steel for the wall"),
    ("Chifre do aprendiz", "The apprentice's horn"),
    ("Exorcismo Marítimo", "Exorcism at Sea"),
    ("Lenha para o vigia", "Firewood for the watch"),
    ("Lenhador da Trilha", "Woodcutter of the Trail"),
    ("Listras na estrada", "Stripes on the road"),
    ("O Coração de Pedra", "The Heart of Stone"),
    ("O uivo da clareira", "The howl in the glade"),
    ("O velho da encosta", "The old man on the slope"),
    ("Os magos do trovão", "The mages of thunder"),
    ("Segredo sob a neve", "A secret under the snow"),
    ("Senhores da guerra", "Warlords"),
    ("Trilha da floresta", "Forest trail"),
    ("Vidro sob as dunas", "Glass beneath the dunes"),
    ("Vigia do Naufrágio", "Shipwreck Watch"),
    ("Vigia do naufrágio", "Shipwreck watch"),
    ("A Relíquia Submersa", "The Sunken Relic"),
    ("Armeiro de si mesmo", "Your own armourer"),
    ("Exploradora do Gelo", "Explorer of the Ice"),
    ("Fragmentos do casco", "Fragments of the hull"),
    ("Guardiã da Floresta", "Guardian of the Forest"),
    ("Guardião da Geleira", "Guardian of the Glacier"),
    ("Limpeza da floresta", "Clearing the forest"),
    ("Linha de tempestade", "Storm line"),
    ("Notícias da taberna", "News from the tavern"),
    ("O Confronto no Cais", "The Clash on the Quay"),
    ("O primeiro molde T2", "The first T2 mould"),
    ("Restos da capitânia", "Remains of the flagship"),
    ("Suprimentos seguros", "Supplies secured"),
    ("Três sinais na neve", "Three signs in the snow"),
    ("A Quebra do Bloqueio", "Breaking the Blockade"),
    ("Caça aos saqueadores", "Hunting the raiders"),
    ("Couro para o curtume", "Leather for the tannery"),
    ("Estoque de darksteel", "Darksteel stock"),
    ("Fuga dos Redemoinhos", "Escape from the Whirlpools"),
    ("Garra para a subarma", "A claw for the off-hand"),
    ("Madeira para o porto", "Wood for the port"),
    ("Mais forte que o aço", "Stronger than steel"),
    ("Minério para a forja", "Ore for the forge"),
    ("O Despertar da Terra", "The Waking of the Earth"),
    ("O mapa do Cartógrafo", "The Cartographer's map"),
    ("O que a pedra guarda", "What the stone keeps"),
    ("O que desceu do gelo", "What came down from the ice"),
    ("Rota para o Planalto", "Route to the Plateau"),
    ("Couro para a armadura", "Leather for the armour"),
    ("Desbravando o Furacão", "Braving the Hurricane"),
    ("O berloque do owlbear", "The owlbear's charm"),
    ("O que a pedra esconde", "What the stone hides"),
    ("Pesquisador das Dunas", "Researcher of the Dunes"),
    ("Predadores do inverno", "Winter predators"),
    ("Água para a travessia", "Water for the crossing"),
    ("Abra Menu › Minha Ilha", "Open Menu › My Island"),
    ("Ferramenta de pesquisa", "A research tool"),
    ("Reconhecimento inimigo", "Enemy reconnaissance"),
    ("Fique Perto das Arvores", "Stay Near the Trees"),
    ("O Coração da Tempestade", "The Heart of the Storm"),
    ("Colha e Entregue Madeira", "Harvest and Deliver Wood"),
    ("O que há sob o naufrágio", "What lies under the wreck"),
    ("Derrote 30 bichos da ilha.", "Defeat 30 beasts on the island."),
    ("Derrote 40 bichos da ilha.", "Defeat 40 beasts on the island."),
    ("Derrote 50 bichos da ilha.", "Defeat 50 beasts on the island."),
    ("Derrote 60 bichos da ilha.", "Defeat 60 beasts on the island."),
    ("Derrote o chefe da Caçada.", "Defeat the boss of the Hunt."),
    ("O Guardião das Profundezas", "The Guardian of the Depths"),
    ("Tenho uma tarefa pra você.", "I have a task for you."),
    ("Arraste uma skill para CIMA", "Drag a skill UP"),
    ("A bandeira do Barba-Tormenta", "Stormbeard's flag"),
    ("Menu › Ficha: gaste um ponto", "Menu › Sheet: spend a point"),
    ("Abra o mapa e toque num lugar", "Open the map and tap a place"),
    ("Junte Energia nos cristais azuis", "Collect Energy from the blue crystals"),
    ("No mural: melhore o Assentamento", "On the board: upgrade the Settlement"),
    ("No mural: Retirar, do baú da ilha", "On the board: Withdraw, from the island chest"),
    ("Menu › Habilidades: evolua um tier", "Menu › Skills: evolve one tier"),
    ("Conheceu o velho Alquimista? Ótimo.", "Met the old Alchemist? Good."),
    ("Derrote três ursos e volte inteiro.", "Defeat three bears and come back whole."),
    ("Conclua uma dungeon (Porão ou Gruta).", "Complete a dungeon (Cellar or Cavern)."),
    ("O ferreiro precisa de minério tier 2.", "The blacksmith needs tier 2 ore."),
    ("Suprimentos para a fortaleza do norte", "Supplies for the northern fortress"),
    ("Mantenha os arredores da vila seguros.", "Keep the outskirts of the village safe."),
    ("Bom trabalho. Aqui está sua recompensa.", "Good work. Here is your reward."),
    ("Reduza os monstros que rondam a cidade.", "Thin out the monsters prowling the city."),
    ("Ah, você veio. Obrigado por passar aqui.", "Ah, you came. Thank you for stopping by."),
    ("Derrote membros da Peacemain em combate.", "Defeat Peacemain members in combat."),
    ("Derrote membros da Morganeers em combate.", "Defeat Morganeers members in combat."),
    (
        "No mural: escolha um ofício na casa vazia",
        "On the board: pick a trade in the empty house",
    ),
    // ─────────────────────── as descrições e as falas de entrega ───────────────────────
    ("Os mercadores não passam mais sem escolta.", "The merchants no longer travel without an escort."),
    ("Quebre 20 pedras em qualquer veio da ilha.", "Break 20 rocks at any vein on the island."),
    ("Quebre 25 pedras em qualquer veio da ilha.", "Break 25 rocks at any vein on the island."),
    ("Quebre 30 pedras em qualquer veio da ilha.", "Break 30 rocks at any vein on the island."),
    ("Quebre 35 pedras em qualquer veio da ilha.", "Break 35 rocks at any vein on the island."),
    ("Ah, sangue novo na praça! Bem-vindo à ilha.", "Ah, fresh blood in the square! Welcome to the island."),
    ("Bestas poderosas ameaçam a ilha. Reduza-as.", "Powerful beasts threaten the island. Thin them out."),
    ("Crie 1 equipamento no Craft (botão do HUD).", "Create 1 piece of gear in Craft (the HUD button)."),
    ("Entregue minério para a fundição da cidade.", "Deliver ore to the city's foundry."),
    ("Menu › Sistema › Barra: ajuste a % da poção", "Menu › System › Bar: set the potion %"),
    ("Pequenas criaturas incomodam os pescadores.", "Small creatures are bothering the fishermen."),
    ("Tente refinar três vezes uma peça na Forja.", "Try refining a piece three times at the Forge."),
    ("A cidade precisa de couro para equipamentos.", "The city needs leather for gear."),
    ("Derrube dez ursos brancos que cercam o posto.", "Bring down ten white bears surrounding the outpost."),
    ("Tigres caçam na estrada do porto. Derrote 12.", "Tigers are hunting on the port road. Defeat 12."),
    ("Conclua as Grutas de Gelo Fundo com seu grupo.", "Complete the Deep Ice Caverns with your party."),
    ("O quadro pede madeira para as obras da cidade.", "The board asks for wood for the city's works."),
    ("Afaste doze ursos brancos da cabana da Guardiã.", "Drive twelve white bears away from the Guardian's cabin."),
    ("Crie um equipamento para a expedição nas dunas.", "Create a piece of gear for the expedition into the dunes."),
    ("Derrote seis deles e a estrada respira de novo.", "Defeat six of them and the road breathes again."),
    ("Fale com ele e depois me conte o que ele disse.", "Talk to him and then tell me what he said."),
    ("O curtume precisa de couro fresco para começar.", "The tannery needs fresh leather to get started."),
    ("Traga trinta de Cobre e a forja volta a cantar.", "Bring thirty Copper and the forge sings again."),
    ("Três ursos! Os lenhadores já voltaram pra mata.", "Three bears! The woodcutters are back in the woods already."),
    ("A fortaleza precisa de madeira tier 3 reforçada.", "The fortress needs reinforced tier 3 wood."),
    ("Criaturas hostis tomaram a mata. Faça a limpeza.", "Hostile creatures have taken the woods. Clear them out."),
    ("Derrote dez inimigos que rondam a costa do Ermo.", "Defeat ten enemies prowling the coast of the Waste."),
    ("Faça um equipamento para a jornada além do Ermo.", "Make a piece of gear for the journey beyond the Waste."),
    ("O Treinador quer ver fôlego: derrote 100 inimigos.", "The Trainer wants to see stamina: defeat 100 enemies."),
    ("Os lobos se multiplicam perto da vila. Derrote 12.", "The wolves are multiplying near the village. Defeat 12."),
    ("Saqueadores veteranos cercam a região. Elimine-os.", "Veteran raiders surround the region. Wipe them out."),
    ("Ursos desceram a encosta e assustam os lenhadores.", "Bears have come down the slope and are frightening the woodcutters."),
    ("Abra Menu › Missões, escolha a missão e toque Fazer", "Open Menu › Quests, pick the quest and tap Do"),
    ("Derrote um chefe de campo da ilha e volte ao Vigia.", "Defeat a field boss on the island and return to the Watch."),
    ("O Ferreiro está sem metal pras ferramentas da vila.", "The Blacksmith is out of metal for the village's tools."),
    ("O porto da vila precisa de madeira para os reparos.", "The village port needs wood for repairs."),
    ("Os lobos já custaram caro à ilha. Derrote 50 deles.", "The wolves have cost this island dearly. Defeat 50 of them."),
    ("Os monstros mais letais do arquipélago rondam aqui.", "The deadliest monsters in the archipelago prowl here."),
    ("Siga a estrada até o cais — o mapa mostra a âncora.", "Follow the road to the quay — the map shows the anchor."),
    ("Você luta melhor do que parece. Aqui está sua paga.", "You fight better than you look. Here's your pay."),
    ("A ilha começa a falar seu nome. Tome sua recompensa.", "The island is starting to speak your name. Take your reward."),
    ("Afaste trinta criaturas da trilha do mirante gelado.", "Drive thirty creatures off the frozen lookout trail."),
    ("Derrube quinze árvores para abrir uma trilha segura.", "Fell fifteen trees to open a safe trail."),
    ("Afaste uma Rainha Escaravelho dos locais de pesquisa.", "Drive a Scarab Queen away from the research sites."),
    ("Infiltre a sede da Peacemain e volte com informações.", "Infiltrate the Peacemain headquarters and come back with information."),
    ("Não é serviço pra novato — mas você já não é mais um.", "This isn't a job for a novice — and you aren't one any more."),
    ("O Capitão do Porto quer conhecer quem protege a ilha.", "The Harbour Captain wants to meet whoever protects the island."),
    ("Os lobos voltaram a rondar as trilhas fora da cidade.", "The wolves are prowling the trails outside the city again."),
    ("Os ursos tomaram a trilha dos lenhadores. Derrote 10.", "The bears have taken the woodcutters' trail. Defeat 10."),
    ("Infiltre a sede da Morganeers e volte com informações.", "Infiltrate the Morganeers headquarters and come back with information."),
    ("Quebre quinze veios para deixar uma reserva na cabana.", "Break fifteen veins to leave a reserve at the cabin."),
    ("Quebre vinte pedras para manter o suprimento de metal.", "Break twenty rocks to keep the metal supply going."),
    ("Conclua mais uma dungeon e leve o relato à Exploradora.", "Complete one more dungeon and take the report to the Explorer."),
    ("Derrote um chefe de campo da ilha (o mapa mostra onde).", "Defeat a field boss on the island (the map shows where)."),
    ("O veio da encosta ainda guarda muito. Quebre 30 pedras.", "The vein on the slope still holds plenty. Break 30 rocks."),
    ("Quebre dez veios perto da costa para reforçar o abrigo.", "Break ten veins near the coast to reinforce the shelter."),
    ("Seis lobos a menos na estrada. Os mercadores agradecem.", "Six fewer wolves on the road. The merchants thank you."),
    ("Conclua uma vez a dungeon do Ermo e conte ao Pesquisador.", "Complete the Waste dungeon once and tell the Researcher."),
    ("Derrote mais dois chefes de campo para mapear suas rotas.", "Defeat two more field bosses to map their routes."),
    ("O inverno vem aí e a vila quer lenha. Derrube 20 árvores.", "Winter is coming and the village wants firewood. Fell 20 trees."),
    ("Quem ouve tudo na ilha é o Taberneiro. Passe lá e escute.", "The one who hears everything on this island is the Innkeeper. Stop by and listen."),
    ("Entregue quarenta unidades de Aço para reparar a cisterna.", "Deliver forty units of Steel to repair the cistern."),
    ("O Mestre te mandou? Então você é o novato de quem falaram.", "The Master sent you? Then you're the newcomer they mentioned."),
    ("Conclua o Casco Congelado e conte ao Vigia o que encontrou.", "Complete the Frozen Hull and tell the Watch what you found."),
    ("Leve estas poções de mana. Vai precisar delas mais adiante.", "Take these mana potions. You'll need them further on."),
    ("Os owlbears também rondam as árvores geladas. Derrote seis.", "The owlbears prowl the frozen trees too. Defeat six."),
    ("Quebre vinte pedras para entender por que o casco congelou.", "Break twenty rocks to work out why the hull froze."),
    ("Escaravelhos cercam a cabana de abastecimento. Derrote oito.", "Scarabs surround the supply cabin. Defeat eight."),
    ("O Capitão gostou de você? Então o mar é o seu próximo passo.", "The Captain took a liking to you? Then the sea is your next step."),
    ("Quebre pedra ou derrube árvore: 60 coletas de qualquer tipo.", "Break rock or fell tree: 60 gathers of any kind."),
    ("Quebre vinte veios da costa para reforçar o abrigo do Vigia.", "Break twenty coastal veins to reinforce the Watch's shelter."),
    ("Crie um equipamento no Craft para preparar a defesa do posto.", "Create a piece of gear in Craft to prepare the outpost's defence."),
    ("Derrote quinze inimigos antes que alcancem a cabana da costa.", "Defeat fifteen enemies before they reach the coastal cabin."),
    ("Faça uma última patrulha e derrote vinte inimigos na Geleira.", "Make one last patrol and defeat twenty enemies on the Glacier."),
    ("Trinta de Cobre, bem contados. O Ferreiro vai ficar contente.", "Thirty Copper, counted out. The Blacksmith will be pleased."),
    ("Afaste doze inimigos dos caminhos entre a cisterna e as dunas.", "Drive twelve enemies off the paths between the cistern and the dunes."),
    ("O Alfaiate paga bem por couro em quantidade. Derrote 40 ursos.", "The Tailor pays well for leather in bulk. Defeat 40 bears."),
    ("Os tigres brancos se aproximaram do abrigo. Afaste oito deles.", "The white tigers have come close to the shelter. Drive eight away."),
    ("A ilha inteira ainda ferve. Derrote 80 bichos de qualquer tipo.", "The whole island is still boiling. Defeat 80 beasts of any kind."),
    ("Antes de pisar fora da cidade, você precisa de poções no bolso.", "Before you set foot outside the city, you need potions in your pocket."),
    ("Leve 10 de madeira tier 3 até a ilha do norte (siga a bússola).", "Take 10 tier 3 wood to the northern island (follow the compass)."),
    ("O Cartógrafo do porto desenha as trilhas da ilha. Fale com ele.", "The Cartographer at the port draws the island's trails. Talk to him."),
    ("Tente refinar mais 5 vezes. Até o +5 a falha só leva o material.", "Try refining 5 more times. Up to +5, failure only takes the material."),
    ("Daqui saem os barcos pras outras ilhas: gelo, deserto e planalto.", "The boats to the other islands leave from here: ice, desert and plateau."),
    ("Derrote um último chefe de campo e volte à cabana da Exploradora.", "Defeat one last field boss and return to the Explorer's cabin."),
    ("Então você é o herói da praça. Chegue mais, o vento aqui é forte.", "So you're the hero from the square. Come closer, the wind is strong here."),
    ("O fogo da costa não pode apagar. Derrube doze árvores da Geleira.", "The fire on the coast cannot go out. Fell twelve trees on the Glacier."),
    ("O Pesquisador das Dunas estuda os escaravelhos. Derrote dez deles.", "The Researcher of the Dunes studies the scarabs. Defeat ten of them."),
    ("Tome algumas poções por conta da casa. Não gaste todas de uma vez.", "Take a few potions on the house. Don't spend them all at once."),
    ("Estas poções maiores vão te manter de pé longe de casa. Boa viagem.", "These larger potions will keep you standing far from home. Safe travels."),
    ("Tente refinar 1 vez uma peça na Forja (botão do HUD ou o Ferreiro).", "Try refining a piece once at the Forge (the HUD button or the Blacksmith)."),
    ("Ursos desceram a encosta e assustam os lenhadores. Derrote 3 ursos.", "Bears have come down the slope and are frightening the woodcutters. Defeat 3 bears."),
    ("Quebre vinte pedras e procure os veios vitrificados pela tempestade.", "Break twenty rocks and look for the veins the storm turned to glass."),
    ("Todo bicho da ilha carrega um pouco de cobre — ninguém sabe por quê.", "Every beast on this island carries a little copper — nobody knows why."),
    ("Conclua 3 dungeons, quaisquer. Cada chefe lá dentro pode largar chave.", "Complete 3 dungeons, any of them. Every boss inside can drop a key."),
    ("Guarde a lição: bebe antes de cair, não depois. Agora volte ao Mestre.", "Remember this: drink before you fall, not after. Now go back to the Master."),
    ("Magos de Morgan puxam raios do céu para as pedras do farol. Derrote 12.", "Morgan's mages pull lightning from the sky into the lighthouse stones. Defeat 12."),
    ("Os lobos rondam as trilhas fora da cidade. Derrote 6 lobos e volte aqui.", "The wolves prowl the trails outside the city. Defeat 6 wolves and come back here."),
    ("Sem poção, a mata engole qualquer um. Aqui eu vendo vida, mana e fôlego.", "Without potions, the woods swallow anyone. Here I sell health, mana and stamina."),
    ("O contrabando voltou à adega sob o cais. Limpe a Adega do Contrabandista.", "The smuggling is back in the cellar under the quay. Clear the Smuggler's Cellar."),
    ("Um mapa aponta um baú lendário numa ilha distante. Abra-o (siga a bússola).", "A map points to a legendary chest on a distant island. Open it (follow the compass)."),
    ("Derrote vinte e cinco criaturas da Geleira antes que a trilha feche de novo.", "Defeat twenty-five creatures on the Glacier before the trail closes again."),
    ("Quem depende de loja não aguenta a tempestade. Crie 2 equipamentos no Craft.", "Anyone who relies on shops won't survive the storm. Create 2 pieces of gear in Craft."),
    ("A Provisora do Ermo precisa de pedra para firmar a cisterna. Quebre dez veios.", "The Provisioner of the Waste needs stone to shore up the cistern. Break ten veins."),
    ("Pistoleiros de Morgan acampam na mata. Derrote 12 e apague as fogueiras deles.", "Morgan's gunmen are camped in the woods. Defeat 12 and put out their fires."),
    ("Vá falar com o Alquimista — a loja de toldo verde. Diga que fui eu que mandei.", "Go talk to the Alchemist — the shop with the green awning. Tell him I sent you."),
    ("A Guardiã da Floresta encontrou pegadas de tigres. Derrote oito tigres brancos.", "The Guardian of the Forest found tiger tracks. Defeat eight white tigers."),
    ("A forja da vila está sem metal escuro. Traga 150 de Darksteel — sai das pedras.", "The village forge is out of dark metal. Bring 150 Darksteel — it comes out of the rocks."),
    ("O Alfaiate tece com fios que seguram o vento. Pergunte se ele costura para você.", "The Tailor weaves with thread that holds the wind. Ask whether he'll sew for you."),
    ("O Batedor dos Ursos precisa de cinquenta unidades de Aço para reforçar a cabana.", "The Bear Scout needs fifty units of Steel to reinforce the cabin."),
    ("Derrote um chefe de campo da Geleira. Outros aventureiros próximos também contam.", "Defeat a field boss on the Glacier. Other adventurers nearby count too."),
    ("Owlbears da Geleira atravessaram o mar gelado e rondam o alto da ilha. Derrote 5.", "Glacier owlbears have crossed the frozen sea and prowl the island's heights. Defeat 5."),
    ("A Exploradora ouviu a Mãe-da-Nevasca na montanha. Derrote dez inimigos no caminho.", "The Explorer heard the Mother of Blizzards on the mountain. Defeat ten enemies on the way."),
    ("A muralha da vila precisa de reforço antes da próxima tempestade. Traga 60 de Aço.", "The village wall needs reinforcing before the next storm. Bring 60 Steel."),
    ("Não bastou. Derrote 60 inimigos — as zonas marcadas no mapa rendem mais por minuto.", "That wasn't enough. Defeat 60 enemies — the zones marked on the map pay more per minute."),
    ("Os Morganeers voltaram ao Porão do Naufrágio. Limpe-o outra vez (Dungeons, no Menu).", "The Morganeers are back in the Shipwreck Cellar. Clear it again (Dungeons, in the Menu)."),
    ("O Identificador lê o que as pedras do farol carregam. Leve a ele o que ouviu no cais.", "The Appraiser reads what the lighthouse stones carry. Take him what you heard on the quay."),
    ("Quando estiver pronto, o mar espera por você. Diga ao Mestre que o porto está aberto.", "When you're ready, the sea is waiting for you. Tell the Master the port is open."),
    ("O Ferreiro diz que peça sem refino é peça pela metade. Tente refinar 3 vezes na Forja.", "The Blacksmith says an unrefined piece is half a piece. Try refining 3 times at the Forge."),
    ("Va ate a estacao de craft e forje a arma T1 da sua escolha com os materiais do Matteo.", "Head to the craft station and forge the T1 weapon of your choice with Matteo's materials."),
    ("O Treinador guarda quatro Garras Cinzas para as secundárias. Derrote 6 lobos da trilha.", "The Trainer keeps four Grey Claws for off-hands. Defeat 6 wolves on the trail."),
    ("Destrua a guarnição externa da Fortaleza de Ferro eliminando 25 soldados da Armada Real.", "Destroy the outer garrison of the Iron Fortress by wiping out 25 Royal Armada soldiers."),
    ("O Vigia das Morsas precisa de ajuda para manter o abrigo. Derrube cinco morsas da praia.", "The Walrus Watch needs help keeping the shelter. Bring down five walruses on the beach."),
    ("O ferreiro precisa de minério para forjar armas de defesa. Traga 10 Minérios de Ferro T1.", "The blacksmith needs ore to forge defensive weapons. Bring 10 T1 Iron Ore."),
    ("O Mestre guarda um Couro Verde para sua primeira armadura T2. Quebre 20 pedras na Geleira.", "The Master keeps a Green Leather for your first T2 armour. Break 20 rocks on the Glacier."),
    ("Sabote as operações inimigas eliminando 20 criaturas vulcânicas nas profundezas das minas.", "Sabotage the enemy's operations by wiping out 20 volcanic creatures deep in the mines."),
    ("Derrote 30 marinheiros fantasmas que assombram as brumas do leste para purificar o caminho.", "Defeat 30 ghost sailors haunting the eastern mists to cleanse the path."),
    ("O Ferreiro separou quatro Escamas Cinzas: uma para cada arma da oficina. Traga 30 de Cobre.", "The Blacksmith set aside four Grey Scales: one for each weapon in the workshop. Bring 30 Copper."),
    ("O Mestre guarda uma Escama Verde para sua primeira arma T2. Derrote 20 inimigos na Geleira.", "The Master keeps a Green Scale for your first T2 weapon. Defeat 20 enemies on the Glacier."),
    ("A vila já conta histórias sobre você. Derrote mais 5 chefes de campo e a lenda vira verdade.", "The village already tells stories about you. Defeat 5 more field bosses and the legend becomes true."),
    ("Alcance o topo da montanha do Templo das Marés no centro do Maelstrom para consagrar a busca.", "Reach the summit of the Temple of Tides mountain at the heart of the Maelstrom to consecrate the quest."),
    ("Confronte os monstros marinhos mutantes nas brumas profundas e derrote 15 criaturas de elite.", "Face the mutant sea monsters in the deep mists and defeat 15 elite creatures."),
    ("Derrote 10 capangas da guarnição corrupta da Armada que estão aterrorizando a praia do porto.", "Defeat 10 thugs from the Armada's corrupt garrison who are terrorising the port beach."),
    ("Derrote 15 guardiões de magma e recupere o Anel da Ignição Negra e o segundo fragmento do mapa.", "Defeat 15 magma guardians and recover the Ring of Black Ignition and the second map fragment."),
    ("Infiltre-se nas masmorras e alcance a cela onde o historiador real está preso (siga a bússola).", "Infiltrate the dungeons and reach the cell where the royal historian is held (follow the compass)."),
    ("Leve 10 Madeiras T1 para o posto avançado na ilha a leste (siga a bússola até a área indicada).", "Take 10 T1 Wood to the outpost on the island to the east (follow the compass to the marked area)."),
    ("O Urso Ancião dorme na encosta desde antes da vila. O trovão o acordou de mau humor. Derrote-o.", "The Elder Bear has slept on that slope since before the village. The thunder woke him in a foul mood. Defeat him."),
    ("Toda jornada começa com poções no bolso. Fale com o Alquimista, na porta da loja de toldo verde.", "Every journey starts with potions in your pocket. Talk to the Alchemist, at the door of the green-awning shop."),
    ("O Alfaiate reservou três Couros Cinzas, um para cada armadura. Afaste 3 ursos da estrada da vila.", "The Tailor set aside three Grey Leathers, one for each armour. Drive 3 bears off the village road."),
    ("Navegue através da frota de bloqueio e transporte o historiador ferido até a ilha segura ao norte.", "Sail through the blockading fleet and carry the wounded historian to the safe island to the north."),
    ("Va ate a arena (a leste) e derrote 3 inimigos com sua arma nova. Vai te dar XP pra subir de nivel!", "Head to the arena (to the east) and defeat 3 enemies with your new weapon. It'll give you the XP to level up!"),
    ("Colete 15 Minérios de Ferro T2 nas encostas do vulcão para forjar escudos de proteção contra calor.", "Gather 15 T2 Iron Ore on the volcano's slopes to forge shields against the heat."),
    ("A pedra dá quintessência a conta-gotas; tigre dá bem mais. Traga 6 — sem ela nenhuma armadura fecha.", "Rock gives quintessence a drop at a time; tigers give far more. Bring 6 — without it no armour closes."),
    ("Quanto mais arvore em volta, mais rapido vem. Junte 5 Madeiras e ENTREGUE pro Matteo (fale com ele).", "The more trees around you, the faster it comes. Gather 5 Wood and DELIVER it to Matteo (talk to him)."),
    ("A ilha está cheia demais. Derrote 30 inimigos, de qualquer espécie — procure as manchas densas no mapa.", "The island is far too crowded. Defeat 30 enemies, any species — look for the dense patches on the map."),
    ("Enfrente a frota de elite da Armada Real derrotando 35 dos seus melhores combatentes no Abismo Central.", "Take on the Royal Armada's elite fleet by defeating 35 of their best fighters in the Central Abyss."),
    ("O Identificador oferece quatro Chifres Cinzas para os acessórios. Quebre 8 pedras e traga o que encontrar.", "The Appraiser offers four Grey Horns for accessories. Break 8 rocks and bring back whatever you find."),
    ("O Banqueiro sabe o que entra e sai do porto — o dinheiro conta tudo. Pergunte a ele pelos barcos de Morgan.", "The Banker knows what comes in and out of the port — money tells everything. Ask him about Morgan's ships."),
    ("O Ferreiro precisa de metal pras ferramentas da vila. Traga 30 de Cobre — todo bicho da ilha carrega um pouco.", "The Blacksmith needs metal for the village's tools. Bring 30 Copper — every beast on the island carries a little."),
    ("Invada a praia do forte e derrote 15 soldados da Armada Real do Sol que controlam o primeiro fragmento do mapa.", "Storm the fort's beach and defeat 15 soldiers of the Royal Armada of the Sun who hold the first map fragment."),
    ("Navegue no mar enevoado e colete 20 couros T4 para preparar velas resistentes à umidade do cemitério de navios.", "Sail the misted sea and gather 20 T4 leathers to prepare sails that resist the damp of the ship graveyard."),
    ("A Armada Real bloqueou o porto. Fale com os pescadores e ajude coletando 15 Madeiras para reparar as barricadas.", "The Royal Armada has blockaded the port. Talk to the fishermen and help by gathering 15 Wood to repair the barricades."),
    ("Confronte e elimine os generais de elite da guarnição final do Almirante Vane e recupere o Coração da Tempestade.", "Face and wipe out the elite generals of Admiral Vane's final garrison and recover the Heart of the Storm."),
    ("Elimine 12 criaturas hostis na praia para limpar as cavernas de contrabando e recuperar o primeiro Anel do Abismo.", "Wipe out 12 hostile creatures on the beach to clear the smuggling caves and recover the first Ring of the Abyss."),
    ("O Capitão do Porto quer conhecer quem protege a ilha. Siga pela estrada até o cais (M abre o mapa) e fale com ele.", "The Harbour Captain wants to meet whoever protects the island. Follow the road to the quay (M opens the map) and talk to him."),
    ("O Capitão Barba-Tormenta desembarcou com a tripulação e fincou bandeira na ilha. Derrube-o e o porto volta a respirar.", "Captain Stormbeard has landed with his crew and planted a flag on the island. Bring him down and the port breathes again."),
    ("Coleta e' automatica: nao precisa de ferramenta nem clique. Fique parado perto das arvores ate a primeira Madeira cair.", "Gathering is automatic: no tool, no clicking. Just stand near the trees until the first Wood drops."),
    ("Ande contra a pedra segurando a direcao pra PULAR por cima dela, e fale com Matteo (chegue perto e aperte E / toque nele).", "Walk into the rock holding the direction to JUMP over it, then talk to Matteo (get close and press E / tap him)."),
    ("Os três chefes do Bosque voltam depois de um tempo. Derrote 3 chefes de campo — qualquer um deles, quantas vezes precisar.", "The three bosses of the Grove come back after a while. Defeat 3 field bosses — any of them, as many times as you need."),
    ("Dentro da pedra há um metal escuro que não enferruja: Darksteel. Toda peça pede 200 dele. Traga 20 para o Ferreiro ver a qualidade do veio daqui.", "Inside the rock there's a dark metal that doesn't rust: Darksteel. Every piece asks for 200 of it. Bring 20 so the Blacksmith can judge the quality of the vein here."),
    ("Abra Menu › Missões. Escolha esta missão na lista e toque Fazer. Depois, no mundo, use Pegar para juntar várias missões antes de usar Ir ou Fazer tudo.", "Open Menu › Quests. Pick this quest from the list and tap Do. Then, out in the world, use Take to gather several quests before using Go or Do all."),
    ("O cais perdeu meio píer na tempestade e o Capitão precisa de madeira. Derrube 8 árvores — é o único lugar de onde sai madeira, e ninguém tinha te dito.", "The quay lost half a pier in the storm and the Captain needs wood. Fell 8 trees — it's the only place wood comes from, and nobody had told you."),
    ("Falta a última peça da receita: o berloque, que os owlbears carregam preso ao pelo. Traga 6 e o Mestre abre o baú da vila — e solta o filhote que anda rondando o depósito.", "One last piece of the recipe is missing: the charm the owlbears carry tangled in their fur. Bring 6 and the Master opens the village chest — and lets out the cub that's been prowling around the storehouse."),
    ("O Porão do Naufrágio guarda o que a maré não levou, e quem manda lá dentro cai com a chave no bolso: chefe de dungeon larga chave três vezes mais que chefe de campo. Entre e limpe uma — sozinho já dá.", "The Shipwreck Cellar keeps what the tide didn't take, and whoever rules down there falls with the key in his pocket: a dungeon boss drops keys three times as often as a field boss. Go in and clear one — solo is enough."),
    ("Um lobo do tamanho de um cavalo lidera a matilha da clareira. Derrote o Lobo Alfa da Clareira — o mapa marca onde ele ronda. Chame alguém: chefe se enfrenta em grupo, e todos que lutarem perto contam.", "A wolf the size of a horse leads the pack in the glade. Defeat the Alpha Wolf of the Glade — the map marks where he prowls. Bring someone: bosses are fought in a party, and everyone who fights nearby counts."),
    ("Conheça o Alquimista", "Meet the Alchemist"),
    ("Lobos na estrada", "Wolves on the road"),
    ("O mirante do Bosque", "The lookout of the Grove"),
];
