//!  Servidor: os avisos que chegam pelo protocolo e o texto que o servidor monta.

pub const VERBETES: &[(&str, &str)] = &[
    // ─────────────────────────── servidor: correio oficial ───────────────────────────
    ("Carta inválida.", "Invalid letter."),
    ("Equipe · {} ({})", "Staff · {} ({})"),
    ("Anexos recebidos e salvos.", "Attachments received and saved."),
    ("Esta carta não tem anexos.", "This letter has no attachments."),
    ("Carta já resgatada ou indisponível.", "Letter already claimed or unavailable."),
    ("Este resgate já está sendo processado.", "This claim is already being processed."),
    ("Libere espaço na bolsa e tente novamente.", "Free up space in your bag and try again."),
    (
        "Carta indisponível. Receba os anexos antes de apagar.",
        "Letter unavailable. Claim the attachments before deleting.",
    ),
    (
        "Não foi possível concluir o resgate. Tente novamente.",
        "The claim could not be completed. Try again.",
    ),
    // ────────────────────────────── servidor: craft e loja ──────────────────────────────
    ("bolsa cheia", "bag full"),
    ("requer nível {}", "requires level {}"),
    ("faltam {} de cobre", "{} copper short"),
    ("este item não se aprimora", "this item cannot be upgraded"),
    ("requer nível {} para essa cor", "requires level {} for that colour"),
    ("só peça de equipamento se aprimora", "only gear can be upgraded"),
    ("escolha duas peças diferentes da bolsa", "choose two different pieces from your bag"),
    ("bolsa cheia pra esse lote", "bag too full for that batch"),
    ("escolha de 1 a {MAX_LOTE}", "choose from 1 to {MAX_LOTE}"),
    ("faltam {} de cobre ({} por unidade)", "{} copper short ({} per unit)"),
    ("{valor} TP", "{valor} TP"),
    ("{vezes}x ", "{vezes}x "),
    ("Compra recusada.", "Purchase refused."),
    ("Pedido inválido.", "Invalid order."),
    ("+{} TP creditados.", "+{} TP credited."),
    ("Pagamento recusado.", "Payment refused."),
    ("Pedido não encontrado.", "Order not found."),
    ("{quantos} é seu!{abatido}", "{quantos} is yours!{abatido}"),
    ("Esta compra já foi entregue.", "This purchase has already been delivered."),
    ("Esta compra já foi creditada.", "This purchase has already been credited."),
    ("{quantos} comprado!{abatido}", "{quantos} bought!{abatido}"),
    ("Pagamento aguardando confirmação.", "Payment awaiting confirmation."),
    ("Pagamento indisponível no momento.", "Payment unavailable right now."),
    ("{quantos} entregue na bolsa!{abatido}", "{quantos} delivered to your bag!{abatido}"),
    // ──────────────────────────────── servidor: mercado ────────────────────────────────
    ("Anúncio cancelado.", "Listing cancelled."),
    ("comprou TP no mercado", "bought TP on the market"),
    ("anunciou TP no mercado", "listed TP on the market"),
    ("cancelou anúncio de TP", "cancelled a TP listing"),
    ("Anúncio não encontrado.", "Listing not found."),
    ("Anúncio recusado: {nome}", "Listing refused: {nome}"),
    ("Anúncio cancelado: {nome}", "Listing cancelled: {nome}"),
    ("Comprado no mercado: {nome}", "Bought on the market: {nome}"),
    ("Venda: {nome} ×{} (taxa {})", "Sale: {nome} ×{} (fee {})"),
    ("O anúncio já não está ativo.", "The listing is no longer active."),
    ("{} {nome} volta em Entregas.", "{} {nome} comes back in Deliveries."),
    ("Compra não fechou: gold devolvido", "The purchase didn't go through: gold refunded"),
    (
        "Comprado: {nome} ×{}. Receba em Entregas.",
        "Bought: {nome} ×{}. Claim it in Deliveries.",
    ),
    (
        "Anúncio cancelado: {restante} TP de volta.",
        "Listing cancelled: {restante} TP back.",
    ),
    (
        "Anunciado: {qtd} TP a {preco_unit} gold cada.",
        "Listed: {qtd} TP at {preco_unit} gold each.",
    ),
    (
        "Anunciado: {nome} ×{qtd} a {preco_unit} gold cada.",
        "Listed: {nome} ×{qtd} at {preco_unit} gold each.",
    ),
    (
        "Pergaminho de Teleporte retirado: reembolso em cobre",
        "Teleport Scroll withdrawn: refunded in copper",
    ),
    (
        "Anúncio cancelado: {nome} ×{restante} volta em Entregas.",
        "Listing cancelled: {nome} ×{restante} comes back in Deliveries.",
    ),
    // ────────────────────────── servidor: sala de dungeon ──────────────────────────
    ("A sala está cheia.", "The room is full."),
    ("Só o líder começa.", "Only the leader can start."),
    ("A sala está começando.", "The room is starting."),
    ("A sala não existe mais.", "The room no longer exists."),
    ("Você não está numa sala.", "You are not in a room."),
    ("O pronto-check já está aberto.", "The ready check is already open."),
    ("Responda o pronto-check antes.", "Answer the ready check first."),
    // ─────────────────────────────── servidor: morte ───────────────────────────────
    ("Precisa de {c} de ouro.", "You need {c} gold."),
    (
        "Essa morte não pode mais ser recuperada.",
        "That death can no longer be recovered from.",
    ),
    ("em combate", "in combat"),
    // ───────────────────────── servidor: o mundo e seus avisos ─────────────────────────
    ("o pet", "the pet"),
    ("A bolsa", "The bag"),
    ("O banco", "The bank"),
    ("Seu pet", "Your pet"),
    ("o bicho", "the beast"),
    ("[FORTE] {}", "[STRONGHOLD] {}"),
    ("erro interno", "internal error"),
    ("arma invalida", "invalid weapon"),
    (" (era {} e {})", " (it was {} and {})"),
    ("já está no +{}", "it is already at +{}"),
    ("troca inválida", "invalid trade"),
    ("Mercador Mágico", "Magic Merchant"),
    ("ergueu o escudo", "raised their shield"),
    ("sessao invalida", "invalid session"),
    ("Capitão Morganeer", "Captain Morganeer"),
    ("ouro insuficiente", "not enough gold"),
    ("Alcance o nível 20", "Reach level 20"),
    ("Alquimista Errante", "Wandering Alchemist"),
    ("Guardião Peacemain", "Peacemain Guardian"),
    ("auth nao disponivel", "auth unavailable"),
    ("char nao autorizado", "character not authorised"),
    ("char nao encontrado", "character not found"),
    ("quantidade inválida", "invalid quantity"),
    (" (libera em \"{t}\")", " (unlocks at \"{t}\")"),
    ("[/who] {} online: {}", "[/who] {} online: {}"),
    ("receita desconhecida", "unknown recipe"),
    ("[/who] ninguém online", "[/who] nobody online"),
    ("[Pet] {} aprendeu {}.", "[Pet] {} learned {}."),
    ("item de loja inválido", "invalid shop item"),
    ("Continua firme, marujo.", "Keep at it, sailor."),
    ("Não há caminho até ali.", "There is no path there."),
    ("Você embarca rumo a {}.", "You set sail for {}."),
    ("[Pet] {nome} já tem {}.", "[Pet] {nome} already has {}."),
    ("longe demais do vendedor", "too far from the vendor"),
    ("Convite de grupo expirou.", "The party invite expired."),
    ("[Pet] {nome} aprendeu {}.", "[Pet] {nome} learned {}."),
    ("voce esta sendo carregado", "you are being carried"),
    ("Coleta: chegue mais perto.", "Gathering: get closer."),
    ("Grupo cheio (5 jogadores).", "Party full (5 players)."),
    ("Já está no tamanho máximo.", "It is already at maximum size."),
    ("[Pet] Equipe um pet antes.", "[Pet] Equip a pet first."),
    ("Esta peça pede nível {req}.", "This piece asks for level {req}."),
    ("História: \"{}\" concluída.", "Story: \"{}\" completed."),
    ("Você já tem essa aparência.", "You already have that appearance."),
    ("slot de inventário inválido", "invalid inventory slot"),
    ("Moedas Mágicas insuficientes", "not enough Magic Coins"),
    ("Bolsa cheia — coleta pausada.", "Bag full — gathering paused."),
    (" (era a afinidade da criatura)", " (that was the creature's affinity)"),
    ("[Poção] {} em recarga: {:.1} s", "[Potion] {} on cooldown: {:.1} s"),
    ("conta conectada em outro lugar", "the account is connected somewhere else"),
    ("confirme seu e-mail para entrar", "confirm your e-mail to sign in"),
    ("essa peça não pode ser refinada", "that piece cannot be refined"),
    ("Chegue mais perto pra conversar.", "Get closer to talk."),
    ("Combate contra jogadores é a pé.", "Player combat happens on foot."),
    ("Comprado por {price} de {moeda}.", "Bought for {price} {moeda}."),
    ("Experiência recuperada (grátis).", "Experience recovered (free)."),
    ("Faltam {} de ouro para aumentar.", "{} gold short to make it bigger."),
    ("Longe demais para ir a pé daqui.", "Too far to walk from here."),
    ("Personagem não está neste canal.", "The character is not on this channel."),
    ("bolsa cheia para receber a troca", "bag too full to receive the trade"),
    ("[Pet] {nome} chegou ao nível {n}.", "[Pet] {nome} reached level {n}."),
    ("[Pet] Esse pet já conhece a skill.", "[Pet] That pet already knows the skill."),
    ("teto da semana: {} Selos por conta", "weekly cap: {} Seals per account"),
    ("A história não pode ser abandonada.", "The story cannot be abandoned."),
    ("Jogador já tem um convite pendente.", "That player already has a pending invite."),
    ("{target_name} não está neste canal.", "{target_name} is not on this channel."),
    ("equipamento se compra um de cada vez", "gear is bought one piece at a time"),
    ("[Pet] Esse pet não tem skill nenhuma.", "[Pet] That pet has no skill at all."),
    ("inventário cheio pros itens comprados", "inventory too full for the items bought"),
    ("quantidade indisponível no inventário", "that quantity is not in your inventory"),
    ("precisa de {ds} Darksteel e {cu} Cobre", "needs {ds} Darksteel and {cu} Copper"),
    ("Convite de grupo enviado (60 segundos).", "Party invite sent (60 seconds)."),
    ("História: \"{}\" concluída. Próximo: {}", "Story: \"{}\" completed. Next: {}"),
    ("use a loja de trocas do Mercador Mágico", "use the Magic Merchant's trade shop"),
    ("A história ainda não chegou a {passo}.", "The story hasn't reached {passo} yet."),
    ("Você abriu o baú e encontrou a relíquia!", "You opened the chest and found the relic!"),
    ("[Afinidade] {nome} agora dá {} e {de}.", "[Affinity] {nome} now gives {} and {de}."),
    ("[Desmantelar] Materiais recuperados: {}.", "[Salvage] Materials recovered: {}."),
    ("[Pet] Esse slot de skill não está livre.", "[Pet] That skill slot is not free."),
    ("{} diária(s) expiraram na virada do dia.", "{} daily quest(s) expired when the day turned over."),
    ("Este representante não atende sua facção.", "This representative does not serve your faction."),
    ("Grupo cheio ou convite não é mais válido.", "Party full, or the invite is no longer valid."),
    ("faltam {falta} de Energia para este ponto", "{falta} Energy short for this point"),
    ("{nome} destravado — veja no guarda-roupa.", "{nome} unlocked — check your wardrobe."),
    ("[Pet] As skills de {nome} foram removidas.", "[Pet] {nome}'s skills were removed."),
    ("Comprou {qtd}x {nome} por {total} de cobre.", "You bought {qtd}x {nome} for {total} copper."),
    ("Dungeon cheia, tente novamente em instantes", "Dungeon full, try again in a moment"),
    ("Experiência recuperada por {custo} de ouro.", "Experience recovered for {custo} gold."),
    ("Faltam {} de {moeda} ({price} por unidade).", "{} {moeda} short ({price} per unit)."),
    ("Missão cumprida: volte ao Mestre de Missões.", "Objective met: go back to the Quest Master."),
    ("Você perdeu proficiência em armas ao morrer.", "You lost weapon proficiency when you died."),
    (
        "Bolsa cheia: {qtd} de cobre foi pras Entregas.",
        "Bag full: {qtd} copper went to your Deliveries.",
    ),
    (
        "{} agora tem {tam} espaços (−{custo} de ouro).",
        "{} now has {tam} slots (−{custo} gold).",
    ),
    (
        "Jogador já está em grupo ou em outra instância.",
        "That player is already in a party or in another instance.",
    ),
    (
        "[Afinidade] Equipe um pet ou uma montaria antes.",
        "[Affinity] Equip a pet or a mount first.",
    ),
    (
        "[Pet] O primeiro slot de skill abre no nível {}.",
        "[Pet] The first skill slot opens at level {}.",
    ),
    (
        "[Invocação] Você não tem pergaminhos suficientes.",
        "[Summoning] You don't have enough scrolls.",
    ),
    (
        "Fale com o Capitão do Porto, no cais, para embarcar.",
        "Talk to the Harbour Captain, on the quay, to set sail.",
    ),
    (
        "Cuidado, marujo! Derrota aquele inimigo ali primeiro.",
        "Careful, sailor! Take down that enemy over there first.",
    ),
    (
        "Recebeu {receber}x {nome} por {total} Moedas Mágicas.",
        "You received {receber}x {nome} for {total} Magic Coins.",
    ),
    (
        "Rota indisponível no momento: {onde} está fora do ar.",
        "That route is unavailable right now: {onde} is offline.",
    ),
    (
        "[Desmantelar] Falta espaço na bolsa para os materiais.",
        "[Salvage] Not enough room in your bag for the materials.",
    ),
    (
        "{}: entregue ao Mestre de Missões, na praça da cidade.",
        "{}: turn it in to the Quest Master, in the city square.",
    ),
    (
        "[Desmantelar] Essa peça não possui receita recuperável.",
        "[Salvage] That piece has no recoverable recipe.",
    ),
    (
        "Equipa o machado pelo inventario que ai a gente continua.",
        "Equip the axe from your inventory and then we carry on.",
    ),
    (
        "[Invocação] {no_correio} prêmio(s) foram para as Entregas.",
        "[Summoning] {no_correio} prize(s) went to your Deliveries.",
    ),
    (
        "[Pet] {nome} chegou ao nível {n} — um slot de skill abriu!",
        "[Pet] {nome} reached level {n} — a skill slot opened!",
    ),
    (
        "[Afinidade] Pra rolar a montaria, tire o pet do slot antes.",
        "[Affinity] To reroll the mount, take the pet out of the slot first.",
    ),
    (
        "O baú está trancado. Aceite a Caça ao tesouro com um morador.",
        "The chest is locked. Take the Treasure Hunt from a resident.",
    ),
    (
        "[Desmantelar] Só peças com atributos podem ser desmanteladas.",
        "[Salvage] Only pieces with attributes can be salvaged.",
    ),
    (
        "[Pet] Todos os slots abertos estão ocupados. Use o Removedor.",
        "[Pet] Every open slot is taken. Use the Remover.",
    ),
    (
        "O banco fica com a Banqueira da cidade ou o Banqueiro do porto.",
        "The bank is with the Banker in the city or the Banker at the port.",
    ),
    (
        "A escritura é sua: fale com o Capitão do Porto e peça MINHA ILHA.",
        "The deed is yours: talk to the Harbour Captain and ask for MY ISLAND.",
    ),
    (
        "[Sistema] Todos os mobs despawnados. Spawn zones reabastecendo...",
        "[System] Every mob despawned. Spawn zones refilling...",
    ),
    (
        "Aumente o banco com a Banqueira da cidade ou o Banqueiro do porto.",
        "Expand the bank with the Banker in the city or the Banker at the port.",
    ),
    (
        "[Pet] Todos os pets equipados comeram. Alimentados por mais {} min.",
        "[Pet] Every equipped pet has eaten. Fed for another {} min.",
    ),
    (
        "Ainda falta madeira. Fica perto das arvores ate juntar 5 e volta aqui.",
        "Still short on wood. Stay near the trees until you have 5, then come back.",
    ),
    (
        "O Pergaminho de Teleporte foi retirado. Use a montaria e as rotas do mapa.",
        "The Teleport Scroll has been withdrawn. Use your mount and the map's routes.",
    ),
    (
        "História: este passo acontece na ilha {ilha}. Embarque com o Capitão do Porto.",
        "Story: this step happens on {ilha}. Set sail with the Harbour Captain.",
    ),
    (
        "Alcance o nível 20 antes de embarcar para a Geleira. Faça as missões secundárias do Bosque.",
        "Reach level 20 before sailing for the Glacier. Do the side quests in the Grove.",
    ),
    (
        "Otimo! Aqui, leva esse material. Vai na estacao de craft e forja a arma T1 que voce quiser.",
        "Good work! Here, take this material. Head to the craft station and forge whichever T1 weapon you like.",
    ),
    (
        "Vai na estacao de craft (a bigorna/bancada ali) e forja sua arma. Os materiais ja sao seus.",
        "Head to the craft station (the anvil/bench over there) and forge your weapon. The materials are already yours.",
    ),
    (
        "Abre Menu > Missoes, escolhe Aprenda a fazer missoes e toca Fazer. Depois podes pegar varias no menu e usar Fazer tudo.",
        "Open Menu > Quests, pick Learn how quests work and tap Do. After that you can take several from the menu and use Do all.",
    ),
    (
        "Boa, pulou a pedra direitinho! Nao precisa de machado nem de nada: fica parado perto daquelas arvores que a madeira vem sozinha. Me traz 5.",
        "Nice, you cleared that rock! You don't need an axe or anything: just stand near those trees and the wood comes on its own. Bring me 5.",
    ),
    (
        "Antes de zarpar, aprende as missoes: abre Menu > Missoes, escolhe Aprenda a fazer missoes na lista e toca Fazer. Mais tarde, Pegar so aceita; usa Fazer tudo quando quiser partir.",
        "Before you sail, learn how quests work: open Menu > Quests, pick Learn how quests work from the list and tap Do. Later on, Take only accepts; use Do all when you want to set off.",
    ),
    ("Guardiao de Treino", "Training Guardian"),
    (
        "Sem espaco acessivel fora da zona segura.",
        "No reachable space outside the safe zone.",
    ),
    // ─────────────────────────────── servidor: a colônia ───────────────────────────────
    ("Do baú: {}.", "From the chest: {}."),
    ("{} foi embora.", "{} has left."),
    ("O baú está vazio.", "The chest is empty."),
    ("{nome} melhorado.", "{nome} upgraded."),
    ("Esse ofício não existe.", "That trade does not exist."),
    ("Este eixo já está no máximo.", "This track is already at maximum."),
    ("Você ainda não tem uma ilha.", "You don't have an island yet."),
    ("{} mudou-se para a sua ilha.", "{} has moved to your island."),
    ("Falta material para esta melhoria.", "Not enough material for this upgrade."),
    ("A bolsa está cheia: nada saiu do baú.", "Your bag is full: nothing left the chest."),
    (
        "Colheita de {horas:.0}h, no baú da ilha: {}.",
        "{horas:.0}h of harvest, into the island chest: {}.",
    ),
    (
        "A ilha ainda não rendeu nada. Volte mais tarde.",
        "The island hasn't yielded anything yet. Come back later.",
    ),
    (
        "Do baú: {}. Ficaram {n} pilha(s) — a bolsa encheu.",
        "From the chest: {}. {n} stack(s) stayed behind — your bag filled up.",
    ),
    (
        "O baú da ilha está cheio. Retire o que há nele primeiro.",
        "The island chest is full. Take what's in it out first.",
    ),
    (
        "Não há casa para mais ninguém. Suba o Assentamento primeiro.",
        "There is no house for anyone else. Raise the Settlement first.",
    ),
    (
        "Ninguém mora aqui ainda. Suba o Assentamento e contrate alguém.",
        "Nobody lives here yet. Raise the Settlement and hire someone.",
    ),
    (
        "Colheita de {horas:.0}h no baú: {}. O resto não caibe — o baú está cheio.",
        "{horas:.0}h of harvest into the chest: {}. The rest doesn't fit — the chest is full.",
    ),
    // ───────────────────────────── servidor: dungeon e arena ─────────────────────────────
    ("Baú · {}", "Chest · {}"),
    ("Bolsa cheia.", "Bag full."),
    ("Guardião da Gruta", "Guardian of the Cavern"),
    ("Levante-se antes.", "Get up first."),
    ("Faltam {} de ouro.", "{} gold short."),
    ("Reviver em {:.0} s.", "Revive in {:.0} s."),
    ("Você deixa a Arena.", "You leave the Arena."),
    ("Chegue perto do baú.", "Get close to the chest."),
    ("Você saiu da dungeon.", "You left the dungeon."),
    ("Você saiu da partida.", "You left the run."),
    ("Personagem fora do jogo.", "Character out of the game."),
    ("Você já está numa dungeon.", "You are already in a dungeon."),
    ("A sala ficou parada e fechou.", "The room sat idle and closed."),
    ("Sem mais entradas à venda hoje.", "No more entries for sale today."),
    ("{} item(ns) do chão recolhidos.", "{} item(s) picked up off the ground."),
    ("O grupo caiu: o andar recomeçou.", "The party went down: the floor restarted."),
    ("A Arena é de passagem: você voltou.", "The Arena is a waypoint: you went back."),
    ("Entrada comprada por {preco} de ouro.", "Entry bought for {preco} gold."),
    (
        "Alguém não aceitou: você voltou pra fila.",
        "Somebody didn't accept: you went back to the queue.",
    ),
    (
        "Você está na Arena. Toque em Sair para voltar.",
        "You are in the Arena. Tap Leave to go back.",
    ),
    (
        "Primeira vitória! A recompensa está no Correio.",
        "First win! The reward is in your Mail.",
    ),
    (
        "A dungeon foi reiniciada; você saiu com segurança.",
        "The dungeon was restarted; you got out safely.",
    ),
    (
        "A dungeon foi reiniciada; você foi recuperado no porto.",
        "The dungeon was restarted; you were recovered at the port.",
    ),
    (
        "Você entra na Arena. Para voltar, abra Dungeons e toque em Sair.",
        "You enter the Arena. To go back, open Dungeons and tap Leave.",
    ),
    // ─────────────────────────── servidor: evolução de skill ───────────────────────────
    ("habilidade inválida", "invalid skill"),
    ("faltam {} de Energia", "{} Energy short"),
    ("falta o Tomo {} de {}", "missing Tome {} of {}"),
    ("grau de tomo inválido", "invalid tome grade"),
    ("o Tier {} exige nível {}", "Tier {} requires level {}"),
    ("{} evoluiu para Tier {}.", "{} evolved to Tier {}."),
    ("Tomo {} de {} condensado.", "Tome {} of {} condensed."),
    ("limite de tomos alcançado", "tome limit reached"),
    ("essa habilidade já está no Tier X", "that skill is already at Tier X"),
    ("essa habilidade libera no nível {precisa}", "that skill unlocks at level {precisa}"),
    // ────────────────────────── servidor: as recusas de skill ──────────────────────────
    ("Skill em recarga.", "Skill on cooldown."),
    ("Mana insuficiente.", "Not enough mana."),
    ("O alvo está morto.", "The target is dead."),
    ("Skill indisponível.", "Skill unavailable."),
    ("Alvo fora do alcance.", "Target out of range."),
    ("O alvo está na zona segura.", "The target is in the safe zone."),
    ("Selecione um inimigo válido.", "Select a valid enemy."),
    ("Aguarde terminar a ação atual.", "Wait for the current action to finish."),
    ("O alvo não está mais disponível.", "The target is no longer available."),
    ("Esta skill pertence a outra arma.", "This skill belongs to another weapon."),
    ("Não foi possível alcançar o alvo.", "The target could not be reached."),
    ("O alvo está atrás de um obstáculo.", "The target is behind an obstacle."),
    ("Não é possível atacar na zona segura.", "You cannot attack in the safe zone."),
    ("Seu nível ainda não libera esta skill.", "Your level does not unlock this skill yet."),
    ("Selecione um inimigo para usar esta skill.", "Select an enemy to use this skill."),
    // ──────────────────────── servidor: loja e montaria no mundo ────────────────────────
    ("Agora não dá para montar.", "You cannot mount right now."),
    ("Pare a coleta para montar.", "Stop gathering to mount."),
    ("Você recebeu {} de {nome}!", "You received {} {nome}!"),
    ("Você recebeu {} de Energia!", "You received {} Energy!"),
    ("Loja indisponível no momento.", "The shop is unavailable right now."),
    (
        "Equipe uma montaria na bolsa antes de montar.",
        "Equip a mount in your bag before mounting.",
    ),
    (
        "{nome} enviado ao correio: sua bolsa está cheia.",
        "{nome} sent to your mail: your bag is full.",
    ),
    (
        "{nome} entregue na bolsa. Abra para revelar o prêmio!",
        "{nome} delivered to your bag. Open it to reveal the prize!",
    ),
    (
        "Invocação indisponível. Os pergaminhos voltaram para sua bolsa.",
        "Summoning unavailable. The scrolls went back to your bag.",
    ),
    (
        "Invocação indisponível. Os pergaminhos voltaram pelas Entregas.",
        "Summoning unavailable. The scrolls came back through Deliveries.",
    ),
    // ───────────────────────── servidor: a Ilha Mágica e o relógio ─────────────────────────
    ("Degrau desconhecido.", "Unknown step."),
    ("{} abre no nível {}.", "{} opens at level {}."),
    ("Você deixa a Ilha Mágica.", "You leave the Magic Island."),
    ("Você já está neste degrau.", "You are already on this step."),
    ("{} está fechada no momento.", "{} is closed right now."),
    ("A Ilha Mágica não abre daqui.", "The Magic Island does not open from here."),
    ("A Ilha Mágica abre no nível {}.", "The Magic Island opens at level {}."),
    ("Não há tempo ativo para retomar.", "There is no active time to resume."),
    ("Seu tempo na Ilha Mágica acabou.", "Your time on the Magic Island is over."),
    ("Ilha Mágica: {} minuto(s) restantes.", "Magic Island: {} minute(s) left."),
    ("{} abre no nível {} (você: {nivel}).", "{} opens at level {} (you: {nivel})."),
    ("Você entra na {} — {minutos} minutos.", "You enter {} — {minutos} minutes."),
    ("Você retoma seu tempo na Ilha Mágica.", "You resume your time on the Magic Island."),
    ("Ilha Mágica: {marco} segundos restantes.", "Magic Island: {marco} seconds left."),
    (
        "Você viaja para a {}. O relógio continua.",
        "You travel to {}. The clock keeps running.",
    ),
    (
        "Tempo da Ilha Mágica estendido: {minutos} minutos restantes.",
        "Magic Island time extended: {minutos} minutes left.",
    ),
    // ───────────────────────── servidor: mercado no mundo ─────────────────────────
    (" (+{gold} gold)", " (+{gold} gold)"),
    ("1 entrega recebida", "1 delivery claimed"),
    ("Nada para receber.", "Nothing to claim."),
    ("{n} entregas recebidas", "{n} deliveries claimed"),
    (
        "O mercado global está desligado neste servidor.",
        "The global market is switched off on this server.",
    ),
    (
        "Bolsa cheia: libere espaço para receber o resto.",
        "Bag full: free up space to claim the rest.",
    ),
    (
        "Compra enviada: {total} gold reservados. Chega em Entregas.",
        "Purchase sent: {total} gold held. It arrives in Deliveries.",
    ),
    (
        "Anúncio enviado: {nome} ×{qtd}. Aparece no mercado em instantes.",
        "Listing sent: {nome} ×{qtd}. It shows up on the market in a moment.",
    ),
    ("isso não se combina", "that cannot be combined"),
    ("Calendário indisponível.", "Calendar unavailable."),
    // ──────────────────────────── servidor: social e clã ────────────────────────────
    ("Atualizado.", "Updated."),
    ("Conta não autenticada.", "Account not authenticated."),
    ("Convite de clã enviado.", "Clan invite sent."),
    ("Aguarde o resgate atual.", "Wait for the current claim."),
    ("Pedido de amizade enviado.", "Friend request sent."),
    ("Não foi possível carregar o social.", "The social panel could not be loaded."),
    ("Social indisponível. Tente novamente.", "Social unavailable. Try again."),
    ("Aguarde um instante e tente novamente.", "Wait a moment and try again."),
    ("Aguarde a atualização e tente novamente.", "Wait for the refresh and try again."),
    ("Social indisponível: servidor sem banco.", "Social unavailable: the server has no database."),
    (
        "Anexos já entregues; aguardando confirmação.",
        "Attachments already delivered; awaiting confirmation.",
    ),
    (
        "Correio oficial enviado para {n} personagem(ns).",
        "Official mail sent to {n} character(s).",
    ),
    ("Você não tem clã.", "You have no clan."),
    ("Carta não encontrada.", "Letter not found."),
    ("Clã cheio (50 membros).", "Clan full (50 members)."),
    ("Escolha outro personagem.", "Choose another character."),
    ("Você já pertence a um clã.", "You already belong to a clan."),
    ("Esse personagem já tem clã.", "That character already has a clan."),
    ("Nome de personagem inválido.", "Invalid character name."),
    ("Já existe um clã com esse nome.", "A clan with that name already exists."),
    ("Resgate deve passar pelo mundo.", "The claim has to go through the world."),
    ("Aguarde 10 segundos entre cartas.", "Wait 10 seconds between letters."),
    ("Aviso do clã: até 200 caracteres.", "Clan notice: up to 200 characters."),
    ("Nome do clã: de 3 a 24 caracteres.", "Clan name: 3 to 24 characters."),
    ("Só o líder do clã pode fazer isso.", "Only the clan leader can do that."),
    ("Personagem não pertence ao seu clã.", "That character does not belong to your clan."),
    ("Limite de convites pendentes atingido.", "Pending invite limit reached."),
    ("Lista de amigos ou pedidos cheia (100).", "Friend or request list is full (100)."),
    ("Saia do seu clã antes de aceitar outro.", "Leave your clan before accepting another."),
    ("Convite de clã não está mais disponível.", "That clan invite is no longer available."),
    ("Já existe amizade ou pedido entre vocês.", "There is already a friendship or request between you."),
    ("Caixa do destinatário cheia (100 cartas).", "The recipient's inbox is full (100 letters)."),
    ("Personagem não encontrado ou nome ambíguo.", "Character not found, or the name is ambiguous."),
    ("Pedido de amizade não está mais disponível.", "That friend request is no longer available."),
    (
        "Transfira a liderança ou dissolva o clã antes de sair.",
        "Transfer leadership or disband the clan before leaving.",
    ),
    (
        "Envio administrativo deve passar pelo canal autenticado.",
        "An administrative send has to go through the authenticated channel.",
    ),
    (
        "Preencha assunto (até 60) e mensagem (até 1000 caracteres).",
        "Fill in a subject (up to 60) and a message (up to 1000 characters).",
    ),
    // ───────────────────────── servidor: missões, objetivos ─────────────────────────
    ("faltam {} de {}", "{} of {} short"),
    ("missão já entregue", "quest already turned in"),
    ("o objetivo ainda não foi cumprido", "the objective has not been met yet"),
    ("item não vendável no basket", "that item cannot be sold in this basket"),
    (
        "[ADMIN] '{}' offline → aplicado no DB (vale no próximo login).",
        "[ADMIN] '{}' offline → applied in the DB (takes effect at next login).",
    ),
    (
        "Reserva de anexo mudou; save recusado para evitar duplicação (carta {}).",
        "The attachment reservation changed; the save was refused to avoid duplication (letter {}).",
    ),
    // ──────────────────────── o web: os dois e-mails da conta ────────────────────────
    ("Olá,", "Hello,"),
    ("Se o botão não abrir:", "If the button doesn't work:"),
    ("Confirme sua conta no Tempest", "Confirm your Tempest account"),
    ("Confirmar minha conta", "Confirm my account"),
    ("Redefinir a senha do Tempest", "Reset your Tempest password"),
    ("Escolher uma senha nova", "Choose a new password"),
    (
        "Falta confirmar seu e-mail para a conta ficar completa.",
        "Your e-mail still needs confirming for the account to be complete.",
    ),
    (
        "Alguém pediu para redefinir a senha desta conta.",
        "Someone asked to reset the password on this account.",
    ),
    (
        "O link vale por 48 horas. Se não foi você que criou a conta, é só ignorar.",
        "The link is good for 48 hours. If you didn't create the account, just ignore this.",
    ),
    (
        "O link vale por 1 hora e só pode ser usado uma vez. Se não foi você,                  pode ignorar — sua senha continua a mesma.",
        "The link is good for 1 hour and can only be used once. If this wasn't you,                  you can ignore it — your password stays the same.",
    ),
];
