//! Cliente: HUD, menus, painéis e os avisos que o próprio cliente escreve.
//!
//! As regras dos buracos estão em `super`.

/// O texto do CLIENTE: HUD, menus, painéis, avisos locais.
pub const VERBETES: &[(&str, &str)] = &[
    // ─────────────────────────── cliente: rede e versão ───────────────────────────
    ("already exists", "já existe"),
    ("invalid data", "dados inválidos"),
    ("response had no body", "resposta sem corpo"),
    ("server error ({c})", "erro do servidor ({c})"),
    ("error ({c})", "erro ({c})"),
    ("response had no HTTP status", "resposta sem codigo HTTP"),
    ("server replied {codigo}", "servidor respondeu {codigo}"),
    ("unexpected response ({codigo})", "resposta inesperada ({codigo})"),
    ("incomplete response from the server", "resposta incompleta do servidor"),
    ("release: HTTP {codigo}", "release: HTTP {codigo}"),
    ("server list: {e}", "lista de servidores: {e}"),
    // atualizacao.rs — a tela que aparece quando o protocolo não bate
    ("Back", "Voltar"),
    ("Not now", "Agora não"),
    ("Open TestFlight", "Abrir TestFlight"),
    ("Update in the store", "Atualizar na loja"),
    ("Download update", "Baixar atualização"),
    ("Client out of date", "Cliente desatualizado"),
    ("Update required", "Atualização necessária"),
    ("Open the site to update", "Abrir site para atualizar"),
    ("Checking for updates...", "Verificando atualizações..."),
    ("Could not open the browser.", "Não foi possível abrir o navegador."),
    ("Open mmo.brunji.com.br in your browser.", "Abra mmo.brunji.com.br no navegador."),
    ("Update the game from the site to continue.", "Atualize o jogo pelo site para continuar."),
    ("Your version is incompatible with the server.", "Sua versão é incompatível com o servidor."),
    ("A new version of Tempest is available.", "Uma nova versão do Tempest está disponível."),
    // ─────────────────────────────── cliente: auras ───────────────────────────────
    ("Crop", "Recorte"),
    ("PET AURAS", "AURAS DE PETS"),
    ("MOUNT AURAS", "AURAS DE MONTARIAS"),
    ("AURAS BY GEAR", "AURAS POR EQUIPAMENTO"),
    (
        "Verde T1 +12 / Azul T2 +12 / Roxo T3 +12 / Laranja T4 +12",
        "Green T1 +12 / Blue T2 +12 / Purple T3 +12 / Orange T4 +12",
    ),
    (
        "Mesma cor e refino: T4           T3           T2           T1",
        "Same colour and refine: T4           T3           T2           T1",
    ),
    // ──────────────────────────── cliente: os automáticos ────────────────────────────
    ("AUTO GATHER · GATHERING", "AUTO COLETA · COLETANDO"),
    ("AUTO GATHER · SEARCHING", "AUTO COLETA · PROCURANDO"),
    ("AUTO GATHER · BAG FULL", "AUTO COLETA · BOLSA CHEIA"),
    ("AUTO GATHER · HEADING TO NODE", "AUTO COLETA · INDO AO RECURSO"),
    ("AUTO GATHER · WAITING FOR NODES…", "AUTO COLETA · AGUARDANDO RECURSOS…"),
    ("AUTO COMBAT · ATTACKING", "AUTO COMBATE · ATACANDO"),
    ("AUTO COMBAT · SEARCHING", "AUTO COMBATE · BUSCANDO"),
    ("AUTO QUEST · {} · {}", "AUTO MISSÃO · {} · {}"),
    ("heading to the vein", "indo ao veio"),
    ("going to talk", "indo conversar"),
    ("returning to the Master", "voltando ao Mestre"),
    ("heading to the key point", "indo ao ponto-chave"),
    ("taking the next one", "recebendo a próxima"),
    ("looking for the objective", "procurando o objetivo"),
    ("heading to the beast zone", "indo à zona dos bichos"),
    ("looking for another node", "procurando outro recurso"),
    ("Story: {nome} to continue.", "História: {nome} para continuar."),
    (
        "Auto quest: the Master has no new quest right now.",
        "Auto missão: o Mestre não tem missão nova agora.",
    ),
    (
        "Auto quest stopped: \"{nome}\" is no longer active.",
        "Auto missão encerrada: \"{nome}\" não está mais ativa.",
    ),
    (
        "Auto quest: I don't know where the objective of \"{nome}\" is on this island.",
        "Auto missão: não sei onde fica o objetivo de \"{nome}\" nesta ilha.",
    ),
    // auto_resumo.rs
    ("item {id}", "item {id}"),
    ("Gathered: {}", "Coletado: {}"),
    ("Gathered: {coletado}", "Coletado: {coletado}"),
    ("Queued: {}", "Na fila: {}"),
    ("Go", "Ir"),
    ("map", "mapa"),
    ("hide", "ocultar"),
    ("show ›", "ver ›"),
    ("click: travel · zone/node: go · Esc closes", "clique: viajar · zona/recurso: ir · Esc fecha"),
    ("Queue: {n} of {m} · locked ones are skipped", "Fila: {n} de {m} · bloqueada é pulada"),
    ("No reward", "Sem recompensa"),
    ("Last: {} · {}", "Última: {} · {}"),
    ("Previous: {} · {}", "Anterior: {} · {}"),
    ("Completed: {} · {}", "Concluída: {} · {}"),
    ("Total received: {}", "Total recebido: {}"),
    ("Picking the next quest...", "Escolhendo próxima missão..."),
    ("AUTO QUEST  ·  {} completed", "AUTO MISSÃO  ·  {} concluída(s)"),
    ("Doing: {nome}  {feito}/{total}", "Fazendo: {nome}  {feito}/{total}"),
    ("Rewards: waiting for completion", "Recompensas: aguardando conclusão"),
    // ──────────────────────────────── cliente: banco ────────────────────────────────
    ("Bank", "Banco"),
    ("Bag", "Bolsa"),
    ("Gold {}", "Ouro {}"),
    ("Maximum size", "Tamanho máximo"),
    ("+{} slots · {} gold", "+{} espaços · {} ouro"),
    (
        "toque num item para guardar ou retirar",
        "tap an item to store or withdraw",
    ),
    // ───────────────────────────── cliente: barra de vida ─────────────────────────────
    ("no Luck active", "sem Sorte ativa"),
    ("no Fortune active", "sem Fortuna ativa"),
    ("mana below the threshold", "mana abaixo do limiar"),
    ("no XP bonus active", "sem bônus de XP ativo"),
    ("health below the threshold", "vida abaixo do limiar"),
    ("stamina below the threshold", "vigor abaixo do limiar"),
    // ──────────────────────────────── cliente: bolsa ────────────────────────────────
    ("Weapon", "Arma"),
    ("Mana", "Mana"),
    ("Use", "Usar"),
    ("Health", "Vida"),
    ("Belt", "Cinto"),
    ("Common", "Comum"),
    ("Craft", "Craft"),
    ("Strength", "Força"),
    ("Currency", "Moeda"),
    ("Level", "Nível"),
    ("Power", "Poder"),
    ("Attack", "Ataque"),
    ("Earring", "Brinco"),
    ("Defence", "Defesa"),
    ("Amulet", "Amuleto"),
    ("Critical", "Crítico"),
    ("Equip", "Equipar"),
    ("Refine", "Refinar"),
    ("Armour", "Armadura"),
    ("Cancel", "Cancelar"),
    ("Combine", "Combinar"),
    ("Dexterity", "Destreza"),
    ("Material", "Material"),
    ("Mount", "Montaria"),
    ("Level {}", "Nível {}"),
    ("Level {req}", "Nível {req}"),
    ("Pet acc.", "Aces. pet"),
    ("Upgrade", "Aprimorar"),
    ("Weapon · {}", "Arma · {}"),
    ("Bracelet", "Bracelete"),
    ("Sort", "Organizar"),
    ("Wisdom", "Sabedoria"),
    ("Open 10+1", "Abrir 10+1"),
    ("Consumable", "Consumível"),
    ("Unequip", "Desequipar"),
    ("Spurring", "Esporeando"),
    ("Off-hand", "Secundária"),
    ("Speed", "Velocidade"),
    ("Mount acc.", "Aces. mont."),
    ("Salvage", "Desmantelar"),
    ("Gear", "Equipamento"),
    ("Equip: {}", "Equipar: {}"),
    ("Atk. speed", "Vel. ataque"),
    ("Loot pickup range", "Busca saque a"),
    ("Quantity {}", "Quantidade {}"),
    ("Restores mana.", "Recupera mana."),
    ("Restores health.", "Recupera vida."),
    ("Restores stamina.", "Recupera vigor."),
    ("In use: {} · {}", "Em uso: {} · {}"),
    ("vs. running on foot", "vs. correr a pé"),
    ("Salvage item?", "Desmantelar item?"),
    ("Requires level {req}", "Requer nível {req}"),
    ("Your bag is full.", "A bolsa está cheia."),
    ("Gold {}    Copper {}", "Ouro {}    Cobre {}"),
    ("In use: no weapon", "Em uso: nenhuma arma"),
    ("Crafting material.", "Material de criação."),
    ("same power as equipped", "mesmo poder do vestido"),
    ("Summoning Scroll", "Pergaminho de Invocação"),
    ("Active with a pet equipped", "Ativo com um pet equipado"),
    ("Darksteel {}    Energy {}", "Darksteel {}    Energia {}"),
    ("No room for the portrait", "Retrato sem espaço na tela"),
    ("Active with a mount equipped", "Ativo com montaria equipada"),
    ("{s} power over what you have on", "{s} de poder sobre o vestido"),
    ("+{s} power over what you have on", "+{s} de poder sobre o vestido"),
    ("{} · Tier {} · item level {}", "{} · Tier {} · nível do item {}"),
    ("No compatible item in your bag.", "Nenhum item compatível na bolsa."),
    ("{}: 10% chance to recover 1", "{}: 10% de chance de recuperar 1"),
    (
        "A peça será consumida. Você receberá:",
        "The piece will be consumed. You will receive:",
    ),
    (
        "Peça básica, sem instância de atributos.",
        "Basic piece, with no attribute roll.",
    ),
    (
        "+30% de XP por 1 hora. Beber outra renova a hora.",
        "+30% XP for 1 hour. Drinking another resets the hour.",
    ),
    (
        "Abra para revelar um prêmio aleatório decidido pelo servidor.",
        "Open to reveal a random prize decided by the server.",
    ),
    (
        "+30% de ouro e cobre dos bichos por 1 hora. Beber outra renova a hora.",
        "+30% gold and copper from beasts for 1 hour. Drinking another resets the hour.",
    ),
    (
        "+20% de chance de drop (bichos e coleta) por 1 hora. Beber outra renova a hora.",
        "+20% drop chance (beasts and gathering) for 1 hour. Drinking another resets the hour.",
    ),
    // ─────────────────────────────── cliente: coleção ───────────────────────────────
    ("In use", "Em uso"),
    ("At the top", "No topo"),
    ("{} · in use", "{} · em uso"),
    ("Combine {}/{}", "Combinar {}/{}"),
    (
        "Nada ainda. O pergaminho da Loja traz um.",
        "Nothing yet. The scroll in the Shop brings one.",
    ),
    (
        "Laranja é o topo: não há grau acima para combinar.",
        "Orange is the top: there is no higher grade to combine.",
    ),
    (
        "Combinar: {} {} tentam {}, {}% de chance, {} de cobre. Falhar consome os {}.",
        "Combine: {} {} attempt {}, {}% chance, {} copper. Failing consumes the {}.",
    ),
    ("Gathering · {} · {:.1} s", "Coletando · {} · {:.1} s"),
    ("Opening · {} · {:.1} s", "Abrindo · {} · {:.1} s"),
    ("Bag full — gathering paused", "Bolsa cheia — coleta pausada"),
    // ────────────────────────────── cliente: a colônia ──────────────────────────────
    ("Harvest", "Colher"),
    ("Withdraw", "Retirar"),
    ("Improve", "Melhorar"),
    ("Residents", "Moradores"),
    ("My Island", "Minha Ilha"),
    ("At maximum.", "No máximo."),
    ("building the island…", "montando a ilha…"),
    ("{} would give {} {}/h", "{} daria {} {}/h"),
    ("→ {} slots (from {})", "→ {} espaços (de {})"),
    ("{}, 1 trade house.", "{}, 1 casa de ofício."),
    ("Ready to harvest: {}", "Pronto para colher: {}"),
    ("{}, {v} trade houses.", "{}, {v} casas de ofício."),
    ("{}, no house for a resident.", "{}, sem casa pra morador."),
    ("→ {nome}, {b} houses (+{})", "→ {nome}, {b} casas (+{})"),
    ("{} slots in the island chest.", "{} espaços no baú da ilha."),
    ("→ {}/h per resident (from {})", "→ {}/h por morador (de {})"),
    ("Island chest · {}/{} slots", "Baú da ilha · {}/{} espaços"),
    ("Empty — the harvest lands here.", "Vazio — a colheita cai aqui."),
    ("→ {nome}, more flat ground", "→ {nome}, mais terreno plano"),
    ("The island hasn't yielded anything yet.", "A ilha ainda não rendeu nada."),
    ("Empty house — pick a trade", "Casa vazia — escolha um ofício"),
    ("drag to rotate · pinch to zoom", "arraste para girar · pinça dá zoom"),
    (
        "Cada morador rende {q}/h do ofício dele.",
        "Each resident yields {q}/h of their trade.",
    ),
    (
        "{horas:.0}h de {h:.0}h — rendendo cheio.",
        "{horas:.0}h of {h:.0}h — yielding at full rate.",
    ),
    (
        "Tamanho {} · Recursos {} · Banco {} espaços",
        "Size {} · Resources {} · Bank {} slots",
    ),
    (
        "{horas:.0}h — parou de render às {teto:.0}h. Colha.",
        "{horas:.0}h — stopped yielding at {teto:.0}h. Harvest it.",
    ),
    (
        "Rendendo {}/h. A primeira unidade sai em ~{min} min.",
        "Yielding {}/h. The first unit arrives in ~{min} min.",
    ),
    (
        "Ninguém mora aqui. Contrate um ofício numa casa vazia.",
        "Nobody lives here. Hire a trade in an empty house.",
    ),
    (
        "{horas:.0}h — passou das {h:.0}h e desde então rende metade.",
        "{horas:.0}h — past {h:.0}h, and yielding half since then.",
    ),
    (
        "Ninguém mora aqui. Melhore o Assentamento para abrir uma casa.",
        "Nobody lives here. Upgrade the Settlement to open a house.",
    ),
    // ──────────────────────────── cliente: barra de itens ────────────────────────────
    ("Empty", "Vazio"),
    ("Clear", "Limpar"),
    ("AUTO · on", "AUTO · ligado"),
    ("Item bar", "Barra de itens"),
    ("AUTO uses at {}", "AUTO usa com {}"),
    ("AUTO · off", "AUTO · desligado"),
    ("Consumables in your bag", "Consumíveis na bolsa"),
    ("Pick an item from the list ›", "Escolha um item na lista ›"),
    ("No consumables in your bag.", "Nenhum consumível na bolsa."),
    (
        "Escolha um item e depois um espaço (ou o contrário). Na tela, arraste o botão pra CIMA pra ligar o AUTO.",
        "Pick an item and then a slot (or the other way round). On screen, drag the button UP to switch AUTO on.",
    ),
    // ─────────────────────────── cliente: opções de coleta ───────────────────────────
    ("Energy", "Energia"),
    ("Auto gather", "Auto coleta"),
    ("What to gather", "O que coletar"),
    ("Search radius", "Raio de busca"),
    (
        "Defender-se: atacado, mata o bicho e volta",
        "Defend yourself: if attacked, kill the beast and return",
    ),
    (
        "Procura a partir de onde o AUTO foi ligado.",
        "Searches from where AUTO was switched on.",
    ),
    // ─────────────────────────── cliente: opções de combate ───────────────────────────
    ("Combat", "Combate"),
    ("Player", "Jogador"),
    ("The nearest", "O mais perto"),
    ("Against players", "Contra jogador"),
    ("Never attack players", "Nunca atacar jogador"),
    ("Attack any player", "Atacar qualquer jogador"),
    ("Whoever hits me from afar", "Quem me acerta de longe"),
    ("After that, in this order", "Depois dela, nesta ordem"),
    ("Only strike back at whoever hit me", "Só revidar em quem me bateu"),
    (
        "só entra se o PvP abaixo permitir",
        "only applies if the PvP setting below allows it",
    ),
    (
        "o de sempre: o que estiver mais próximo",
        "the usual: whichever is closest",
    ),
    (
        "Missão de caça ativa vem sempre primeiro.",
        "An active hunt quest always comes first.",
    ),
    (
        "você bate no de perto e continua apanhando",
        "you hit the near one and keep taking hits",
    ),
    // ────────────────────────── cliente: opções de interface ──────────────────────────
    ("Light", "Leves"),
    ("Never", "Nunca"),
    ("Pretty", "Bonitas"),
    ("Shadows", "Sombras"),
    ("Interface", "Interface"),
    ("{min} min", "{min} min"),
    ("Off", "Desligadas"),
    ("Enable now", "Ativar agora"),
    ("HUD size", "Tamanho do HUD"),
    ("Default size", "Tamanho padrão"),
    ("Battery saver", "Economia de energia"),
    ("No active quest. Open Menu › Quests to take several.", "Nenhuma missão ativa. Abra Menu › Missões para pegar várias."),
    ("Turn on by itself after idling for", "Entrar sozinho sem tocar na tela por"),
    ("Pretty: late-afternoon light and scenery shadows.", "Bonitas: luz de fim de tarde e sombras do cenário."),
    ("Untranslated lines show in Portuguese.", "Frase sem tradução aparece em português."),
    ("Changes apply at once and are saved on your character.", "Muda na hora e fica salvo no personagem."),
    ("Auto after idling", "Auto após inatividade"),
    ("Back to default ({:.0}%)", "Voltar ao padrão ({:.0}%)"),
    ("Size of the HUD and text", "Tamanho do HUD e dos textos"),
    ("Pretty: late-afternoon sun", "Bonitas: sol de fim de tarde"),
    ("and soft shadows from the scenery.", "e sombras suaves do cenário."),
    ("The choice is saved on this device.", "A escolha fica salva no aparelho."),
    // ──────────────────────────── cliente: gráficos ────────────────────────────
    ("Graphics", "Gráficos"),
    ("Preset", "Predefinição"),
    ("Low", "Baixo"),
    ("Medium", "Médio"),
    ("High", "Alto"),
    ("Ultra", "Ultra"),
    ("View distance", "Distância de visão"),
    ("Near", "Perto"),
    ("Normal", "Normal"),
    ("Far", "Longe"),
    ("Very far", "Muito longe"),
    ("Extreme", "Extrema"),
    ("Fog hides the edge. Farther lets the camera tilt lower.", "A névoa esconde a borda. Mais longe deixa a câmera deitar mais."),
    ("Grass and bushes", "Grama e arbustos"),
    ("Sparse", "Pouca"),
    ("Full", "Cheia"),
    ("Trees, rocks and anything solid always show.", "Árvores, pedras e tudo que é sólido sempre aparecem."),
    ("Frame-rate cap", "Limite de quadros"),
    ("Unlimited", "Sem limite"),
    ("30 saves battery on phones.", "30 economiza bateria no celular."),
    ("Sea", "Mar"),
    ("Calm", "Calmo"),
    ("Waves", "Ondas"),
    ("Other players' skill effects", "Efeitos de habilidade dos outros jogadores"),
    ("Hide", "Esconder"),
    ("Show", "Mostrar"),
    ("Monster and boss attacks always show.", "Ataques de monstros e chefes sempre aparecem."),
    ("No AA", "Sem AA"),
    ("Anti-aliasing", "Anti-aliasing"),
    ("Anti-aliasing (restart to apply)", "Anti-aliasing (reinicie para aplicar)"),
    // O idioma, que é o motivo deste módulo existir.
    ("Language", "Idioma"),
    ("Game language", "Idioma do jogo"),
    (
        "Vale para menus, itens, missões e avisos. Fica salvo no aparelho.",
        "Applies to menus, items, quests and notices. Saved on this device.",
    ),
    (
        "Frase sem tradução aparece em português.",
        "Untranslated text falls back to Portuguese.",
    ),
    // ───────────────────────── cliente: confirmar e recomeçar ─────────────────────────
    ("{m}m", "{m}m"),
    ("{s}s", "{s}s"),
    ("{h}h {m:02}m", "{h}h {m:02}m"),
    ("Use again?", "Usar de novo?"),
    ("Use it anyway", "Usar assim mesmo"),
    ("{nome} is already active, with {} left.", "{nome} já está ativa, com {} restando."),
    (
        "Usar outra recomeça a hora do zero: o tempo que resta é perdido, e o efeito não acumula.",
        "Using another restarts the hour from zero: the remaining time is lost, and the effect does not stack.",
    ),
    (
        "Entrar sozinho sem tocar na tela por",
        "Enter alone without touching the screen for",
    ),
    (
        "Muda na hora e fica salvo no personagem.",
        "Changes right away and is saved on the character.",
    ),
    (
        "Bonitas: luz de fim de tarde e sombras do cenário.",
        "Pretty: late-afternoon light and shadows from the scenery.",
    ),
    // ──────────────────────────────── cliente: criação ────────────────────────────────
    ("Steel", "Aço"),
    ("Create", "Criar"),
    ("Horn", "Chifre"),
    ("Gives: {}", "Dá: {}"),
    ("Scale", "Escama"),
    ("Katana", "Katana"),
    ("Pistols", "Pistolas"),
    ("Green Steel", "Aço Verde"),
    ("Materials", "Materiais"),
    ("Green Horn", "Chifre Verde"),
    ("Strength +{emp}", "Força +{emp}"),
    ("Ingredients", "Ingredientes"),
    ("Light Armour", "Armadura Leve"),
    ("Shimmering Dust", "Pó Cintilante"),
    ("Medium Armour", "Armadura Média"),
    ("Requires level {}", "Requer nível {}"),
    ("{} · minimum level {}", "{} · nível mínimo {}"),
    ("usable from Lv {}", "usar a partir do Nv {}"),
    ("No recipe in this tab.", "Nenhuma receita nesta aba."),
    ("Creates: {qtd}× {nome_da_saida}", "Cria: {qtd}× {nome_da_saida}"),
    ("Missing {faltam} ingredient(s)", "Faltam {faltam} ingrediente(s)"),
    (
        "chave + materiais da cor + darksteel + cobre",
        "key + materials of that colour + darksteel + copper",
    ),
    (
        "chaves, pets e montarias: 5 para tentar a cor seguinte",
        "keys, pets and mounts: 5 to attempt the next colour",
    ),
    (
        "duas peças iguais sobem o tier; duas Tier IV +8 sobem a cor",
        "two identical pieces raise the tier; two Tier IV +8 raise the colour",
    ),
    (
        "10 materiais + cobre, darksteel e pó criam 1 da cor seguinte",
        "10 materials + copper, darksteel and dust create 1 of the next colour",
    ),
    // ─────────────────────────────── cliente: diálogo ───────────────────────────────
    ("Close", "Fechar"),
    ("Accept", "Aceitar"),
    ("Next", "Próximo"),
    ("Receive", "Receber"),
    ("Complete", "Concluir"),
    ("Reward: {}", "Recompensa: {}"),
    // ─────────────────────────────── cliente: diárias ───────────────────────────────
    ("Item", "Item"),
    ("Take", "Pegar"),
    ("Dailies", "Diárias"),
    ("Coming soon", "Em breve"),
    ("Available", "Disponível"),
    ("Go turn it in", "Ir entregar"),
    ("Completed today", "Concluída hoje"),
    ("Prerequisites", "Pré-requisitos"),
    ("Ready to turn in", "Pronta pra entregar"),
    ("Experience Potion", "Poção de Experiência"),
    ("{ilha} · resets in {}", "{ilha} · reset em {}"),
    ("No daily on this island.", "Nenhuma diária nesta ilha."),
    ("In progress · {feito}/{total}", "Em andamento · {feito}/{total}"),
    ("\"{}\" completed today · resets in {}.", "\"{}\" concluída hoje · reset em {}."),
    // ───────────────────────── cliente: recompensas de dungeon ─────────────────────────
    ("Boss", "Chefe"),
    ("Checking progress…", "Consultando progresso…"),
    ("Possible boss drops", "Drops possíveis do boss"),
    ("Already received this week", "Já recebeu nesta semana"),
    ("Random key · colour {}", "Chave aleatória · cor {}"),
    ("Key {}: {:.0}% in total.", "Chave {}: {:.0}% no total."),
    ("Gear: {:.0}% · up to {}.", "Equipamento: {:.0}% · até {}."),
    ("Guaranteed gear: {graus}.", "Equipamento garantido: {graus}."),
    ("Already completed · one-off bonus closed", "Já concluída · bônus único encerrado"),
    ("First completion · stage {estagio}", "Primeira conclusão · estágio {estagio}"),
    ("First win of the week · per account", "Primeira vitória da semana · por conta"),
    (
        "Nenhum drop cadastrado para este chefe.",
        "No drop registered for this boss.",
    ),
    ("Random gear · one of these pieces", "Equipamento aleatório · uma destas peças"),
    (
        "Baú de conclusão · separado do drop do boss",
        "Completion chest · separate from the boss drop",
    ),
    (
        "{} ouro + {} Marcas da Tempestade (sem bônus).",
        "{} gold + {} Storm Marks (no bonus).",
    ),
    (
        "Bônus de tempo: +50% de Marcas e material extra.",
        "Time bonus: +50% Marks and extra material.",
    ),
    (
        "Também contém cobre, darksteel e material de craft.",
        "Also contains copper, darksteel and crafting material.",
    ),
    (
        "Entrega no Correio ao vencer com entrada/recompensa.",
        "Delivered by Mail when you win with an entry/reward.",
    ),
    (
        "1 equipamento aleatório + 1 chave de craft aleatória.",
        "1 random piece of gear + 1 random crafting key.",
    ),
    (
        "Ajudante: sem equipamento, chave ou bônus de estreia.",
        "Helper: no gear, key or first-time bonus.",
    ),
    (
        "Na estreia, os dois bônus podem ser recebidos juntos.",
        "On your first run, both bonuses can be received together.",
    ),
    (
        "+1 equipamento aleatório garantido, enviado ao Correio.",
        "+1 guaranteed random piece of gear, sent to your Mail.",
    ),
    (
        "Saque no chão; itens e quantidades variam a cada abate.",
        "Loot on the ground; items and amounts vary with each kill.",
    ),
    // ───────────────────────────── cliente: dungeon e arena ─────────────────────────────
    ("Leave", "Sair"),
    ("Solo", "Solo"),
    ("Enter", "Entrar"),
    ("› AUTO", "› AUTO"),
    ("Start", "Começar"),
    ("Dungeon", "Dungeon"),
    ("Entry", "Entrada"),
    ("Stage", "Estágio"),
    ("Decline", "Recusar"),
    ("Revive", "Reviver"),
    ("VICTORY", "VITÓRIA"),
    (" (leader)", " (líder)"),
    ("Dungeons", "Dungeons"),
    ("New island", "Ilha nova"),
    ("YOU FELL", "VOCÊ CAIU"),
    ("Create room", "Criar sala"),
    ("Floor {}/{}", "Andar {}/{}"),
    ("Loading…", "Carregando…"),
    ("Closed: {}", "Fechado: {}"),
    ("Rewards", "Recompensas"),
    ("Tap: AUTO", "Toque: AUTO"),
    ("Complete {}", "Completar {}"),
    ("Gather loot", "Juntar saque"),
    ("Leave queue", "Sair da fila"),
    ("Leave room", "Sair da sala"),
    ("LEAVE THE ARENA", "SAIR DA ARENA"),
    ("Leave the Arena", "Sair da Arena"),
    ("Back to island", "Voltar à ilha"),
    ("{} · Coming soon", "{} · Em breve"),
    ("Join queue", "Entrar na fila"),
    ("Enter alone", "Entrar sozinho"),
    ("Find rooms", "Procurar salas"),
    ("OUT OF TIME", "TEMPO ESGOTADO"),
    ("Party of up to {}", "Grupo de até {}"),
    ("Go to the Arena", "Ir para a Arena"),
    ("Go to the portal", "Ir para o portal"),
    ("Connection lost — reconnecting…", "Conexão perdida — reconectando…"),
    ("Attempt {}", "Tentativa {}"),
    ("Give up", "Desistir"),
    ("Dodge", "Esquiva"),
    ("Unlock", "Desbloquear"),
    ("Reconnected.", "Reconectado."),
    ("On another island", "Em outra ilha"),
    ("COMPLETION CHEST", "BAÚ DE CONCLUSÃO"),
    ("Dungeon: {texto}", "Dungeon: {texto}"),
    ("Party found", "Grupo encontrado"),
    ("Enter the dungeon", "Entrar na dungeon"),
    ("Leader starts it", "Só o líder começa"),
    ("Revive in {:.0} s", "Reviver em {:.0} s"),
    ("{} · level {} · {}", "{} · nível {} · {}"),
    ("Waiting for the others…", "Esperando os outros…"),
    ("{} · stage {} · {}", "{} · estágio {} · {}"),
    ("Rewards today: {}/{}", "Recompensas hoje: {}/{}"),
    ("Buy entry · {} gold", "Comprar entrada · {} ouro"),
    ("{} · stage {} · {:.0} s", "{} · estágio {} · {:.0} s"),
    ("{} · stage {} · {andar}", "{} · estágio {} · {andar}"),
    ("The dungeon starts in the Arena.", "A dungeon começa na Arena."),
    ("Your room · {} · stage {}", "Sua sala · {} · estágio {}"),
    ("Entries: {}/{} (2 per day)", "Entradas: {}/{} (2 por dia)"),
    ("Fills the open spots from the queue.", "Completa as vagas pela fila."),
    ("Victory in {}! Tap the chest.", "Vitória em {}! Toque no baú."),
    ("FIRST WIN · IN YOUR MAIL", "PRIMEIRA VITÓRIA · NO CORREIO"),
    ("Time bonus: +50% Marks", "Bônus de tempo: +50% de Marcas"),
    ("{} · enemies {} · party {}/{}", "{} · inimigos {} · grupo {}/{}"),
    ("The Hunt (raid) is coming soon.", "A Caçada (raid) chega em breve."),
    ("Out of time: the stage failed.", "Tempo esgotado: o estágio falhou."),
    ("Victory! Tap the chest to open it.", "Vitória! Toque no baú para abrir."),
    ("{} · {} · limit {} · wins {}", "{} · {} · limite {} · vitórias {}"),
    ("No room open at this stage.", "Nenhuma sala aberta neste estágio."),
    ("Finding a party · {} · {} in the queue", "Procurando grupo · {} · {} na fila"),
    ("{} item(s) in your Mail: bag full", "{} item(ns) no Correio: bolsa cheia"),
    (
        "Junte o saque · a dungeon fecha em {}",
        "Gather the loot · the dungeon closes in {}",
    ),
    ("{lider} · {} player(s) · {} spot(s)", "{lider} · {} jogador(es) · {} vaga(s)"),
    (
        "Sem perda de experiência dentro da dungeon.",
        "No experience lost inside the dungeon.",
    ),
    (
        "Completar as vagas pela fila depois de 1 min",
        "Fill the open spots from the queue after 1 min",
    ),
    (
        "Sem baú de conclusão. A entrada ficou gasta.",
        "No completion chest. The entry was spent.",
    ),
    (
        "Entre sozinho ou vá até lá para formar grupo.",
        "Enter alone or go there to form a party.",
    ),
    (
        "Cada compra do dia custa o triplo da anterior.",
        "Each purchase of the day costs triple the last one.",
    ),
    (
        "Chave de craft {} {:.0}% · Marcas da Tempestade",
        "Crafting key {} {:.0}% · Storm Marks",
    ),
    (
        "Toque no baú para abrir (abre sozinho em 1 min).",
        "Tap the chest to open it (opens by itself in 1 min).",
    ),
    (
        "Entrada livre; sem recompensa, só cobre e Marcas.",
        "Free entry; no reward, just copper and Marks.",
    ),
    (
        "PROCURANDO GRUPO · {} · est. {} · {} · {} na fila",
        "FINDING A PARTY · {} · st. {} · {} · {} in the queue",
    ),
    (
        "Inimigos nível {nivel} · poder mínimo {} · peça até {}",
        "Enemies level {nivel} · minimum power {} · piece up to {}",
    ),
    (
        "Sem entrada você vai como Ajudante: sem peça nem chave.",
        "With no entry you go as a Helper: no piece and no key.",
    ),
    // ────────────────────────── cliente: ganhos e modo economia ──────────────────────────
    ("Gold", "Ouro"),
    ("Deaths", "Mortes"),
    ("Levels", "Níveis"),
    ("{m}m {seg:02}s", "{m}m {seg:02}s"),
    ("SINCE YOU STARTED", "DESDE QUE LIGOU"),
    ("+ {} other items", "+ {} outros itens"),
    ("No item yet", "Nenhum item ainda"),
    ("Swipe to go back", "Deslize para voltar"),
    ("No item gathered", "Nenhum item coletado"),
    ("BATTERY SAVER MODE", "MODO ECONOMIA DE ENERGIA"),
    ("While you were away", "Enquanto você estava fora"),
    ("Lv {} {nome}", "Lv {} {nome}"),
    ("+{q} Energy", "+{q} Energia"),
    // ─────────────────────────── cliente: escolha de NPC ───────────────────────────
    ("Quests", "Missões"),
    ("What do you want?", "O que você quer?"),
    ("tap outside to close", "toque fora para fechar"),
    // ────────────────────────── cliente: evolução de habilidade ──────────────────────────
    ("Copper {}", "Cobre {}"),
    ("Energy {}", "Energia {}"),
    ("Tier {}: {}", "Tier {}: {}"),
    ("TO TIER {}", "PARA O TIER {}"),
    ("Craft tome {}", "Fabricar tomo {}"),
    ("Evolve skill", "Evoluir habilidade"),
    ("Unlocks at level {}", "Libera no nível {}"),
    ("Tier {}  ·  +{:.0}%", "Tier {}  ·  +{:.0}%"),
    ("{} copper · you: {}", "{} cobre · você: {}"),
    ("Maximum tier reached", "Tier máximo alcançado"),
    ("{} Energy · you: {}", "{} Energia · você: {}"),
    ("TOMES FOR THIS SKILL", "TOMOS DESTA HABILIDADE"),
    ("This tier needs no tome.", "Este tier não pede tomo."),
    ("Level {} · you: {nivel}", "Nível {} · você: {nivel}"),
    ("Tier {}  ·  Power {:.0}%", "Tier {}  ·  Poder {:.0}%"),
    ("1 tome {} · you: {tem_tomo}", "1 tomo {} · você: {tem_tomo}"),
    (
        "Fabricar 1 tomo {} desta habilidade — custa {} Energia + {} cobre",
        "Craft 1 tome {} for this skill — costs {} Energy + {} copper",
    ),
    // ──────────────────────── cliente: ficha do personagem ────────────────────────
    ("Block", "Bloqueio"),
    ("POWER  {}", "PODER  {}"),
    ("Dmg. red.", "Red. dano"),
    ("Mana regen", "Reg. mana"),
    ("Health regen", "Reg. vida"),
    ("Unspent: {}", "Livres: {}"),
    ("Stamina regen", "Reg. vigor"),
    ("Max stamina", "Vigor máx."),
    ("Magic ring", "Anel mágico"),
    ("Maximum mana", "Mana máxima"),
    ("Lv. {nivel}", "Nv. {nivel}"),
    ("Maximum health", "Vida máxima"),
    ("Maximum level", "Nível máximo"),
    ("PROFICIENCIES", "PROFICIÊNCIAS"),
    ("Confirm reset", "Confirmar reset"),
    ("Sword and shield", "Espada e escudo"),
    ("Dash cooldown", "Recarga do Dash"),
    ("{}  ·  Lv. {nivel}", "{}  ·  Nv. {nivel}"),
    ("+1 attack · +2 health", "+1 ataque · +2 vida"),
    ("CHARACTER SHEET", "FICHA DO PERSONAGEM"),
    ("Redistribute for free", "Redistribuir grátis"),
    ("+1 defence · block", "+1 defesa · bloqueio"),
    ("Waiting for the server…", "Aguardando servidor…"),
    ("+5 health · regeneration", "+5 vida · regeneração"),
    ("Energy: {} · point −{}", "Energia: {} · ponto −{}"),
    ("+1 magic damage · +2 mana · -0.1% skill cooldown", "+1 dano mágico · +2 mana · -0,1% de recarga das habilidades"),
    ("XP to the next level: {}", "XP para o próximo nível: {}"),
    ("+1 dexterity · crit/attack · pistol: +1 health, +0.5% dodge", "+1 destreza · crítico/ataque · pistola: +1 de vida, +0,5% de esquiva"),
    ("Tap again to confirm", "Toque novamente para confirmar"),
    ("Bonuses active with the equipped weapon", "Bônus ativos com a arma equipada"),
    ("Waiting for attributes from the server…", "Aguardando atributos do servidor…"),
    ("Equip this weapon to activate the bonuses", "Equipe esta arma para ativar os bônus"),
    (
        "+2 vigor · regeneração · recarga do Dash",
        "+2 stamina · regeneration · Dash cooldown",
    ),
    (
        "Destreza também aumenta o dano desta arma.",
        "Dexterity also raises this weapon's damage.",
    ),
    (
        "Os bônus são calculados pelo seu nível atual.",
        "The bonuses are worked out from your current level.",
    ),
    // ──────────────────────────────── cliente: forja ────────────────────────────────
    ("Forge", "Forja"),
    ("in your bag", "na bolsa"),
    ("Chance: {}%", "Chance: {}%"),
    ("Gather speed", "Vel. coleta"),
    ("Yes, refine", "Sim, refinar"),
    ("Mounted spd.", "Vel. montado"),
    ("+{} (at the top)", "+{} (no topo)"),
    ("Copper {cu}/{}", "Cobre {cu}/{}"),
    ("Darksteel {ds}/{}", "Darksteel {ds}/{}"),
    ("Refine (risky)", "Refinar (arriscado)"),
    ("Refining wasn't possible.", "Não deu pra refinar."),
    ("Refine anyway?", "Refinar mesmo assim?"),
    ("IF THE REFINE SUCCEEDS", "SE O REFINO DER CERTO"),
    ("Not refined: {motivo}.", "Não refinou: {motivo}."),
    ("Power {a} › {b}  (+{})", "Poder {a} › {b}  (+{})"),
    ("No refinable piece.", "Nenhuma peça refinável."),
    ("This item gains no attribute.", "Este item não ganha atributo."),
    ("It failed and {nome} was destroyed.", "Falhou e {nome} foi destruída."),
    ("Failing here only spends the material.", "Falhar aqui só gasta o material."),
    ("Success! {nome} is now +{nivel}.", "Sucesso! {nome} agora é +{nivel}."),
    ("{}% to rise · {}% to DESTROY the piece.", "{}% de subir · {}% de DESTRUIR a peça."),
    ("Careful: if it fails, the piece is DESTROYED.", "Atenção: se falhar, a peça é DESTRUÍDA."),
    (
        "Falhou. {nome} continua +{nivel} (só o material foi).",
        "It failed. {nome} stays +{nivel} (only the material was spent).",
    ),
    (
        "até +5 é seguro · do +6 em diante falhar destrói a peça",
        "up to +5 is safe · from +6 on, failing destroys the piece",
    ),
    (
        "Destruída, ela não volta: o refino e os materiais dela vão junto.",
        "Once destroyed it does not come back: its refine and its materials go with it.",
    ),
    // ────────────────────────────── cliente: guarda-roupa ──────────────────────────────
    ("Skin tone", "Pele"),
    ("Face", "Rosto"),
    ("Hair", "Cabelo"),
    ("default", "padrão"),
    ("Apply", "Aplicar"),
    ("no hair", "sem cabelo"),
    ("Appearance and skins", "Aparência e skins"),
    ("Drag to rotate", "Arraste para girar"),
    ("Loading character…", "Carregando personagem…"),
    (
        "Veja as mudanças antes de aplicar.",
        "See the changes before applying them.",
    ),
    // ───────────────────────────── cliente: habilidades ─────────────────────────────
    ("Release: AUTO", "Solte: AUTO"),
    ("{} · Tier {}", "{} · Tier {}"),
    ("Release: MANUAL", "Solte: MANUAL"),
    ("Skill on cooldown", "Skill em recarga"),
    ("Not enough mana", "Mana insuficiente"),
    ("Skill interrupted", "Skill interrompida"),
    ("Automatic use switched on", "Uso automático ativado"),
    ("Character incapacitated", "Personagem incapacitado"),
    ("Automatic use switched off", "Uso automático desativado"),
    ("Wait for the current action to finish", "Aguarde terminar a ação atual"),
    ("This skill is still locked", "Esta skill ainda está bloqueada"),
    (
        "Selecione um inimigo para usar esta skill",
        "Select an enemy to use this skill",
    ),
    (
        "Lv {}  ·  {} MP  ·  {:.0}s  ·  {}  ·  pra cima: AUTO · pra baixo: manual",
        "Lv {}  ·  {} MP  ·  {:.0}s  ·  {}  ·  up: AUTO · down: manual",
    ),
    // ───────────────────────────────── cliente: HUD ─────────────────────────────────
    ("Party", "Grupo"),
    ("Notices", "Avisos"),
    ("Hostile", "Hostil"),
    ("Ride", "Montar"),
    ("{min}m", "{min}m"),
    ("Peaceful", "Pacífico"),
    ("Presence", "Presença"),
    ("Dismount", "Desmontar"),
    ("Exploring", "Explorando"),
    ("Lv {nivel}", "Lv {nivel}"),
    ("Healing", "Curando vida"),
    ("Open world", "Mundo aberto"),
    ("Recovering mana", "Recuperando mana"),
    ("{nome} · {:.0} s", "{nome} · {:.0} s"),
    ("{} · out of stock", "{} · sem estoque"),
    ("Recovering stamina", "Recuperando vigor"),
    ("{dica} · {min} min", "{dica} · {min} min"),
    ("+{}% drop chance", "+{}% chance de drop"),
    ("Sprint on [Shift]", "Ligar sprint [Shift]"),
    ("Sprint off [Shift]", "Desligar sprint [Shift]"),
    ("Tap to switch to Hostile", "Toque para ativar Hostil"),
    ("Tap to go Peaceful", "Toque para ficar Pacífico"),
    ("+{}% gold and copper from beasts", "+{}% ouro e cobre de bicho"),
    (
        "Espaço vazio · clique pra configurar",
        "Empty slot · click to configure",
    ),
    (
        "{:.0} fps · tick {tick} · {ents} entidades · {pedacos}/{vivos} terreno",
        "{:.0} fps · tick {tick} · {ents} entities · {pedacos}/{vivos} terrain",
    ),
    (
        "{base} · {} · pra cima: AUTO · pra baixo: manual · botão direito configura",
        "{base} · {} · up: AUTO · down: manual · right click configures",
    ),
    // ────────────────────────────── cliente: invocação ──────────────────────────────
    ("Tome", "Tomo"),
    ("Key", "Chave"),
    ("Grade {}", "Grau {}"),
    ("Tome {}", "Tomo {}"),
    ("Skill", "Habilidade"),
    ("REVEALING…", "REVELANDO…"),
    ("Blue Horn", "Chifre Azul"),
    ("Crafting Key", "Chave de Craft"),
    ("OPENING THE SCROLL", "ABRINDO PERGAMINHO"),
    ("tap to reveal", "toque para revelar"),
    ("SUMMONING COMPLETE", "INVOCAÇÃO CONCLUÍDA"),
    ("11 PRIZES · 10+1 BONUS", "11 PRÊMIOS · BÔNUS 10+1"),
    ("{} · now x{quantidade}", "{} · agora x{quantidade}"),
    ("{nome} · you own x{quantidade}", "{nome} · você possui x{quantidade}"),
    (
        "Equipe no slot da montaria: {:.0}% de velocidade montado",
        "Equip in the mount slot: {:.0}% mounted speed",
    ),
    (
        "Equipe no slot do pet: busca o saque a {:.0} tiles e dá {} pontos",
        "Equip in the pet slot: picks loot up at {:.0} tiles and gives {} points",
    ),
    // ────────────────────────────── cliente: ir até lá ──────────────────────────────
    ("Arrived: {}.", "Chegou: {}."),
    ("HEADING · {} · {:.0} m", "INDO · {} · {:.0} m"),
    ("I found no path to {rotulo}.", "Não achei caminho até {rotulo}."),
    // ──────────────────────────── cliente: login com Google ────────────────────────────
    ("Opening Google…", "Abrindo o Google…"),
    ("Could not start: {e}", "Não deu pra iniciar: {e}"),
    ("The request expired. Try again.", "O pedido expirou. Tente de novo."),
    ("Waiting for confirmation in the browser…", "Aguardando confirmação no navegador…"),
    ("Timed out waiting for the browser.", "Tempo esgotado esperando o navegador."),
    // ─────────────────────────────── cliente: lojas ───────────────────────────────
    ("Max", "Máx"),
    ("Buy {}x", "Comprar {}x"),
    ("in your bag: {}", "na bolsa: {}"),
    ("Nothing for sale.", "Nada à venda."),
    ("Trade for {}x", "Trocar por {}x"),
    ("Total: {} {moeda}", "Total: {} {moeda}"),
    ("Magic Coins: {}", "Moedas Mágicas: {}"),
    ("Copper {}  ·  Gold {}", "Cobre {}  ·  Ouro {}"),
    ("Gear: one at a time.", "Equipamento: um por vez."),
    ("Island vendors", "Vendedores da ilha"),
    ("No vendor on this island.", "Nenhum vendedor nesta ilha."),
    (
        "Só se compra falando com o vendedor: \"Ir\" leva você até ele.",
        "You can only buy by talking to the vendor: \"Go\" takes you to them.",
    ),
    // ───────────────────────────── cliente: loja de TP ─────────────────────────────
    ("Pets", "Pets"),
    ("{n}x", "{n}x"),
    ("Price", "Preço"),
    ("Coins", "Moedas"),
    ("Purple 5%", "Roxa 5%"),
    ("{lote}x", "{lote}x"),
    ("PLEASE WAIT…", "AGUARDE…"),
    ("Blue 12%", "Azul 12%"),
    ("Purple 20%", "Roxo 20%"),
    ("Appearance", "Aparência"),
    ("Grey 55%", "Cinza 55%"),
    ("Your balance", "Seu saldo"),
    ("Green 28%", "Verde 28%"),
    ("Green 75%", "Verde 75%"),
    ("BUY TP", "COMPRAR TP"),
    ("TP pouch", "Bolsa de TP"),
    ("Legendary 5%", "Lendário 5%"),
    ("You receive", "Você recebe"),
    ("BEST VALUE", "MELHOR VALOR"),
    ("{:.1} TP/thousand", "{:.1} TP/mil"),
    ("+{}% BONUS", "+{}% DE BÔNUS"),
    ("After the purchase", "Após a compra"),
    ("Shop: {texto}", "Loja: {texto}"),
    ("{} Energy", "{} de Energia"),
    ("{} at once", "{} de uma vez"),
    ("Confirm purchase", "Confirmar compra"),
    ("Pet Summoning", "Invocação de Pet"),
    ("{} + {} bonus", "{} + {} de bônus"),
    ("Purchase complete!", "Compra concluída!"),
    ("1 entry · 30 min", "1 entrada · 30 min"),
    ("BUY SCROLL", "COMPRAR PERGAMINHO"),
    ("Tome Summoning", "Invocação de Tomos"),
    ("SIMULATED PAYMENT", "PAGAMENTO SIMULADO"),
    ("Price · {lote}x {}", "Preço · {lote}x {}"),
    ("Not enough balance", "Saldo insuficiente"),
    ("{:.0} TP per pass", "{:.0} TP por passe"),
    ("{} · applied right away", "{} · entra na hora"),
    ("Key Summoning", "Invocação de Chaves"),
    ("{} entries · {} min", "{} entradas · {} min"),
    ("Latest purchases:  {}", "Últimas compras:  {}"),
    ("Loading the storefront…", "Carregando a vitrine…"),
    ("Mount Summoning", "Invocação de Montaria"),
    ("Tempest Points bundle", "Pacote de Tempest Points"),
    ("Tap to view and buy", "Toque para ver e comprar"),
    ("1 random crafting key.", "1 chave aleatória de craft."),
    ("1 mount, species drawn at random.", "1 montaria, espécie sorteada."),
    ("{} Energy · applied right away", "{} de Energia · entra na hora"),
    ("Items exclusive to the Storm", "Itens exclusivos da Tempestade"),
    ("1 gatherer pet, species drawn at random.", "1 pet coletor, espécie sorteada."),
    ("No appearance for sale right now.", "Nenhuma aparência à venda agora."),
    ("1 tome for one of 12 skills.", "1 tomo para uma de 12 habilidades."),
    ("Simulated payment: nothing is charged.", "Pagamento simulado: nada é cobrado."),
    ("The shop is switched off on this server.", "A loja está desligada neste servidor."),
    ("MOUNTED · {nome} · rider on the tiger", "MONTADO · {nome} · cavaleiro no tigre"),
    (
        "Pergaminho · abra na bolsa · chave aleatória",
        "Scroll · open it in your bag · random key",
    ),
    (
        "TP é da conta e vale em todos os servidores.",
        "TP belongs to the account and works on every server.",
    ),
    (
        "Chapéu · fica no guarda-roupa deste personagem",
        "Hat · kept in this character's wardrobe",
    ),
    (
        "Pergaminho · 1 montaria · espécie e cor sorteadas",
        "Scroll · 1 mount · species and colour drawn at random",
    ),
    (
        "Pergaminho de Invocação: Montaria entregue na bolsa!",
        "Summoning Scroll: Mount delivered to your bag!",
    ),
    (
        "Pergaminho · tomo aleatório para 1 de 12 habilidades",
        "Scroll · random tome for 1 of 12 skills",
    ),
    (
        "Pergaminho · 1 pet coletor · espécie e grau sorteados",
        "Scroll · 1 gatherer pet · species and grade drawn at random",
    ),
    (
        "Roupa completa · fica no guarda-roupa deste personagem",
        "Full outfit · kept in this character's wardrobe",
    ),
    (
        "Passe · vai pra bolsa · use quando quiser ({} entrada{})",
        "Pass · goes to your bag · use it whenever you like ({} use{})",
    ),
    (
        "Skin · use na bolsa · fica no guarda-roupa deste personagem",
        "Skin · use it from your bag · kept in this character's wardrobe",
    ),
    (
        "Montarias e skins não dão poder de combate: só estilo e mobilidade.",
        "Mounts and skins give no combat power: only style and mobility.",
    ),
    (
        "MUNDO · {nome} · lobo, urso, tigre, owlbear, chefe Lobo Alfa, cavaleiro no tigre",
        "WORLD · {nome} · wolf, bear, tiger, owlbear, Alpha Wolf boss, rider on the tiger",
    ),
    // ─────────────────────────────── cliente: Ilha Mágica ───────────────────────────────
    ("Bridge", "Ponte"),
    ("clock", "relógio"),
    ("no bonus", "sem bônus"),
    ("PvP open", "PvP aberto"),
    ("Magic Island", "Ilha Mágica"),
    ("{n} = {}min", "{n} = {}min"),
    ("Leave island", "Sair da ilha"),
    ("Opens at level {}", "Abre no nível {}"),
    ("Enter — {n} free", "Entrar — {n} grátis"),
    ("Enter — {n} pass(es)", "Entrar — {n} passe(s)"),
    ("Safe zone · no PvP", "Zona segura · sem PvP"),
    ("Go back without spending a pass", "Voltar sem gastar passe"),
    ("Mobs lv {}-{} · power {}", "Mobs nv {}-{} · poder {}"),
    ("{} · mobs lv {}-{} · power {}", "{} · mobs nv {}-{} · poder {}"),
    ("Switch island without spending a pass", "Trocar de ilha sem gastar passe"),

    ("Mobs lv {}-{} · power {} · you {}", "Mobs nv {}-{} · poder {} · você {}"),
    ("Switching and leaving do not pause the clock.", "Trocar e sair não pausam o relógio."),
    ("Enter — {de_graca} free + {} pass", "Entrar — {de_graca} grátis + {} passe"),
    (
        "Your time keeps running while you are off the island.",
        "Seu tempo continua correndo fora da ilha.",
    ),
    (
        "Each entry is worth 30 min. The free ones come back at 4am.",
        "Cada entrada vale 30 min. As grátis voltam às 4h.",
    ),
    (
        "Seven islets joined by bridges · PvP open · dying sends you back to the landing",
        "Sete ilhotas por pontes · PvP aberto · morrer volta à chegada",
    ),
    (
        "No entry left: the 3 free ones come back at 4am, and passes drop from bosses.",
        "Sem entrada: as 3 grátis voltam às 4h, e o passe cai de chefes.",
    ),
    // ──────────────────────── cliente: o laço principal e o login ────────────────────────
    ("Shop", "Loja"),
    ("e-mail", "e-mail"),
    ("didn't work", "não deu"),
    ("username", "usuário"),
    ("Heading to: {}", "Indo: {}"),
    ("Banker", "Banqueira"),
    ("Created: {}", "Criado: {}"),
    ("Character", "Personagem"),
    ("AUTO GATHER", "AUTO COLETA"),
    ("AUTO QUEST", "AUTO MISSÃO"),
    ("NO CONNECTION", "SEM CONEXÃO"),
    ("create account", "criar conta"),
    ("failed: {e}", "falhou: {e}"),
    ("failed: {m}", "falhou: {m}"),
    ("AUTO COMBAT", "AUTO COMBATE"),
    ("Walking · {}", "Andando · {}"),
    ("Tutorial: {}", "Tutorial: {}"),
    ("leave queue", "sair da fila"),
    ("10 s cap", "teto de 10 s"),
    ("{jog} online", "{jog} online"),
    ("send the link", "enviar o link"),
    ("Bank · {nome}", "Banco · {nome}"),
    ("kicked: {reason}", "kick: {reason}"),
    ("remember me", "lembrar de mim"),
    ("shop: {reason}", "loja: {reason}"),
    ("WAITING FOR YOU", "AGUARDANDO VOCÊ"),
    ("BOSS DEFEATED", "CHEFE DERROTADO"),
    ("Close the tutorial", "Fechar tutorial"),
    ("New quest: {}", "Nova missão: {}"),
    ("invalid e-mail", "e-mail inválido"),
    ("entry queue", "fila de entrada"),
    ("heading to {zona}", "indo pra {zona}"),
    ("map: that is water", "mapa: lá é água"),
    ("repeat the password", "repetir a senha"),
    ("Party: coming soon.", "Grupo: em breve."),
    ("QUEST COMPLETE", "MISSÃO CONCLUÍDA"),
    ("Market: {texto}", "Mercado: {texto}"),
    ("No {} in your bag.", "Sem {} na bolsa."),
    ("search again", "procurar de novo"),
    ("server {realm}", "servidor {realm}"),
    ("Sign in with Google", "Entrar com Google"),
    ("Notices: nothing new.", "Avisos: nada novo."),
    ("Quest accepted: {}.", "Missão aceita: {}."),
    ("choose the server", "escolha o servidor"),
    ("Map: only on the islands.", "Mapa: só nas ilhas."),
    ("I forgot my password", "esqueci minha senha"),
    ("Auto quest paused.", "Auto missão pausada."),
    ("Auto quest: setting sail for {nome}.", "Auto missão: embarcando para {nome}."),
    ("Auto quest: landed, resuming.", "Auto missão: desembarcou, retomando."),
    ("{} · {}/{} · Ready!", "{} · {}/{} · Pronta!"),
    ("Heading to the bank: {nome}", "Indo ao banco: {nome}"),
    ("I couldn't find the NPC here.", "Não achei o NPC aqui."),
    ("this channel is full", "este canal está cheio"),
    ("no server online", "nenhum servidor no ar"),
    ("{posicao} of {total}", "{posicao}º de {total}"),
    ("{} needs you to act.", "{} exige ação manual."),
    ("Not upgraded: {texto}", "Não aprimorou: {texto}"),
    ("login denied: {reason}", "login negado: {reason}"),
    ("Craft refused: {motivo}", "Craft recusado: {motivo}"),
    ("No line of sight · closing in", "Sem visada · aproximando"),
    ("looking for servers...", "procurando servidores..."),
    ("Type the account's e-mail.", "Digite o e-mail da conta."),
    ("No enemy nearby.", "Nenhum inimigo por perto."),
    ("travel: path blocked", "viagem: caminho bloqueado"),
    ("Quests completed: {} · {}", "Missões concluídas: {} · {}"),
    ("Upgraded: {} is now {} {}!", "Aprimorado: {} agora é {} {}!"),
    ("No line of sight · switching target", "Sem visada · trocando de alvo"),
    ("the two passwords don't match", "as duas senhas não são iguais"),
    ("password: at least 6 characters", "senha: no mínimo 6 caracteres"),
    ("username: 1 to 32 characters", "usuário: de 1 a 32 caracteres"),
    ("Auto quest paused: you went down.", "Auto missão pausada: você caiu."),
    ("I couldn't open the browser.", "Não consegui abrir o navegador."),
    ("Loot on the ground · pick the items up", "Saque no chão · colete os itens"),
    ("password: at most 128 characters", "senha: no máximo 128 caracteres"),
    ("Auto gather: attacked, striking back.", "Auto coleta: atacado, revidando."),
    ("Queue finished: {f} quest(s).", "Fila terminada: {f} missão(ões)."),
    ("your session expired — sign in again", "sua sessão expirou — entre de novo"),
    ("Auto quest moved on to \"{nome}\".", "Auto missão seguiu para \"{nome}\"."),
    ("Quest: craft a piece of gear in Craft.", "Missão: crie um equipamento no Craft."),
    ("Quest: try refining a piece at the Forge.", "Missão: tente refinar uma peça na Forja."),
    (
        "Auto quest: only steps that are yours to do are left.",
        "Auto missão: só restam passos que são seus.",
    ),
    (
        "Fila terminada: {f} feita(s), {pl} pulada(s).",
        "Queue finished: {f} done, {pl} skipped.",
    ),
    (
        "Seguindo {nome}. Mova-se ou use Esc para parar.",
        "Following {nome}. Move or press Esc to stop.",
    ),
    (
        "Missão: vença a dungeon (o auto não luta por você).",
        "Quest: win the dungeon (auto does not fight for you).",
    ),
    (
        "{from} convidou você para um grupo. Abra Menu › Grupo.",
        "{from} invited you to a party. Open Menu › Party.",
    ),
    (
        "Fila: {} missões. O que não der pra fazer agora é pulado.",
        "Queue: {} quests. Whatever can't be done now is skipped.",
    ),
    (
        "Banco: procure a Banqueira da cidade ou o Banqueiro do porto.",
        "Bank: look for the Banker in the city or the Banker at the port.",
    ),
    (
        "Esse mob não aparece na ilha atual. Viaje para a ilha dele antes de usar Ir.",
        "That mob does not appear on the current island. Travel to its island before using Go.",
    ),
    (
        "Montaria: equipe uma no slot Montaria da bolsa. Onde obter: Menu › Comércio › Loja.",
        "Mount: equip one in the Mount slot of your bag. Where to get one: Menu › Trade › Shop.",
    ),
    (
        "Mapa: toque um círculo FORTE para ir à área com mais mobs. Ao chegar, o auto combate liga.",
        "Map: tap a STRONGHOLD circle to head for the area with more mobs. On arrival, auto combat switches on.",
    ),
    (
        "Secundárias: toque Pegar, depois Ir. A auto missão segue o objetivo; craft e dungeon pedem sua ação.",
        "Side quests: tap Take, then Go. Auto quest follows the objective; craft and dungeon need you to act.",
    ),
    (
        "Se houver uma conta com esse e-mail, o link já saiu.                          Confira a caixa de entrada e o spam.",
        "If an account with that e-mail exists, the link is already on its way.                          Check your inbox and your spam.",
    ),
    // ───────────────────────────────── cliente: mapa ─────────────────────────────────
    ("Island", "Ilha"),
    ("Mobs", "Mobs"),
    ("Village", "Vila"),
    ("water", "água"),
    ("World", "Mundo"),
    ("Villages", "Vilas"),
    ("Beasts", "Bichos"),
    ("Bosses", "Chefes"),
    ("City", "Cidade"),
    ("Filters", "Filtros"),
    ("Go to", "Ir para"),
    ("Wood", "Madeira"),
    ("Node", "Recurso"),
    ("Nodes", "Recursos"),
    ("no zone", "sem zona"),
    ("Boatman", "Barqueiro"),
    ("Blue stone", "Pedra azul"),
    ("Purple stone", "Pedra roxa"),
    ("Grey stone", "Pedra cinza"),
    ("Green stone", "Pedra verde"),
    ("Beast {kind}", "Bicho {kind}"),
    ("Hunting zone", "Zona de caça"),
    ("Map · {nome}", "Mapa · {nome}"),
    ("Island Board", "Mural da Ilha"),
    ("Lv {a}–{b} · ", "Nv {a}–{b} · "),
    ("Village square", "Praça da vila"),
    (" · back in {}", " · volta em {}"),
    ("loading map…", "carregando mapa…"),
    ("loading zones…", "carregando zonas…"),
    ("Travelling · {:.0} m", "Viajando · {:.0} m"),
    ("Stronghold · {} · Lv {}–{}", "Forte · {} · Nv {}–{}"),
    ("asking the islands…", "consultando as ilhas…"),
    ("{n} regions · {:.0} m", "{n} regiões · {:.0} m"),
    ("no island replied.", "nenhuma ilha respondeu."),
    ("NPCs ({n_npcs}) · {acao}", "NPCs ({n_npcs}) · {acao}"),
    ("click: go hunt (auto combat)", "clique: ir caçar (auto combate)"),
    ("click: go gather (auto gather)", "clique: ir coletar (auto coleta)"),
    ("click: go talk (or teleport)", "clique: ir falar (ou teleportar)"),
    ("many more enemies in the same space", "muito mais inimigos no mesmo espaço"),
    ("bosses from every island · Esc closes", "chefes de todas as ilhas · Esc fecha"),
    (
        "clique: viajar · zona/recurso: ir · Esc fecha",
        "click: travel · zone/node: go · Esc closes",
    ),
    // ─────────────────────────────── cliente: o menu ───────────────────────────────
    ("Clan", "Clã"),
    ("Map", "Mapa"),
    ("Bar", "Barra"),
    ("Sheet", "Ficha"),
    ("All", "Todas"),
    ("Friends", "Amigos"),
    ("Gathering", "Coleta"),
    ("Switch", "Trocar"),
    ("Mail", "Correio"),
    ("Market", "Mercado"),
    ("TRADE", "COMÉRCIO"),
    ("Enchant", "Encantar"),
    ("Achievements", "Conquistas"),
    ("Vendors", "Vendedores"),
    ("Skills", "Habilidades"),
    ("Recover XP", "Recuperar XP"),
    // ────────────────────────── cliente: o diário de missões ──────────────────────────
    ("Open", "Abrir"),
    ("Do", "Fazer"),
    ("Faction", "Facção"),
    ("QUESTS", "MISSÕES"),
    ("Details", "Detalhes"),
    ("Story", "História"),
    ("Workshop", "A oficina"),
    ("Completed", "Concluída"),
    ("Locked", "Bloqueadas"),
    ("How to level", "Como subir"),
    ("On {}", "Na ilha {}"),
    ("Only from {}.", "Só pela {}."),
    ("{} is only entered from {}.", "{} só se entra pela {}."),
    ("Only for {}", "Só para {}"),
    ("Complete: {}", "Conclua: {}"),
    ("Side quests", "Secundárias"),
    ("Complete: {t}", "Conclua: {t}"),
    ("Gives: {premio}", "Dá: {premio}"),
    ("In progress", "Em andamento"),
    ("Do all {n}", "Fazer as {n}"),
    ("Select all", "Marcar todas"),
    ("{}h {:02}min", "{}h {:02}min"),
    ("Village folk", "Gente da vila"),
    ("Hands in the soil", "Mãos na terra"),
    ("Requires level ", "Requer nível "),
    ("The Ice Climb", "Subida do Gelo"),
    ("Tutorial · {o}", "Tutorial · {o}"),
    ("Lookout Guide", "Guia do Mirante"),
    ("Cellars and vaults", "Porões e adegas"),
    ("{} of {} steps", "{} de {} passos"),
    ("Walrus Coast", "Costa das Morsas"),
    ("What to do: {}.", "O que fazer: {}."),
    ("any dungeon", "qualquer dungeon"),
    ("{} faction pts", "{} pts de facção"),
    ("The first days", "Os primeiros dias"),
    ("Forest Shelter", "Abrigo da Floresta"),
    ("Reach level {}", "Alcance o nível {}"),
    ("Bear Pass", "Passagem dos Ursos"),
    ("Shipwreck Cellar", "Porão do Naufrágio"),
    ("the dungeon named", "a dungeon indicada"),
    ("Bestiary of the Grove", "Bestiário do Bosque"),
    ("The bosses of the Grove", "Os chefes do Bosque"),
    ("Step {} of {} · {}", "Passo {} de {} · {}"),
    ("Secrets of the Glacier", "Segredos da Geleira"),
    ("No {} in this tab.", "Nada de {} nesta aba."),
    ("Nothing to take right now.", "Nada pra pegar agora."),
    ("No locked line.", "Nenhuma linha travada."),
    ("Ready · turn in to: {q}", "Pronta · entregar: {q}"),
    ("Learn how quests work", "Aprenda a fazer missões"),
    ("Complete the raid named", "Conclua a raid indicada"),
    ("\"{}\" has already been completed.", "\"{}\" já foi concluída."),
    ("Unavailable in this version", "Indisponível nesta versão"),
    ("\"{}\" needs you to act.", "\"{}\" exige ação manual."),
    ("Follow the quest description", "Siga a descrição da missão"),
    ("Tutorial · {o}  {}/{total}", "Tutorial · {o}  {}/{total}"),
    ("Available · take it from: {q}", "Disponível · pegar com: {q}"),
    ("Manual · {feito}/{total} · {}", "Manual · {feito}/{total} · {}"),
    ("Enchant the gear named", "Encante o equipamento indicado"),
    ("No line completed yet.", "Nenhuma linha concluída ainda."),
    ("Available again in {min} min", "Disponível de novo em {min} min"),
    ("The queue already has {FILA_MAX} quests.", "A fila já tem {FILA_MAX} missões."),
    ("PvP combat: defeat {} rival(s)", "Combate PvP: derrote {} rival(is)"),
    ("Map: find and open the chest named", "Mapa: encontre e abra o baú indicado"),
    ("Menu › Craft: create {} piece(s) of gear", "Menu › Craft: crie {} equipamento(s)"),
    ("Menu › Craft: create the {}", "Menu › Craft: crie a {}"),
    ("Menu › Forge: try refining {} time(s)", "Menu › Forja: tente refinar {} vez(es)"),
    ("Nothing in progress. Check Available.", "Nada em andamento. Veja as Disponíveis."),
    (
        "Menu › Dungeons: conclua {} vez(es) {onde}",
        "Menu › Dungeons: complete {onde} {} time(s)",
    ),
    (
        "Fila: {n} de {FILA_MAX} · bloqueada é pulada",
        "Queue: {n} of {FILA_MAX} · locked ones are skipped",
    ),
    (
        "Nível {feito}/{total} · escolha: Ilha Mágica, missões secundárias ou caça em áreas densas",
        "Level {feito}/{total} · your pick: Magic Island, side quests or hunting in dense areas",
    ),
    // ─────────────────────────────── cliente: mercado ───────────────────────────────
    ("Min", "Mín"),
    ("Yours", "Seu"),
    ("Up", "Subir"),
    ("Total", "Total"),
    ("Search", "Buscar"),
    ("Down", "Descer"),
    ("Sell", "Vender"),
    ("Sold", "Vendeu"),
    ("Buy", "Comprar"),
    ("Bought", "Comprou"),
    ("Item {}", "Item {}"),
    ("Your TP", "Seus TP"),
    ("List", "Anunciar"),
    ("From bag", "Da bolsa"),
    ("Deliveries", "Entregas"),
    ("Fee {}%", "Taxa {}%"),
    ("History", "Histórico"),
    ("Next ›", "Próxima ›"),
    ("Page {}", "Página {}"),
    ("Quantity", "Quantidade"),
    ("‹ Previous", "‹ Anterior"),
    ("List TP", "Anunciar TP"),
    ("Gold per TP", "Gold por TP"),
    ("Nothing yet.", "Nada ainda."),
    ("TP to sell", "TP a vender"),
    ("Search item…", "Buscar item…"),
    ("Claim everything", "Receber tudo"),
    ("My listings", "Meus anúncios"),
    ("Active ({}/{})", "Ativos ({}/{})"),
    ("Not enough gold.", "Gold insuficiente."),
    ("Active listings {}/{}", "Anúncios ativos {}/{}"),
    ("No active listing.", "Nenhum anúncio ativo."),
    ("Nothing sellable in your bag.", "Nada vendável na bolsa."),
    ("Price per unit (gold)", "Preço por unidade (gold)"),
    ("TP for sale (gold per TP)", "TP à venda (gold por TP)"),
    ("Pick an item from your bag.", "Escolha um item da bolsa."),
    ("{} gold each · {} for sale", "{} gold cada · {} à venda"),
    ("No listing found.", "Nenhum anúncio encontrado."),
    ("No delivery waiting.", "Nenhuma entrega esperando."),
    ("Nobody selling TP right now.", "Ninguém vendendo TP agora."),
    ("Lowest asking price: {} gold", "Menor preço à venda: {} gold"),
    ("Selling TP unlocks at level {}.", "Vender TP libera no nível {}."),
    ("{presos} bound item(s) left out of the list", "{presos} vinculado(s) fora da lista"),
    (
        "Vender no mercado libera no nível {}.",
        "Selling on the market unlocks at level {}.",
    ),
    (
        "Vendas, compras, cancelamentos e devoluções esperam aqui.",
        "Sales, purchases, cancellations and returns wait here.",
    ),
    // ──────────────────────── cliente: objetivos das missões ────────────────────────
    ("Reach", "Chegar"),
    ("Collect", "Juntar"),
    ("Beat", "Vencer"),
    ("Travel", "Viajar"),
    ("Gather", "Coletar"),
    ("Learn", "Aprender"),
    ("Defeat", "Derrotar"),
    ("Turn in", "Entregar"),
    ("Objective", "Objetivo"),
    ("Abandon", "Abandonar"),
    ("Talk", "Conversar"),
    ("Go to {}", "Ir até {}"),
    ("Quests ›", "Missões ›"),
    ("{}x {nome}", "{}x {nome}"),
    ("Turning in…", "Concluindo…"),
    ("Quest journal", "Diário de missões"),
    ("whoever gave the quest", "quem deu a missão"),
    ("Talk to {nome}", "Conversar com {nome}"),
    ("No active quest.", "Nenhuma missão ativa."),
    ("Ready — turn in to: {quem}", "Pronta — entregue: {quem}"),
    ("Talk to the Harbour Captain", "Fale com o Capitão do Porto"),
    ("No quest in progress", "Nenhuma missão em andamento"),
    ("Beat {} · tap to open", "Vencer {} · toque para abrir"),
    ("Reach level {} · you: {nivel}", "Alcance o nível {} · você: {nivel}"),
    ("Beat a dungeon · tap to open", "Vencer uma dungeon · toque para abrir"),
    (
        "Nenhuma missão ativa. Abra Menu › Missões para pegar várias.",
        "No active quest. Open Menu › Quests to take several.",
    ),
    // ────────────────────────────── cliente: bestiário ──────────────────────────────
    ("{} · yours {}", "{} · seu {}"),
    ("Proficiency", "Proficiência"),
    ("+{} · yours +{}", "+{} · sua +{}"),
    ("Mob attack", "Ataque do mob"),
    ("Mob defence", "Defesa do mob"),
    ("Suggested power", "Poder sugerido"),
    ("Weapon refine", "Refino da arma"),
    ("Suggested attack", "Ataque sugerido"),
    ("Suggested defence", "Defesa sugerida"),
    ("Set pieces", "Peças do conjunto"),
    ("{} {} Lv{} · yours {}", "{} {} Nv{} · suas {}"),
    ("Visit an island to see its mobs.", "Visite uma ilha para ver seus mobs."),
    ("Tap a mob to see the details.", "Toque em um mob para ver os detalhes."),
    (
        "Inimigos das áreas visitadas · atributos reais do servidor",
        "Enemies from the areas you've visited · real attributes from the server",
    ),
    // ────────────────────────────── cliente: montarias ──────────────────────────────
    ("MOUNTING…", "MONTANDO…"),
    ("See in Shop", "Ver na Loja"),
    ("MY MOUNTS", "MINHAS MONTARIAS"),
    ("Mounted speed", "Velocidade montado"),
    (
        "Nenhuma montaria equipada. Equipe uma no slot Montaria da bolsa — a cor dela manda na velocidade.",
        "No mount equipped. Equip one in the Mount slot of your bag — its colour sets the speed.",
    ),
    // ──────────────────────────────── cliente: morte ────────────────────────────────
    ("Revive in city", "Reviver na cidade"),
    ("YOU WERE DEFEATED", "VOCÊ FOI DERROTADO"),
    ("RECOVER EXPERIENCE", "RECUPERAR EXPERIÊNCIA"),
    ("Recover XP · {} gold", "Recuperar XP · {} ouro"),
    ("{} XP · expires in {resta} h", "{} XP · expira em {resta} h"),
    ("No death to recover from.", "Nenhuma morte para recuperar."),
    ("Recover XP (free {gratis}/3)", "Recuperar XP (grátis {gratis}/3)"),
    ("Free today: {}/3 · after that it costs gold", "Grátis hoje: {}/3 · depois custa ouro"),
    ("Recovering XP does not give proficiency back.", "Recuperar XP não devolve proficiência."),
    (
        "Nenhuma experiência a recuperar desta morte.",
        "No experience to recover from this death.",
    ),
    (
        "Cada proficiência treinada perde XP ao morrer:",
        "Each trained proficiency loses XP when you die:",
    ),
    (
        "Experiência perdida: {} (recuperável por 24 h)",
        "Experience lost: {} (recoverable for 24 h)",
    ),
    (
        "10% do custo do próximo nível. Seu nível pode cair.",
        "10% of the cost of the next level. Your level can drop.",
    ),
    ("{} · offline", "{} · fora do ar"),
    ("{} · you are here", "{} · você está aqui"),
    // ──────────────────────────────── cliente: rede ────────────────────────────────
    ("the server closed the connection", "server fechou"),
    ("TLS connection not supported yet", "conexao TLS nao suportada ainda"),
    // ───────────────────────── cliente: caminhos para o nível ─────────────────────────
    ("MAGIC ISLAND", "ILHA MÁGICA"),
    ("SIDE QUESTS", "MISSÕES SECUNDÁRIAS"),
    ("HUNT IN DENSE AREAS", "CAÇAR EM ÁREAS DENSAS"),
    ("WAYS TO REACH LEVEL {alvo}", "CAMINHOS PARA O NÍVEL {alvo}"),
    (
        "Escolha como ganhar XP para continuar a história.",
        "Choose how to earn XP to carry on with the story.",
    ),
    (
        "PvP nas ilhotas de combate; XP e coleta até 2× nas ilhotas de bônus.",
        "PvP on the combat islets; XP and gathering up to 2× on the bonus islets.",
    ),
    (
        "No mapa, toque um círculo FORTE. Ir leva até lá e liga o auto combate.",
        "On the map, tap a STRONGHOLD circle. Go takes you there and switches auto combat on.",
    ),
    (
        "XP, equipamentos e recursos. Toque Pegar e depois Ir para usar auto missão.",
        "XP, gear and resources. Tap Take and then Go to use auto quest.",
    ),
    ("LEVEL {nivel}", "NÍVEL {nivel}"),
    ("Continue", "Continuar"),
    ("What's new", "Novidades"),
    ("WHAT'S NEW IN TEMPEST", "NOVIDADES DO TEMPEST"),
    // ─────────────────────────────── cliente: oficina ───────────────────────────────
    ("Combine 1x", "Combinar 1x"),
    ("Combine {n}x", "Combinar {n}x"),
    ("Synthesise 1x", "Sintetizar 1x"),
    ("Synthesise {n}x", "Sintetizar {n}x"),
    ("always succeeds", "sempre dá certo"),
    ("{} · {} to {}", "{} · {} para {}"),
    ("{}% per attempt", "{}% por tentativa"),
    ("Each synthesis spends", "Cada síntese gasta"),
    ("Missing {} copper", "Faltam {} de cobre"),
    ("Not created: {motivo}", "Não criou: {motivo}"),
    ("Each attempt spends", "Cada tentativa gasta"),
    ("Failing consumes everything.", "Falhar consome tudo."),
    ("Legendary IV is the top", "Lendário IV é o topo"),
    ("No piece in your bag.", "Nenhuma peça na bolsa."),
    ("Not combined: {motivo}", "Não combinou: {motivo}"),
    ("Requires level {} for {}", "Requer nível {} para {}"),
    ("{} for 1 · {}% · you have {}", "{} por 1 · {}% · tem {}"),
    ("{} · Tier {} · {} in your bag", "{} · Tier {} · {} na bolsa"),
    ("{} for 1 · guaranteed · you have {}", "{} por 1 · garantido · tem {}"),
    ("Not enough material for one attempt.", "Falta material para uma tentativa."),
    ("show only what works ({quantas_dao})", "mostrar só o que dá ({quantas_dao})"),
    ("showing only what works ({quantas_dao})", "mostrando só o que dá ({quantas_dao})"),
    ("Material craft: {criados}x {saida}!", "Craft de material: {criados}x {saida}!"),
    (
        "Crie no Craft ou guarde as que caírem.",
        "Make them in Craft or keep the ones that drop.",
    ),
    (
        "O refino +{perdido} das peças se perde.",
        "The +{perdido} refine on the pieces is lost.",
    ),
    (
        "Duas Tier IV +{} viram uma da cor de cima,",
        "Two Tier IV +{} become one of the colour above,",
    ),
    (
        "Duas peças iguais viram uma do tier de cima,",
        "Two identical pieces become one of the tier above,",
    ),
    (
        "{tentativas} tentativa(s), nenhuma deu certo.",
        "{tentativas} attempt(s), none succeeded.",
    ),
    (
        "no Tier I, com os atributos fixos da nova cor.",
        "at Tier I, with the fixed attributes of the new colour.",
    ),
    (
        "{tentativas} tentativa(s): {sucessos}x {saida}!",
        "{tentativas} attempt(s): {sucessos}x {saida}!",
    ),
    (
        "com os atributos fixos do novo tier, mais fortes.",
        "with the fixed attributes of the new tier, stronger ones.",
    ),
    (
        "Para subir de cor: duas Tier IV +{} (você tem {n})",
        "To raise the colour: two Tier IV +{} (you have {n})",
    ),
    (
        "Precisa de mais uma peça igual (mesmo item, cor e tier)",
        "You need one more identical piece (same item, colour and tier)",
    ),
    (
        "Nada pronto pra criar agora. Toque de novo pra ver a lista inteira.",
        "Nothing ready to create right now. Tap again to see the whole list.",
    ),
    (
        "Nada pronto pra combinar agora. Toque de novo pra ver a lista inteira.",
        "Nothing ready to combine right now. Tap again to see the whole list.",
    ),
    // ────────────────────────────── cliente: onde obter ──────────────────────────────
    ("Islands", "Ilhas"),
    ("Quest", "Missão"),
    ("Another island", "Outra ilha"),
    ("Respawning", "Renascendo"),
    ("Gather: {}", "Coletar: {}"),
    ("Buy: {}", "Comprar: {}"),
    ("Off the islands", "Fora de ilha"),
    ("Hunt: {nome}", "Caçar: {nome}"),
    ("Boss: {nome}", "Chefe: {nome}"),
    ("Craft: {nome}", "Criar: {nome}"),
    ("Daily quest", "Missão diária"),
    ("{preco} gold", "{preco} de ouro"),
    ("Material craft", "Craft de material"),
    ("None on this island", "Não há nesta ilha"),
    ("{} per kill · {}", "{} por morte · {}"),
    ("Where to get: {nome}", "Onde obter: {nome}"),
    ("{} per gather · {}", "{} por coleta · {}"),
    ("Reward: {titulo}", "Recompensa: {titulo}"),
    ("Boss Lv {nivel} · {}", "Chefe Nv {nivel} · {}"),
    ("Attendance calendar", "Calendário de presença"),
    ("TODAY", "HOJE"),
    ("BONUS", "BÔNUS"),
    ("Today's reward", "Prêmio de hoje"),
    ("Next reward", "Próximo prêmio"),
    ("All rewards claimed this month", "Todos os prêmios do mês resgatados"),
    ("Day {} of {} · claimed {}/{}", "Dia {} de {} · resgatados {}/{}"),
    ("Claimed {}/{} · next claim in {}", "Resgatados {}/{} · próximo resgate em {}"),
    ("Claimed today", "Resgatado hoje"),
    ("Pet Summon Scroll", "Pergaminho de Invocação de Pet"),
    ("Mount Summon Scroll", "Pergaminho de Invocação de Montaria"),
    ("Glittering Dust", "Pó Cintilante"),
    ("Pet Scroll", "Pergaminho de Pet"),
    ("Mount Scroll", "Perg. de Montaria"),
    ("Magic Pass", "Passe Mágico"),
    ("Pet", "Pet"),
    ("Pass", "Passe"),
    ("Dust", "Pó"),
    ("Darksteel", "Darksteel"),
    ("Day {}{}: {}", "Dia {}{}: {}"),
    (" (bonus)", " (bônus)"),
    ("Craft · minimum level {}", "Craft · nível mínimo {}"),
    ("Dungeon boss (Cavern)", "Chefe de dungeon (Gruta)"),
    ("Requires level {nivel_min}", "Requer nível {nivel_min}"),
    ("Daily claim · day{} {}", "Resgate diário · dia{} {}"),
    ("Buy from other players", "Comprar de outros jogadores"),
    ("Lv {}–{} · {} per kill · {}", "Nv {}–{} · {} por morte · {}"),
    ("Level {}+ zone: above your level", "Zona nível {}+: acima do seu nível"),
    ("No known source for this item.", "Nenhuma fonte conhecida para este item."),
    ("15/10/6/3/1% per band · Hunt coming soon", "15/10/6/3/1% por faixa · Caçada em breve"),
    (
        "{} da cor anterior · {} cobre · {} darksteel · {} pó",
        "{} of the previous colour · {} copper · {} darksteel · {} dust",
    ),
    (
        "Nível {nivel}: bem acima do seu — o combate não liga sozinho",
        "Level {nivel}: well above yours — combat won't switch on by itself",
    ),
    // ───────────────────────── cliente: escolha de personagem ─────────────────────────
    ("Outfit", "Roupa"),
    ("FACTION", "FACÇÃO"),
    ("APPEARANCE", "APARÊNCIA"),
    ("STARTING WEAPON", "ARMA INICIAL"),
    ("Unavailable", "Indisponível"),
    ("Weapon & Faction", "Arma & Facção"),
    ("name already taken", "nome ja em uso"),
    ("Enter the world", "Entrar no mundo"),
    ("Choose a name", "Escolha um nome"),
    ("Magic and support", "Magia e suporte"),
    ("Level {}  ·  {}", "Nível {}  ·  {}"),
    ("name 2-24 chars", "nome 2-24 chars"),
    ("Create character", "Criar personagem"),
    ("Defence and pressure", "Defesa e pressão"),
    ("Write your own story", "Crie sua história"),
    ("+  New character", "+  Novo personagem"),
    ("CHARACTER NAME", "NOME DO PERSONAGEM"),
    ("Ranged combat", "Combate à distância"),
    ("Opens and closes the fight", "Abre e fecha a luta"),
    ("Creating the character…", "Criando personagem…"),
    ("Choose your character", "Escolha seu personagem"),
    ("YOUR CHARACTERS  ·  {}", "SEUS PERSONAGENS  ·  {}"),
    ("name: letters/numbers/_ only", "nome so letras/numeros/_"),
    ("No room for the preview", "Prévia sem espaço na tela"),
    ("One weapon. One fresh start.", "Uma arma. Um novo começo."),
    ("Use 2 to 24 characters.", "Use de 2 a 24 caracteres."),
    ("Tap to choose the name", "Toque para escolher o nome"),
    ("Pirates after plunder.", "Piratas em busca de saques."),
    ("Adventurers and explorers.", "Aventureiros e exploradores."),
    ("Choose an available weapon.", "Escolha uma arma disponível."),
    ("Drag the character to rotate", "Arraste o personagem para girar"),
    ("Drag to see more characters", "Arraste para ver mais personagens"),
    ("Character model unavailable", "Modelo do personagem indisponível"),
    ("Use a name of 2 to 24 characters.", "Use um nome de 2 a 24 caracteres."),
    ("Waiting for confirmation from the server…", "Aguardando confirmação do servidor…"),
    ("Your next chapter is waiting.", "Seu próximo capítulo está esperando."),
    ("Use unaccented letters, numbers or _.", "Use letras sem acento, números ou _."),
    ("2 to 24 characters · letters, numbers and _", "2 a 24 caracteres · letras, números e _"),
    ("That name is already taken. Choose another.", "Esse nome já está em uso. Escolha outro."),
    (
        "Personagem criado. Sua jornada pode começar.",
        "Character created. Your journey can begin.",
    ),
    (
        "Nenhuma arma inicial disponível neste servidor.",
        "No starting weapon available on this server.",
    ),
    (
        "Sua história começa aqui. Crie seu primeiro personagem.",
        "Your story starts here. Create your first character.",
    ),
    (
        "Mantenha distância com tiros precisos, rajadas e um barril explosivo.",
        "Keep your distance with precise shots, bursts and an explosive barrel.",
    ),
    (
        "Lute na linha de frente com investidas, cortes amplos e uma barreira protetora.",
        "Fight on the front line with charges, wide slashes and a protective barrier.",
    ),
    (
        "Restaure sua vida, cure aliados próximos e invoque um impacto mágico sobre o alvo.",
        "Restore your health, heal nearby allies and call down a magical impact on your target.",
    ),
    (
        "Empunhe com as duas mãos: o saque contra quem ainda não te viu dá 2,5x de dano, e o golpe em alvo abaixo de 30% de vida dá 1,6x. Em troca, o dano contínuo é menor que o das pistolas, e a vida só volta na janela da Dança.",
        "Wield it two-handed: the draw against someone who has not seen you hits for 2.5x, and a strike on a target below 30% health for 1.6x. In exchange its sustained damage is lower than the pistols', and health only comes back inside Danca's window.",
    ),
    // ───────────────────────────────── cliente: pets ─────────────────────────────────
    ("MY PETS", "MEUS PETS"),
    ("Maximum level.", "Nível máximo."),
    ("Feed ({racoes})", "Alimentar ({racoes})"),
    ("Skill for slot {}", "Skill para o slot {}"),
    ("Feed lasts {}h per use", "A Ração dura {}h por uso"),
    ("Fed for another {}h{:02}", "Alimentado por mais {}h{:02}"),
    ("Free slot · tap to choose", "Slot livre · toque para escolher"),
    ("Hungry: gains no experience at all", "Com fome: não ganha experiência nenhuma"),
    ("{} experience short of level {}", "Faltam {} de experiência para o nível {}"),
    ("Level {nivel} / {} · {ocupados}/3 pets · T{} +{}", "Nível {nivel} / {} · {ocupados}/3 pets · T{} +{}"),
    (
        "Toque num slot livre para escolher uma skill da bolsa.",
        "Tap a free slot to choose a skill from your bag.",
    ),
    (
        "Você não tem skills disponíveis na bolsa. Elas podem ser compradas na Loja.",
        "You have no skills available in your bag. They can be bought in the Shop.",
    ),
    (
        "Nenhum pet equipado. Equipe um no slot Pet da bolsa — ele nasce no mundo e busca o saque do chão pra você.",
        "No pet equipped. Equip one in the Pet slot of your bag — it appears in the world and picks loot up off the ground for you.",
    ),
    // ──────────────────────────────── cliente: presença ────────────────────────────────
    ("Pet Summ.", "Inv. Pet"),
    ("Claim", "Resgatar"),
    ("Claimed", "Resgatado"),
    ("{} gold", "{} de ouro"),
    ("Day {n}: {}", "Dia {n}: {}"),
    ("Mount Summ.", "Inv. Montaria"),
    ("Claimed {}/{}", "Resgatados {}/{}"),
    ("{} · ends in {}", "{} · termina em {}"),
    ("Next claim in {}", "Próximo resgate em {}"),
    ("No active calendar.", "Nenhum calendário ativo."),
    ("Attendance · day {dia}: {}", "Presença · dia {dia}: {}"),
    ("Today's claim is available", "Resgate de hoje disponível"),
    (" (bag full: part of it in your Mail)", " (bolsa cheia: parte no Correio)"),
    ("{} · the month turns over on the 1st at 04:00", "{} · o mês vira no dia 1 às 04:00"),
    (
        "Presença · prêmio pendente entregue: {}",
        "Attendance · pending prize delivered: {}",
    ),
    ("+{} faction", "+{} facção"),
    // ───────────────────────────── cliente: HUD social ─────────────────────────────
    ("Actions +", "Ações +"),
    ("Actions −", "Ações −"),
    ("PARTY · {}  {}", "GRUPO · {}  {}"),
    ("Follow player", "Seguir jogador"),
    ("Add friend", "Adicionar amigo"),
    ("Out of range", "Fora de alcance"),
    ("Stop following", "Parar de seguir"),
    ("Manage party ›", "Gerenciar grupo ›"),
    ("Invite to party", "Convidar para grupo"),
    // ──────────────────── cliente: correio, amigos, clã e grupo ────────────────────
    ("To", "Para"),
    ("Inbox", "Caixa"),
    ("Letter", "Carta"),
    ("Leader", "Líder"),
    ("Delete", "Apagar"),
    ("Captain", "Capitã"),
    ("From: {}", "De: {}"),
    ("Send", "Enviar"),
    ("Subject", "Assunto"),
    ("Remove", "Remover"),
    ("System", "Sistema"),
    (" · Leader", " · Líder"),
    ("Invite", "Convidar"),
    ("Corsair", "Corsário"),
    ("Kick", "Expulsar"),
    ("Message", "Mensagem"),
    ("Add", "Adicionar"),
    ("Confirm", "Confirmar"),
    ("Create clan", "Criar clã"),
    ("Reply", "Responder"),
    ("Received.", "Recebidos."),
    ("Bag full", "Bolsa cheia"),
    ("Search item", "Buscar item"),
    ("Clan name", "Nome do clã"),
    ("Leave clan", "Sair do clã"),
    ("on this channel", "neste canal"),
    ("Clan notice", "Aviso do clã"),
    ("Leave the clan?", "Sair do clã?"),
    ("Save notice", "Salvar aviso"),
    ("Disband clan", "Dissolver clã"),
    ("Health Potion", "Poção de Vida"),
    ("Claim items", "Receber itens"),
    ("Leave party", "Sair do grupo"),
    ("Text {} / {}", "Texto {} / {}"),
    ("One character", "Um personagem"),
    ("Attachments: {} / 8", "Anexos: {} / 8"),
    ("Letter sent.", "Carta enviada."),
    ("Write a letter", "Escrever carta"),
    ("Forge Stone", "Pedra de Forja"),
    ("Back to the letter", "Voltar à carta"),
    ("request sent", "pedido enviado"),
    ("Admin/mod send", "Envio admin/mod"),
    ("Meeting in the village", "Encontro na vila"),
    ("First win", "Primeira vitória"),
    ("Rewards ({})", "Recompensas ({})"),
    ("off this channel", "fora deste canal"),
    ("Delete this letter?", "Apagar esta carta?"),
    ("Invites received", "Convites recebidos"),
    ("Character name", "Nome do personagem"),
    ("wants to be your friend", "quer ser seu amigo"),
    ("{} · invite from {}", "{} · convite de {}"),
    ("Waiting to be claimed.", "Aguardando resgate."),
    ("Invite a character", "Convidar personagem"),
    ("Kick {n} from the clan?", "Expulsar {n} do clã?"),
    ("Event reward", "Recompensa do evento"),
    ("All characters", "Todos os personagens"),
    ("{nome} invited you", "{nome} convidou você"),
    ("Your inbox is empty.", "Sua caixa está vazia."),
    ("All: {} characters", "Todos: {} personagens"),
    ("{}  |  Attachments: {}. {}", "{}  |  Anexos: {}. {}"),
    ("Delete everything ({quantas})", "Apagar tudo ({quantas})"),
    ("Official mail sent", "Correio oficial enviado"),
    ("Official · switch inbox", "Oficiais · trocar caixa"),
    ("Personal · switch inbox", "Pessoais · trocar caixa"),
    ("You are playing solo.", "Você está jogando solo."),
    ("Search for an item by name or ID", "Buscar item por nome ou ID"),
    ("First win of the week", "Primeira vitória da semana"),
    ("Emptying the inbox… {} left", "Esvaziando a caixa… faltam {}"),
    ("Select a letter to read.", "Selecione uma carta para ler."),
    ("Message (up to 1000 characters)", "Mensagem (até 1000 caracteres)"),
    ("Take everything and delete ({quantas})", "Pegar tudo e apagar ({quantas})"),
    ("Ready for the next adventure?", "Prontos para a próxima aventura?"),
    ("{} · {} / {} members · Leader: {}", "{} · {} / {} membros · Líder: {}"),
    ("You have no clan invites yet.", "Você ainda não tem convites de clã."),
    ("Name of the new clan (3 to 24 characters)", "Nome do novo clã (3 a 24 caracteres)"),
    ("Remove friendship or request with {nome}?", "Remover amizade ou pedido com {nome}?"),
    ("Add friends to find them here.", "Adicione amigos para encontrá-los aqui."),
    (
        "Nenhuma recompensa aguardando no Correio.",
        "No reward waiting in your Mail.",
    ),
    (
        "Encontro na vila para a próxima expedição.",
        "Meeting in the village for the next expedition.",
    ),
    (
        "Dissolver o clã e remover todos os membros?",
        "Disband the clan and remove every member?",
    ),
    (
        "TODOS os personagens existentes (aprox. {})",
        "EVERY existing character (approx. {})",
    ),
    (
        "{} / {} amigos · Presença indica este canal",
        "{} / {} friends · Presence points to this channel",
    ),
    (
        "Vamos explorar juntos depois de reunir o grupo?",
        "Shall we explore together once the party is together?",
    ),
    (
        "2 próximos: +10% (55% cada) · 3: +20% (40% cada)",
        "2 nearby: +10% (55% each) · 3: +20% (40% each)",
    ),
    (
        "4 próximos: +30% (32,5% cada) · 5: +30% (26% cada)",
        "4 nearby: +30% (32.5% each) · 5: +30% (26% each)",
    ),
    (
        "Obrigado por participar! Receba seus itens abaixo.",
        "Thank you for taking part! Claim your items below.",
    ),
    (
        "Até 5 jogadores no mesmo canal. Convites duram 60 segundos.",
        "Up to 5 players on the same channel. Invites last 60 seconds.",
    ),
    (
        "Transferir a liderança para {n}? Você perderá a administração do clã.",
        "Transfer leadership to {n}? You will lose control of the clan.",
    ),
    (
        "XP dividida igualmente: membros na mesma área, a até 25 m de quem abate.",
        "XP split evenly: members in the same area, within 25 m of whoever lands the kill.",
    ),
    (
        "Receber os itens de {} carta(s) e apagar as {quantas}? Não dá pra desfazer.",
        "Claim the items from {} letter(s) and delete all {quantas}? This cannot be undone.",
    ),
    (
        "Bônus cresce até 4 participantes. Solo: 100%. Frações de XP são descartadas.",
        "The bonus grows up to 4 participants. Solo: 100%. Fractions of XP are discarded.",
    ),
    (
        "Vamos reunir o grupo na vila e explorar as dungeons. Se precisar de ajuda, mande uma carta!",
        "Let's gather the party in the village and explore the dungeons. If you need help, send a letter!",
    ),
    (
        "Enviar correio oficial para {destino}? Assunto: {}. Anexos por destinatário: {}. O envio será registrado e não pode ser desfeito.",
        "Send official mail to {destino}? Subject: {}. Attachments per recipient: {}. The send will be logged and cannot be undone.",
    ),
    // ────────────────────────── cliente: som, chefe e viagem ──────────────────────────
    ("Sound: off", "Som: desligado"),
    ("PHASE 1", "FASE 1"),
    ("PHASE 2", "FASE 2"),
    ("BOSS · {}", "CHEFE · {}"),
    ("{nome} · Lv {nivel}", "{nome} · Lv {nivel}"),
    ("Board", "Embarcar"),
    ("Level {}–{}", "Nível {}–{}"),
    ("Bound for the Glacier", "Rumo à Geleira"),
    ("{nivel} · locked", "{nivel} · bloqueada"),
    ("{nivel} · you are here", "{nivel} · você está aqui"),
    ("{nivel} · unlocks at \"{}\"", "{nivel} · libera em \"{}\""),
    (
        "{nivel} · sem barco agora (servidor fora do ar)",
        "{nivel} · no boat right now (server offline)",
    ),
    (
        "Sua colônia · rende sozinha enquanto você navega",
        "Your colony · yields on its own while you sail",
    ),
    (
        "O Capitão leva a qualquer ilha que a história já abriu.",
        "The Captain will take you to any island the story has opened.",
    ),
    // ─────────────── os que sobraram da varredura (rótulo solto, título curto) ───────────────
    ("New: ", "Nova: "),
    ("Port", "Porto"),
    ("Copper", "Cobre"),
    ("Accessory", "Acessório"),
    ("Other", "Outros"),
    ("Defeat forest monsters  3/10", "Derrote monstros da floresta  3/10"),
    // ───────────────── os rótulos em CAIXA ALTA (HUD, menu, botão) ─────────────────
    //
    // Esta leva quase escapou: a varredura tratava todo literal em caixa alta
    // como nome de const e jogava fora. Só apareceu na captura de tela, com
    // "ATRIBUTOS" e "COMBATE" em português no meio da ficha em inglês — e é
    // justamente a classe mais visível, porque é o menu e o HUD.
    ("ATTRIBUTES", "ATRIBUTOS"),
    ("COMBAT", "COMBATE"),
    ("BAG", "BOLSA"),
    ("POWER", "PODER"),
    ("BACK", "VOLTAR"),
    ("GATHER", "COLETA"),
    ("ON", "LIGADO"),
    ("ATTACK", "ATACAR"),
    ("TARGET", "ALVO"),
    ("STAMINA", "VIGOR"),
    ("BOSS", "CHEFE"),
    ("CHARACTER", "PERSONAGEM"),
    ("PROGRESS", "PROGRESSO"),
    ("WORKSHOP", "OFICINA"),
    ("ADVENTURE", "AVENTURA"),
    ("EVENT", "EVENTO"),
    ("SYSTEM", "SISTEMA"),
    ("BALANCES", "SALDOS"),
    ("DEAD", "MORTO"),
    ("IDLE", "PARADO"),
    ("NAME", "NOME"),
    ("MAPS", "MAPAS"),
    ("MOUNT", "MONTARIA"),
    ("MOUNT UP", "MONTAR"),
    ("ITEMS", "ITENS"),
    ("SKILLS", "HABILIDADES"),
    ("STORE", "GUARDAR"),
    ("STRONGHOLD", "FORTE"),
    // DUAS FORMAS, e não uma com `{}{}` no fim.
    //
    // A linha é montada com um sufixo condicional, então no ar ela existe em
    // duas formas. O verbete único terminado em `{}{}` NÃO casa nenhuma das
    // duas: dois buracos colados deixam entre eles um pedaço fixo vazio, e não
    // há como saber onde um termina e o outro começa. A forma mais longa vem
    // primeiro porque tem mais texto fixo.
    (
        "Free today {}/{}  ·  Passes {}  ·  {}:{} left",
        "Grátis hoje {}/{}  ·  Passes {}  ·  resta {}:{}",
    ),
    ("Free today {}/{}  ·  Passes {}", "Grátis hoje {}/{}  ·  Passes {}"),
    // Chegaram DEPOIS da varredura, com a caixa de grupo no rastreador. É o
    // caso normal: frase nova no jogo, verbete novo aqui.
    ("You are not in a party", "Você não está em grupo"),
    ("Invite players ›", "Convidar jogadores ›"),
    ("out of range", "fora de alcance"),
    ("check the web (/api/channels)", "confira o web (/api/channels)"),
];
