//! Game data: items, skills, creatures, shop, pets, mounts, colony.

pub const VERBETES: &[(&str, &str)] = &[
    // ─────────────────────────── the colors and the grades ───────────────────────────
    // These five phrases appear on items, keys, pets, mounts and refinement.
    // They are the spine of the vocabulary: changing one here changes the whole game.
    ("Blue", "Azul"),
    ("Grey", "Cinza"),
    ("Green", "Verde"),
    ("Purple", "Roxo"),
    ("Epic", "Épico"),
    ("Legendary", "Lendário"),
    ("Fine", "Fino"),
    ("Rare", "Raro"),
    // ─────────────────────────── accessories: the bonuses ───────────────────────────
    ("XP gained +10%", "XP recebido +10%"),
    ("Drop chance +10%", "Chance de drop +10%"),
    ("Energy gathering +15%", "Coleta de Energia +15%"),
    ("Ore gathering +15%", "Coleta de minério +15%"),
    ("Base health regen +1/s", "Regen base de vida +1/s"),
    ("Darksteel gathering +15%", "Coleta de Darksteel +15%"),
    ("Better loot chance +5%", "Chance de loot melhor +5%"),
    ("Base mana regen +0.5/s", "Regen base de mana +0,5/s"),
    // ───────────────────────────── appearance: hats ─────────────────────────────
    ("Hood", "Capuz"),
    ("Headband", "Faixa"),
    ("Bandana", "Lenço"),
    ("Cap", "Touca"),
    ("Wanderer", "Andarilho"),
    ("Tricorne", "Tricórnio"),
    ("Mercenary", "Mercenário"),
    ("Adventurer", "Aventureiro"),
    ("Feathered Beret", "Boina de Pena"),
    ("Brimmed Hat", "Chapéu de Aba"),
    ("Pointed Hat", "Chapéu Pontudo"),
    ("Storm Captain", "Capitão da Tempestade"),
    // ──────────────────────────── chefes e seus golpes ────────────────────────────
    ("{r}s", "{r}s"),
    ("{m}m{r:02}s", "{m}m{r:02}s"),
    ("Meteor", "Meteoro"),
    ("Whirl", "Rodopio"),
    ("Barrage", "Barragem"),
    ("Charge", "Investida"),
    ("Arcane Bolt", "Raio Arcano"),
    ("Elder Bear", "Urso Anciao"),
    ("Ice Nova", "Nova de Gelo"),
    ("Double Swipe", "Patada Dupla"),
    ("Wide Swipe", "Patada Larga"),
    ("Feral Spin", "Giro Selvagem"),
    ("Firing Line", "Linha de Tiro"),
    ("Stone Wave", "Onda de Pedra"),
    ("Seismic Stomp", "Pisao Sismico"),
    ("Ring of Flames", "Anel de Chamas"),
    ("Sabre Slash", "Corte de Sabre"),
    ("Predator Leap", "Salto Predador"),
    ("Cannon Shot", "Tiro de Canhao"),
    ("Fanning Claws", "Garras em Leque"),
    ("Primeval Owlbear", "Owlbear Primevo"),
    ("Seismic Blow", "Pancada Sísmica"),
    ("Fanning Volley", "Rajada em Leque"),
    ("Fallen Lightning", "Relampago Caido"),
    ("Howl of the Pack", "Uivo da Matilha"),
    ("Archer of the Waste", "Arqueira do Ermo"),
    ("Explosive Barrel", "Barril Explosivo"),
    ("Arrow Rain", "Chuva de Flechas"),
    ("Thunderous Fall", "Queda Estrondosa"),
    ("Crushing Roar", "Rugido Esmagador"),
    ("Piercing Arrow", "Flecha Perfurante"),
    ("Storm Wolf", "Lobo da Tempestade"),
    ("Howl of the Storm", "Uivo da Tempestade"),
    ("Thorn Trap", "Armadilha Espinhosa"),
    ("Rending Bite", "Mordida Dilacerante"),
    ("Thundering Charge", "Investida Trovejante"),
    ("Charge of the Colossus", "Investida do Colosso"),
    ("Sand Raider", "Saqueador das Areias"),
    ("Archmage of the Tempest", "Arquimago da Tormenta"),
    ("Alpha Wolf of the Glade", "Lobo Alfa da Clareira"),
    ("Captain Stormbeard", "Capitao Barba-Tormenta"),
    ("Colossus of the Magic Island", "Colosso da Ilha Mágica"),
    ("Reliquary Warden", "Guardião do Relicário"),
    ("Fallen Seraph", "Serafim Caído"),
    ("Storm Pegasus", "Pégaso da Tormenta"),
    ("Gilded Colossus", "Colosso Dourado"),
    ("Seraph Archon", "Arconte Serafim"),
    // ──────────────────────────────── the colony ────────────────────────────────
    ("House", "Casa"),
    ("Trade", "Ofício"),
    ("Castle", "Castelo"),
    ("Tanner", "Curtidor"),
    ("Woodcutter", "Lenhador"),
    ("Miner", "Minerador"),
    ("Settlement", "Assentamento"),
    // ──────────────────────────── os NPCs da vila ────────────────────────────
    ("Armourer", "Armeiro"),
    ("Tailor", "Alfaiate"),
    ("Blacksmith", "Ferreiro"),
    ("Castaway", "Naufrago"),
    ("Trainer", "Treinador"),
    ("Cartographer", "Cartografo"),
    ("Innkeeper", "Taberneiro"),
    ("Appraiser", "Identificador"),
    ("Harbour Captain", "Capitao do Porto"),
    ("Quest Master", "Mestre de Missoes"),
    ("Resident", "Morador"),
    ("Alchemist", "Alquimista"),
    ("Master", "Mestre"),
    // ─────────────────────────────── as dungeons ───────────────────────────────
    ("Cavern", "Gruta"),
    ("Hunt", "Caçada"),
    ("Arena", "Arena"),
    ("Forge of the Titan", "Forja do Titã"),
    ("Mother of Blizzards", "Mãe-da-Nevasca"),
    ("Frozen Hull", "Casco Congelado"),
    ("Requires level {n}", "Requer nível {n}"),
    ("Ship Graveyard", "Cemitério de Navios"),
    ("Monastery of the Winds", "Mosteiro dos Ventos"),
    ("Seraph Reliquary", "Relicário Serafim"),
    ("Cathedral of Clouds", "Catedral das Nuvens"),
    ("Pegasus Aerie", "Ninho do Pégaso"),
    ("Beat stage {e}", "Vença o estágio {e}"),
    ("Deep Ice Caverns", "Grutas de Gelo Fundo"),
    ("Power {tem}/{precisa}", "Poder {tem}/{precisa}"),
    ("Sea Wolves' Den", "Toca dos Lobos-do-Mar"),
    ("Smuggler's Cellar", "Adega do Contrabandista"),
    ("Requires a Storm Seal", "Requer Selo da Tempestade"),
    ("Tomb of the Salt Sands", "Tumba das Areias Salgadas"),
    // ──────────────────────────── a forja: as recusas ────────────────────────────
    ("take the gems out of the pieces first", "tire as gemas das peças antes"),
    (
        "as duas peças precisam ser da mesma cor",
        "both pieces have to be the same colour",
    ),
    (
        "as duas peças precisam ser o mesmo item",
        "both pieces have to be the same item",
    ),
    (
        "as duas peças precisam ter o mesmo tier",
        "both pieces have to be the same tier",
    ),
    (
        "para subir de cor, as duas Tier IV precisam estar +{REFINO_PARA_COR}",
        "to raise the colour, both Tier IV pieces have to be +{REFINO_PARA_COR}",
    ),
    // ─────────────────── the item affixes (the attribute instance) ───────────────────
    // They are suffixes and prefixes that attach to the piece's name. In English
    //  gender disappears, so "Ágil" and "da Fúria" both become either an
    // adjective or an "of the …" — whichever sounds like an item name.
    ("Nimble", "Ágil"),
    ("Mighty", "Forte"),
    ("Wise", "Sábio"),
    ("Swift", "Veloz"),
    ("Brutal", "Brutal"),
    ("Arcane", "Mágico"),
    ("of the Mage", "do Mago"),
    ("of the Bear", "do Urso"),
    ("of Fury", "da Fúria"),
    ("of the Lynx", "do Lince"),
    ("of the Bull", "do Touro"),
    ("of the Wind", "do Vento"),
    ("Relentless", "Implacável"),
    ("Sturdy", "Resistente"),
    ("Fortified", "Fortificado"),
    ("of the Turtle", "da Tartaruga"),
    ("of the Assassin", "do Assassino"),
    ("of the Wellspring", "do Manancial"),
    ("of Regeneration", "da Regeneração"),
    // ───────────────────────────── a loja de TP: os pacotes ─────────────────────────────
    ("TP Chest", "Baú de TP"),
    ("Sack of Gold", "Saco de Ouro"),
    ("Handful of TP", "Punhado de TP"),
    ("Sack of Copper", "Saco de Cobre"),
    ("TP Hoard", "Tesouro de TP"),
    ("Pouch of Passes", "Bolsa de Passes"),
    ("Not enough TP.", "TP insuficiente."),
    ("Energy Core", "Núcleo de Energia"),
    ("Handful of Passes", "Punhado de Passes"),
    ("Energy Crystal", "Cristal de Energia"),
    ("Energy Spark", "Fagulha de Energia"),
    ("Skill Remover", "Removedor de Skill"),
    ("Darksteel Bars", "Barras de Darksteel"),
    ("Product unavailable.", "Produto indisponível."),
    (
        "Tira todas as skills do pet e devolve os slots.",
        "Strips every skill from the pet and gives the slots back.",
    ),
    (
        "Abra na bolsa para invocar 1 chave aleatória de craft.",
        "Open it in your bag to summon 1 random crafting key.",
    ),
    (
        "Alimenta o pet por 2 h. Com fome ele não ganha experiência.",
        "Feeds the pet for 2 h. While hungry it gains no experience.",
    ),
    (
        "Sorteia de novo os atributos do pet ou da montaria equipada.",
        "Rerolls the attributes of the equipped pet or mount.",
    ),
    // ───────────────────────────── the Magic Island: the islets ─────────────────────────────
    ("Stone", "Pedra"),
    ("Colossus", "Colosso"),
    ("Spoils", "Espólio"),
    ("Experience", "Experiência"),
    ("Magic Island I", "Ilha Mágica I"),
    ("Magic Island II", "Ilha Mágica II"),
    ("Islet of Gold", "Ilhota do Ouro"),
    ("Magic Island III", "Ilha Mágica III"),
    ("Islet of Stone", "Ilhota da Pedra"),
    ("Guide of the Steps", "Guia dos Degraus"),
    ("Islet of Energy", "Ilhota da Energia"),
    ("Islet of Wood", "Ilhota da Madeira"),
    ("Islet of the Colossus", "Ilhota do Colosso"),
    ("Islet of Spoils", "Ilhota do Espólio"),
    ("between 1 and 3 entries", "entre 1 e 3 entradas"),
    ("Islet of Experience", "Ilhota da Experiência"),
    ("Greater Colossus of the Magic Island", "Colosso Maior da Ilha Mágica"),
    ("Elder Colossus of the Magic Island", "Colosso Ancião da Ilha Mágica"),
    ("not enough passes: you have {passes}", "faltam passes: você tem {passes}"),
    (
        "seu tempo já está perto do teto de 1h30",
        "your time is already close to the 1h30 cap",
    ),
    // ────────────────────────────── mercado: as recusas ──────────────────────────────
    ("Invalid quantity.", "Quantidade inválida."),
    ("Bound item: it cannot be sold.", "Item vinculado: não pode ser vendido."),
    (
        "Limite de {MAX_ANUNCIOS} anúncios ativos.",
        "Limit of {MAX_ANUNCIOS} active listings.",
    ),
    (
        "Preço inválido (1 a {PRECO_MAX_UNIT} por unidade).",
        "Invalid price (1 to {PRECO_MAX_UNIT} per unit).",
    ),
    (
        "O preço do anúncio mudou; o gold volta em Entregas.",
        "The listing's price changed; the gold comes back in Deliveries.",
    ),
    (
        "Mercado indisponível agora. Tente de novo em instantes.",
        "Market unavailable right now. Try again in a moment.",
    ),
    (
        "Precisa do nível {NIVEL_PARA_VENDER} para vender no mercado.",
        "You need level {NIVEL_PARA_VENDER} to sell on the market.",
    ),
    (
        "Não dá para comprar o próprio anúncio; o gold volta em Entregas.",
        "You cannot buy your own listing; the gold comes back in Deliveries.",
    ),
    (
        "O anúncio acabou ou não tem essa quantidade; o gold volta em Entregas.",
        "The listing is gone or has less than that; the gold comes back in Deliveries.",
    ),
    // ──────────────────────────────── as montarias ────────────────────────────────
    ("Dragon", "Dragão"),
    ("Hippogriff", "Hipogrifo"),
    ("Grove Stag", "Cervo do Bosque"),
    ("Silent in the snow, fierce on the road.", "Silencioso na neve, feroz na estrada."),
    (
        "Leal e ligeiro, criado nas matas do Bosque.",
        "Loyal and quick, raised in the woods of the Grove.",
    ),
    (
        "Meio águia, meio cavalo. Não anda: quase voa.",
        "Half eagle, half horse. It doesn't walk: it nearly flies.",
    ),
    (
        "O topo. Quem monta um, todo mundo vê de longe.",
        "The very top. Ride one and everybody sees you coming.",
    ),
    (
        "Manso e ligeiro. A primeira montaria de qualquer um.",
        "Gentle and quick. Everybody's first mount.",
    ),
    // ───────────────────────────── os pets e suas skills ─────────────────────────────
    ("Orange", "Laranja"),
    ("Apprentice", "Aprendiz"),
    ("Owlbear Cub", "Corujurso"),
    ("Piglet", "Porquinho"),
    ("+4 DEX.", "+4 de DES."),
    ("+4 STR.", "+4 de FOR."),
    ("+4 INT.", "+4 de INT."),
    ("+4 RES.", "+4 de RES."),
    ("+4 SPD.", "+4 de SPD."),
    ("+4 VIT.", "+4 de VIT."),
    ("Light Step", "Passo Leve"),
    ("Keen Nose", "Faro Apurado"),
    ("Deep Stomach", "Estômago Fundo"),
    ("Inner Spring", "Fonte Interior"),
    ("Healing Breath", "Sopro Curativo"),
    ("Wolf Cub", "Filhote de Lobo"),
    ("Tiger Cub", "Filhote de Tigre"),
    ("Borrowed Strength", "Força Emprestada"),
    ("Borrowed Stamina", "Vigor Emprestado"),
    ("Dragon Hatchling", "Filhote de Dragão"),
    ("+20% speed.", "+20% de velocidade."),
    ("Borrowed Dexterity", "Destreza Emprestada"),
    ("Borrowed Quickness", "Ligeireza Emprestada"),
    ("Borrowed Wisdom", "Sabedoria Emprestada"),
    ("Feed lasts twice as long.", "A Ração dura o dobro."),
    ("Borrowed Vitality", "Vitalidade Emprestada"),
    ("Borrowed Resilience", "Resistência Emprestada"),
    ("+2 mana per second.", "+2 de mana por segundo."),
    ("+1.5 health per second.", "+1,5 de vida por segundo."),
    ("+3 tiles on the search radius.", "+3 tiles no raio de busca."),
    ("Eats anything, complains about nothing. Vitality.", "Come tudo e não reclama. Vitalidade."),
    ("+50% of the experience the pet gains.", "+50% da experiência que o pet recebe."),
    ("Odd and wise. The pet for the magic weapon.", "Estranho e sábio. O pet da arma mágica."),
    ("A hunter from the start. Strength and dexterity.", "Caçador desde pequeno. Força e destreza."),
    ("Quick and curious. Dexterity and speed.", "Rápido e curioso. Destreza e velocidade."),
    (
        "Pequeno, e já sabe disso. O topo da ladder.",
        "Small, and well aware of it. The top of the ladder.",
    ),
    (
        "+3 pontos de atributo, na afinidade da espécie.",
        "+3 attribute points, in the species' affinity.",
    ),
    ("Stamina", "Vigor"),
    // ───────────────────────────── attendance: the calendar ─────────────────────────────
    ("Attendance for the month", "Presença do mês"),
    ("That calendar is not active.", "Esse calendário não está ativo."),
    (
        "Calendário completo! O próximo começa no dia 1.",
        "Calendar complete! The next one starts on the 1st.",
    ),
    (
        "Você já resgatou hoje. Volte depois do reset (04:00).",
        "You've already claimed today. Come back after the reset (04:00).",
    ),
    ("Calendar unavailable right now. Try again.", "Calendário indisponível agora. Tente de novo."),
    // ───────────────────── the skills and the evolution steps ─────────────────────
    ("Aura", "Aura"),
    ("Dance", "Dança"),
    ("Draw", "Saque"),
    ("Barrel", "Barril"),
    ("Blessing", "Bênção"),
    ("Life Drain", "Dreno Vital"),
    ("Volley", "Rajada"),
    ("Bulwark", "Muralha"),
    ("Wider aura", "Aura maior"),
    ("Judgement", "Julgamento"),
    ("Wider area", "Área maior"),
    ("Wide Strike", "Golpe Largo"),
    ("Final strike", "Golpe final"),
    ("Wider fan", "Leque maior"),
    ("Final volley", "Rajada final"),
    ("Greater impact", "Impacto maior"),
    ("True Shot", "Tiro Certeiro"),
    ("Stronger drain", "Dreno reforçado"),
    ("Steals 35% of the damage", "Rouba 35% do dano"),
    ("Steals 40% and hits harder", "Rouba 40% e bate mais forte"),
    ("Pushes the target", "Empurra o alvo"),
    ("Bigger explosion", "Explosão maior"),
    ("Cutting Wind", "Vento Cortante"),
    ("Longer cone", "Cone mais longo"),
    ("Stronger slash", "Corte reforçado"),
    ("Bulwark for 6 s", "Muralha por 6 s"),
    ("Stronger shot", "Tiro mais forte"),
    ("Pushes enemies", "Empurra inimigos"),
    ("Final judgement", "Julgamento final"),
    ("Longer line", "Linha mais longa"),
    ("Guaranteed critical", "Crítico garantido"),
    ("Cuts 55% of the damage", "Reduz 55% do dano"),
    ("Cuts 60% for 8 s", "Reduz 60% por 8 s"),
    ("Stronger impact", "Impacto mais forte"),
    ("Stronger explosion", "Explosão mais forte"),
    ("Devastating blaze", "Incêndio devastador"),
    ("Wider final wave", "Onda final ampliada"),
    ("Wider final slash", "Corte final ampliado"),
    ("Wider final strike", "Golpe final ampliado"),
    ("Maximum healing pulse", "Pulso de cura máximo"),
    ("Wider final draw", "Saque final ampliado"),
    ("Wider area and more damage", "Área e dano ampliados"),
    ("Wider area and stronger healing", "Área e cura reforçadas"),
    ("Stronger, longer wave", "Onda mais forte e longa"),
    ("A bolt that drains the target and heals you for 30% of the damage dealt.", "Um disparo que drena o alvo e te cura com 30% do dano causado."),
    ("The wave travels further", "Onda atravessa mais longe"),
    ("The slash travels further", "Corte atravessa mais longe"),
    ("Reaches targets further away", "Atinge alvos mais distantes"),
    ("Shield for 2 s after the charge", "Escudo por 2 s após a investida"),
    ("Heals you and allies around you.", "Cura você e aliados ao seu redor."),
    (
        "Arremessa um barril que explode no alvo.",
        "Hurls a barrel that explodes on the target.",
    ),
    (
        "Saca a katana e corta em linha até o alvo.",
        "Draws the katana and cuts in a line up to the target.",
    ),
    (
        "Corte amplo voltado para o alvo selecionado.",
        "A wide slash aimed at the selected target.",
    ),
    (
        "Reduz o dano recebido em 50% por 5 segundos.",
        "Cuts incoming damage by 50% for 5 seconds.",
    ),
    (
        "Uma onda cortante atinge o alvo selecionado.",
        "A cutting wave strikes the selected target.",
    ),
    (
        "Dispara um tiro poderoso no alvo selecionado.",
        "Fires a powerful shot at the selected target.",
    ),
    (
        "Avança até o alvo e atinge inimigos no caminho.",
        "Charges to the target, hitting enemies on the way.",
    ),
    (
        "Impacto mágico no alvo e nos inimigos próximos.",
        "A magical impact on the target and the enemies near it.",
    ),
    (
        "Rajada em leque voltada para o alvo selecionado.",
        "A fanning volley aimed at the selected target.",
    ),
    (
        "Atinge o alvo e os inimigos ao redor, e rouba 25% do dano dos seus golpes por 3 segundos.",
        "Strikes the target and the enemies around it, and steals 25% of your strike damage for 3 seconds.",
    ),
    ("Watchman", "Vigia"),
    // ─────────────────────── the items (the name that comes from the database) ───────────────────────
    // These names are born in the Postgres seed and reach the client over the
    // protocol. Translation happens at draw time, so there is no new column and
    // no migration: the database stays in Portuguese and it is what the logic compares.
    ("Pufferfish", "Baiacu"),
    ("Scabbard", "Bainha"),
    ("Holster", "Coldre"),
    ("Anchovy", "Anchova"),
    ("Blue Steel", "Aço Azul"),
    ("Purple Steel", "Aço Roxa"),
    ("Grey Steel", "Aço Cinza"),
    ("Leather T1", "Couro T1"),
    ("Leather T2", "Couro T2"),
    ("Leather T3", "Couro T3"),
    ("Leather T4", "Couro T4"),
    ("Blue Claw", "Garra Azul"),
    ("Purple Claw", "Garra Roxa"),
    ("Grey Claw", "Garra Cinza"),
    ("Green Claw", "Garra Verde"),
    ("Wood T1", "Madeira T1"),
    ("Wood T2", "Madeira T2"),
    ("Wood T3", "Madeira T3"),
    ("Wood T4", "Madeira T4"),
    ("Magic Ring", "Anel Mágico"),
    ("Purple Horn", "Chifre Roxa"),
    ("Grey Horn", "Chifre Cinza"),
    ("Blue Scale", "Escama Azul"),
    ("Purple Scale", "Escama Roxa"),
    ("Grey Scale", "Escama Cinza"),
    ("Green Scale", "Escama Verde"),
    ("Magic Coin", "Moeda Mágica"),
    ("Blue Platinum", "Platina Azul"),
    ("Purple Platinum", "Platina Roxa"),
    ("Grey Platinum", "Platina Cinza"),
    ("Green Platinum", "Platina Verde"),
    ("Pet Feed", "Ração de Pet"),
    ("Twin Pistols", "Duas Pistolas"),
    ("Mage's Mantle", "Manto do Mago"),
    ("Clownfish", "Peixe-palhaço"),
    ("Legendary Leather", "Couro Lendário"),
    ("Legendary Claw", "Garra Lendária"),
    ("Potion of Luck", "Poção de Sorte"),
    ("Heavy Armour", "Armadura Pesada"),
    ("Legendary Horn", "Chifre Lendário"),
    ("Legendary Scale", "Escama Lendária"),
    ("Sword and Shield", "Espada e Escudo"),
    ("Surgeonfish", "Peixe-cirurgião"),
    ("Potion of Fortune", "Poção de Fortuna"),
    ("Warrior's Mantle", "Manto do Guerreiro"),
    ("Affinity Stone", "Pedra de Afinidade"),
    ("Blue Quintessence", "Quintessência Azul"),
    ("Purple Quintessence", "Quintessência Roxa"),
    ("Storm Seal", "Selo da Tempestade"),
    ("Blue Anima Stone", "Pedra de Ânima Azul"),
    ("Purple Anima Stone", "Pedra de Ânima Roxa"),
    ("Grey Quintessence", "Quintessência Cinza"),
    ("Green Quintessence", "Quintessência Verde"),
    ("Storm Marks", "Marcas da Tempestade"),
    ("Magic Island Pass", "Passe da Ilha Mágica"),
    ("Grey Anima Stone", "Pedra de Ânima Cinza"),
    ("Green Anima Stone", "Pedra de Ânima Verde"),
    ("Teleport Scroll", "Pergaminho de Teleporte"),
    ("Blue Moonshadow Stone", "Pedra Sombra-da-Lua Azul"),
    ("Purple Moonshadow Stone", "Pedra Sombra-da-Lua Roxa"),
    ("Blue Illuminating Shard", "Fragmento Iluminante Azul"),
    ("Purple Illuminating Shard", "Fragmento Iluminante Roxa"),
    ("Grey Moonshadow Stone", "Pedra Sombra-da-Lua Cinza"),
    ("Green Moonshadow Stone", "Pedra Sombra-da-Lua Verde"),
    ("Pet Skill Remover", "Removedor de Skill de Pet"),
    ("Blue Exorcism Charm", "Berloque de Exorcismo Azul"),
    ("Purple Exorcism Charm", "Berloque de Exorcismo Roxa"),
    ("Grey Illuminating Shard", "Fragmento Iluminante Cinza"),
    ("Green Illuminating Shard", "Fragmento Iluminante Verde"),
    ("Grey Exorcism Charm", "Berloque de Exorcismo Cinza"),
    ("Green Exorcism Charm", "Berloque de Exorcismo Verde"),
    ("Blue Blackheart Stone", "Pedra do Coração Negro Azul"),
    ("Purple Blackheart Stone", "Pedra do Coração Negro Roxa"),
    ("Grey Blackheart Stone", "Pedra do Coração Negro Cinza"),
    ("Green Blackheart Stone", "Pedra do Coração Negro Verde"),
    ("Summoning Scroll: Pet", "Pergaminho de Invocação: Pet"),
    ("Summoning Scroll: Tomes", "Pergaminho de Invocação: Tomos"),
    ("Summoning Scroll: Keys", "Pergaminho de Invocação: Chaves"),
    ("Summoning Scroll: Mount", "Pergaminho de Invocação: Montaria"),
    ("Skill: {}", "Skill: {}"),
    // ───────────────────────────── os bichos do mundo ─────────────────────────────
    ("Walrus", "Morsa"),
    ("Tiger", "Tigre"),
    ("Rockback", "Rochoso"),
    ("Archer", "Arqueiro"),
    ("Crab", "Caranguejo"),
    ("Gunman", "Pistoleiro"),
    ("Scarab", "Escaravelho"),
    ("Great Wolf", "Lobo Grande"),
    ("White Bear", "Urso Branco"),
    ("White Tiger", "Tigre Branco"),
    ("King Crab", "Caranguejo-rei"),
    ("Scarab Queen", "Rainha Escaravelho"),
    ("Wolf", "Lobo"),
    ("Bear", "Urso"),
    ("Mage", "Mago"),
    ("Owlbear", "Owlbear"),
    // Island variants (`bestiary::VARIANTS`).
    ("Frostcoat Archer", "Arqueiro Casaco-de-Gelo"),
    ("Frostcoat Mage", "Mago Casaco-de-Gelo"),
    ("Snow Owlbear", "Owlbear da Neve"),
    ("Dune Raider", "Saqueador das Dunas"),
    ("Sand Archer", "Arqueiro das Areias"),
    ("Sun Mage", "Mago do Sol"),
    ("Crag Lynx", "Lince do Penhasco"),
    ("Cliff Archer", "Arqueiro do Penhasco"),
    ("Cave Bear", "Urso das Cavernas"),
    ("Storm Mage", "Mago da Tormenta"),
    ("Storm Owlbear", "Owlbear da Tormenta"),
    ("Snow Tiger", "Tigre das Neves"),
    ("Glade Wolf", "Lobo da Clareira"),
    ("Midnight Wolf", "Lobo da Meia-Noite"),
    ("Training Guardian", "Guardião de Treino"),
    ("Valley of Winds", "Vale dos Ventos"),
];
