//! Story: the chapters, the chronicles and the campaign's lines.

pub const VERBETES: &[(&str, &str)] = &[
    // ───────────────── the places the compass names (short phrases) ─────────────────
    ("the square", "a praça"),
    ("the place", "o lugar"),
    ("the port", "o porto"),
    ("the lookout", "o mirante"),
    ("the end of the quay", "a ponta do cais"),
    ("the distant coast", "a costa distante"),
    ("the way out of the city", "a saída da cidade"),
    // ──────────────────────── the titles of the story steps ────────────────────────
    ("Steady hands", "Mãos firmes"),
    ("Wood for the cellar key", "Madeira para a chave do porão"),
    ("Steel for the cellar key", "Aço para a chave do porão"),
    ("The Shipwreck Cellar Key", "A Chave do Porão do Naufrágio"),
    ("Follow the hint", "Siga a dica"),
    ("Thin air", "Ar rarefeito"),
    ("Skystone", "Pedra do céu"),
    ("Bound for the Waste", "Rumo ao Ermo"),
    ("The last rune", "A última runa"),
    ("Thunder steel", "Aço de trovão"),
    ("Fire in the forge", "Fogo na forja"),
    ("What lies beyond", "O que há além"),
    ("Mages of the sand", "Magos da areia"),
    ("The lighthouse of the sky", "O farol do céu"),
    ("The map of the Waste", "O mapa do Ermo"),
    ("Signs on the quay", "Sinais no cais"),
    ("Water and remedy", "Água e remédio"),
    ("Weapon of the desert", "Arma do deserto"),
    ("The gleam of steel", "O brilho do aço"),
    ("The heat of the Waste", "O calor do Ermo"),
    ("The singing stone", "Pedra que canta"),
    ("Shadows in the woods", "Sombras na mata"),
    ("Take this and go.", "Tome isto e vá."),
    ("The endless hunt", "A caçada sem fim"),
    ("The distant coast", "A costa distante"),
    ("The light in the stones", "A luz nas pedras"),
    ("Back to the quay", "De volta ao cais"),
    ("A hotter fire", "Fogo mais quente"),
    ("Fighting hands-free", "Luta sem as mãos"),
    ("Blades of glass", "Lâminas de vidro"),
    ("Bound for the Plateau", "Rumo ao Planalto"),
    ("Climb before he does.", "Suba antes dele."),
    ("Tempered in the heat", "Têmpera no calor"),
    ("Bears on the slope", "Ursos na encosta"),
    ("Watch of the lookout", "Vigia do mirante"),
    ("Morgan's fleet", "A frota de Morgan"),
    ("The beasts of the wind", "As feras do vento"),
    ("A toast to the lighthouses", "Brinde aos faróis"),
    ("Chronicle {n} · {t}", "Crônica {n} · {t}"),
    ("Wake in the square", "Desperte na praça"),
    ("The Captain of the Waste", "O Capitão do Ermo"),
    ("The siege of the dunes", "O cerco das dunas"),
    ("The frozen lighthouse", "O farol congelado"),
    ("The buried lighthouse", "O farol soterrado"),
    ("Stones that sing", "Pedras que cantam"),
    ("Your first piece", "Sua primeira peça"),
    ("The port road", "A estrada do porto"),
    ("The wolves' trail", "A trilha dos lobos"),
    ("Reach level 22", "Alcance o nível 22"),
    ("Reach level 25", "Alcance o nível 25"),
    ("Reach level 30", "Alcance o nível 30"),
    ("Reach level 35", "Alcance o nível 35"),
    ("Reach level 40", "Alcance o nível 40"),
    ("Reach level 45", "Alcance o nível 45"),
    ("Reach level 50", "Alcance o nível 50"),
    ("Reach level 55", "Alcance o nível 55"),
    ("Reach level 60", "Alcance o nível 60"),
    ("Steel that will not break", "Aço que não quebra"),
    ("Gathering without effort", "Coleta sem esforço"),
    ("Owlbear cubs in the snow", "Corujursos na neve"),
    ("Beasts of the high tide", "Feras da maré alta"),
    ("Firewood for the forge", "Lenha para a forja"),
    ("The Harbour Captain", "O Capitão do Porto"),
    ("The trail of thunder", "O rastro do trovão"),
    ("The vein of the tempest", "O veio da tormenta"),
    ("A sip of courage", "Um gole de coragem"),
    ("Lightning glass", "Vidro de relâmpago"),
    ("Striking on automatic", "Golpe no automático"),
    ("The quay at dawn", "O cais ao amanhecer"),
    ("The shard of ice", "O fragmento de gelo"),
    ("The eye on the horizon", "O olho no horizonte"),
    ("A potion at the right moment", "Poção na hora certa"),
    ("Morgan's patrol", "A patrulha de Morgan"),
    ("Armour for the eye", "Armadura para o olho"),
    ("Archers of the blizzard", "Arqueiros da nevasca"),
    ("Tavern tales", "Histórias de taberna"),
    ("Lightning ore", "Minério do relâmpago"),
    ("The shipwreck cellar", "O porão do naufrágio"),
    ("The first waking", "O primeiro despertar"),
    ("What the level gave you", "O que o nível te deu"),
    ("The dance of the storm", "A dança da tempestade"),
    ("A shell against the cold", "Couraça contra o frio"),
    ("I · The Lighthouse of the Grove", "I · O Farol do Bosque"),
    ("The metal of the storm", "O metal da tempestade"),
    ("Morgan's shipwreck", "O naufrágio de Morgan"),
    ("Iron forged in the wind", "Ferro forjado no vento"),
    ("Ice that holds thunder", "Gelo que guarda trovão"),
    ("II · The Frozen Lighthouse", "II · O Farol Congelado"),
    ("Sentinels of the Plateau", "Sentinelas do Planalto"),
    ("Bone-cracking cold", "Frio de rachar os ossos"),
    ("III · Sands That Scream", "III · Areias que Gritam"),
    ("The Guardian's oath", "O juramento do Guardião"),
    ("The map shows the way", "O mapa mostra o caminho"),
    ("A piece for the journey", "Uma peça para a jornada"),
    ("Cloak of stormwool", "Capa de lã-de-tempestade"),
    ("Morgan's gunmen", "Os pistoleiros de Morgan"),
    ("The smuggler's cellar", "A adega do contrabandista"),
    ("Claws on the road to the quay", "Garras no caminho do cais"),
    ("May the lighthouses guide you.", "Que os faróis guiem você."),
    ("Chronicles of the Storm · {}", "Crônicas da Tempestade · {}"),
    ("Take copper and craft your weapon.", "Leve cobre e crie sua arma."),
    ("Get up there before it falls.", "Suba lá antes que ele caia."),
    ("IV · The Heart of the Storm", "IV · O Coração da Tempestade"),
    ("Your chronicles begin now.", "Suas crônicas começam agora."),
    ("You are ready for what comes next.", "Você está pronto para o que vem."),
    ("Try refining twice at the Forge.", "Tente refinar duas vezes na Forja."),
    ("Try refining three times at the Forge.", "Tente refinar três vezes na Forja."),
    ("The boat is ready and the tide is with us.", "O barco está pronto e a maré ajuda."),
    ("Chronicle {n} · Guardian of the Storm", "Crônica {n} · Guardião da Tempestade"),
    ("Chronicle {n} · Reach level {trava}", "Crônica {n} · Alcance o nível {trava}"),
    ("The last lighthouse is out there. I'll take you.", "O último farol fica lá. Eu levo você."),
    ("Drink. Tomorrow the wind will blow hard.", "Beba. Amanhã o vento vai soprar forte."),
    ("You reached the Waste alive. Few do.", "Você chegou vivo ao Ermo. Poucos chegam."),
    ("Move with the storm, not against it.", "Mova-se com a tempestade, não contra ela."),
    ("The Cartographer at the port has something for you.", "O Cartógrafo do porto tem algo para você."),
    ("Three lighthouses lit! The house buys this round.", "Três faróis acesos! A casa paga a rodada."),
    ("Archers watch the cliffs. Defeat 12.", "Arqueiros vigiam os penhascos. Derrote 12."),
    ("The air is thin up here. Breathe slowly.", "O ar é fino aqui em cima. Respire devagar."),
    ("With the map in hand, return to the port yard.", "Com o mapa na mão, volte ao pátio do porto."),
    ("When you're ready, the Master is waiting for you.", "Quando estiver pronto, o Mestre espera você."),
    ("With this you can cut through the storm's wind.", "Com isso dá para cortar o vento da tempestade."),
    ("Talk to the Alchemist before you set foot on the sand.", "Fale com o Alquimista antes de pisar na areia."),
    ("From here you can see the eye of the storm turning.", "Daqui dá para ver o olho da tempestade girando."),
    ("But the storm does not die: it sleeps and it wakes.", "Mas a tempestade não morre: ela dorme e acorda."),
    ("Show the Appraiser what you found in the stones.", "Mostre o que achou nas pedras ao Identificador."),
    ("The lighthouse of the Waste shines again. I saw it from the sea.", "O farol do Ermo voltou a brilhar. Eu vi do mar."),
    ("Create a new piece in Craft for the cold that's coming.", "Crie uma peça nova no Craft para o frio que vem."),
    ("Whoever fights inside the wind cannot stand still.", "Quem luta dentro do vento não pode ficar parado."),
    ("Someone is tearing stones out of the frozen lighthouse.", "Alguém está arrancando pedras do farol congelado."),
    ("Create a new piece in Craft with what the Waste gave you.", "Crie uma peça nova no Craft com o que o Ermo deu."),
    ("They say Morgan has landed with the entire fleet.", "Dizem que Morgan desembarcou com a frota inteira."),
    ("With all four lighthouses lit, perhaps the sea will open.", "Com os quatro faróis acesos, talvez o mar se abra."),
    ("Let me see… This shard is a piece of the lighthouse.", "Deixe eu ver… Este fragmento é um pedaço do farol."),
    ("Take the map. Come back to the port when you're ready.", "Leve o mapa. Volte ao porto quando estiver pronto."),
    ("But the eye of the storm has moved closer to the Plateau.", "Mas o olho da tempestade se aproximou do Planalto."),
    ("The Appraiser reads the rune carved into the skystone.", "O Identificador lê a runa gravada na pedra do céu."),
    ("The Master sent you? Then you're the castaway from the lighthouse.", "O Mestre mandou você? Então é o náufrago do farol."),
    ("The Morganeers want the lighthouse. Defeat 40 enemies.", "Os Morganeers querem o farol. Derrote 40 inimigos."),
    ("Morganeer archers are watching the lighthouse. Defeat 8.", "Arqueiros dos Morganeers vigiam o farol. Derrote 8."),
    // ─────────────────── the lines: what the NPCs say at each step ───────────────────
    ("The Waste lies to the south, past the sea of wet sand.", "O Ermo fica ao sul, depois do mar de areia molhada."),
    ("Take the glass to the Blacksmith. They say it cuts through storms.", "Leve o vidro ao Ferreiro. Dizem que corta tempestade."),
    ("You saved our lighthouse. This cloak is on me.", "Você salvou nosso farol. Esta capa é por minha conta."),
    ("Water, salt and remedy: that's what keeps a person alive out here.", "Água, sal e remédio: é o que mantém alguém vivo aqui."),
    ("The Glacier's stone traps lightning. Break 20 rocks.", "A pedra da Geleira prende relâmpago. Quebre 20 pedras."),
    ("Where lightning strikes, sand turns to stone. Break 25 rocks.", "Onde o raio cai, a areia vira pedra. Quebre 25 pedras."),
    ("The mages use the thunder in the sand. Mind the lightning.", "Os magos usam o trovão da areia. Cuidado com os raios."),
    ("Lightning glass… Sharper than anything I've ever forged.", "Vidro de relâmpago… Afiado como nada que eu já forjei."),
    ("Welcome to the Glacier's port. The road leads to the city.", "Bem-vindo ao porto da Geleira. A estrada leva à cidade."),
    ("Nobody has ever drawn what lies beyond the storm.", "Ninguém nunca desenhou o que existe além da tempestade."),
    ("The Captain lit a signal at the end of the quay. Go to him.", "O Capitão acendeu um sinal na ponta do cais. Vá até lá."),
    ("The lighthouse there was buried. Morgan got there first.", "O farol de lá foi soterrado. Morgan esteve lá primeiro."),
    ("The owlbear cubs come down the trails after them, starving.", "Os corujursos descem das trilhas atrás deles, famintos."),
    ("Starving owlbears are attacking the ice trails. Defeat 6.", "Owlbears famintos atacam as trilhas de gelo. Derrote 6."),
    ("So you saw the dark lighthouse from the lookout. I saw it too.", "Então você viu o farol apagado do mirante. Eu vi também."),
    ("The Waste's lighthouse sits atop the dunes. Climb to the lookout.", "O farol do Ermo está no topo das dunas. Suba ao mirante."),
    ("I heard about the wolves. Not bad for someone who washed up floating.", "Ouvi falar dos lobos. Nada mal para quem chegou boiando."),
    ("And the stone here traps lightning. That stone is what they want.", "E a pedra daqui prende relâmpago. Eles querem essa pedra."),
    ("The Innkeeper knows where the Morganeers hide in the snow.", "O Taberneiro sabe onde os Morganeers se escondem na neve."),
    ("A singing stone? Let me listen… That's thunder trapped in metal.", "Pedra que canta? Deixe eu ouvir… É trovão preso no metal."),
    ("This rune reads: “whoever lights the lighthouse of the sky becomes a guardian”.", "Esta runa diz: “quem acende o farol do céu vira guardião”."),
    ("Keep this: quintessence. No armour closes without it.", "Guarde isto: quintessência. Armadura nenhuma fecha sem ela."),
    ("Our lighthouse still shines, but the ice is cracking the stone.", "Nosso farol ainda brilha, mas o gelo está rachando a pedra."),
    ("The Cartographer wants to draw what lies beyond the storm.", "O Cartógrafo quer desenhar o que existe além da tempestade."),
    ("The wolves are behaving strangely. Go look at the trail, but carefully.", "Os lobos estão estranhos. Vá ver a trilha, mas com cuidado."),
    ("Nobody crosses the dunes without water. Talk to the Alchemist.", "Sem água ninguém atravessa as dunas. Fale com o Alquimista."),
    ("At the port, the Captain says the last lighthouse is on the Plateau.", "No porto, o Capitão diz que o último farol fica no Planalto."),
    ("The Glacier's lighthouse stands high up. Climb to the island's lookout.", "O farol da Geleira fica no alto. Suba até o mirante da ilha."),
    ("If the lighthouses fall, the storm swallows the islands one by one.", "Se os faróis caírem, a tempestade engole as ilhas uma a uma."),
    ("Sit, warm your hands. Morganeers? They came in with the blizzard.", "Senta, esquenta as mãos. Morganeers? Chegaram com a nevasca."),
    ("Three lighthouses shine again. The Innkeeper is pouring.", "Três faróis voltaram a brilhar. O Taberneiro serve a rodada."),
    ("The Plateau's stones hold the strongest thunder. Break 30.", "As pedras do Planalto guardam o trovão mais forte. Quebre 30."),
    ("On the Plateau the wind cuts. Report to the Quest Master.", "No Planalto o vento corta. Apresente-se ao Mestre de Missões."),
    ("At the roof of power, the watch never ends. Defeat {q} enemies.", "No teto do poder, a guarda nunca acaba. Derrote {q} inimigos."),
    ("The last lighthouse is the highest of them all. You'll need strength.", "O último farol é o mais alto de todos. Vai precisar de força."),
    ("All four lighthouses shine. You did what no castaway ever has.", "Os quatro faróis brilham. Você fez o que nenhum náufrago fez."),
    ("First, look after yourself: the Alchemist has what you need.", "Primeiro, cuide de você: o Alquimista tem o que você precisa."),
    ("Strange boats are circling the island's far coast. Go and look.", "Barcos estranhos rondam a costa mais distante da ilha. Vá ver."),
    ("Morganeer mages use the thunder trapped in the sand. Defeat 10.", "Magos dos Morganeers usam o trovão preso na areia. Derrote 10."),
    ("The Tailor sews with thread that holds the wind. Talk to him.", "O Alfaiate costura com fios que seguram o vento. Fale com ele."),
    ("Come aboard. On the other side, report to the Harbour Captain.", "Suba a bordo. Do outro lado, apresente-se ao Capitão do Porto."),
    ("From the end of the quay you can see the eye of the storm turning. Go there.", "Da ponta do cais se vê o olho da tempestade girando. Vá até lá."),
    ("Morgan read the same rune. He wants to be the guardian of the storm.", "Morgan leu a mesma runa. Ele quer ser o guardião da tempestade."),
    ("The Captain knows why the lighthouses go dark. Talk to him at the port.", "O Capitão sabe por que os faróis apagam. Fale com ele no porto."),
    ("Come to the end of the quay with me at dawn. I'll show you the route.", "Vá até a ponta do cais comigo ao amanhecer. Vou mostrar a rota."),
    ("The Morganeers' entire fleet has landed. Defeat 50 enemies.", "A frota inteira dos Morganeers desembarcou. Derrote 50 inimigos."),
    ("Morgan's flagship lies on the far coast. Go there.", "A nau capitânia de Morgan jaz na costa mais distante. Vá até lá."),
    ("Create a new piece in Craft to face the eye of the storm.", "Crie uma peça nova no Craft para enfrentar o olho da tempestade."),
    ("There's an islet half an hour from the quay. Ownerless since the storm.", "Tem uma ilhota a meia hora do cais. Sem dono desde a tempestade."),
    ("That metal is what hardens the beasts. It also makes good armour.", "Esse metal é o que endurece os bichos. E também faz boa armadura."),
    ("Stormwool: thread that holds the wind. Not for just anyone.", "Lã-de-tempestade: fio que segura o vento. Não é para qualquer um."),
    ("You're alive! The sea brought you in the night the lighthouse went dark.", "Você está vivo! O mar trouxe você na noite em que o farol apagou."),
    ("The Morganeers are closing in on the island. Defeat 30 enemies of any kind.", "Os Morganeers cercam a ilha. Derrote 30 inimigos de qualquer tipo."),
    ("The guardians need new gear. Create a piece in Craft.", "Os guardiões precisam de equipamento novo. Crie uma peça no Craft."),
    ("A Morganeer boat ran aground on the far coast. Go there.", "Um barco dos Morganeers encalhou na costa mais distante. Vá até lá."),
    ("The Peacemain guard the port. Follow the road to the quay yard.", "Os Peacemain guardam o porto. Siga pela estrada até o pátio do cais."),
    ("The lighthouses drink thunderstone. Break {q} rocks at any vein.", "Os faróis bebem pedra de trovão. Quebre {q} pedras em qualquer veio."),
    ("Go to the end of the quay: the Captain promised to show the island route.", "Vá até a ponta do cais: o Capitão prometeu mostrar a rota das ilhas."),
    ("Sand as far as the eye can see. Look for the Quest Master in the square.", "Areia até onde a vista alcança. Procure o Mestre de Missões na praça."),
    ("Set sail with the Captain for the Plateau, close to the eye of the storm.", "Embarque com o Capitão rumo ao Planalto, perto do olho da tempestade."),
    ("A weak piece won't survive the storm. Try refining a piece at the Forge.", "Peça fraca não aguenta a tempestade. Tente refinar uma peça na Forja."),
    ("The beasts from the eye of the storm come down to the Plateau. Defeat 15 owlbears.", "As feras do olho da tempestade descem ao Planalto. Derrote 15 owlbears."),
    ("Take the Guardians' oath: to watch the lighthouses as long as there is wind.", "Faça o juramento dos Guardiões: vigiar os faróis enquanto houver vento."),
    ("The last lighthouse stands at the highest point of the archipelago. Climb to the lookout.", "O último farol fica no ponto mais alto do arquipélago. Suba ao mirante."),
    ("The one who knows about the Morganeers in the snow is the Innkeeper. Buy his ear.", "Quem sabe dos Morganeers na neve é o Taberneiro. Pague um ouvido a ele."),
    ("The deed is yours. Small land, but it yields on its own while you sail.", "A escritura é sua. Terra pequena, mas rende sozinha enquanto você navega."),
    ("The Cartographer at the port drew the route to the Waste. Fetch the map from him.", "O Cartógrafo do porto desenhou a rota para o Ermo. Busque o mapa com ele."),
    ("All four lighthouses shine. The Quest Master has an oath for you.", "Os quatro faróis brilham. O Mestre de Missões tem um juramento para você."),
    ("Whenever you want to go there, just say the word: the boat leaves here and comes back here.", "Quando quiser ir até lá, é só me dizer: o barco sai daqui e volta pra cá."),
    ("Climb to the lookout of whichever island you're on and check whether the lighthouse still shines.", "Suba ao mirante da ilha em que estiver e confira se o farol ainda brilha."),
    ("The Harbour Captain will take you to the Waste, where the third lighthouse was buried.", "O Capitão do Porto leva você ao Ermo, onde o terceiro farol foi soterrado."),
    ("The Trainer knows the footwork of those who fight inside the wind. Learn it from him.", "O Treinador conhece o passo de quem luta dentro do vento. Aprenda com ele."),
    ("The bears came down from the slopes chasing the smell of thunder. Defeat 4 bears.", "Os ursos desceram das encostas atrás do cheiro de trovão. Derrote 4 ursos."),
    ("The cellar hatch is barred with a Morganeer lock, and only a key cut for it will turn. The key is made in Craft from wood and grey Steel. Fell 6 trees — the woodcutters make up whatever wood you're missing.", "A escotilha do porão está trancada com um cadeado dos Morganeers, e só gira com uma chave feita pra ele. A chave se faz no Craft, com madeira e Aço cinza. Derrube 6 árvores — os lenhadores completam a madeira que faltar."),
    ("Now the metal: break 6 stones in any vein — Steel comes out of the stone. The miners make up whatever the key still asks for.", "Agora o metal: quebre 6 pedras em qualquer veio — o Aço sai da pedra. Os mineiros completam o que a chave ainda pedir."),
    ("You have the wood and the Steel. Open Menu › Craft and create the Shipwreck Cellar Key. It opens the hatch of the wreck, and the door keeps it: one key, one run.", "Você tem a madeira e o Aço. Abra Menu › Craft e crie a Chave do Porão do Naufrágio. Ela abre a escotilha do naufrágio, e a porta fica com ela: uma chave, uma entrada."),
    ("Take the copper as well. With what you've gathered, that's an armour. Go to Craft.", "Tome o cobre também. Com o que você juntou, já dá uma armadura. Vá ao Craft."),
    ("The lighthouse here is under the dunes, and Morgan's mages dig day and night.", "O farol daqui está debaixo das dunas, e os magos de Morgan cavam dia e noite."),
    ("Another one only a boss will give up: the one in the Shipwreck Cellar carries a key in his pocket.", "Outro só arrancando de chefe: o do Porão do Naufrágio carrega chave no bolso."),
    (
        "A forja precisa de lenha e o Ferreiro paga bem por ela. Vá derrubar umas árvores.",
        "The forge needs firewood and the Blacksmith pays well for it. Go fell some trees.",
    ),
    (
        "O do Bosque se apagou. Os bichos enlouquecem e os Morganeers já sentiram o cheiro.",
        "The one in the Grove went dark. The beasts are going mad and the Morganeers have caught the scent.",
    ),
    (
        "A tempestade não dorme e os bichos não param. Derrote {q} inimigos de qualquer tipo.",
        "The storm does not sleep and the beasts do not stop. Defeat {q} enemies of any kind.",
    ),
    (
        "Pistoleiros dos Morganeers rondam a mata atrás das pedras do farol. Derrote 6 deles.",
        "Morganeer gunmen prowl the woods after the lighthouse stones. Defeat 6 of them.",
    ),
    (
        "Sem poção, a mata engole qualquer um. Tome estas, e beba antes de cair — não depois.",
        "Without potions, the woods swallow anyone. Take these, and drink before you fall — not after.",
    ),
    (
        "Aço que enfrenta a tempestade é aço refinado. Tente refinar {vezes} vez(es) na Forja.",
        "Steel that faces the storm is refined steel. Try refining {vezes} time(s) at the Forge.",
    ),
    (
        "Há gerações quatro faróis de pedra-trovão seguram a Grande Tempestade longe das ilhas.",
        "For generations, four lighthouses of thunderstone have held the Great Storm away from the islands.",
    ),
    (
        "Os Peacemain guardam os portos e os faróis. Os Morganeers querem a tempestade para eles.",
        "The Peacemain guard the ports and the lighthouses. The Morganeers want the storm for themselves.",
    ),
    (
        "O farol da Geleira ainda brilha, mas por pouco. Peça ao Capitão do Porto um lugar no barco.",
        "The Glacier's lighthouse still shines, but only just. Ask the Harbour Captain for a place on the boat.",
    ),
    (
        "Você desembarcou no porto da Geleira. Fale com o Capitão antes de seguir pela estrada até a cidade.",
        "You've landed at the Glacier's port. Talk to the Captain before following the road to the city.",
    ),
    (
        "Seu morador já trabalhou. Toque em COLHER: o que ele produziu vai pro BAÚ DA ILHA, e não pra sua bolsa.",
        "Your resident has been working. Tap HARVEST: what they produced goes into the ISLAND CHEST, not into your bag.",
    ),
    (
        "A história continua quando você chegar a esse nível. Cace, colete e faça as diárias do Mestre de Missões.",
        "The story carries on once you reach that level. Hunt, gather and do the Quest Master's dailies.",
    ),
    (
        "Toda peça pede um couro curtido para segurar o metal. Tome o meu — é o último, e some depois de uma forja.",
        "Every piece asks for a tanned leather to hold the metal. Take mine — it's the last one, and it's gone after one forging.",
    ),
    (
        "O baú é da ilha. Toque em RETIRAR para passar o que há nele pra sua bolsa — o que não couber fica guardado.",
        "The chest belongs to the island. Tap WITHDRAW to move what's in it into your bag — whatever doesn't fit stays stored.",
    ),
    (
        "O Mestre quer você de pé. Fale com o Alquimista, na loja de toldo verde: sem poção, a mata engole qualquer um.",
        "The Master wants you on your feet. Talk to the Alchemist, at the green-awning shop: without potions, the woods swallow anyone.",
    ),
    (
        "Suba ao ponto mais alto da ilha. De lá se vê o olho da tempestade — e, lá embaixo, o casco do naufrágio encalhado.",
        "Climb to the highest point on the island. From there you can see the eye of the storm — and, down below, the grounded hull of the wreck.",
    ),
    (
        "Você acordou na praia na noite em que o farol do Bosque apagou. Procure o Mestre de Missões, perto do poço da praça.",
        "You woke on the beach the night the Grove's lighthouse went dark. Look for the Quest Master, near the well in the square.",
    ),
    (
        "Uma casa sozinha não sustenta ninguém. No painel da ilha, melhore o ASSENTAMENTO: ele abre a primeira casa de ofício.",
        "One house alone supports nobody. On the island panel, upgrade the SETTLEMENT: it opens the first trade house.",
    ),
    (
        "O Treinador mostra: arraste uma skill PARA CIMA e ela passa a ser usada sozinha no combate. Para baixo, volta pro manual.",
        "The Trainer shows you: drag a skill UP and it starts being used on its own in combat. Drag it down and it goes back to manual.",
    ),
    (
        "Você sobreviveu aos lobos. O Treinador da praça quer ver do que é capaz — e guarda quintessência para quem aguenta o tranco.",
        "You survived the wolves. The Trainer in the square wants to see what you can do — and he keeps quintessence for whoever can take a beating.",
    ),
    (
        "Casa vazia não rende. Na casa que abriu, escolha um ofício — o Lenhador traz madeira, o Minerador traz aço, o Mercenário traz cobre.",
        "An empty house yields nothing. In the house you opened, pick a trade — the Woodcutter brings wood, the Miner brings steel, the Mercenary brings copper.",
    ),
    (
        "Leve o que ouviu nas pedras ao Ferreiro. Ele sabe o que o metal carrega — e guarda o couro e o cobre que faltam para quem vai forjar.",
        "Take what you heard in the stones to the Blacksmith. He knows what the metal carries — and he keeps the leather and copper that anyone about to forge is missing.",
    ),
    (
        "A forja come madeira e pedra. Toque em COLETA: o personagem corta e quebra sozinho o que estiver por perto — a engrenagem do botão escolhe o quê.",
        "The forge eats wood and stone. Tap GATHER: your character cuts and breaks whatever is nearby on its own — the gear icon on the button chooses what.",
    ),
    (
        "A Energia que você juntou no Bosque não é só brilho: ela desperta o que você já sabe. Abra Menu › Personagem › Habilidades, escolha uma das suas e suba um tier.",
        "The Energy you gathered in the Grove isn't just a glow: it wakes what you already know. Open Menu › Character › Skills, pick one of yours and raise it a tier.",
    ),
    (
        "Antes dos lobos, aprenda a lutar sem pensar: toque em COMBATE, no canto de baixo, e o personagem enfrenta sozinho o que estiver perto. Toque de novo para parar.",
        "Before the wolves, learn to fight without thinking: tap COMBAT, in the bottom corner, and your character takes on whatever is near on its own. Tap again to stop.",
    ),
    (
        "As pedras da ilha zumbem com o trovão. Quebre 10 pedras em qualquer veio — é da pedra que saem o Aço e o Darksteel de toda peça. A mineradora completa o seu Aço.",
        "The island's stones hum with thunder. Break 10 rocks at any vein — stone is where the Steel and Darksteel of every piece come from. The miner tops up your Steel.",
    ),
    (
        "O Alquimista insiste: poção boa é a que se bebe sozinha. Abra Menu › Sistema › Barra, escolha a Poção de Vida e ajuste com − e + a % de vida em que ela é bebida.",
        "The Alchemist insists: a good potion is one that drinks itself. Open Menu › System › Bar, pick the Health Potion and use − and + to set the health % at which it is drunk.",
    ),
    (
        "Tigres cercam a estrada dos carregadores e ninguém passa com carga. Derrote 5 — deles se tira a Quintessência, que toda armadura pede e a pedra dá a conta-gotas.",
        "Tigers have surrounded the porters' road and nobody gets through with cargo. Defeat 5 — they're where Quintessence comes from, which every armour asks for and stone gives a drop at a time.",
    ),
    (
        "A forja da vila come madeira dia e noite. Derrube 8 árvores — é da árvore que sai toda a madeira da ilha. O Ferreiro paga em Darksteel, o metal escuro que toda peça pede.",
        "The village forge eats wood day and night. Fell 8 trees — trees are where all the island's wood comes from. The Blacksmith pays in Darksteel, the dark metal every piece asks for.",
    ),
    (
        "Antes de zarpar, o Capitão quer o porto limpo: os contrabandistas de Morgan guardam pedra do farol numa adega sob o cais. Toque no passo (ou em Dungeons, no Menu) e limpe a Adega do Contrabandista.",
        "Before setting sail, the Captain wants the port clean: Morgan's smugglers are keeping lighthouse stone in a cellar under the quay. Tap the step (or Dungeons, in the Menu) and clear the Smuggler's Cellar.",
    ),
    (
        "Os lobos enlouqueceram desde que o farol apagou: descem à trilha de dia, coisa que nunca fizeram. Derrote 5 fora da cidade. Os caçadores juntaram berloques que os bichos arrancaram das carroças — são seus.",
        "The wolves have gone mad since the lighthouse went dark: they come down to the trail in daylight, which they never did. Defeat 5 outside the city. The hunters gathered up charms the beasts tore off the carts — they're yours.",
    ),
    (
        "Toque no minimapa para abrir o mapa da ilha e toque num lugar: o personagem vai sozinho até lá. Ao concluir, abra o Pergaminho de Invocação: Montaria na bolsa, equipe a montaria e use o botão Montar para viajar mais rápido.",
        "Tap the minimap to open the island map and tap a place: your character walks there on its own. When you're done, open the Summoning Scroll: Mount in your bag, equip the mount and use the Mount button to travel faster.",
    ),
    (
        "O Capitão te entrega uma escritura: uma ilhota a meia hora do cais, sem dono desde a tempestade. É sua — e ela rende sozinha enquanto você navega. Abra Menu › Minha Ilha para vê-la: o Capitão deixou lá o material da primeira obra.",
        "The Captain hands you a deed: an islet half an hour from the quay, ownerless since the storm. It's yours — and it yields on its own while you sail. Open Menu › My Island to see it: the Captain left the material for the first build there.",
    ),
    (
        "O trovão deixou cristais azuis no relevo: é Energia, e ela não ocupa espaço na bolsa e é o que paga os seus pontos de atributo. Toque no passo que o caminho até um veio abre sozinho — junte o bastante pra gastar tudo o que os primeiros níveis te deram.",
        "The thunder left blue crystals across the terrain: that's Energy, it takes no space in your bag, and it's what pays for your attribute points. Tap the step and the path to a vein opens on its own — gather enough to spend everything the first few levels gave you.",
    ),
    (
        "Do mirante você viu o casco. Os Morganeers fizeram do porão um esconderijo, e quem manda lá dentro carrega chave no bolso — chefe de dungeon larga chave bem mais que chefe de campo. Com a chave do porão na bolsa, toque no passo (ou em Dungeons, no Menu), use \"Ir para o portal\" e limpe o Porão do Naufrágio. Sozinho dá.",
        "From the lookout you saw the hull. The Morganeers have made the cellar a hideout, and whoever rules down there carries a key in his pocket — a dungeon boss drops keys far more often than a field boss. With the cellar key in your bag, tap the step (or Dungeons, in the Menu), use \"Go to the portal\" and clear the Shipwreck Cellar. Solo is enough.",
    ),
    (
        "Cada ponto de atributo custa Energia — a mesma dos cristais azuis do relevo. Abra Menu › Personagem › Ficha e coloque um ponto no atributo que combina com a sua arma: FOR bate mais forte, DES acerta mais, INT move a magia. Se faltar Energia, quebre um cristal e volte.",
        "Every attribute point costs Energy — the same Energy as the blue crystals out on the terrain. Open Menu › Character › Sheet and put a point into the attribute that suits your weapon: STR hits harder, DEX lands more often, INT drives the magic. If you run short of Energy, break a crystal and come back.",
    ),
    (
        "Você tem tudo o que a Armadura pede: o couro do Ferreiro, Aço, Quintessência, Berloque, Darksteel e cobre. Abra o Craft e crie sua primeira armadura. Depois disso, tudo isso se farma: pedra, árvore, bicho e chefe — e o pergaminho que o Ferreiro te dá chama quem colhe por você.",
        "You have everything the Armour asks for: the Blacksmith's leather, Steel, Quintessence, a Charm, Darksteel and copper. Open Craft and create your first armour. After that, all of it can be farmed: stone, tree, beast and boss — and the scroll the Blacksmith gives you calls someone who gathers for you.",
    ),
];
