//! Quests: the title, description and hand-in line of each one.

pub const VERBETES: &[(&str, &str)] = &[
    // ─────────────────────────── the quest titles ───────────────────────────
    // A short title is what shows up most: list, journal, compass. It should
    // sound like an English quest name, not like a literal translation.
    ("The Tannery", "Curtume"),
    ("Deep ice", "Gelo fundo"),
    ("Timberman", "Madeireiro"),
    ("Heavy hand", "Mão pesada"),
    ("Hunt of the day", "Caça do dia"),
    ("To work", "Mãos à obra"),
    ("Boss of the day", "Chefe do dia"),
    ("Crossfire", "Fogo Cruzado"),
    ("Hot forge", "Forja quente"),
    ("Through the Mists", "Pelas Névoas"),
    ("Cellar of the day", "Porão do dia"),
    ("Jump the Rock", "Pule a Pedra"),
    ("Tempered steel", "Aço temperado"),
    ("Cargo on the quay", "Carga no cais"),
    ("Chase of the day", "Caçada do dia"),
    ("Bear leather", "Couro de urso"),
    ("Trail-clearing", "Limpa-trilhas"),
    ("Fine timber", "Madeira nobre"),
    ("Eyes on the woods", "Olhos na mata"),
    ("Quintessence", "Quintessência"),
    ("White trail", "Rastro branco"),
    ("Village rounds", "Ronda da vila"),
    ("Bears in the woods", "Ursos na mata"),
    ("Deep vein", "Veio profundo"),
    ("Heat and Ashes", "Calor e Cinzas"),
    ("Enchant of the day", "Encanto do dia"),
    ("Forge your Weapon", "Forje sua Arma"),
    ("Watch of the Waste", "Guarda do Ermo"),
    ("Calloused hands", "Mãos calejadas"),
    ("The Salt of the Earth", "O Sal da Terra"),
    ("Wolf fangs", "Presas de lobo"),
    ("A Bold Rescue", "Resgate Ousado"),
    ("Hunting routine", "Rotina de caça"),
    ("Visit the Port", "Visite o Porto"),
    ("Beasts on the beach", "Bichos na praia"),
    ("Shells on the trail", "Casco na trilha"),
    ("Copper for the forge", "Cobre pra forja"),
    ("A guarded coast", "Costa protegida"),
    ("Clearing the woods", "Limpeza da mata"),
    ("Line of defence", "Linha de defesa"),
    ("Marks in the sand", "Marcas na areia"),
    ("Marks in the stone", "Marcas na pedra"),
    ("Metal for the shelter", "Metal do abrigo"),
    ("Quarry of the day", "Pedreira do dia"),
    ("Prove your Worth", "Prove seu Valor"),
    ("Gunpowder in the woods", "Pólvora na mata"),
    ("Dungeon rat", "Rato de dungeon"),
    ("Tap GATHER", "Toque em COLETA"),
    ("Voices on the climb", "Vozes na subida"),
    ("The Strength of the Forge", "A Força da Forja"),
    ("The cellar, again", "A adega, de novo"),
    ("A growing threat", "Ameaça crescente"),
    ("Glacier leather", "Couro da Geleira"),
    ("Peacemain Defence", "Defesa Peacemain"),
    ("Claws on the trail", "Garras na trilha"),
    ("Clearing the coast", "Limpeza da costa"),
    ("The grey pack", "Matilha cinzenta"),
    ("On the board: Harvest", "No mural: Colher"),
    ("The Coastal Stronghold", "O Forte Costeiro"),
    ("The first boss", "O primeiro chefe"),
    ("Water patrol", "Patrulha da água"),
    ("Frozen branches", "Ramos congelados"),
    ("Metal reserve", "Reserva de metal"),
    ("Following the Wind", "Seguindo o Vento"),
    ("Legendary treasure", "Tesouro lendário"),
    ("Tap COMBAT", "Toque em COMBATE"),
    ("Walrus Watch", "Vigia das Morsas"),
    ("The legend of the Grove", "A lenda do Bosque"),
    ("The first scale", "A primeira escama"),
    ("Bear Scout", "Batedor dos Ursos"),
    ("Boss hunter", "Caçador de chefes"),
    ("Protective leather", "Couro de proteção"),
    ("Back to the cellar", "De volta ao porão"),
    ("Morganeer Dominion", "Domínio Morganeer"),
    ("Enchant a piece.", "Encante uma peça."),
    ("Glacier scale", "Escama da Geleira"),
    ("Firewood for the quay", "Lenha para o cais"),
    ("Hammer and anvil", "Martelo e bigorna"),
    ("The shelter on the coast", "O abrigo da costa"),
    ("The way to the summit", "O caminho do cume"),
    ("The buried hull", "O casco enterrado"),
    ("Stones under the snow", "Pedras sob a neve"),
    ("Provisioner of the Waste", "Provisora do Ermo"),
    ("Glade Watch", "Vigia da Clareira"),
    ("The forest breathes", "A floresta respira"),
    ("The queen of the dunes", "A rainha das dunas"),
    ("Steel for the wall", "Aço para a muralha"),
    ("The apprentice's horn", "Chifre do aprendiz"),
    ("Exorcism at Sea", "Exorcismo Marítimo"),
    ("Firewood for the watch", "Lenha para o vigia"),
    ("Woodcutter of the Trail", "Lenhador da Trilha"),
    ("Stripes on the road", "Listras na estrada"),
    ("The Heart of Stone", "O Coração de Pedra"),
    ("The howl in the glade", "O uivo da clareira"),
    ("The old man on the slope", "O velho da encosta"),
    ("The mages of thunder", "Os magos do trovão"),
    ("A secret under the snow", "Segredo sob a neve"),
    ("Warlords", "Senhores da guerra"),
    ("Forest trail", "Trilha da floresta"),
    ("Glass beneath the dunes", "Vidro sob as dunas"),
    ("Shipwreck Watch", "Vigia do Naufrágio"),
    ("Shipwreck watch", "Vigia do naufrágio"),
    ("The Sunken Relic", "A Relíquia Submersa"),
    ("Your own armourer", "Armeiro de si mesmo"),
    ("Explorer of the Ice", "Exploradora do Gelo"),
    ("Fragments of the hull", "Fragmentos do casco"),
    ("Guardian of the Forest", "Guardiã da Floresta"),
    ("Guardian of the Glacier", "Guardião da Geleira"),
    ("Clearing the forest", "Limpeza da floresta"),
    ("Storm line", "Linha de tempestade"),
    ("News from the tavern", "Notícias da taberna"),
    ("The Clash on the Quay", "O Confronto no Cais"),
    ("The first T2 mould", "O primeiro molde T2"),
    ("Remains of the flagship", "Restos da capitânia"),
    ("Supplies secured", "Suprimentos seguros"),
    ("Three signs in the snow", "Três sinais na neve"),
    ("Breaking the Blockade", "A Quebra do Bloqueio"),
    ("Hunting the raiders", "Caça aos saqueadores"),
    ("Leather for the tannery", "Couro para o curtume"),
    ("Darksteel stock", "Estoque de darksteel"),
    ("Escape from the Whirlpools", "Fuga dos Redemoinhos"),
    ("A claw for the off-hand", "Garra para a subarma"),
    ("Wood for the port", "Madeira para o porto"),
    ("Stronger than steel", "Mais forte que o aço"),
    ("Ore for the forge", "Minério para a forja"),
    ("The Waking of the Earth", "O Despertar da Terra"),
    ("The Cartographer's map", "O mapa do Cartógrafo"),
    ("What the stone keeps", "O que a pedra guarda"),
    ("What came down from the ice", "O que desceu do gelo"),
    ("Route to the Plateau", "Rota para o Planalto"),
    ("Leather for the armour", "Couro para a armadura"),
    ("Braving the Hurricane", "Desbravando o Furacão"),
    ("The owlbear's charm", "O berloque do owlbear"),
    ("What the stone hides", "O que a pedra esconde"),
    ("Researcher of the Dunes", "Pesquisador das Dunas"),
    ("Winter predators", "Predadores do inverno"),
    ("Water for the crossing", "Água para a travessia"),
    ("Open Menu › My Island", "Abra Menu › Minha Ilha"),
    ("A research tool", "Ferramenta de pesquisa"),
    ("Enemy reconnaissance", "Reconhecimento inimigo"),
    ("Stay Near the Trees", "Fique Perto das Arvores"),
    ("The Heart of the Storm", "O Coração da Tempestade"),
    ("Harvest and Deliver Wood", "Colha e Entregue Madeira"),
    ("What lies under the wreck", "O que há sob o naufrágio"),
    ("Defeat 30 beasts on the island.", "Derrote 30 bichos da ilha."),
    ("Defeat 40 beasts on the island.", "Derrote 40 bichos da ilha."),
    ("Defeat 50 beasts on the island.", "Derrote 50 bichos da ilha."),
    ("Defeat 60 beasts on the island.", "Derrote 60 bichos da ilha."),
    ("Defeat the boss of the Hunt.", "Derrote o chefe da Caçada."),
    ("The Guardian of the Depths", "O Guardião das Profundezas"),
    ("I have a task for you.", "Tenho uma tarefa pra você."),
    ("Drag a skill UP", "Arraste uma skill para CIMA"),
    ("Stormbeard's flag", "A bandeira do Barba-Tormenta"),
    ("Menu › Sheet: spend a point", "Menu › Ficha: gaste um ponto"),
    ("Open the map and tap a place", "Abra o mapa e toque num lugar"),
    ("Collect Energy from the blue crystals", "Junte Energia nos cristais azuis"),
    ("On the board: upgrade the Settlement", "No mural: melhore o Assentamento"),
    ("On the board: Withdraw, from the island chest", "No mural: Retirar, do baú da ilha"),
    ("Menu › Skills: evolve one tier", "Menu › Habilidades: evolua um tier"),
    ("Met the old Alchemist? Good.", "Conheceu o velho Alquimista? Ótimo."),
    ("Defeat three bears and come back whole.", "Derrote três ursos e volte inteiro."),
    ("Complete a dungeon (Cellar or Cavern).", "Conclua uma dungeon (Porão ou Gruta)."),
    ("The blacksmith needs tier 2 ore.", "O ferreiro precisa de minério tier 2."),
    ("Supplies for the northern fortress", "Suprimentos para a fortaleza do norte"),
    ("Keep the outskirts of the village safe.", "Mantenha os arredores da vila seguros."),
    ("Good work. Here is your reward.", "Bom trabalho. Aqui está sua recompensa."),
    ("Thin out the monsters prowling the city.", "Reduza os monstros que rondam a cidade."),
    ("Ah, you came. Thank you for stopping by.", "Ah, você veio. Obrigado por passar aqui."),
    ("Defeat Peacemain members in combat.", "Derrote membros da Peacemain em combate."),
    ("Defeat Morganeers members in combat.", "Derrote membros da Morganeers em combate."),
    (
        "No mural: escolha um ofício na casa vazia",
        "On the board: pick a trade in the empty house",
    ),
    // ─────────────────────── the descriptions and hand-in lines ───────────────────────
    ("The merchants no longer travel without an escort.", "Os mercadores não passam mais sem escolta."),
    ("Break 20 rocks at any vein on the island.", "Quebre 20 pedras em qualquer veio da ilha."),
    ("Break 25 rocks at any vein on the island.", "Quebre 25 pedras em qualquer veio da ilha."),
    ("Break 30 rocks at any vein on the island.", "Quebre 30 pedras em qualquer veio da ilha."),
    ("Break 35 rocks at any vein on the island.", "Quebre 35 pedras em qualquer veio da ilha."),
    ("Ah, fresh blood in the square! Welcome to the island.", "Ah, sangue novo na praça! Bem-vindo à ilha."),
    ("Powerful beasts threaten the island. Thin them out.", "Bestas poderosas ameaçam a ilha. Reduza-as."),
    ("Create 1 piece of gear in Craft (the HUD button).", "Crie 1 equipamento no Craft (botão do HUD)."),
    ("Deliver ore to the city's foundry.", "Entregue minério para a fundição da cidade."),
    ("Menu › System › Bar: set the potion %", "Menu › Sistema › Barra: ajuste a % da poção"),
    ("Small creatures are bothering the fishermen.", "Pequenas criaturas incomodam os pescadores."),
    ("Try refining a piece three times at the Forge.", "Tente refinar três vezes uma peça na Forja."),
    ("The city needs leather for gear.", "A cidade precisa de couro para equipamentos."),
    ("Bring down ten white bears surrounding the outpost.", "Derrube dez ursos brancos que cercam o posto."),
    ("Tigers are hunting on the port road. Defeat 12.", "Tigres caçam na estrada do porto. Derrote 12."),
    ("Complete the Deep Ice Caverns with your party.", "Conclua as Grutas de Gelo Fundo com seu grupo."),
    ("The board asks for wood for the city's works.", "O quadro pede madeira para as obras da cidade."),
    ("Drive twelve white bears away from the Guardian's cabin.", "Afaste doze ursos brancos da cabana da Guardiã."),
    ("Create a piece of gear for the expedition into the dunes.", "Crie um equipamento para a expedição nas dunas."),
    ("Defeat six of them and the road breathes again.", "Derrote seis deles e a estrada respira de novo."),
    ("Talk to him and then tell me what he said.", "Fale com ele e depois me conte o que ele disse."),
    ("The tannery needs fresh leather to get started.", "O curtume precisa de couro fresco para começar."),
    ("Bring thirty Copper and the forge sings again.", "Traga trinta de Cobre e a forja volta a cantar."),
    ("Three bears! The woodcutters are back in the woods already.", "Três ursos! Os lenhadores já voltaram pra mata."),
    ("The fortress needs reinforced tier 3 wood.", "A fortaleza precisa de madeira tier 3 reforçada."),
    ("Hostile creatures have taken the woods. Clear them out.", "Criaturas hostis tomaram a mata. Faça a limpeza."),
    ("Defeat ten enemies prowling the coast of the Waste.", "Derrote dez inimigos que rondam a costa do Ermo."),
    ("Make a piece of gear for the journey beyond the Waste.", "Faça um equipamento para a jornada além do Ermo."),
    ("The Trainer wants to see stamina: defeat 100 enemies.", "O Treinador quer ver fôlego: derrote 100 inimigos."),
    ("The wolves are multiplying near the village. Defeat 12.", "Os lobos se multiplicam perto da vila. Derrote 12."),
    ("Veteran raiders surround the region. Wipe them out.", "Saqueadores veteranos cercam a região. Elimine-os."),
    ("Bears have come down the slope and are frightening the woodcutters.", "Ursos desceram a encosta e assustam os lenhadores."),
    ("Open Menu › Quests, pick the quest and tap Do", "Abra Menu › Missões, escolha a missão e toque Fazer"),
    ("Defeat a field boss on the island and return to the Watch.", "Derrote um chefe de campo da ilha e volte ao Vigia."),
    ("The Blacksmith is out of metal for the village's tools.", "O Ferreiro está sem metal pras ferramentas da vila."),
    ("The village port needs wood for repairs.", "O porto da vila precisa de madeira para os reparos."),
    ("The wolves have cost this island dearly. Defeat 50 of them.", "Os lobos já custaram caro à ilha. Derrote 50 deles."),
    ("The deadliest monsters in the archipelago prowl here.", "Os monstros mais letais do arquipélago rondam aqui."),
    ("Follow the road to the quay — the map shows the anchor.", "Siga a estrada até o cais — o mapa mostra a âncora."),
    ("You fight better than you look. Here's your pay.", "Você luta melhor do que parece. Aqui está sua paga."),
    ("The island is starting to speak your name. Take your reward.", "A ilha começa a falar seu nome. Tome sua recompensa."),
    ("Drive thirty creatures off the frozen lookout trail.", "Afaste trinta criaturas da trilha do mirante gelado."),
    ("Fell fifteen trees to open a safe trail.", "Derrube quinze árvores para abrir uma trilha segura."),
    ("Drive a Scarab Queen away from the research sites.", "Afaste uma Rainha Escaravelho dos locais de pesquisa."),
    ("Infiltrate the Peacemain headquarters and come back with information.", "Infiltre a sede da Peacemain e volte com informações."),
    ("This isn't a job for a novice — and you aren't one any more.", "Não é serviço pra novato — mas você já não é mais um."),
    ("The Harbour Captain wants to meet whoever protects the island.", "O Capitão do Porto quer conhecer quem protege a ilha."),
    ("The wolves are prowling the trails outside the city again.", "Os lobos voltaram a rondar as trilhas fora da cidade."),
    ("The bears have taken the woodcutters' trail. Defeat 10.", "Os ursos tomaram a trilha dos lenhadores. Derrote 10."),
    ("Infiltrate the Morganeers headquarters and come back with information.", "Infiltre a sede da Morganeers e volte com informações."),
    ("Break fifteen veins to leave a reserve at the cabin.", "Quebre quinze veios para deixar uma reserva na cabana."),
    ("Break twenty rocks to keep the metal supply going.", "Quebre vinte pedras para manter o suprimento de metal."),
    ("Complete one more dungeon and take the report to the Explorer.", "Conclua mais uma dungeon e leve o relato à Exploradora."),
    ("Defeat a field boss on the island (the map shows where).", "Derrote um chefe de campo da ilha (o mapa mostra onde)."),
    ("The vein on the slope still holds plenty. Break 30 rocks.", "O veio da encosta ainda guarda muito. Quebre 30 pedras."),
    ("Break ten veins near the coast to reinforce the shelter.", "Quebre dez veios perto da costa para reforçar o abrigo."),
    ("Six fewer wolves on the road. The merchants thank you.", "Seis lobos a menos na estrada. Os mercadores agradecem."),
    ("Complete the Waste dungeon once and tell the Researcher.", "Conclua uma vez a dungeon do Ermo e conte ao Pesquisador."),
    ("Defeat two more field bosses to map their routes.", "Derrote mais dois chefes de campo para mapear suas rotas."),
    ("Winter is coming and the village wants firewood. Fell 20 trees.", "O inverno vem aí e a vila quer lenha. Derrube 20 árvores."),
    ("The one who hears everything on this island is the Innkeeper. Stop by and listen.", "Quem ouve tudo na ilha é o Taberneiro. Passe lá e escute."),
    ("Deliver forty units of Steel to repair the cistern.", "Entregue quarenta unidades de Aço para reparar a cisterna."),
    ("The Master sent you? Then you're the newcomer they mentioned.", "O Mestre te mandou? Então você é o novato de quem falaram."),
    ("Complete the Frozen Hull and tell the Watch what you found.", "Conclua o Casco Congelado e conte ao Vigia o que encontrou."),
    ("Take these mana potions. You'll need them further on.", "Leve estas poções de mana. Vai precisar delas mais adiante."),
    ("The owlbears prowl the frozen trees too. Defeat six.", "Os owlbears também rondam as árvores geladas. Derrote seis."),
    ("Break twenty rocks to work out why the hull froze.", "Quebre vinte pedras para entender por que o casco congelou."),
    ("Scarabs surround the supply cabin. Defeat eight.", "Escaravelhos cercam a cabana de abastecimento. Derrote oito."),
    ("The Captain took a liking to you? Then the sea is your next step.", "O Capitão gostou de você? Então o mar é o seu próximo passo."),
    ("Break rock or fell tree: 60 gathers of any kind.", "Quebre pedra ou derrube árvore: 60 coletas de qualquer tipo."),
    ("Break twenty coastal veins to reinforce the Watch's shelter.", "Quebre vinte veios da costa para reforçar o abrigo do Vigia."),
    ("Create a piece of gear in Craft to prepare the outpost's defence.", "Crie um equipamento no Craft para preparar a defesa do posto."),
    ("Defeat fifteen enemies before they reach the coastal cabin.", "Derrote quinze inimigos antes que alcancem a cabana da costa."),
    ("Make one last patrol and defeat twenty enemies on the Glacier.", "Faça uma última patrulha e derrote vinte inimigos na Geleira."),
    ("Thirty Copper, counted out. The Blacksmith will be pleased.", "Trinta de Cobre, bem contados. O Ferreiro vai ficar contente."),
    ("Drive twelve enemies off the paths between the cistern and the dunes.", "Afaste doze inimigos dos caminhos entre a cisterna e as dunas."),
    ("The Tailor pays well for leather in bulk. Defeat 40 bears.", "O Alfaiate paga bem por couro em quantidade. Derrote 40 ursos."),
    ("The white tigers have come close to the shelter. Drive eight away.", "Os tigres brancos se aproximaram do abrigo. Afaste oito deles."),
    ("The whole island is still boiling. Defeat 80 beasts of any kind.", "A ilha inteira ainda ferve. Derrote 80 bichos de qualquer tipo."),
    ("Before you set foot outside the city, you need potions in your pocket.", "Antes de pisar fora da cidade, você precisa de poções no bolso."),
    ("Take 10 tier 3 wood to the northern island (follow the compass).", "Leve 10 de madeira tier 3 até a ilha do norte (siga a bússola)."),
    ("The Cartographer at the port draws the island's trails. Talk to him.", "O Cartógrafo do porto desenha as trilhas da ilha. Fale com ele."),
    ("Try refining 5 more times. Up to +5, failure only takes the material.", "Tente refinar mais 5 vezes. Até o +5 a falha só leva o material."),
    ("The boats to the other islands leave from here: ice, desert and plateau.", "Daqui saem os barcos pras outras ilhas: gelo, deserto e planalto."),
    ("Defeat one last field boss and return to the Explorer's cabin.", "Derrote um último chefe de campo e volte à cabana da Exploradora."),
    ("So you're the hero from the square. Come closer, the wind is strong here.", "Então você é o herói da praça. Chegue mais, o vento aqui é forte."),
    ("The fire on the coast cannot go out. Fell twelve trees on the Glacier.", "O fogo da costa não pode apagar. Derrube doze árvores da Geleira."),
    ("The Researcher of the Dunes studies the scarabs. Defeat ten of them.", "O Pesquisador das Dunas estuda os escaravelhos. Derrote dez deles."),
    ("Take a few potions on the house. Don't spend them all at once.", "Tome algumas poções por conta da casa. Não gaste todas de uma vez."),
    ("These larger potions will keep you standing far from home. Safe travels.", "Estas poções maiores vão te manter de pé longe de casa. Boa viagem."),
    ("Try refining a piece once at the Forge (the HUD button or the Blacksmith).", "Tente refinar 1 vez uma peça na Forja (botão do HUD ou o Ferreiro)."),
    ("Bears have come down the slope and are frightening the woodcutters. Defeat 3 bears.", "Ursos desceram a encosta e assustam os lenhadores. Derrote 3 ursos."),
    ("Break twenty rocks and look for the veins the storm turned to glass.", "Quebre vinte pedras e procure os veios vitrificados pela tempestade."),
    ("Every beast on this island carries a little copper — nobody knows why.", "Todo bicho da ilha carrega um pouco de cobre — ninguém sabe por quê."),
    ("Complete 3 dungeons, any of them. Every boss inside can drop a key.", "Conclua 3 dungeons, quaisquer. Cada chefe lá dentro pode largar chave."),
    ("Remember this: drink before you fall, not after. Now go back to the Master.", "Guarde a lição: bebe antes de cair, não depois. Agora volte ao Mestre."),
    ("Morgan's mages pull lightning from the sky into the lighthouse stones. Defeat 12.", "Magos de Morgan puxam raios do céu para as pedras do farol. Derrote 12."),
    ("The wolves prowl the trails outside the city. Defeat 6 wolves and come back here.", "Os lobos rondam as trilhas fora da cidade. Derrote 6 lobos e volte aqui."),
    ("Without potions, the woods swallow anyone. Here I sell health, mana and stamina.", "Sem poção, a mata engole qualquer um. Aqui eu vendo vida, mana e fôlego."),
    ("The smuggling is back in the cellar under the quay. Clear the Smuggler's Cellar.", "O contrabando voltou à adega sob o cais. Limpe a Adega do Contrabandista."),
    ("A map points to a legendary chest on a distant island. Open it (follow the compass).", "Um mapa aponta um baú lendário numa ilha distante. Abra-o (siga a bússola)."),
    ("Defeat twenty-five creatures on the Glacier before the trail closes again.", "Derrote vinte e cinco criaturas da Geleira antes que a trilha feche de novo."),
    ("Anyone who relies on shops won't survive the storm. Create 2 pieces of gear in Craft.", "Quem depende de loja não aguenta a tempestade. Crie 2 equipamentos no Craft."),
    ("The Provisioner of the Waste needs stone to shore up the cistern. Break ten veins.", "A Provisora do Ermo precisa de pedra para firmar a cisterna. Quebre dez veios."),
    ("Morgan's gunmen are camped in the woods. Defeat 12 and put out their fires.", "Pistoleiros de Morgan acampam na mata. Derrote 12 e apague as fogueiras deles."),
    ("Go talk to the Alchemist — the shop with the green awning. Tell him I sent you.", "Vá falar com o Alquimista — a loja de toldo verde. Diga que fui eu que mandei."),
    ("The Guardian of the Forest found tiger tracks. Defeat eight white tigers.", "A Guardiã da Floresta encontrou pegadas de tigres. Derrote oito tigres brancos."),
    ("The village forge is out of dark metal. Bring 150 Darksteel — it comes out of the rocks.", "A forja da vila está sem metal escuro. Traga 150 de Darksteel — sai das pedras."),
    ("The Tailor weaves with thread that holds the wind. Ask whether he'll sew for you.", "O Alfaiate tece com fios que seguram o vento. Pergunte se ele costura para você."),
    ("The Bear Scout needs fifty units of Steel to reinforce the cabin.", "O Batedor dos Ursos precisa de cinquenta unidades de Aço para reforçar a cabana."),
    ("Defeat a field boss on the Glacier. Other adventurers nearby count too.", "Derrote um chefe de campo da Geleira. Outros aventureiros próximos também contam."),
    ("Glacier owlbears have crossed the frozen sea and prowl the island's heights. Defeat 5.", "Owlbears da Geleira atravessaram o mar gelado e rondam o alto da ilha. Derrote 5."),
    ("The Explorer heard the Mother of Blizzards on the mountain. Defeat ten enemies on the way.", "A Exploradora ouviu a Mãe-da-Nevasca na montanha. Derrote dez inimigos no caminho."),
    ("The village wall needs reinforcing before the next storm. Bring 60 Steel.", "A muralha da vila precisa de reforço antes da próxima tempestade. Traga 60 de Aço."),
    ("That wasn't enough. Defeat 60 enemies — the zones marked on the map pay more per minute.", "Não bastou. Derrote 60 inimigos — as zonas marcadas no mapa rendem mais por minuto."),
    ("The Morganeers are back in the Shipwreck Cellar. Clear it again (Dungeons, in the Menu).", "Os Morganeers voltaram ao Porão do Naufrágio. Limpe-o outra vez (Dungeons, no Menu)."),
    ("The Appraiser reads what the lighthouse stones carry. Take him what you heard on the quay.", "O Identificador lê o que as pedras do farol carregam. Leve a ele o que ouviu no cais."),
    ("When you're ready, the sea is waiting for you. Tell the Master the port is open.", "Quando estiver pronto, o mar espera por você. Diga ao Mestre que o porto está aberto."),
    ("The Blacksmith says an unrefined piece is half a piece. Try refining 3 times at the Forge.", "O Ferreiro diz que peça sem refino é peça pela metade. Tente refinar 3 vezes na Forja."),
    ("Head to the craft station and forge the T1 weapon of your choice with Matteo's materials.", "Va ate a estacao de craft e forje a arma T1 da sua escolha com os materiais do Matteo."),
    ("The Trainer keeps four Grey Claws for off-hands. Defeat 6 wolves on the trail.", "O Treinador guarda quatro Garras Cinzas para as secundárias. Derrote 6 lobos da trilha."),
    ("Destroy the outer garrison of the Iron Fortress by wiping out 25 Royal Armada soldiers.", "Destrua a guarnição externa da Fortaleza de Ferro eliminando 25 soldados da Armada Real."),
    ("The Walrus Watch needs help keeping the shelter. Bring down five walruses on the beach.", "O Vigia das Morsas precisa de ajuda para manter o abrigo. Derrube cinco morsas da praia."),
    ("The blacksmith needs ore to forge defensive weapons. Bring 10 T1 Iron Ore.", "O ferreiro precisa de minério para forjar armas de defesa. Traga 10 Minérios de Ferro T1."),
    ("The Master keeps a Green Leather for your first T2 armour. Break 20 rocks on the Glacier.", "O Mestre guarda um Couro Verde para sua primeira armadura T2. Quebre 20 pedras na Geleira."),
    ("Sabotage the enemy's operations by wiping out 20 volcanic creatures deep in the mines.", "Sabote as operações inimigas eliminando 20 criaturas vulcânicas nas profundezas das minas."),
    ("Defeat 30 ghost sailors haunting the eastern mists to cleanse the path.", "Derrote 30 marinheiros fantasmas que assombram as brumas do leste para purificar o caminho."),
    ("The Blacksmith set aside four Grey Scales: one for each weapon in the workshop. Bring 30 Copper.", "O Ferreiro separou quatro Escamas Cinzas: uma para cada arma da oficina. Traga 30 de Cobre."),
    ("The Master keeps a Green Scale for your first T2 weapon. Defeat 20 enemies on the Glacier.", "O Mestre guarda uma Escama Verde para sua primeira arma T2. Derrote 20 inimigos na Geleira."),
    ("The village already tells stories about you. Defeat 5 more field bosses and the legend becomes true.", "A vila já conta histórias sobre você. Derrote mais 5 chefes de campo e a lenda vira verdade."),
    ("Reach the summit of the Temple of Tides mountain at the heart of the Maelstrom to consecrate the quest.", "Alcance o topo da montanha do Templo das Marés no centro do Maelstrom para consagrar a busca."),
    ("Face the mutant sea monsters in the deep mists and defeat 15 elite creatures.", "Confronte os monstros marinhos mutantes nas brumas profundas e derrote 15 criaturas de elite."),
    ("Defeat 10 thugs from the Armada's corrupt garrison who are terrorising the port beach.", "Derrote 10 capangas da guarnição corrupta da Armada que estão aterrorizando a praia do porto."),
    ("Defeat 15 magma guardians and recover the Ring of Black Ignition and the second map fragment.", "Derrote 15 guardiões de magma e recupere o Anel da Ignição Negra e o segundo fragmento do mapa."),
    ("Infiltrate the dungeons and reach the cell where the royal historian is held (follow the compass).", "Infiltre-se nas masmorras e alcance a cela onde o historiador real está preso (siga a bússola)."),
    ("Take 10 T1 Wood to the outpost on the island to the east (follow the compass to the marked area).", "Leve 10 Madeiras T1 para o posto avançado na ilha a leste (siga a bússola até a área indicada)."),
    ("The Elder Bear has slept on that slope since before the village. The thunder woke him in a foul mood. Defeat him.", "O Urso Ancião dorme na encosta desde antes da vila. O trovão o acordou de mau humor. Derrote-o."),
    ("Every journey starts with potions in your pocket. Talk to the Alchemist, at the door of the green-awning shop.", "Toda jornada começa com poções no bolso. Fale com o Alquimista, na porta da loja de toldo verde."),
    ("The Tailor set aside three Grey Leathers, one for each armour. Drive 3 bears off the village road.", "O Alfaiate reservou três Couros Cinzas, um para cada armadura. Afaste 3 ursos da estrada da vila."),
    ("Sail through the blockading fleet and carry the wounded historian to the safe island to the north.", "Navegue através da frota de bloqueio e transporte o historiador ferido até a ilha segura ao norte."),
    ("Head to the arena (to the east) and defeat 3 enemies with your new weapon. It'll give you the XP to level up!", "Va ate a arena (a leste) e derrote 3 inimigos com sua arma nova. Vai te dar XP pra subir de nivel!"),
    ("Gather 15 T2 Iron Ore on the volcano's slopes to forge shields against the heat.", "Colete 15 Minérios de Ferro T2 nas encostas do vulcão para forjar escudos de proteção contra calor."),
    ("Rock gives quintessence a drop at a time; tigers give far more. Bring 6 — without it no armour closes.", "A pedra dá quintessência a conta-gotas; tigre dá bem mais. Traga 6 — sem ela nenhuma armadura fecha."),
    ("The more trees around you, the faster it comes. Gather 5 Wood and DELIVER it to Matteo (talk to him).", "Quanto mais arvore em volta, mais rapido vem. Junte 5 Madeiras e ENTREGUE pro Matteo (fale com ele)."),
    ("The island is far too crowded. Defeat 30 enemies, any species — look for the dense patches on the map.", "A ilha está cheia demais. Derrote 30 inimigos, de qualquer espécie — procure as manchas densas no mapa."),
    ("Take on the Royal Armada's elite fleet by defeating 35 of their best fighters in the Central Abyss.", "Enfrente a frota de elite da Armada Real derrotando 35 dos seus melhores combatentes no Abismo Central."),
    ("The Appraiser offers four Grey Horns for accessories. Break 8 rocks and bring back whatever you find.", "O Identificador oferece quatro Chifres Cinzas para os acessórios. Quebre 8 pedras e traga o que encontrar."),
    ("The Banker knows what comes in and out of the port — money tells everything. Ask him about Morgan's ships.", "O Banqueiro sabe o que entra e sai do porto — o dinheiro conta tudo. Pergunte a ele pelos barcos de Morgan."),
    ("The Blacksmith needs metal for the village's tools. Bring 30 Copper — every beast on the island carries a little.", "O Ferreiro precisa de metal pras ferramentas da vila. Traga 30 de Cobre — todo bicho da ilha carrega um pouco."),
    ("Storm the fort's beach and defeat 15 soldiers of the Royal Armada of the Sun who hold the first map fragment.", "Invada a praia do forte e derrote 15 soldados da Armada Real do Sol que controlam o primeiro fragmento do mapa."),
    ("Sail the misted sea and gather 20 T4 leathers to prepare sails that resist the damp of the ship graveyard.", "Navegue no mar enevoado e colete 20 couros T4 para preparar velas resistentes à umidade do cemitério de navios."),
    ("The Royal Armada has blockaded the port. Talk to the fishermen and help by gathering 15 Wood to repair the barricades.", "A Armada Real bloqueou o porto. Fale com os pescadores e ajude coletando 15 Madeiras para reparar as barricadas."),
    ("Face and wipe out the elite generals of Admiral Vane's final garrison and recover the Heart of the Storm.", "Confronte e elimine os generais de elite da guarnição final do Almirante Vane e recupere o Coração da Tempestade."),
    ("Wipe out 12 hostile creatures on the beach to clear the smuggling caves and recover the first Ring of the Abyss.", "Elimine 12 criaturas hostis na praia para limpar as cavernas de contrabando e recuperar o primeiro Anel do Abismo."),
    ("The Harbour Captain wants to meet whoever protects the island. Follow the road to the quay (M opens the map) and talk to him.", "O Capitão do Porto quer conhecer quem protege a ilha. Siga pela estrada até o cais (M abre o mapa) e fale com ele."),
    ("Captain Stormbeard has landed with his crew and planted a flag on the island. Bring him down and the port breathes again.", "O Capitão Barba-Tormenta desembarcou com a tripulação e fincou bandeira na ilha. Derrube-o e o porto volta a respirar."),
    ("Gathering is automatic: no tool, no clicking. Just stand near the trees until the first Wood drops.", "Coleta e' automatica: nao precisa de ferramenta nem clique. Fique parado perto das arvores ate a primeira Madeira cair."),
    ("Walk into the rock holding the direction to JUMP over it, then talk to Matteo (get close and press E / tap him).", "Ande contra a pedra segurando a direcao pra PULAR por cima dela, e fale com Matteo (chegue perto e aperte E / toque nele)."),
    ("The three bosses of the Grove come back after a while. Defeat 3 field bosses — any of them, as many times as you need.", "Os três chefes do Bosque voltam depois de um tempo. Derrote 3 chefes de campo — qualquer um deles, quantas vezes precisar."),
    ("Inside the rock there's a dark metal that doesn't rust: Darksteel. Every piece asks for 200 of it. Bring 20 so the Blacksmith can judge the quality of the vein here.", "Dentro da pedra há um metal escuro que não enferruja: Darksteel. Toda peça pede 200 dele. Traga 20 para o Ferreiro ver a qualidade do veio daqui."),
    ("Open Menu › Quests. Pick this quest from the list and tap Do. Then, out in the world, use Take to gather several quests before using Go or Do all.", "Abra Menu › Missões. Escolha esta missão na lista e toque Fazer. Depois, no mundo, use Pegar para juntar várias missões antes de usar Ir ou Fazer tudo."),
    ("The quay lost half a pier in the storm and the Captain needs wood. Fell 8 trees — it's the only place wood comes from, and nobody had told you.", "O cais perdeu meio píer na tempestade e o Capitão precisa de madeira. Derrube 8 árvores — é o único lugar de onde sai madeira, e ninguém tinha te dito."),
    ("One last piece of the recipe is missing: the charm the owlbears carry tangled in their fur. Bring 6 and the Master opens the village chest — and lets out the cub that's been prowling around the storehouse.", "Falta a última peça da receita: o berloque, que os owlbears carregam preso ao pelo. Traga 6 e o Mestre abre o baú da vila — e solta o filhote que anda rondando o depósito."),
    ("The Shipwreck Cellar keeps what the tide didn't take, and whoever rules down there falls with the key in his pocket: a dungeon boss drops keys three times as often as a field boss. Go in and clear one — solo is enough.", "O Porão do Naufrágio guarda o que a maré não levou, e quem manda lá dentro cai com a chave no bolso: chefe de dungeon larga chave três vezes mais que chefe de campo. Entre e limpe uma — sozinho já dá."),
    ("A wolf the size of a horse leads the pack in the glade. Defeat the Alpha Wolf of the Glade — the map marks where he prowls. Bring someone: bosses are fought in a party, and everyone who fights nearby counts.", "Um lobo do tamanho de um cavalo lidera a matilha da clareira. Derrote o Lobo Alfa da Clareira — o mapa marca onde ele ronda. Chame alguém: chefe se enfrenta em grupo, e todos que lutarem perto contam."),
    ("Meet the Alchemist", "Conheça o Alquimista"),
    ("Wolves on the road", "Lobos na estrada"),
    ("The lookout of the Grove", "O mirante do Bosque"),
];
