//! Server: the notices that arrive over the protocol and the text the server builds.

pub const VERBETES: &[(&str, &str)] = &[
    // ─────────────────────────── servidor: correio oficial ───────────────────────────
    ("Invalid letter.", "Carta inválida."),
    ("Staff · {} ({})", "Equipe · {} ({})"),
    ("Attachments received and saved.", "Anexos recebidos e salvos."),
    ("This letter has no attachments.", "Esta carta não tem anexos."),
    ("Letter already claimed or unavailable.", "Carta já resgatada ou indisponível."),
    ("This claim is already being processed.", "Este resgate já está sendo processado."),
    ("Free up space in your bag and try again.", "Libere espaço na bolsa e tente novamente."),
    (
        "Carta indisponível. Receba os anexos antes de apagar.",
        "Letter unavailable. Claim the attachments before deleting.",
    ),
    (
        "Não foi possível concluir o resgate. Tente novamente.",
        "The claim could not be completed. Try again.",
    ),
    // ────────────────────────────── servidor: craft e loja ──────────────────────────────
    ("bag full", "bolsa cheia"),
    ("requires level {}", "requer nível {}"),
    ("{} copper short", "faltam {} de cobre"),
    ("this item cannot be upgraded", "este item não se aprimora"),
    ("requires level {} for that colour", "requer nível {} para essa cor"),
    ("only gear can be upgraded", "só peça de equipamento se aprimora"),
    ("choose two different pieces from your bag", "escolha duas peças diferentes da bolsa"),
    ("bag too full for that batch", "bolsa cheia pra esse lote"),
    ("choose from 1 to {MAX_LOTE}", "escolha de 1 a {MAX_LOTE}"),
    ("{} copper short ({} per unit)", "faltam {} de cobre ({} por unidade)"),
    ("{valor} TP", "{valor} TP"),
    ("{vezes}x ", "{vezes}x "),
    ("Purchase refused.", "Compra recusada."),
    ("Invalid order.", "Pedido inválido."),
    ("+{} TP credited.", "+{} TP creditados."),
    ("Payment refused.", "Pagamento recusado."),
    ("Order not found.", "Pedido não encontrado."),
    ("{quantos} is yours!{abatido}", "{quantos} é seu!{abatido}"),
    ("This purchase has already been delivered.", "Esta compra já foi entregue."),
    ("This purchase has already been credited.", "Esta compra já foi creditada."),
    ("{quantos} bought!{abatido}", "{quantos} comprado!{abatido}"),
    ("Payment awaiting confirmation.", "Pagamento aguardando confirmação."),
    ("Payment unavailable right now.", "Pagamento indisponível no momento."),
    ("{quantos} delivered to your bag!{abatido}", "{quantos} entregue na bolsa!{abatido}"),
    // ──────────────────────────────── servidor: mercado ────────────────────────────────
    ("Listing cancelled.", "Anúncio cancelado."),
    ("bought TP on the market", "comprou TP no mercado"),
    ("listed TP on the market", "anunciou TP no mercado"),
    ("cancelled a TP listing", "cancelou anúncio de TP"),
    ("Listing not found.", "Anúncio não encontrado."),
    ("Listing refused: {nome}", "Anúncio recusado: {nome}"),
    ("Listing cancelled: {nome}", "Anúncio cancelado: {nome}"),
    ("Bought on the market: {nome}", "Comprado no mercado: {nome}"),
    ("Sale: {nome} ×{} (fee {})", "Venda: {nome} ×{} (taxa {})"),
    ("The listing is no longer active.", "O anúncio já não está ativo."),
    ("{} {nome} comes back in Deliveries.", "{} {nome} volta em Entregas."),
    ("The purchase didn't go through: gold refunded", "Compra não fechou: gold devolvido"),
    (
        "Comprado: {nome} ×{}. Receba em Entregas.",
        "Bought: {nome} ×{}. Claim it in Deliveries.",
    ),
    (
        "Anúncio cancelado: {restante} TP de volta.",
        "Listing cancelled: {restante} TP back.",
    ),
    (
        "Anunciado: {qtd} TP a {preco_unit} gold cada.",
        "Listed: {qtd} TP at {preco_unit} gold each.",
    ),
    (
        "Anunciado: {nome} ×{qtd} a {preco_unit} gold cada.",
        "Listed: {nome} ×{qtd} at {preco_unit} gold each.",
    ),
    (
        "Pergaminho de Teleporte retirado: reembolso em cobre",
        "Teleport Scroll withdrawn: refunded in copper",
    ),
    (
        "Anúncio cancelado: {nome} ×{restante} volta em Entregas.",
        "Listing cancelled: {nome} ×{restante} comes back in Deliveries.",
    ),
    // ────────────────────────── servidor: sala de dungeon ──────────────────────────
    ("The room is full.", "A sala está cheia."),
    ("Only the leader can start.", "Só o líder começa."),
    ("The room is starting.", "A sala está começando."),
    ("The room no longer exists.", "A sala não existe mais."),
    ("You are not in a room.", "Você não está numa sala."),
    ("The ready check is already open.", "O pronto-check já está aberto."),
    ("Answer the ready check first.", "Responda o pronto-check antes."),
    // ─────────────────────────────── servidor: morte ───────────────────────────────
    ("You need {c} gold.", "Precisa de {c} de ouro."),
    (
        "Essa morte não pode mais ser recuperada.",
        "That death can no longer be recovered from.",
    ),
    ("in combat", "em combate"),
    // ───────────────────────── servidor: o mundo e seus avisos ─────────────────────────
    ("the pet", "o pet"),
    ("The bag", "A bolsa"),
    ("The bank", "O banco"),
    ("Your pet", "Seu pet"),
    ("the beast", "o bicho"),
    ("[STRONGHOLD] {}", "[FORTE] {}"),
    ("internal error", "erro interno"),
    ("invalid weapon", "arma invalida"),
    (" (it was {} and {})", " (era {} e {})"),
    ("it is already at +{}", "já está no +{}"),
    ("invalid trade", "troca inválida"),
    ("Magic Merchant", "Mercador Mágico"),
    ("raised their shield", "ergueu o escudo"),
    ("invalid session", "sessao invalida"),
    ("Captain Morganeer", "Capitão Morganeer"),
    ("not enough gold", "ouro insuficiente"),
    ("Reach level 20", "Alcance o nível 20"),
    ("Wandering Alchemist", "Alquimista Errante"),
    ("Peacemain Guardian", "Guardião Peacemain"),
    ("auth unavailable", "auth nao disponivel"),
    ("character not authorised", "char nao autorizado"),
    ("character not found", "char nao encontrado"),
    ("invalid quantity", "quantidade inválida"),
    (" (unlocks at \"{t}\")", " (libera em \"{t}\")"),
    ("[/who] {} online: {}", "[/who] {} online: {}"),
    ("unknown recipe", "receita desconhecida"),
    ("[/who] nobody online", "[/who] ninguém online"),
    ("[Pet] {} learned {}.", "[Pet] {} aprendeu {}."),
    ("invalid shop item", "item de loja inválido"),
    ("Keep at it, sailor.", "Continua firme, marujo."),
    ("There is no path there.", "Não há caminho até ali."),
    ("You set sail for {}.", "Você embarca rumo a {}."),
    ("[Pet] {nome} already has {}.", "[Pet] {nome} já tem {}."),
    ("too far from the vendor", "longe demais do vendedor"),
    ("The party invite expired.", "Convite de grupo expirou."),
    ("[Pet] {nome} learned {}.", "[Pet] {nome} aprendeu {}."),
    ("you are being carried", "voce esta sendo carregado"),
    ("Gathering: get closer.", "Coleta: chegue mais perto."),
    ("Party full (5 players).", "Grupo cheio (5 jogadores)."),
    ("It is already at maximum size.", "Já está no tamanho máximo."),
    ("[Pet] Equip a pet first.", "[Pet] Equipe um pet antes."),
    ("This piece asks for level {req}.", "Esta peça pede nível {req}."),
    ("Story: \"{}\" completed.", "História: \"{}\" concluída."),
    ("You already have that appearance.", "Você já tem essa aparência."),
    ("invalid inventory slot", "slot de inventário inválido"),
    ("not enough Magic Coins", "Moedas Mágicas insuficientes"),
    ("Bag full — gathering paused.", "Bolsa cheia — coleta pausada."),
    (" (that was the creature's affinity)", " (era a afinidade da criatura)"),
    ("[Potion] {} on cooldown: {:.1} s", "[Poção] {} em recarga: {:.1} s"),
    ("the account is connected somewhere else", "conta conectada em outro lugar"),
    ("confirm your e-mail to sign in", "confirme seu e-mail para entrar"),
    ("that piece cannot be refined", "essa peça não pode ser refinada"),
    ("Get closer to talk.", "Chegue mais perto pra conversar."),
    ("Player combat happens on foot.", "Combate contra jogadores é a pé."),
    ("Bought for {price} {moeda}.", "Comprado por {price} de {moeda}."),
    ("Experience recovered (free).", "Experiência recuperada (grátis)."),
    ("{} gold short to make it bigger.", "Faltam {} de ouro para aumentar."),
    ("Too far to walk from here.", "Longe demais para ir a pé daqui."),
    ("The character is not on this channel.", "Personagem não está neste canal."),
    ("bag too full to receive the trade", "bolsa cheia para receber a troca"),
    ("[Pet] {nome} reached level {n}.", "[Pet] {nome} chegou ao nível {n}."),
    ("[Pet] That pet already knows the skill.", "[Pet] Esse pet já conhece a skill."),
    ("weekly cap: {} Seals per account", "teto da semana: {} Selos por conta"),
    ("The story cannot be abandoned.", "A história não pode ser abandonada."),
    ("That player already has a pending invite.", "Jogador já tem um convite pendente."),
    ("{target_name} is not on this channel.", "{target_name} não está neste canal."),
    ("gear is bought one piece at a time", "equipamento se compra um de cada vez"),
    ("[Pet] That pet has no skill at all.", "[Pet] Esse pet não tem skill nenhuma."),
    ("inventory too full for the items bought", "inventário cheio pros itens comprados"),
    ("that quantity is not in your inventory", "quantidade indisponível no inventário"),
    ("needs {ds} Darksteel and {cu} Copper", "precisa de {ds} Darksteel e {cu} Cobre"),
    ("Party invite sent (60 seconds).", "Convite de grupo enviado (60 segundos)."),
    ("Story: \"{}\" completed. Next: {}", "História: \"{}\" concluída. Próximo: {}"),
    ("use the Magic Merchant's trade shop", "use a loja de trocas do Mercador Mágico"),
    ("The story hasn't reached {passo} yet.", "A história ainda não chegou a {passo}."),
    ("You opened the chest and found the relic!", "Você abriu o baú e encontrou a relíquia!"),
    ("[Affinity] {nome} now gives {} and {de}.", "[Afinidade] {nome} agora dá {} e {de}."),
    ("[Salvage] Materials recovered: {}.", "[Desmantelar] Materiais recuperados: {}."),
    ("[Pet] That skill slot is not free.", "[Pet] Esse slot de skill não está livre."),
    ("{} daily quest(s) expired when the day turned over.", "{} diária(s) expiraram na virada do dia."),
    ("This representative does not serve your faction.", "Este representante não atende sua facção."),
    ("Party full, or the invite is no longer valid.", "Grupo cheio ou convite não é mais válido."),
    ("{falta} Energy short for this point", "faltam {falta} de Energia para este ponto"),
    ("{nome} unlocked — check your wardrobe.", "{nome} destravado — veja no guarda-roupa."),
    ("[Pet] {nome}'s skills were removed.", "[Pet] As skills de {nome} foram removidas."),
    ("You bought {qtd}x {nome} for {total} copper.", "Comprou {qtd}x {nome} por {total} de cobre."),
    ("Dungeon full, try again in a moment", "Dungeon cheia, tente novamente em instantes"),
    ("Experience recovered for {custo} gold.", "Experiência recuperada por {custo} de ouro."),
    ("{} {moeda} short ({price} per unit).", "Faltam {} de {moeda} ({price} por unidade)."),
    ("Objective met: go back to the Quest Master.", "Missão cumprida: volte ao Mestre de Missões."),
    ("You lost weapon proficiency when you died.", "Você perdeu proficiência em armas ao morrer."),
    (
        "Bolsa cheia: {qtd} de cobre foi pras Entregas.",
        "Bag full: {qtd} copper went to your Deliveries.",
    ),
    (
        "{} agora tem {tam} espaços (−{custo} de ouro).",
        "{} now has {tam} slots (−{custo} gold).",
    ),
    (
        "Jogador já está em grupo ou em outra instância.",
        "That player is already in a party or in another instance.",
    ),
    (
        "[Afinidade] Equipe um pet ou uma montaria antes.",
        "[Affinity] Equip a pet or a mount first.",
    ),
    (
        "[Pet] O primeiro slot de skill abre no nível {}.",
        "[Pet] The first skill slot opens at level {}.",
    ),
    (
        "[Invocação] Você não tem pergaminhos suficientes.",
        "[Summoning] You don't have enough scrolls.",
    ),
    (
        "Fale com o Capitão do Porto, no cais, para embarcar.",
        "Talk to the Harbour Captain, on the quay, to set sail.",
    ),
    (
        "Cuidado, marujo! Derrota aquele inimigo ali primeiro.",
        "Careful, sailor! Take down that enemy over there first.",
    ),
    (
        "Recebeu {receber}x {nome} por {total} Moedas Mágicas.",
        "You received {receber}x {nome} for {total} Magic Coins.",
    ),
    (
        "Rota indisponível no momento: {onde} está fora do ar.",
        "That route is unavailable right now: {onde} is offline.",
    ),
    (
        "[Desmantelar] Falta espaço na bolsa para os materiais.",
        "[Salvage] Not enough room in your bag for the materials.",
    ),
    (
        "{}: entregue ao Mestre de Missões, na praça da cidade.",
        "{}: turn it in to the Quest Master, in the city square.",
    ),
    (
        "[Desmantelar] Essa peça não possui receita recuperável.",
        "[Salvage] That piece has no recoverable recipe.",
    ),
    (
        "Equipa o machado pelo inventario que ai a gente continua.",
        "Equip the axe from your inventory and then we carry on.",
    ),
    (
        "[Invocação] {no_correio} prêmio(s) foram para as Entregas.",
        "[Summoning] {no_correio} prize(s) went to your Deliveries.",
    ),
    (
        "[Pet] {nome} chegou ao nível {n} — um slot de skill abriu!",
        "[Pet] {nome} reached level {n} — a skill slot opened!",
    ),
    (
        "[Afinidade] Pra rolar a montaria, tire o pet do slot antes.",
        "[Affinity] To reroll the mount, take the pet out of the slot first.",
    ),
    (
        "O baú está trancado. Aceite a Caça ao tesouro com um morador.",
        "The chest is locked. Take the Treasure Hunt from a resident.",
    ),
    (
        "[Desmantelar] Só peças com atributos podem ser desmanteladas.",
        "[Salvage] Only pieces with attributes can be salvaged.",
    ),
    (
        "[Pet] Todos os slots abertos estão ocupados. Use o Removedor.",
        "[Pet] Every open slot is taken. Use the Remover.",
    ),
    (
        "O banco fica com a Banqueira da cidade ou o Banqueiro do porto.",
        "The bank is with the Banker in the city or the Banker at the port.",
    ),
    (
        "A escritura é sua: fale com o Capitão do Porto e peça MINHA ILHA.",
        "The deed is yours: talk to the Harbour Captain and ask for MY ISLAND.",
    ),
    (
        "[Sistema] Todos os mobs despawnados. Spawn zones reabastecendo...",
        "[System] Every mob despawned. Spawn zones refilling...",
    ),
    (
        "Aumente o banco com a Banqueira da cidade ou o Banqueiro do porto.",
        "Expand the bank with the Banker in the city or the Banker at the port.",
    ),
    (
        "[Pet] Todos os pets equipados comeram. Alimentados por mais {} min.",
        "[Pet] Every equipped pet has eaten. Fed for another {} min.",
    ),
    (
        "Ainda falta madeira. Fica perto das arvores ate juntar 5 e volta aqui.",
        "Still short on wood. Stay near the trees until you have 5, then come back.",
    ),
    (
        "O Pergaminho de Teleporte foi retirado. Use a montaria e as rotas do mapa.",
        "The Teleport Scroll has been withdrawn. Use your mount and the map's routes.",
    ),
    (
        "\"{titulo}\" belongs to the island {ilha}. Sail there with the Harbour Captain to continue it.",
        "\"{titulo}\" é da ilha {ilha}. Embarque com o Capitão do Porto para continuar.",
    ),
    (
        "\"{titulo}\" is done: hand it in to {quem}, who is not on this island.",
        "\"{titulo}\" está pronta: entregue a {quem}, que não está nesta ilha.",
    ),
    (
        "\"{titulo}\": {quem} does not live on this island. Look for them in another island's village.",
        "\"{titulo}\": {quem} não mora nesta ilha. Procure na vila de outra ilha.",
    ),
    (
        "\"{titulo}\": no boss of this kind lives on this island. Check the map on the other islands.",
        "\"{titulo}\": nenhum chefe desse tipo vive nesta ilha. Confira o mapa das outras ilhas.",
    ),
    (
        "\"{titulo}\": no {bicho} lives on this island.",
        "\"{titulo}\": nenhum {bicho} vive nesta ilha.",
    ),
    (
        "\"{titulo}\": no {bicho} lives on this island. Found on: {onde}.",
        "\"{titulo}\": nenhum {bicho} vive nesta ilha. Encontrado em: {onde}.",
    ),
    (
        "\"{titulo}\": nothing on this island drops {item}.",
        "\"{titulo}\": nada nesta ilha dropa {item}.",
    ),
    (
        "\"{titulo}\": nothing on this island drops {item}. Hunt on: {onde}.",
        "\"{titulo}\": nada nesta ilha dropa {item}. Cace em: {onde}.",
    ),
    (
        "\"{titulo}\": every node that gives {item} is exhausted right now. Wait a little for them to grow back.",
        "\"{titulo}\": todo recurso que dá {item} está esgotado agora. Espere um pouco até renascerem.",
    ),
    (
        "\"{titulo}\": {item} cannot be hunted or gathered on this island.",
        "\"{titulo}\": {item} não se caça nem se coleta nesta ilha.",
    ),
    (
        "\"{titulo}\": every node on this island is exhausted right now. Wait a little for them to grow back.",
        "\"{titulo}\": todos os recursos desta ilha estão esgotados agora. Espere um pouco até renascerem.",
    ),
    (
        "\"{titulo}\": that place is not on this island.",
        "\"{titulo}\": esse lugar não fica nesta ilha.",
    ),
    (
        "whoever gave it",
        "quem a deu",
    ),
    (
        "Story: this step happens on {ilha}. Set sail with the Harbour Captain.",
        "História: este passo acontece na ilha {ilha}. Embarque com o Capitão do Porto.",
    ),
    (
        "Story: this step happens in {ilha}. The Submarine Captain dives there from the Docks.",
        "História: este passo acontece em {ilha}. O Capitão do Submarino mergulha até lá a partir das Docas.",
    ),
    (
        "\"{titulo}\" happens in {ilha}. The Submarine Captain dives there from the Docks.",
        "\"{titulo}\" acontece em {ilha}. O Capitão do Submarino mergulha até lá a partir das Docas.",
    ),
    (
        "Story: this step happens in {ilha}. Go to Kōgen-tō and take the submarine from its Docks.",
        "História: este passo acontece em {ilha}. Vá a Kōgen-tō e pegue o submarino nas Docas.",
    ),
    (
        "\"{titulo}\" happens in {ilha}. Go to Kōgen-tō and take the submarine from its Docks.",
        "\"{titulo}\" acontece em {ilha}. Vá a Kōgen-tō e pegue o submarino nas Docas.",
    ),
    (
        "Story: this step happens on {ilha}. The Sky Bus Professor flies there from the Throne of the Sky.",
        "História: este passo acontece em {ilha}. O Professor do Ônibus Celeste voa até lá a partir do Trono do Céu.",
    ),
    (
        "\"{titulo}\" happens on {ilha}. The Sky Bus Professor flies there from the Throne of the Sky.",
        "\"{titulo}\" acontece em {ilha}. O Professor do Ônibus Celeste voa até lá a partir do Trono do Céu.",
    ),
    (
        "Story: this step happens on {ilha}. Sail to Skyreach and take the Sky Bus from the Throne of the Sky.",
        "História: este passo acontece em {ilha}. Navegue até Skyreach e pegue o Ônibus Celeste no Trono do Céu.",
    ),
    (
        "\"{titulo}\" happens on {ilha}. Sail to Skyreach and take the Sky Bus from the Throne of the Sky.",
        "\"{titulo}\" acontece em {ilha}. Navegue até Skyreach e pegue o Ônibus Celeste no Trono do Céu.",
    ),
    (
        "\"{titulo}\" happens on {ilha}. Set sail with the Harbour Captain.",
        "\"{titulo}\" acontece na ilha {ilha}. Embarque com o Capitão do Porto.",
    ),
    (
        "Reach level 20 before sailing for the Glacier. Do the side quests in the Grove.",
        "Alcance o nível 20 antes de embarcar para a Geleira. Faça as missões secundárias do Bosque.",
    ),
    (
        "Otimo! Aqui, leva esse material. Vai na estacao de craft e forja a arma T1 que voce quiser.",
        "Good work! Here, take this material. Head to the craft station and forge whichever T1 weapon you like.",
    ),
    (
        "Vai na estacao de craft (a bigorna/bancada ali) e forja sua arma. Os materiais ja sao seus.",
        "Head to the craft station (the anvil/bench over there) and forge your weapon. The materials are already yours.",
    ),
    (
        "Abre Menu > Missoes, escolhe Aprenda a fazer missoes e toca Fazer. Depois podes pegar varias no menu e usar Fazer tudo.",
        "Open Menu > Quests, pick Learn how quests work and tap Do. After that you can take several from the menu and use Do all.",
    ),
    (
        "Boa, pulou a pedra direitinho! Nao precisa de machado nem de nada: fica parado perto daquelas arvores que a madeira vem sozinha. Me traz 5.",
        "Nice, you cleared that rock! You don't need an axe or anything: just stand near those trees and the wood comes on its own. Bring me 5.",
    ),
    (
        "Antes de zarpar, aprende as missoes: abre Menu > Missoes, escolhe Aprenda a fazer missoes na lista e toca Fazer. Mais tarde, Pegar so aceita; usa Fazer tudo quando quiser partir.",
        "Before you sail, learn how quests work: open Menu > Quests, pick Learn how quests work from the list and tap Do. Later on, Take only accepts; use Do all when you want to set off.",
    ),
    (
        "Sem espaco acessivel fora da zona segura.",
        "No reachable space outside the safe zone.",
    ),
    // ─────────────────────────────── server: the colony ───────────────────────────────
    ("From the chest: {}.", "Do baú: {}."),
    ("{} has left.", "{} foi embora."),
    ("The chest is empty.", "O baú está vazio."),
    ("{nome} upgraded.", "{nome} melhorado."),
    ("That trade does not exist.", "Esse ofício não existe."),
    ("This track is already at maximum.", "Este eixo já está no máximo."),
    ("You don't have an island yet.", "Você ainda não tem uma ilha."),
    ("{} has moved to your island.", "{} mudou-se para a sua ilha."),
    ("Not enough material for this upgrade.", "Falta material para esta melhoria."),
    ("Your bag is full: nothing left the chest.", "A bolsa está cheia: nada saiu do baú."),
    (
        "Colheita de {horas:.0}h, no baú da ilha: {}.",
        "{horas:.0}h of harvest, into the island chest: {}.",
    ),
    (
        "A ilha ainda não rendeu nada. Volte mais tarde.",
        "The island hasn't yielded anything yet. Come back later.",
    ),
    (
        "Do baú: {}. Ficaram {n} pilha(s) — a bolsa encheu.",
        "From the chest: {}. {n} stack(s) stayed behind — your bag filled up.",
    ),
    (
        "O baú da ilha está cheio. Retire o que há nele primeiro.",
        "The island chest is full. Take what's in it out first.",
    ),
    (
        "Não há casa para mais ninguém. Suba o Assentamento primeiro.",
        "There is no house for anyone else. Raise the Settlement first.",
    ),
    (
        "Ninguém mora aqui ainda. Suba o Assentamento e contrate alguém.",
        "Nobody lives here yet. Raise the Settlement and hire someone.",
    ),
    (
        "Colheita de {horas:.0}h no baú: {}. O resto não caibe — o baú está cheio.",
        "{horas:.0}h of harvest into the chest: {}. The rest doesn't fit — the chest is full.",
    ),
    // ───────────────────────────── servidor: dungeon e arena ─────────────────────────────
    ("Chest · {}", "Baú · {}"),
    ("Bag full.", "Bolsa cheia."),
    ("Guardian of the Cavern", "Guardião da Gruta"),
    ("Get up first.", "Levante-se antes."),
    ("{} gold short.", "Faltam {} de ouro."),
    ("Revive in {:.0} s.", "Reviver em {:.0} s."),
    ("You leave the Arena.", "Você deixa a Arena."),
    ("Get close to the chest.", "Chegue perto do baú."),
    ("You left the dungeon.", "Você saiu da dungeon."),
    ("You left the run.", "Você saiu da partida."),
    ("Character out of the game.", "Personagem fora do jogo."),
    ("You are already in a dungeon.", "Você já está numa dungeon."),
    ("The room sat idle and closed.", "A sala ficou parada e fechou."),
    ("No more entries for sale today.", "Sem mais entradas à venda hoje."),
    ("{} item(s) picked up off the ground.", "{} item(ns) do chão recolhidos."),
    ("The party went down: the floor restarted.", "O grupo caiu: o andar recomeçou."),
    ("The Arena is a waypoint: you went back.", "A Arena é de passagem: você voltou."),
    ("Entry bought for {preco} gold.", "Entrada comprada por {preco} de ouro."),
    (
        "Alguém não aceitou: você voltou pra fila.",
        "Somebody didn't accept: you went back to the queue.",
    ),
    (
        "Você está na Arena. Toque em Sair para voltar.",
        "You are in the Arena. Tap Leave to go back.",
    ),
    (
        "Primeira vitória! A recompensa está no Correio.",
        "First win! The reward is in your Mail.",
    ),
    (
        "A dungeon foi reiniciada; você saiu com segurança.",
        "The dungeon was restarted; you got out safely.",
    ),
    (
        "A dungeon foi reiniciada; você foi recuperado no porto.",
        "The dungeon was restarted; you were recovered at the port.",
    ),
    (
        "Você entra na Arena. Para voltar, abra Dungeons e toque em Sair.",
        "You enter the Arena. To go back, open Dungeons and tap Leave.",
    ),
    // ─────────────────────────── server: skill evolution ───────────────────────────
    ("invalid skill", "habilidade inválida"),
    ("{} Energy short", "faltam {} de Energia"),
    ("missing Tome {} of {}", "falta o Tomo {} de {}"),
    ("invalid tome grade", "grau de tomo inválido"),
    ("Tier {} requires level {}", "o Tier {} exige nível {}"),
    ("{} evolved to Tier {}.", "{} evoluiu para Tier {}."),
    ("Tome {} of {} condensed.", "Tomo {} de {} condensado."),
    ("tome limit reached", "limite de tomos alcançado"),
    ("that skill is already at Tier X", "essa habilidade já está no Tier X"),
    ("that skill unlocks at level {precisa}", "essa habilidade libera no nível {precisa}"),
    // ────────────────────────── servidor: as recusas de skill ──────────────────────────
    ("Skill on cooldown.", "Skill em recarga."),
    ("Not enough mana.", "Mana insuficiente."),
    ("The target is dead.", "O alvo está morto."),
    ("Skill unavailable.", "Skill indisponível."),
    ("Target out of range.", "Alvo fora do alcance."),
    ("The target is in the safe zone.", "O alvo está na zona segura."),
    ("Select a valid enemy.", "Selecione um inimigo válido."),
    ("Wait for the current action to finish.", "Aguarde terminar a ação atual."),
    ("The target is no longer available.", "O alvo não está mais disponível."),
    ("This skill belongs to another weapon.", "Esta skill pertence a outra arma."),
    ("The target could not be reached.", "Não foi possível alcançar o alvo."),
    ("The target is behind an obstacle.", "O alvo está atrás de um obstáculo."),
    ("You cannot attack in the safe zone.", "Não é possível atacar na zona segura."),
    ("Your level does not unlock this skill yet.", "Seu nível ainda não libera esta skill."),
    ("Select an enemy to use this skill.", "Selecione um inimigo para usar esta skill."),
    // ──────────────────────── servidor: loja e montaria no mundo ────────────────────────
    ("You cannot mount right now.", "Agora não dá para montar."),
    ("Stop gathering to mount.", "Pare a coleta para montar."),
    ("You received {} {nome}!", "Você recebeu {} de {nome}!"),
    ("You received {} Energy!", "Você recebeu {} de Energia!"),
    ("The shop is unavailable right now.", "Loja indisponível no momento."),
    (
        "Equipe uma montaria na bolsa antes de montar.",
        "Equip a mount in your bag before mounting.",
    ),
    (
        "{nome} enviado ao correio: sua bolsa está cheia.",
        "{nome} sent to your mail: your bag is full.",
    ),
    (
        "{nome} entregue na bolsa. Abra para revelar o prêmio!",
        "{nome} delivered to your bag. Open it to reveal the prize!",
    ),
    (
        "Invocação indisponível. Os pergaminhos voltaram para sua bolsa.",
        "Summoning unavailable. The scrolls went back to your bag.",
    ),
    (
        "Invocação indisponível. Os pergaminhos voltaram pelas Entregas.",
        "Summoning unavailable. The scrolls came back through Deliveries.",
    ),
    // ───────────────────────── server: the Magic Island and the clock ─────────────────────────
    ("Unknown step.", "Degrau desconhecido."),
    ("{} opens at level {}.", "{} abre no nível {}."),
    ("You leave the Magic Island.", "Você deixa a Ilha Mágica."),
    ("You are already on this step.", "Você já está neste degrau."),
    ("{} is closed right now.", "{} está fechada no momento."),
    ("The Magic Island does not open from here.", "A Ilha Mágica não abre daqui."),
    ("The Magic Island opens at level {}.", "A Ilha Mágica abre no nível {}."),
    ("There is no active time to resume.", "Não há tempo ativo para retomar."),
    ("Your time on the Magic Island is over.", "Seu tempo na Ilha Mágica acabou."),
    ("Magic Island: {} minute(s) left.", "Ilha Mágica: {} minuto(s) restantes."),
    ("{} opens at level {} (you: {nivel}).", "{} abre no nível {} (você: {nivel})."),
    ("You enter {} — {minutos} minutes.", "Você entra na {} — {minutos} minutos."),
    ("You resume your time on the Magic Island.", "Você retoma seu tempo na Ilha Mágica."),
    ("Magic Island: {marco} seconds left.", "Ilha Mágica: {marco} segundos restantes."),
    (
        "Você viaja para a {}. O relógio continua.",
        "You travel to {}. The clock keeps running.",
    ),
    (
        "Tempo da Ilha Mágica estendido: {minutos} minutos restantes.",
        "Magic Island time extended: {minutos} minutes left.",
    ),
    // ───────────────────────── servidor: mercado no mundo ─────────────────────────
    (" (+{gold} gold)", " (+{gold} gold)"),
    ("1 delivery claimed", "1 entrega recebida"),
    ("Nothing to claim.", "Nada para receber."),
    ("{n} deliveries claimed", "{n} entregas recebidas"),
    (
        "O mercado global está desligado neste servidor.",
        "The global market is switched off on this server.",
    ),
    (
        "Bolsa cheia: libere espaço para receber o resto.",
        "Bag full: free up space to claim the rest.",
    ),
    (
        "Compra enviada: {total} gold reservados. Chega em Entregas.",
        "Purchase sent: {total} gold held. It arrives in Deliveries.",
    ),
    (
        "Anúncio enviado: {nome} ×{qtd}. Aparece no mercado em instantes.",
        "Listing sent: {nome} ×{qtd}. It shows up on the market in a moment.",
    ),
    ("that cannot be combined", "isso não se combina"),
    ("Calendar unavailable.", "Calendário indisponível."),
    // ──────────────────────────── server: social and clan ────────────────────────────
    ("Updated.", "Atualizado."),
    ("Account not authenticated.", "Conta não autenticada."),
    ("Clan invite sent.", "Convite de clã enviado."),
    ("Wait for the current claim.", "Aguarde o resgate atual."),
    ("Friend request sent.", "Pedido de amizade enviado."),
    ("The social panel could not be loaded.", "Não foi possível carregar o social."),
    ("Social unavailable. Try again.", "Social indisponível. Tente novamente."),
    ("Wait a moment and try again.", "Aguarde um instante e tente novamente."),
    ("Wait for the refresh and try again.", "Aguarde a atualização e tente novamente."),
    ("Social unavailable: the server has no database.", "Social indisponível: servidor sem banco."),
    (
        "Anexos já entregues; aguardando confirmação.",
        "Attachments already delivered; awaiting confirmation.",
    ),
    (
        "Correio oficial enviado para {n} personagem(ns).",
        "Official mail sent to {n} character(s).",
    ),
    ("You have no clan.", "Você não tem clã."),
    ("Letter not found.", "Carta não encontrada."),
    ("Clan full (50 members).", "Clã cheio (50 membros)."),
    ("Choose another character.", "Escolha outro personagem."),
    ("You already belong to a clan.", "Você já pertence a um clã."),
    ("That character already has a clan.", "Esse personagem já tem clã."),
    ("Invalid character name.", "Nome de personagem inválido."),
    ("A clan with that name already exists.", "Já existe um clã com esse nome."),
    ("The claim has to go through the world.", "Resgate deve passar pelo mundo."),
    ("Wait 10 seconds between letters.", "Aguarde 10 segundos entre cartas."),
    ("Clan notice: up to 200 characters.", "Aviso do clã: até 200 caracteres."),
    ("Clan name: 3 to 24 characters.", "Nome do clã: de 3 a 24 caracteres."),
    ("Only the clan leader can do that.", "Só o líder do clã pode fazer isso."),
    ("That character does not belong to your clan.", "Personagem não pertence ao seu clã."),
    ("Pending invite limit reached.", "Limite de convites pendentes atingido."),
    ("Friend or request list is full (100).", "Lista de amigos ou pedidos cheia (100)."),
    ("Leave your clan before accepting another.", "Saia do seu clã antes de aceitar outro."),
    ("That clan invite is no longer available.", "Convite de clã não está mais disponível."),
    ("There is already a friendship or request between you.", "Já existe amizade ou pedido entre vocês."),
    ("The recipient's inbox is full (100 letters).", "Caixa do destinatário cheia (100 cartas)."),
    ("Character not found, or the name is ambiguous.", "Personagem não encontrado ou nome ambíguo."),
    ("That friend request is no longer available.", "Pedido de amizade não está mais disponível."),
    (
        "Transfira a liderança ou dissolva o clã antes de sair.",
        "Transfer leadership or disband the clan before leaving.",
    ),
    (
        "Envio administrativo deve passar pelo canal autenticado.",
        "An administrative send has to go through the authenticated channel.",
    ),
    (
        "Preencha assunto (até 60) e mensagem (até 1000 caracteres).",
        "Fill in a subject (up to 60) and a message (up to 1000 characters).",
    ),
    // ───────────────────────── server: quests, objectives ─────────────────────────
    ("{} of {} short", "faltam {} de {}"),
    ("quest already turned in", "missão já entregue"),
    ("the objective has not been met yet", "o objetivo ainda não foi cumprido"),
    ("that item cannot be sold in this basket", "item não vendável no basket"),
    (
        "[ADMIN] '{}' offline → aplicado no DB (vale no próximo login).",
        "[ADMIN] '{}' offline → applied in the DB (takes effect at next login).",
    ),
    (
        "Reserva de anexo mudou; save recusado para evitar duplicação (carta {}).",
        "The attachment reservation changed; the save was refused to avoid duplication (letter {}).",
    ),
    // ──────────────────────── o web: os dois e-mails da conta ────────────────────────
    ("Hello,", "Olá,"),
    ("If the button doesn't work:", "Se o botão não abrir:"),
    ("Confirm your Tempest account", "Confirme sua conta no Tempest"),
    ("Confirm my account", "Confirmar minha conta"),
    ("Reset your Tempest password", "Redefinir a senha do Tempest"),
    ("Choose a new password", "Escolher uma senha nova"),
    (
        "Falta confirmar seu e-mail para a conta ficar completa.",
        "Your e-mail still needs confirming for the account to be complete.",
    ),
    (
        "Alguém pediu para redefinir a senha desta conta.",
        "Someone asked to reset the password on this account.",
    ),
    (
        "O link vale por 48 horas. Se não foi você que criou a conta, é só ignorar.",
        "The link is good for 48 hours. If you didn't create the account, just ignore this.",
    ),
    (
        "O link vale por 1 hora e só pode ser usado uma vez. Se não foi você,                  pode ignorar — sua senha continua a mesma.",
        "The link is good for 1 hour and can only be used once. If this wasn't you,                  you can ignore it — your password stays the same.",
    ),
];
