[package]
name = "server"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
shared.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
futures-util.workspace = true
hecs.workspace = true
glam.workspace = true
bincode.workspace = true
serde.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
thiserror.workspace = true
